#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/PauseDialogTabEnum.h"
#include "unitysdk/RPG/Client/UISkillIndex.h"
#include "unitysdk/RPG/GameCore/AttackDamageType.h"
#include "unitysdk/RPG/GameCore/BattleOperationType.h"
#include "unitysdk/RPG/GameCore/FixPoint.h"
#include "unitysdk/RPG/GameCore/GameComponentBase.h"
#include "unitysdk/RPG/GameCore/MonsterHUDType.h"
#include "unitysdk/RPG/GameCore/MonsterStanceBarStyle.h"
#include "unitysdk/RPG/GameCore/TrashSummonPeriodState.h"
#include "unitysdk/Struct_2_A7EFF121F1A9ACBF.h"
#include "unitysdk/UnityEngine/Rect.h"
#include "unitysdk/UnityEngine/Vector2.h"

class Class_0_16E4307DCC419505_382;
class Class_0_16E4307DCC419505_483;
class Class_1_0807E78A61F02AFF;
class Class_1_1D7B69991D584C07;
class Class_1_1EDFFB645AFD9A3E;
class Class_1_2FA40FF0BD34B01D;
class Class_1_48FB41EE27FB816A;
class Class_1_50AEFB409ED29B92;
class Class_1_5EB2C6616A5654C1;
class Class_1_7807B2B04302CD7B_21;
class Class_1_83665B095F1535B5_18;
class Class_1_8DDC457C49061FD1;
class Class_1_945ACFB1FEBC7A2C_18;
class Class_1_AB817CB39E494C61;
class Class_1_AC4FF21662D4EBB2;
class Class_1_B34155E97AA41F6E;
class Class_1_BAF34E22336FA194;
class Class_1_D1797279B49332E9;
class Class_1_E12E73A35C16604A;
class Class_1_E54220BE5BFB3B20;
class Class_1_F3C6DC456A6F78EF;
class Class_2_434D09EE8A1FE6FE;
class Class_2_6B57C0CB1CF5E075;
namespace RPG::Client { class BattleAvatarCustomData; }
namespace RPG::Client { class QingQueBattleEnergyBarNotify; }
namespace RPG::Client { class TrialObjectiveData; }
namespace RPG::GameCore { class BattleInstance; }
namespace RPG::GameCore { class BattlePauseEnvironmentInfos; }
namespace RPG::GameCore { class GameEntity; }
namespace System { class Object; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class RenderTexture; }

#define RPG_GAMECORE_LEVELUICOMPONENT_ADDOVERRIDEWEAKNESSWITHADDANIM_OFFSET UNITYSDK_OFFSET(0x1920EB20)
#define RPG_GAMECORE_LEVELUICOMPONENT_DISPOSE_OFFSET UNITYSDK_OFFSET(0x1920EE70)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETACTIONDELAYICON_OFFSET UNITYSDK_OFFSET(0x1920F2D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETACTIVITYBUFFLAYERCOUNT_OFFSET UNITYSDK_OFFSET(0x1920EA30)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETENTITYMULTIHPMAXSEG_OFFSET UNITYSDK_OFFSET(0x1920E780)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETMODELSCALEBYENTITY_OFFSET UNITYSDK_OFFSET(0x1920E990)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETMONSTERSTANCEBARSTYLE_OFFSET UNITYSDK_OFFSET(0x1920E8D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETOVERRIDEMONSTERPHASEPOINTPREFAB_OFFSET UNITYSDK_OFFSET(0x1920F190)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETOVERRIDEWEAKNESSWITHADDANIM_OFFSET UNITYSDK_OFFSET(0x1920EDB0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GETQINGQUEENERGYBARDATA_OFFSET UNITYSDK_OFFSET(0x1920E6A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIONBARDATA_OFFSET UNITYSDK_OFFSET(0x192122E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIVITYTELEVISIONBUFFINFOINITPARAM_OFFSET UNITYSDK_OFFSET(0x192126C0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIVITYTELEVISIONBUFFINFOLIST_OFFSET UNITYSDK_OFFSET(0x19212800)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEALERTMARKMANAGER_OFFSET UNITYSDK_OFFSET(0x192127A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEAVATARCUSTOMDATA_OFFSET UNITYSDK_OFFSET(0x19212500)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEAVATARHUDSPECIALBUFFDATA_OFFSET UNITYSDK_OFFSET(0x19212520)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEHINTTOASTMANAGER_OFFSET UNITYSDK_OFFSET(0x192127C0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEITEMPROGRESSINFOINITPARAM_OFFSET UNITYSDK_OFFSET(0x192126E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLESPECIALSKILLMARKDATA_OFFSET UNITYSDK_OFFSET(0x19212540)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLETARGETDIALOGOFFSET_OFFSET UNITYSDK_OFFSET(0x192127E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLETARGETMULTITARGETSWITCH_OFFSET UNITYSDK_OFFSET(0x19212680)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEUIEFFECTMANAGER_OFFSET UNITYSDK_OFFSET(0x19212380)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEUINODEMANAGER_OFFSET UNITYSDK_OFFSET(0x192123A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BOSSENTITY_OFFSET UNITYSDK_OFFSET(0x19212480)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_BOSSPLURALITYHPNUM_OFFSET UNITYSDK_OFFSET(0x192124E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_CYRENEULTRASKILLSPECIALSTATE_OFFSET UNITYSDK_OFFSET(0x19210520)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_DAWNSEYEWEATHERDATA_OFFSET UNITYSDK_OFFSET(0x19212760)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_FEIXIAOBUTTONEFFECTINDEX_OFFSET UNITYSDK_OFFSET(0x19210460)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_FEVERTIMEINFO_OFFSET UNITYSDK_OFFSET(0x19212820)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_HUDVIEWRECT_OFFSET UNITYSDK_OFFSET(0x192124A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_IRONTOMBINFINITYHPUICONFIG_OFFSET UNITYSDK_OFFSET(0x19212600)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISAVATARPANELVISIBLE_OFFSET UNITYSDK_OFFSET(0x192123E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISCHALLENGEPEAKMISSIONUISIZEMINI_OFFSET UNITYSDK_OFFSET(0x19212860)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISEXITBATTLEDISABLE_OFFSET UNITYSDK_OFFSET(0x19212400)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISFORBIDBATTLECONDITIONONSTART_OFFSET UNITYSDK_OFFSET(0x19212640)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISSHOWBOSSPLURALITYUI_OFFSET UNITYSDK_OFFSET(0x19212620)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISSHOWIRONTOMBINFINITEUI_OFFSET UNITYSDK_OFFSET(0x192125A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISTIMELINEDETAILINFOPANELOPEN_OFFSET UNITYSDK_OFFSET(0x19212440)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISTOASTPAUSEWHENGAMEPAUSE_OFFSET UNITYSDK_OFFSET(0x19212580)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_ISVIEWMODEENABLED_OFFSET UNITYSDK_OFFSET(0x19212420)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_MONSTERHUDTYPE_OFFSET UNITYSDK_OFFSET(0x19212460)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_MONSTERSTANCEBARSTYLEDICT_OFFSET UNITYSDK_OFFSET(0x192123C0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_OVERRIDEMONSTERPHASEPOINTPREFAB_OFFSET UNITYSDK_OFFSET(0x19212920)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_PAUSEENVIRONMENTINFOS_OFFSET UNITYSDK_OFFSET(0x19212780)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_PHAINONACTIONCOUNT_OFFSET UNITYSDK_OFFSET(0x19212890)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_PREVIEWADDSP_OFFSET UNITYSDK_OFFSET(0x19212930)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_PROTECTIONMASKALPHA_OFFSET UNITYSDK_OFFSET(0x19212560)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_RECORDFRAMECAPTURERT_OFFSET UNITYSDK_OFFSET(0x192124C0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_SCOREPANELSHOW_OFFSET UNITYSDK_OFFSET(0x19212660)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_SHOWCHALLENGEPEEKCOUNTDOWNEFFECT_OFFSET UNITYSDK_OFFSET(0x19212840)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_SHOWCHALLENGESTORYWAVEPANEL_OFFSET UNITYSDK_OFFSET(0x19212880)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_TARGETSELECTCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212340)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_TRASHSUMMONPERIODSTATE_OFFSET UNITYSDK_OFFSET(0x192126A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_TRIALOBJECTIVEDATA_OFFSET UNITYSDK_OFFSET(0x19212300)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_UIBATTLECAMERACONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212360)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_UISKILLCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212320)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_VERSUSBARDATA_OFFSET UNITYSDK_OFFSET(0x19212700)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_VERSUSBARQUESTDATA_OFFSET UNITYSDK_OFFSET(0x19212720)
#define RPG_GAMECORE_LEVELUICOMPONENT_GET_WEATHERDATA_OFFSET UNITYSDK_OFFSET(0x19212740)
#define RPG_GAMECORE_LEVELUICOMPONENT_INITCOMPONENT_OFFSET UNITYSDK_OFFSET(0x1920D200)
#define RPG_GAMECORE_LEVELUICOMPONENT_ISOPERATIONLOCKED_OFFSET UNITYSDK_OFFSET(0x1920E5E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0x1920E2E0)
#define RPG_GAMECORE_LEVELUICOMPONENT_RECORDOPENPAUSEDIALOG_OFFSET UNITYSDK_OFFSET(0x1920F4C0)
#define RPG_GAMECORE_LEVELUICOMPONENT_RESETOVERRIDEWEAKNESSWITHADDANIM_OFFSET UNITYSDK_OFFSET(0x1920ED40)
#define RPG_GAMECORE_LEVELUICOMPONENT_SETSHOWACTIONBARCOUNTDOWNEFFECT_OFFSET UNITYSDK_OFFSET(0x1920F280)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIONBARDATA_OFFSET UNITYSDK_OFFSET(0x192122F0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIVITYTELEVISIONBUFFINFOINITPARAM_OFFSET UNITYSDK_OFFSET(0x192126D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIVITYTELEVISIONBUFFINFOLIST_OFFSET UNITYSDK_OFFSET(0x19212810)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEALERTMARKMANAGER_OFFSET UNITYSDK_OFFSET(0x192127B0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEAVATARCUSTOMDATA_OFFSET UNITYSDK_OFFSET(0x19212510)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEAVATARHUDSPECIALBUFFDATA_OFFSET UNITYSDK_OFFSET(0x19212530)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEHINTTOASTMANAGER_OFFSET UNITYSDK_OFFSET(0x192127D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEITEMPROGRESSINFOINITPARAM_OFFSET UNITYSDK_OFFSET(0x192126F0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLESPECIALSKILLMARKDATA_OFFSET UNITYSDK_OFFSET(0x19212550)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLETARGETDIALOGOFFSET_OFFSET UNITYSDK_OFFSET(0x192127F0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLETARGETMULTITARGETSWITCH_OFFSET UNITYSDK_OFFSET(0x19212690)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEUIEFFECTMANAGER_OFFSET UNITYSDK_OFFSET(0x19212390)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEUINODEMANAGER_OFFSET UNITYSDK_OFFSET(0x192123B0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BOSSENTITY_OFFSET UNITYSDK_OFFSET(0x19212490)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_BOSSPLURALITYHPNUM_OFFSET UNITYSDK_OFFSET(0x192124F0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_CYRENEULTRASKILLSPECIALSTATE_OFFSET UNITYSDK_OFFSET(0x19210530)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_DAWNSEYEWEATHERDATA_OFFSET UNITYSDK_OFFSET(0x19212770)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_FEIXIAOBUTTONEFFECTINDEX_OFFSET UNITYSDK_OFFSET(0x19210470)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_FEVERTIMEINFO_OFFSET UNITYSDK_OFFSET(0x19212830)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_HUDVIEWRECT_OFFSET UNITYSDK_OFFSET(0x192124B0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_IRONTOMBINFINITYHPUICONFIG_OFFSET UNITYSDK_OFFSET(0x19212610)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISAVATARPANELVISIBLE_OFFSET UNITYSDK_OFFSET(0x192123F0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISCHALLENGEPEAKMISSIONUISIZEMINI_OFFSET UNITYSDK_OFFSET(0x19212870)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISEXITBATTLEDISABLE_OFFSET UNITYSDK_OFFSET(0x19212410)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISFORBIDBATTLECONDITIONONSTART_OFFSET UNITYSDK_OFFSET(0x19212650)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISSHOWBOSSPLURALITYUI_OFFSET UNITYSDK_OFFSET(0x19212630)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISTIMELINEDETAILINFOPANELOPEN_OFFSET UNITYSDK_OFFSET(0x19212450)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISTOASTPAUSEWHENGAMEPAUSE_OFFSET UNITYSDK_OFFSET(0x19212590)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_ISVIEWMODEENABLED_OFFSET UNITYSDK_OFFSET(0x19212430)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_MONSTERHUDTYPE_OFFSET UNITYSDK_OFFSET(0x19212470)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_MONSTERSTANCEBARSTYLEDICT_OFFSET UNITYSDK_OFFSET(0x192123D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_PAUSEENVIRONMENTINFOS_OFFSET UNITYSDK_OFFSET(0x19212790)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_PHAINONACTIONCOUNT_OFFSET UNITYSDK_OFFSET(0x192128A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_PROTECTIONMASKALPHA_OFFSET UNITYSDK_OFFSET(0x19212570)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_RECORDFRAMECAPTURERT_OFFSET UNITYSDK_OFFSET(0x192124D0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_SCOREPANELSHOW_OFFSET UNITYSDK_OFFSET(0x19212670)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_SHOWCHALLENGEPEEKCOUNTDOWNEFFECT_OFFSET UNITYSDK_OFFSET(0x19212850)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_TARGETSELECTCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212350)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_TRASHSUMMONPERIODSTATE_OFFSET UNITYSDK_OFFSET(0x192126B0)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_TRIALOBJECTIVEDATA_OFFSET UNITYSDK_OFFSET(0x19212310)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_UIBATTLECAMERACONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212370)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_UISKILLCONTROLLER_OFFSET UNITYSDK_OFFSET(0x19212330)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_VERSUSBARDATA_OFFSET UNITYSDK_OFFSET(0x19212710)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_VERSUSBARQUESTDATA_OFFSET UNITYSDK_OFFSET(0x19212730)
#define RPG_GAMECORE_LEVELUICOMPONENT_SET_WEATHERDATA_OFFSET UNITYSDK_OFFSET(0x19212750)
#define RPG_GAMECORE_LEVELUICOMPONENT_SHOWBOSSINFOBAR_OFFSET UNITYSDK_OFFSET(0x1920F3A0)
#define RPG_GAMECORE_LEVELUICOMPONENT_TICK_OFFSET UNITYSDK_OFFSET(0x1920E1F0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ADDHANDLERS_OFFSET UNITYSDK_OFFSET(0x1920D340)
#define RPG_GAMECORE_LEVELUICOMPONENT__BATTLEPAUSETOASTWHENGAMEPAUSE_OFFSET UNITYSDK_OFFSET(0x19210A40)
#define RPG_GAMECORE_LEVELUICOMPONENT__CTOR_OFFSET UNITYSDK_OFFSET(0x19212940)
#define RPG_GAMECORE_LEVELUICOMPONENT__INITBEFORELEVELSETUP_OFFSET UNITYSDK_OFFSET(0x1920FDC0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONACTIONDELAYICONCHANGE_OFFSET UNITYSDK_OFFSET(0x192118D0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEFORBIDBATTLECONDITIONONSTART_OFFSET UNITYSDK_OFFSET(0x19211500)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEINITACTIVITYTELEVISIONBUFFINFOPANEL_OFFSET UNITYSDK_OFFSET(0x19210B90)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEINITBATTLEITEMPROGRESSINFOPANEL_OFFSET UNITYSDK_OFFSET(0x19210C30)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEMONSTERHPTOTALSEGCHANGE_OFFSET UNITYSDK_OFFSET(0x192107E0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEONSETQINGQUEENERGYBARSTATE_OFFSET UNITYSDK_OFFSET(0x19210040)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETACTIVITYTELEVISIONBUFFINFOPANEL_OFFSET UNITYSDK_OFFSET(0x19210210)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETBATTLETARGETDIALOGOFFSET_OFFSET UNITYSDK_OFFSET(0x19210150)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETDAWNSEYEWEATHERUI_OFFSET UNITYSDK_OFFSET(0x192111D0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETIRONTOMBINFINITYHPUI_OFFSET UNITYSDK_OFFSET(0x192113A0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETIRONTOMBPLURIALITYHPUI_OFFSET UNITYSDK_OFFSET(0x19211440)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETMONSTERHUDTYPE_OFFSET UNITYSDK_OFFSET(0x192109A0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETMONSTERPHASEPOINTPREFAB_OFFSET UNITYSDK_OFFSET(0x19211550)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETTRASHSUMMONHUDSTATE_OFFSET UNITYSDK_OFFSET(0x19211740)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETVERSUSBARDATA_OFFSET UNITYSDK_OFFSET(0x19210E40)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETWEATHERUI_OFFSET UNITYSDK_OFFSET(0x19211130)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESHOWCHALLEGESTORYWAVEPANEL_OFFSET UNITYSDK_OFFSET(0x192103A0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESWITCHBATTLETARGETMULTITARGETSWITCH_OFFSET UNITYSDK_OFFSET(0x19210CD0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESWITCHCHALLENGEPEAKMISSIONUISIZE_OFFSET UNITYSDK_OFFSET(0x19211810)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETOGGLESCORECOUNTERSHOW_OFFSET UNITYSDK_OFFSET(0x19210AD0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETOGGLESKILLPRESHOW_OFFSET UNITYSDK_OFFSET(0x192105A0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETRYSELECTACTIONBARITEMWITHHIGHLIGHT_OFFSET UNITYSDK_OFFSET(0x192121D0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETRYSELECTACTIONBARITEM_OFFSET UNITYSDK_OFFSET(0x19212100)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUICYRENEENTERSPECIALSTATE_OFFSET UNITYSDK_OFFSET(0x19210540)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUIPAUSEENVIRONMENTINFOADD_OFFSET UNITYSDK_OFFSET(0x19211300)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUIPAUSEENVIRONMENTINFORESET_OFFSET UNITYSDK_OFFSET(0x19211250)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEVERSUSBARQUESTCHANGE_OFFSET UNITYSDK_OFFSET(0x19210FF0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONENTITYACTIONBEGIN_OFFSET UNITYSDK_OFFSET(0x1920FFF0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONLEVELFEVERTIMEINFOCHANGE_OFFSET UNITYSDK_OFFSET(0x19212020)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONLEVELREMOVEMODIFIER_OFFSET UNITYSDK_OFFSET(0x19211B40)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONLOCKBATTLEOPERATION_OFFSET UNITYSDK_OFFSET(0x1920F550)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONRESETBATTLEOPERATION_OFFSET UNITYSDK_OFFSET(0x1920DC50)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONSETPLURALITYHPNUM_OFFSET UNITYSDK_OFFSET(0x192108E0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONTRIGGERFEIXIAOSUBSKILL01BUTTONEFFECT_OFFSET UNITYSDK_OFFSET(0x19210480)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONTRIGGERFEIXIAOSUBSKILL02BUTTONEFFECT_OFFSET UNITYSDK_OFFSET(0x192104D0)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONUICHARACTERMODELSCALE_OFFSET UNITYSDK_OFFSET(0x19210D90)
#define RPG_GAMECORE_LEVELUICOMPONENT__ONUISTARTFADEOUTCUTIN_OFFSET UNITYSDK_OFFSET(0x192117C0)
#define RPG_GAMECORE_LEVELUICOMPONENT__TICKONSELECTACTIONBARITEM_OFFSET UNITYSDK_OFFSET(0x1920E3C0)
#define RPG_GAMECORE_LEVELUICOMPONENT__TICKTRYOPENPAUSEDIALOG_OFFSET UNITYSDK_OFFSET(0x1920E530)
#define RPG_GAMECORE_LEVELUICOMPONENT___IFIXBASEPROXY_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0x19212FD0)
#define RPG_GAMECORE_LEVELUICOMPONENT___IFIXBASEPROXY_TICK_OFFSET UNITYSDK_OFFSET(0x19212FC0)

namespace RPG::GameCore
{
	inline static constexpr unsigned int LevelUIComponent_TypeDefinitionIndex = 52812;

	class LevelUIComponent : public ::RPG::GameCore::GameComponentBase
	{
	public:
		::Class_1_E54220BE5BFB3B20* _VersusBarQuestData_k__BackingField; // 0x18
		::Class_1_D1797279B49332E9* _UISkillController_k__BackingField; // 0x20
		::Class_1_E12E73A35C16604A* _BattleAlertMarkManager_k__BackingField; // 0x28
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::BattleOperationType, ::System::Boolean>* _LockBattleOperationDict; // 0x30
		::Class_1_83665B095F1535B5_18* _IronTombInfinityHPUIConfig_k__BackingField; // 0x38
		::Class_1_945ACFB1FEBC7A2C_18* _WeatherData_k__BackingField; // 0x40
		::Class_1_AC4FF21662D4EBB2* _BattleHintToastManager_k__BackingField; // 0x48
		::Class_1_1EDFFB645AFD9A3E* _BattleUIEffectManager_k__BackingField; // 0x50
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Single>* _ModelScaleDict; // 0x58
		::UnityEngine::RenderTexture* _RecordFrameCaptureRT_k__BackingField; // 0x60
		::Class_1_BAF34E22336FA194* _FeverTimeInfo_k__BackingField; // 0x68
		::Class_1_1D7B69991D584C07* _BattleItemProgressInfoInitParam_k__BackingField; // 0x70
		::Class_1_5EB2C6616A5654C1* _VersusBarData_k__BackingField; // 0x78
		::Class_1_2FA40FF0BD34B01D* _ActivityTelevisionBuffInfoInitParam_k__BackingField; // 0x80
		::Class_1_0807E78A61F02AFF* _UIBattleCameraController_k__BackingField; // 0x88
		::Class_1_AB817CB39E494C61* _ActionBarData_k__BackingField; // 0x90
		::Struct_2_A7EFF121F1A9ACBF _TimeLineDetailInfoSetupData; // 0x98
		::System::Collections::Generic::List_1<::Class_1_7807B2B04302CD7B_21*>* _ActivityTelevisionBuffInfoList_k__BackingField; // 0xB0
		::Class_2_6B57C0CB1CF5E075* EvolveBuildCountDownItemPanel; // 0xB8
		::RPG::Client::TrialObjectiveData* _TrialObjectiveData_k__BackingField; // 0xC0
		::Class_1_48FB41EE27FB816A* _TargetSelectController_k__BackingField; // 0xC8
		::RPG::Client::BattleAvatarCustomData* _BattleAvatarCustomData_k__BackingField; // 0xD0
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::System::String*>* _ActionDelayIconDict; // 0xD8
		::Class_2_434D09EE8A1FE6FE* EvolveBuildExpPanel; // 0xE0
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::Il2CppArray<::System::String*>*>* _OverrideMonsterPhasePointPrefab; // 0xE8
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::MonsterStanceBarStyle>* _MonsterStanceBarStyleDict_k__BackingField; // 0xF0
		::RPG::GameCore::BattlePauseEnvironmentInfos* _PauseEnvironmentInfos_k__BackingField; // 0xF8
		::RPG::GameCore::BattleInstance* _BattleInstanceRef; // 0x100
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::RPG::GameCore::FixPoint>* _PreviewAddSP; // 0x108
		::RPG::GameCore::GameEntity* _BossEntity_k__BackingField; // 0x110
		::Class_1_F3C6DC456A6F78EF* _BattleUINodeManager_k__BackingField; // 0x118
		::Class_1_8DDC457C49061FD1* _BattleSpecialSkillMarkData_k__BackingField; // 0x120
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::System::UInt32>* _EntityMultiHPMaxSeg; // 0x128
		::Class_1_50AEFB409ED29B92* _OpenPauseDialogParam; // 0x130
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::QingQueBattleEnergyBarNotify*>* _QingqueEnergyBarDataDict; // 0x138
		::Class_1_B34155E97AA41F6E* _BattleAvatarHUDSpecialBuffData_k__BackingField; // 0x140
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::RPG::GameCore::AttackDamageType>* _OverrideWeaknessWithAddAnim; // 0x148
		::Class_0_16E4307DCC419505_483* _DawnsEyeWeatherData_k__BackingField; // 0x150
		::System::Boolean _IsChallengePeakMissionUISizeMini_k__BackingField; // 0x158
		::System::Boolean _IsToastPauseWhenGamePause_k__BackingField; // 0x159
		::System::Boolean _ScorePanelShow_k__BackingField; // 0x15A
		::RPG::GameCore::TrashSummonPeriodState _TrashSummonPeriodState_k__BackingField; // 0x15C
		::UnityEngine::Rect _HUDViewRect_k__BackingField; // 0x160
		::System::Single _ProtectionMaskAlpha_k__BackingField; // 0x170
		::System::UInt32 _PhainonActionCount; // 0x174
		::System::Boolean NotifyFadeOutCutIn; // 0x178
		::System::Boolean ViewModePropertyShowTotal; // 0x179
		::System::Boolean _CyreneUltraSkillSpecialState_k__BackingField; // 0x17A
		::System::Boolean _ShowChallengeStoryWavePanel; // 0x17B
		::UnityEngine::Vector2 _BattleTargetDialogOffset_k__BackingField; // 0x17C
		::System::Boolean _IsForbidBattleConditionOnStart_k__BackingField; // 0x184
		::System::Boolean _IsTimeLineDetailInfoPanelOpen_k__BackingField; // 0x185
		::System::Boolean _IsExitBattleDisable_k__BackingField; // 0x186
		::System::Boolean _ShowChallengePeekCountDownEffect_k__BackingField; // 0x187
		::RPG::Client::UISkillIndex _FeixiaoButtonEffectIndex_k__BackingField; // 0x188
		::System::Int32 _BossPluralityHPNum_k__BackingField; // 0x18C
		::System::Boolean _IsAvatarPanelVisible_k__BackingField; // 0x190
		::System::Boolean _BattleTargetMultiTargetSwitch_k__BackingField; // 0x191
		::System::Boolean _IsViewModeEnabled_k__BackingField; // 0x192
		::System::Boolean _IsShowBossPluralityUI_k__BackingField; // 0x193
		::RPG::GameCore::MonsterHUDType _MonsterHUDType_k__BackingField; // 0x194

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__CTOR_OFFSET))(this);
		}

		::System::Void InitComponent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_INITCOMPONENT_OFFSET))(this);
		}

		::System::Void Tick(::System::Single deltaTime)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_TICK_OFFSET))(this, deltaTime);
		}

		::System::Void LateUpdate(::System::Single deltaTime)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_LATEUPDATE_OFFSET))(this, deltaTime);
		}

		::System::Boolean IsOperationLocked(::RPG::GameCore::BattleOperationType type)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::BattleOperationType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_ISOPERATIONLOCKED_OFFSET))(this, type);
		}

		::RPG::Client::QingQueBattleEnergyBarNotify* GetQingqueEnergyBarData(::System::UInt32 runtimeID)
		{
			return ((::RPG::Client::QingQueBattleEnergyBarNotify*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETQINGQUEENERGYBARDATA_OFFSET))(this, runtimeID);
		}

		::System::UInt32 GetEntityMultiHpMaxSeg(::RPG::GameCore::GameEntity* entity)
		{
			return ((::System::UInt32(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETENTITYMULTIHPMAXSEG_OFFSET))(this, entity);
		}

		::RPG::GameCore::MonsterStanceBarStyle GetMonsterStanceBarStyle(::System::UInt32 runtimeID)
		{
			return ((::RPG::GameCore::MonsterStanceBarStyle(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETMONSTERSTANCEBARSTYLE_OFFSET))(this, runtimeID);
		}

		::System::Single GetModelScaleByEntity(::System::UInt32 runtimeID)
		{
			return ((::System::Single(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETMODELSCALEBYENTITY_OFFSET))(this, runtimeID);
		}

		::System::Int32 GetActivityBuffLayerCount(::System::Int32 buffID)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETACTIVITYBUFFLAYERCOUNT_OFFSET))(this, buffID);
		}

		::System::Void AddOverrideWeaknessWithAddAnim(::RPG::GameCore::GameEntity* gameEntity, ::RPG::GameCore::AttackDamageType attackDamageType)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AttackDamageType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_ADDOVERRIDEWEAKNESSWITHADDANIM_OFFSET))(this, gameEntity, attackDamageType);
		}

		::System::Void ResetOverrideWeaknessWithAddAnim(::RPG::GameCore::GameEntity* gameEntity)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_RESETOVERRIDEWEAKNESSWITHADDANIM_OFFSET))(this, gameEntity);
		}

		::RPG::GameCore::AttackDamageType GetOverrideWeaknessWithAddAnim(::RPG::GameCore::GameEntity* gameEntity)
		{
			return ((::RPG::GameCore::AttackDamageType(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETOVERRIDEWEAKNESSWITHADDANIM_OFFSET))(this, gameEntity);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_DISPOSE_OFFSET))(this);
		}

		::Il2CppArray<::System::String*>* GetOverrideMonsterPhasePointPrefab(::RPG::GameCore::GameEntity* entity)
		{
			return ((::Il2CppArray<::System::String*>*(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETOVERRIDEMONSTERPHASEPOINTPREFAB_OFFSET))(this, entity);
		}

		::System::Void SetShowActionBarCountDownEffect(::System::Boolean isShow)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SETSHOWACTIONBARCOUNTDOWNEFFECT_OFFSET))(this, isShow);
		}

		::System::String* GetActionDelayIcon(::RPG::GameCore::GameEntity* entity)
		{
			return ((::System::String*(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GETACTIONDELAYICON_OFFSET))(this, entity);
		}

		::System::Void ShowBossInfoBar(::RPG::GameCore::GameEntity* entity)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SHOWBOSSINFOBAR_OFFSET))(this, entity);
		}

		::System::Void RecordOpenPauseDialog(::System::Boolean isExitBattleBtnDisable, ::RPG::Client::PauseDialogTabEnum initTabEnum)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::PauseDialogTabEnum))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_RECORDOPENPAUSEDIALOG_OFFSET))(this, isExitBattleBtnDisable, initTabEnum);
		}

		::System::Void _AddHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ADDHANDLERS_OFFSET))(this);
		}

		::System::Void _OnLockBattleOperation(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONLOCKBATTLEOPERATION_OFFSET))(this, arg);
		}

		::System::Void _OnResetBattleOperation(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONRESETBATTLEOPERATION_OFFSET))(this, arg);
		}

		::System::Void _InitBeforeLevelSetup(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__INITBEFORELEVELSETUP_OFFSET))(this, arg);
		}

		::System::Void _OnEntityActionBegin(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONENTITYACTIONBEGIN_OFFSET))(this, arg);
		}

		::System::Void _OnBattleOnSetQingQueEnergyBarState(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEONSETQINGQUEENERGYBARSTATE_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetBattleTargetDialogOffset(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETBATTLETARGETDIALOGOFFSET_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetActivityTelevisionBuffInfoPanel(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETACTIVITYTELEVISIONBUFFINFOPANEL_OFFSET))(this, arg);
		}

		::System::Void _OnBattleShowChallegeStoryWavePanel(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESHOWCHALLEGESTORYWAVEPANEL_OFFSET))(this, arg);
		}

		::RPG::Client::UISkillIndex get_FeixiaoButtonEffectIndex()
		{
			return ((::RPG::Client::UISkillIndex(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_FEIXIAOBUTTONEFFECTINDEX_OFFSET))(this);
		}

		::System::Void set_FeixiaoButtonEffectIndex(::RPG::Client::UISkillIndex value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::UISkillIndex))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_FEIXIAOBUTTONEFFECTINDEX_OFFSET))(this, value);
		}

		::System::Void _OnTriggerFeixiaoSubSkill01ButtonEffect(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONTRIGGERFEIXIAOSUBSKILL01BUTTONEFFECT_OFFSET))(this, arg);
		}

		::System::Void _OnTriggerFeixiaoSubSkill02ButtonEffect(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONTRIGGERFEIXIAOSUBSKILL02BUTTONEFFECT_OFFSET))(this, arg);
		}

		::System::Boolean get_CyreneUltraSkillSpecialState()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_CYRENEULTRASKILLSPECIALSTATE_OFFSET))(this);
		}

		::System::Void set_CyreneUltraSkillSpecialState(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_CYRENEULTRASKILLSPECIALSTATE_OFFSET))(this, value);
		}

		::System::Void _OnBattleUICyreneEnterSpecialState(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUICYRENEENTERSPECIALSTATE_OFFSET))(this, arg);
		}

		::System::Void _OnBattleToggleSkillPreShow(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETOGGLESKILLPRESHOW_OFFSET))(this, arg);
		}

		::System::Void _OnBattleMonsterHPTotalSegChange(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEMONSTERHPTOTALSEGCHANGE_OFFSET))(this, arg);
		}

		::System::Void _OnSetPluralityHPNum(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONSETPLURALITYHPNUM_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetMonsterHUDType(::System::Object* obj)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETMONSTERHUDTYPE_OFFSET))(this, obj);
		}

		::System::Void _BattlePauseToastWhenGamePause(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__BATTLEPAUSETOASTWHENGAMEPAUSE_OFFSET))(this, arg);
		}

		::System::Void _OnBattleToggleScoreCounterShow(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETOGGLESCORECOUNTERSHOW_OFFSET))(this, arg);
		}

		::System::Void _OnBattleInitActivityTelevisionBuffInfoPanel(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEINITACTIVITYTELEVISIONBUFFINFOPANEL_OFFSET))(this, arg);
		}

		::System::Void _OnBattleInitBattleItemProgressInfoPanel(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEINITBATTLEITEMPROGRESSINFOPANEL_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSwitchBattleTargetMultiTargetSwitch(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESWITCHBATTLETARGETMULTITARGETSWITCH_OFFSET))(this, arg);
		}

		::System::Void _OnUICharacterModelScale(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONUICHARACTERMODELSCALE_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetVersusBarData(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETVERSUSBARDATA_OFFSET))(this, arg);
		}

		::System::Void _OnBattleVersusBarQuestChange(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEVERSUSBARQUESTCHANGE_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetWeatherUI(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETWEATHERUI_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetDawnsEyeWeatherUI(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETDAWNSEYEWEATHERUI_OFFSET))(this, arg);
		}

		::System::Void _OnBattleUIPauseEnvironmentInfoReset(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUIPAUSEENVIRONMENTINFORESET_OFFSET))(this, arg);
		}

		::System::Void _OnBattleUIPauseEnvironmentInfoAdd(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEUIPAUSEENVIRONMENTINFOADD_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetIronTombInfinityHPUI(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETIRONTOMBINFINITYHPUI_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetIronTombPlurialityHPUI(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETIRONTOMBPLURIALITYHPUI_OFFSET))(this, arg);
		}

		::System::Void _OnBattleForbidBattleConditionOnStart(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLEFORBIDBATTLECONDITIONONSTART_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetMonsterPhasePointPrefab(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETMONSTERPHASEPOINTPREFAB_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSetTrashSummonHUDState(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESETTRASHSUMMONHUDSTATE_OFFSET))(this, arg);
		}

		::System::Void _OnUIStartFadeOutCutIn(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONUISTARTFADEOUTCUTIN_OFFSET))(this, arg);
		}

		::System::Void _OnBattleSwitchChallengePeakMissionUISize(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLESWITCHCHALLENGEPEAKMISSIONUISIZE_OFFSET))(this, arg);
		}

		::System::Void _OnActionDelayIconChange(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONACTIONDELAYICONCHANGE_OFFSET))(this, arg);
		}

		::System::Void _OnLevelRemoveModifier(::Class_0_16E4307DCC419505_382* pEvt)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_382*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONLEVELREMOVEMODIFIER_OFFSET))(this, pEvt);
		}

		::System::Void _OnLevelFeverTimeInfoChange(::Class_0_16E4307DCC419505_382* evt)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_382*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONLEVELFEVERTIMEINFOCHANGE_OFFSET))(this, evt);
		}

		::System::Void _TickTryOpenPauseDialog()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__TICKTRYOPENPAUSEDIALOG_OFFSET))(this);
		}

		::System::Void _OnBattleTrySelectActionBarItem(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETRYSELECTACTIONBARITEM_OFFSET))(this, arg);
		}

		::System::Void _OnBattleTrySelectActionBarItemWithHighlight(::System::Object* arg)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__ONBATTLETRYSELECTACTIONBARITEMWITHHIGHLIGHT_OFFSET))(this, arg);
		}

		::System::Void _TickOnSelectActionBarItem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT__TICKONSELECTACTIONBARITEM_OFFSET))(this);
		}

		::Class_1_AB817CB39E494C61* get_ActionBarData()
		{
			return ((::Class_1_AB817CB39E494C61*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIONBARDATA_OFFSET))(this);
		}

		::System::Void set_ActionBarData(::Class_1_AB817CB39E494C61* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_AB817CB39E494C61*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIONBARDATA_OFFSET))(this, value);
		}

		::RPG::Client::TrialObjectiveData* get_TrialObjectiveData()
		{
			return ((::RPG::Client::TrialObjectiveData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_TRIALOBJECTIVEDATA_OFFSET))(this);
		}

		::System::Void set_TrialObjectiveData(::RPG::Client::TrialObjectiveData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TrialObjectiveData*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_TRIALOBJECTIVEDATA_OFFSET))(this, value);
		}

		::Class_1_D1797279B49332E9* get_UISkillController()
		{
			return ((::Class_1_D1797279B49332E9*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_UISKILLCONTROLLER_OFFSET))(this);
		}

		::System::Void set_UISkillController(::Class_1_D1797279B49332E9* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D1797279B49332E9*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_UISKILLCONTROLLER_OFFSET))(this, value);
		}

		::Class_1_48FB41EE27FB816A* get_TargetSelectController()
		{
			return ((::Class_1_48FB41EE27FB816A*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_TARGETSELECTCONTROLLER_OFFSET))(this);
		}

		::System::Void set_TargetSelectController(::Class_1_48FB41EE27FB816A* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_48FB41EE27FB816A*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_TARGETSELECTCONTROLLER_OFFSET))(this, value);
		}

		::Class_1_0807E78A61F02AFF* get_UIBattleCameraController()
		{
			return ((::Class_1_0807E78A61F02AFF*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_UIBATTLECAMERACONTROLLER_OFFSET))(this);
		}

		::System::Void set_UIBattleCameraController(::Class_1_0807E78A61F02AFF* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_0807E78A61F02AFF*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_UIBATTLECAMERACONTROLLER_OFFSET))(this, value);
		}

		::Class_1_1EDFFB645AFD9A3E* get_BattleUIEffectManager()
		{
			return ((::Class_1_1EDFFB645AFD9A3E*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEUIEFFECTMANAGER_OFFSET))(this);
		}

		::System::Void set_BattleUIEffectManager(::Class_1_1EDFFB645AFD9A3E* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_1EDFFB645AFD9A3E*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEUIEFFECTMANAGER_OFFSET))(this, value);
		}

		::Class_1_F3C6DC456A6F78EF* get_BattleUINodeManager()
		{
			return ((::Class_1_F3C6DC456A6F78EF*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEUINODEMANAGER_OFFSET))(this);
		}

		::System::Void set_BattleUINodeManager(::Class_1_F3C6DC456A6F78EF* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F3C6DC456A6F78EF*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEUINODEMANAGER_OFFSET))(this, value);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::MonsterStanceBarStyle>* get_MonsterStanceBarStyleDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::MonsterStanceBarStyle>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_MONSTERSTANCEBARSTYLEDICT_OFFSET))(this);
		}

		::System::Void set_MonsterStanceBarStyleDict(::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::MonsterStanceBarStyle>* value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::MonsterStanceBarStyle>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_MONSTERSTANCEBARSTYLEDICT_OFFSET))(this, value);
		}

		::System::Boolean get_IsAvatarPanelVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISAVATARPANELVISIBLE_OFFSET))(this);
		}

		::System::Void set_IsAvatarPanelVisible(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISAVATARPANELVISIBLE_OFFSET))(this, value);
		}

		::System::Boolean get_IsExitBattleDisable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISEXITBATTLEDISABLE_OFFSET))(this);
		}

		::System::Void set_IsExitBattleDisable(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISEXITBATTLEDISABLE_OFFSET))(this, value);
		}

		::System::Boolean get_IsViewModeEnabled()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISVIEWMODEENABLED_OFFSET))(this);
		}

		::System::Void set_IsViewModeEnabled(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISVIEWMODEENABLED_OFFSET))(this, value);
		}

		::System::Boolean get_IsTimeLineDetailInfoPanelOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISTIMELINEDETAILINFOPANELOPEN_OFFSET))(this);
		}

		::System::Void set_IsTimeLineDetailInfoPanelOpen(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISTIMELINEDETAILINFOPANELOPEN_OFFSET))(this, value);
		}

		::RPG::GameCore::MonsterHUDType get_MonsterHUDType()
		{
			return ((::RPG::GameCore::MonsterHUDType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_MONSTERHUDTYPE_OFFSET))(this);
		}

		::System::Void set_MonsterHUDType(::RPG::GameCore::MonsterHUDType value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::MonsterHUDType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_MONSTERHUDTYPE_OFFSET))(this, value);
		}

		::RPG::GameCore::GameEntity* get_BossEntity()
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BOSSENTITY_OFFSET))(this);
		}

		::System::Void set_BossEntity(::RPG::GameCore::GameEntity* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BOSSENTITY_OFFSET))(this, value);
		}

		::UnityEngine::Rect get_HUDViewRect()
		{
			return ((::UnityEngine::Rect(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_HUDVIEWRECT_OFFSET))(this);
		}

		::System::Void set_HUDViewRect(::UnityEngine::Rect value)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Rect))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_HUDVIEWRECT_OFFSET))(this, value);
		}

		::UnityEngine::RenderTexture* get_RecordFrameCaptureRT()
		{
			return ((::UnityEngine::RenderTexture*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_RECORDFRAMECAPTURERT_OFFSET))(this);
		}

		::System::Void set_RecordFrameCaptureRT(::UnityEngine::RenderTexture* value)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::RenderTexture*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_RECORDFRAMECAPTURERT_OFFSET))(this, value);
		}

		::System::Int32 get_BossPluralityHPNum()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BOSSPLURALITYHPNUM_OFFSET))(this);
		}

		::System::Void set_BossPluralityHPNum(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BOSSPLURALITYHPNUM_OFFSET))(this, value);
		}

		::RPG::Client::BattleAvatarCustomData* get_BattleAvatarCustomData()
		{
			return ((::RPG::Client::BattleAvatarCustomData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEAVATARCUSTOMDATA_OFFSET))(this);
		}

		::System::Void set_BattleAvatarCustomData(::RPG::Client::BattleAvatarCustomData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::BattleAvatarCustomData*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEAVATARCUSTOMDATA_OFFSET))(this, value);
		}

		::Class_1_B34155E97AA41F6E* get_BattleAvatarHUDSpecialBuffData()
		{
			return ((::Class_1_B34155E97AA41F6E*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEAVATARHUDSPECIALBUFFDATA_OFFSET))(this);
		}

		::System::Void set_BattleAvatarHUDSpecialBuffData(::Class_1_B34155E97AA41F6E* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_B34155E97AA41F6E*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEAVATARHUDSPECIALBUFFDATA_OFFSET))(this, value);
		}

		::Class_1_8DDC457C49061FD1* get_BattleSpecialSkillMarkData()
		{
			return ((::Class_1_8DDC457C49061FD1*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLESPECIALSKILLMARKDATA_OFFSET))(this);
		}

		::System::Void set_BattleSpecialSkillMarkData(::Class_1_8DDC457C49061FD1* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_8DDC457C49061FD1*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLESPECIALSKILLMARKDATA_OFFSET))(this, value);
		}

		::System::Single get_ProtectionMaskAlpha()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_PROTECTIONMASKALPHA_OFFSET))(this);
		}

		::System::Void set_ProtectionMaskAlpha(::System::Single value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_PROTECTIONMASKALPHA_OFFSET))(this, value);
		}

		::System::Boolean get_IsToastPauseWhenGamePause()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISTOASTPAUSEWHENGAMEPAUSE_OFFSET))(this);
		}

		::System::Void set_IsToastPauseWhenGamePause(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISTOASTPAUSEWHENGAMEPAUSE_OFFSET))(this, value);
		}

		::System::Boolean get_IsShowIronTombInfiniteUI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISSHOWIRONTOMBINFINITEUI_OFFSET))(this);
		}

		::Class_1_83665B095F1535B5_18* get_IronTombInfinityHPUIConfig()
		{
			return ((::Class_1_83665B095F1535B5_18*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_IRONTOMBINFINITYHPUICONFIG_OFFSET))(this);
		}

		::System::Void set_IronTombInfinityHPUIConfig(::Class_1_83665B095F1535B5_18* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_83665B095F1535B5_18*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_IRONTOMBINFINITYHPUICONFIG_OFFSET))(this, value);
		}

		::System::Boolean get_IsShowBossPluralityUI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISSHOWBOSSPLURALITYUI_OFFSET))(this);
		}

		::System::Void set_IsShowBossPluralityUI(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISSHOWBOSSPLURALITYUI_OFFSET))(this, value);
		}

		::System::Boolean get_IsForbidBattleConditionOnStart()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISFORBIDBATTLECONDITIONONSTART_OFFSET))(this);
		}

		::System::Void set_IsForbidBattleConditionOnStart(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISFORBIDBATTLECONDITIONONSTART_OFFSET))(this, value);
		}

		::System::Boolean get_ScorePanelShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_SCOREPANELSHOW_OFFSET))(this);
		}

		::System::Void set_ScorePanelShow(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_SCOREPANELSHOW_OFFSET))(this, value);
		}

		::System::Boolean get_BattleTargetMultiTargetSwitch()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLETARGETMULTITARGETSWITCH_OFFSET))(this);
		}

		::System::Void set_BattleTargetMultiTargetSwitch(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLETARGETMULTITARGETSWITCH_OFFSET))(this, value);
		}

		::RPG::GameCore::TrashSummonPeriodState get_TrashSummonPeriodState()
		{
			return ((::RPG::GameCore::TrashSummonPeriodState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_TRASHSUMMONPERIODSTATE_OFFSET))(this);
		}

		::System::Void set_TrashSummonPeriodState(::RPG::GameCore::TrashSummonPeriodState value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TrashSummonPeriodState))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_TRASHSUMMONPERIODSTATE_OFFSET))(this, value);
		}

		::Class_1_2FA40FF0BD34B01D* get_ActivityTelevisionBuffInfoInitParam()
		{
			return ((::Class_1_2FA40FF0BD34B01D*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIVITYTELEVISIONBUFFINFOINITPARAM_OFFSET))(this);
		}

		::System::Void set_ActivityTelevisionBuffInfoInitParam(::Class_1_2FA40FF0BD34B01D* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2FA40FF0BD34B01D*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIVITYTELEVISIONBUFFINFOINITPARAM_OFFSET))(this, value);
		}

		::Class_1_1D7B69991D584C07* get_BattleItemProgressInfoInitParam()
		{
			return ((::Class_1_1D7B69991D584C07*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEITEMPROGRESSINFOINITPARAM_OFFSET))(this);
		}

		::System::Void set_BattleItemProgressInfoInitParam(::Class_1_1D7B69991D584C07* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_1D7B69991D584C07*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEITEMPROGRESSINFOINITPARAM_OFFSET))(this, value);
		}

		::Class_1_5EB2C6616A5654C1* get_VersusBarData()
		{
			return ((::Class_1_5EB2C6616A5654C1*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_VERSUSBARDATA_OFFSET))(this);
		}

		::System::Void set_VersusBarData(::Class_1_5EB2C6616A5654C1* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_5EB2C6616A5654C1*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_VERSUSBARDATA_OFFSET))(this, value);
		}

		::Class_1_E54220BE5BFB3B20* get_VersusBarQuestData()
		{
			return ((::Class_1_E54220BE5BFB3B20*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_VERSUSBARQUESTDATA_OFFSET))(this);
		}

		::System::Void set_VersusBarQuestData(::Class_1_E54220BE5BFB3B20* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_E54220BE5BFB3B20*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_VERSUSBARQUESTDATA_OFFSET))(this, value);
		}

		::Class_1_945ACFB1FEBC7A2C_18* get_WeatherData()
		{
			return ((::Class_1_945ACFB1FEBC7A2C_18*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_WEATHERDATA_OFFSET))(this);
		}

		::System::Void set_WeatherData(::Class_1_945ACFB1FEBC7A2C_18* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_945ACFB1FEBC7A2C_18*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_WEATHERDATA_OFFSET))(this, value);
		}

		::Class_0_16E4307DCC419505_483* get_DawnsEyeWeatherData()
		{
			return ((::Class_0_16E4307DCC419505_483*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_DAWNSEYEWEATHERDATA_OFFSET))(this);
		}

		::System::Void set_DawnsEyeWeatherData(::Class_0_16E4307DCC419505_483* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_483*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_DAWNSEYEWEATHERDATA_OFFSET))(this, value);
		}

		::RPG::GameCore::BattlePauseEnvironmentInfos* get_PauseEnvironmentInfos()
		{
			return ((::RPG::GameCore::BattlePauseEnvironmentInfos*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_PAUSEENVIRONMENTINFOS_OFFSET))(this);
		}

		::System::Void set_PauseEnvironmentInfos(::RPG::GameCore::BattlePauseEnvironmentInfos* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::BattlePauseEnvironmentInfos*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_PAUSEENVIRONMENTINFOS_OFFSET))(this, value);
		}

		::Class_1_E12E73A35C16604A* get_BattleAlertMarkManager()
		{
			return ((::Class_1_E12E73A35C16604A*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEALERTMARKMANAGER_OFFSET))(this);
		}

		::System::Void set_BattleAlertMarkManager(::Class_1_E12E73A35C16604A* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_E12E73A35C16604A*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEALERTMARKMANAGER_OFFSET))(this, value);
		}

		::Class_1_AC4FF21662D4EBB2* get_BattleHintToastManager()
		{
			return ((::Class_1_AC4FF21662D4EBB2*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLEHINTTOASTMANAGER_OFFSET))(this);
		}

		::System::Void set_BattleHintToastManager(::Class_1_AC4FF21662D4EBB2* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_AC4FF21662D4EBB2*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLEHINTTOASTMANAGER_OFFSET))(this, value);
		}

		::UnityEngine::Vector2 get_BattleTargetDialogOffset()
		{
			return ((::UnityEngine::Vector2(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_BATTLETARGETDIALOGOFFSET_OFFSET))(this);
		}

		::System::Void set_BattleTargetDialogOffset(::UnityEngine::Vector2 value)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_BATTLETARGETDIALOGOFFSET_OFFSET))(this, value);
		}

		::System::Collections::Generic::List_1<::Class_1_7807B2B04302CD7B_21*>* get_ActivityTelevisionBuffInfoList()
		{
			return ((::System::Collections::Generic::List_1<::Class_1_7807B2B04302CD7B_21*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ACTIVITYTELEVISIONBUFFINFOLIST_OFFSET))(this);
		}

		::System::Void set_ActivityTelevisionBuffInfoList(::System::Collections::Generic::List_1<::Class_1_7807B2B04302CD7B_21*>* value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_1_7807B2B04302CD7B_21*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ACTIVITYTELEVISIONBUFFINFOLIST_OFFSET))(this, value);
		}

		::Class_1_BAF34E22336FA194* get_FeverTimeInfo()
		{
			return ((::Class_1_BAF34E22336FA194*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_FEVERTIMEINFO_OFFSET))(this);
		}

		::System::Void set_FeverTimeInfo(::Class_1_BAF34E22336FA194* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BAF34E22336FA194*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_FEVERTIMEINFO_OFFSET))(this, value);
		}

		::System::Boolean get_ShowChallengePeekCountDownEffect()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_SHOWCHALLENGEPEEKCOUNTDOWNEFFECT_OFFSET))(this);
		}

		::System::Void set_ShowChallengePeekCountDownEffect(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_SHOWCHALLENGEPEEKCOUNTDOWNEFFECT_OFFSET))(this, value);
		}

		::System::Boolean get_IsChallengePeakMissionUISizeMini()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_ISCHALLENGEPEAKMISSIONUISIZEMINI_OFFSET))(this);
		}

		::System::Void set_IsChallengePeakMissionUISizeMini(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_ISCHALLENGEPEAKMISSIONUISIZEMINI_OFFSET))(this, value);
		}

		::System::Boolean get_ShowChallengeStoryWavePanel()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_SHOWCHALLENGESTORYWAVEPANEL_OFFSET))(this);
		}

		::System::UInt32 get_PhainonActionCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_PHAINONACTIONCOUNT_OFFSET))(this);
		}

		::System::Void set_PhainonActionCount(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_SET_PHAINONACTIONCOUNT_OFFSET))(this, value);
		}

		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::Il2CppArray<::System::String*>*>* get_OverrideMonsterPhasePointPrefab()
		{
			return ((::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::Il2CppArray<::System::String*>*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_OVERRIDEMONSTERPHASEPOINTPREFAB_OFFSET))(this);
		}

		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::RPG::GameCore::FixPoint>* get_PreviewAddSP()
		{
			return ((::System::Collections::Generic::Dictionary_2<::RPG::GameCore::GameEntity*, ::RPG::GameCore::FixPoint>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT_GET_PREVIEWADDSP_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Tick(::System::Single P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT___IFIXBASEPROXY_TICK_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_LateUpdate(::System::Single P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_LEVELUICOMPONENT___IFIXBASEPROXY_LATEUPDATE_OFFSET))(this, P0);
		}
	};
}
