#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/AkCallbackType.h"
#include "unitysdk/RPG/Client/ReasonBool_1.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/Client/TriggerEffectCallbackParams.h"
#include "unitysdk/RPG/GameCore/AttackDamageType.h"
#include "unitysdk/RPG/GameCore/DisableBillboardReason.h"
#include "unitysdk/RPG/GameCore/ELevelPerformanceType.h"
#include "unitysdk/RPG/GameCore/ETriggerHintState.h"
#include "unitysdk/RPG/GameCore/EntityType.h"
#include "unitysdk/RPG/GameCore/FixPoint.h"
#include "unitysdk/RPG/GameCore/GameComponentBase.h"
#include "unitysdk/RPG/GameCore/LevelPerformanceHideType.h"
#include "unitysdk/RPG/GameCore/PropEventType.h"
#include "unitysdk/RPG/GameCore/PropInteractMode.h"
#include "unitysdk/RPG/GameCore/PropState.h"
#include "unitysdk/RPG/GameCore/PropType.h"
#include "unitysdk/RPG/GameCore/PuzzleDeactiveTag.h"
#include "unitysdk/RPG/GameCore/PuzzleUnloadTag.h"
#include "unitysdk/RPG/GameCore/RollShopGroupType.h"
#include "unitysdk/RPG/GameCore/SDFTextAlignType.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/UnityEngine/Color.h"
#include "unitysdk/UnityEngine/Vector3.h"

class AkCallbackInfo;
class Class_0_16E4307DCC419505_358;
class Class_0_16E4307DCC419505_401;
class Class_0_16E4307DCC419505_542;
class Class_0_16E4307DCC419505_543;
class Class_1_0245247C127EF1B6_1;
class Class_1_2A0CAE09F52620A0;
class Class_1_43BD383C98B4C0C5_122;
class Class_1_47F263CB5C51B1A3;
class Class_1_56221E821F588017;
class Class_1_5F51D4049EA87B7B;
class Class_1_5FEA23DE7B72218E;
class Class_1_83665B095F1535B5_19;
class Class_1_E5F3FA10EC56B9A0;
class Class_1_E5F3FA10EC56B9A0_1;
class Class_2_001AE252D7459BB9;
class Class_2_37D832480CB327E1;
class Class_2_712F0D5179511052;
class Class_2_7858266B34A2C48E;
class Class_2_911FE722F91DCE30;
class Class_2_F0C283D91BDD122E;
class Class_2_FD219B01AC2352E5;
class Class_3_07C3C4D2990C49EE;
namespace RPG::Client { class Effect_Transform; }
namespace RPG::Client { class IAssetOperation; }
namespace RPG::Client { class MapPropDef; }
namespace RPG::Client { class MaterialSwitchBehavior; }
namespace RPG::Client { class MonoDestructibleObject; }
namespace RPG::Client { class MonoEffect; }
namespace RPG::Client { class NavMeshStateConfig; }
namespace RPG::Client { class SceneTV; }
namespace RPG::Client { class SlotMachineController; }
namespace RPG::Client { class Wheel; }
namespace RPG::Client::Prop { class AdvMoneyManager; }
namespace RPG::Client::Prop { class PuzzleBoardBase; }
namespace RPG::GameCore { class ColliderTriggerComponent; }
namespace RPG::GameCore { class GameEntity; }
namespace RPG::GameCore { class JsonEnum; }
namespace RPG::GameCore { class LevelGraph; }
namespace RPG::GameCore { class PropButtonConfig; }
namespace RPG::GameCore { class PropConfig; }
namespace RPG::GameCore { class PropDayOfWeekComponent; }
namespace RPG::GameCore { class PropInitPuzzle; }
namespace RPG::GameCore { class PropRow; }
namespace RPG::GameCore { class PropStateConfig; }
namespace RPG::GameCore { class PropStateIcon; }
namespace RPG::GameCore { class SingleHitBoxConfig; }
namespace RPG::GameCore { class TaskConfig; }
namespace RPG::GameCore { class TaskContext; }
namespace RPG::GameCore { class TransformComponent; }
namespace System { class Action; }
namespace System { class Object; }
namespace System { class String; }
namespace System { template <typename T> class Action_1; }
namespace System::Collections { class IEnumerator; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class AnimationCurve; }
namespace UnityEngine { class Animator; }
namespace UnityEngine { class Collider; }
namespace UnityEngine { class Coroutine; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Texture; }
namespace UnityEngine { class Transform; }

#define RPG_GAMECORE_PROPCOMPONENT_ADDSTEERREQUEST_OFFSET UNITYSDK_OFFSET(0x14B2CBF0)
#define RPG_GAMECORE_PROPCOMPONENT_ADDTIMEREWINDSTRIKECALLBACK_OFFSET UNITYSDK_OFFSET(0x14B2DDF0)
#define RPG_GAMECORE_PROPCOMPONENT_APPLYCUSTOMEFFECTTRANSFORMPARAMS_OFFSET_OFFSET UNITYSDK_OFFSET(0x14B3C120)
#define RPG_GAMECORE_PROPCOMPONENT_APPLYCUSTOMEFFECTTRANSFORMPARAMS_ROTATE_OFFSET UNITYSDK_OFFSET(0x14B3C1D0)
#define RPG_GAMECORE_PROPCOMPONENT_BEGINDESTRUCTION_OFFSET UNITYSDK_OFFSET(0x14B388D0)
#define RPG_GAMECORE_PROPCOMPONENT_BEGINFADEIN_OFFSET UNITYSDK_OFFSET(0x14B2FB10)
#define RPG_GAMECORE_PROPCOMPONENT_CANCELPENDINGMAZEPUZZLESTART_OFFSET UNITYSDK_OFFSET(0x14B2BDE0)
#define RPG_GAMECORE_PROPCOMPONENT_CANCELPUZZLEASYNCLOADING_OFFSET UNITYSDK_OFFSET(0x14B2ABD0)
#define RPG_GAMECORE_PROPCOMPONENT_CANDAILYMINIMAPICONTINT_OFFSET UNITYSDK_OFFSET(0x14B39770)
#define RPG_GAMECORE_PROPCOMPONENT_CANSTATEMINIMAPICONTINT_OFFSET UNITYSDK_OFFSET(0x14B39850)
#define RPG_GAMECORE_PROPCOMPONENT_CLEARPUZZLE_OFFSET UNITYSDK_OFFSET(0x14B2A9B0)
#define RPG_GAMECORE_PROPCOMPONENT_DESTORYPUZZLE_OFFSET UNITYSDK_OFFSET(0x14B2B5C0)
#define RPG_GAMECORE_PROPCOMPONENT_DESTROYCUSTOMTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36CC0)
#define RPG_GAMECORE_PROPCOMPONENT_DESTROYPUZZLEOBJ_OFFSET UNITYSDK_OFFSET(0x14B2B370)
#define RPG_GAMECORE_PROPCOMPONENT_DESTROYSERVERSYNCTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B340E0)
#define RPG_GAMECORE_PROPCOMPONENT_DESTRUCTSHOWBEGIN_OFFSET UNITYSDK_OFFSET(0x14B389B0)
#define RPG_GAMECORE_PROPCOMPONENT_DISPOSETIMEREWINDSTRIKELISTENER_OFFSET UNITYSDK_OFFSET(0x14B2DF00)
#define RPG_GAMECORE_PROPCOMPONENT_DISPOSE_OFFSET UNITYSDK_OFFSET(0x14B33870)
#define RPG_GAMECORE_PROPCOMPONENT_DISTORYTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B3A5F0)
#define RPG_GAMECORE_PROPCOMPONENT_ENABLETRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36320)
#define RPG_GAMECORE_PROPCOMPONENT_ENDPROPINTERACT_OFFSET UNITYSDK_OFFSET(0x14B3A2F0)
#define RPG_GAMECORE_PROPCOMPONENT_FINISHADVANCEINTERACT_OFFSET UNITYSDK_OFFSET(0x14B3A920)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYICON_OFFSET UNITYSDK_OFFSET(0x14B39430)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYMINIMAPICONCOLOR_OFFSET UNITYSDK_OFFSET(0x14B396C0)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYMINIMAPICON_OFFSET UNITYSDK_OFFSET(0x14B393D0)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEANCHORKEY_OFFSET UNITYSDK_OFFSET(0x14B39080)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEICON_OFFSET UNITYSDK_OFFSET(0x14B390E0)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEMINIMAPICONCOLOR_OFFSET UNITYSDK_OFFSET(0x14B39360)
#define RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEMINIMAPICON_OFFSET UNITYSDK_OFFSET(0x14B39300)
#define RPG_GAMECORE_PROPCOMPONENT_GETDESTROYAFTEREVENT_OFFSET UNITYSDK_OFFSET(0x14B38770)
#define RPG_GAMECORE_PROPCOMPONENT_GETENTITYTAG_OFFSET UNITYSDK_OFFSET(0x14B3AAD0)
#define RPG_GAMECORE_PROPCOMPONENT_GETMOVEMENT_OFFSET UNITYSDK_OFFSET(0x14B35C30)
#define RPG_GAMECORE_PROPCOMPONENT_GETORIGINALYAWANGLE_OFFSET UNITYSDK_OFFSET(0x14B2CBA0)
#define RPG_GAMECORE_PROPCOMPONENT_GETPUZZLEINITCONFIG_OFFSET UNITYSDK_OFFSET(0x14B2BBF0)
#define RPG_GAMECORE_PROPCOMPONENT_GETTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36D70)
#define RPG_GAMECORE_PROPCOMPONENT_GETWHEELCURVEDATA_OFFSET UNITYSDK_OFFSET(0x14B327D0)
#define RPG_GAMECORE_PROPCOMPONENT_GETWHEELDATA_OFFSET UNITYSDK_OFFSET(0x14B32660)
#define RPG_GAMECORE_PROPCOMPONENT_GETWHEELDURATION_OFFSET UNITYSDK_OFFSET(0x14B324D0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ATTACHPUZZLEBOARD_OFFSET UNITYSDK_OFFSET(0x14B2CAC0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_COCOONID_OFFSET UNITYSDK_OFFSET(0x14B3CDB0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_CURSTATECONFIG_OFFSET UNITYSDK_OFFSET(0x14B3C660)
#define RPG_GAMECORE_PROPCOMPONENT_GET_EFFECTHIDE_OFFSET UNITYSDK_OFFSET(0x14B3A3D0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ENABLEBILLBOARD_OFFSET UNITYSDK_OFFSET(0x14B3CB40)
#define RPG_GAMECORE_PROPCOMPONENT_GET_EVENTCONTEXT_OFFSET UNITYSDK_OFFSET(0x14B3CA80)
#define RPG_GAMECORE_PROPCOMPONENT_GET_HIDEINPERFORMANCE_OFFSET UNITYSDK_OFFSET(0x14B39920)
#define RPG_GAMECORE_PROPCOMPONENT_GET_HITBOX_OFFSET UNITYSDK_OFFSET(0x14B3C6D0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_HP_OFFSET UNITYSDK_OFFSET(0x14B3C2A0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTICONTYPE_OFFSET UNITYSDK_OFFSET(0x14B3CB10)
#define RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTIVEOVERRIDEDATA_OFFSET UNITYSDK_OFFSET(0x14B3CD90)
#define RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTMODE_OFFSET UNITYSDK_OFFSET(0x14B3CD70)
#define RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTTITLE_OFFSET UNITYSDK_OFFSET(0x14B3CAD0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISCAPTURED_OFFSET UNITYSDK_OFFSET(0x14B3CB90)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISDAMAGEABLE_OFFSET UNITYSDK_OFFSET(0x14B387C0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISDAYOFWEEKPROP_OFFSET UNITYSDK_OFFSET(0x14B3B090)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISDESTRUCTED_OFFSET UNITYSDK_OFFSET(0x14B3C320)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISDESTRUCTRESOURCE_OFFSET UNITYSDK_OFFSET(0x14B37DB0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISINDESTRUCT_OFFSET UNITYSDK_OFFSET(0x14B3C300)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISLIFERUNOUT_OFFSET UNITYSDK_OFFSET(0x14B3C740)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISMOVEABLE_OFFSET UNITYSDK_OFFSET(0x14B3CAB0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ISPRESHOWDESTRUCT_OFFSET UNITYSDK_OFFSET(0x14B3C340)
#define RPG_GAMECORE_PROPCOMPONENT_GET_JSONCONFIG_OFFSET UNITYSDK_OFFSET(0x14B3C6B0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_LIFETIME_OFFSET UNITYSDK_OFFSET(0x14B3C2E0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_MAPPROPDEF_OFFSET UNITYSDK_OFFSET(0x14B3C7E0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_MAXHP_OFFSET UNITYSDK_OFFSET(0x14B3C2C0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ONCREATECONFIG_OFFSET UNITYSDK_OFFSET(0x14B3CA90)
#define RPG_GAMECORE_PROPCOMPONENT_GET_OWNERABILITYINSTANCE_OFFSET UNITYSDK_OFFSET(0x14B3C7F0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PLAYERLOCKABLE_OFFSET UNITYSDK_OFFSET(0x14B3C650)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PROPNAME_OFFSET UNITYSDK_OFFSET(0x14B3CA60)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PROPNAVMESHSTATECONFIG_OFFSET UNITYSDK_OFFSET(0x14B33060)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PROPSTATE_OFFSET UNITYSDK_OFFSET(0x14B3A840)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PROPTEXTIDNAME_OFFSET UNITYSDK_OFFSET(0x14B3C3B0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_PROPTYPE_OFFSET UNITYSDK_OFFSET(0x14B35590)
#define RPG_GAMECORE_PROPCOMPONENT_GET_REALTIMEPLAYERLOCKABLE_OFFSET UNITYSDK_OFFSET(0x14B27FD0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ROLLSHOPREWARDRESULT_OFFSET UNITYSDK_OFFSET(0x14B318A0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_ROWREF_OFFSET UNITYSDK_OFFSET(0x14B3C690)
#define RPG_GAMECORE_PROPCOMPONENT_GET_SCALE_OFFSET UNITYSDK_OFFSET(0x14B3C760)
#define RPG_GAMECORE_PROPCOMPONENT_GET_SERVERENTITYID_OFFSET UNITYSDK_OFFSET(0x14B3C6F0)
#define RPG_GAMECORE_PROPCOMPONENT_GET_STATICPROP_OFFSET UNITYSDK_OFFSET(0x14B3C670)
#define RPG_GAMECORE_PROPCOMPONENT_GET__HINTSTATE_OFFSET UNITYSDK_OFFSET(0x14B3CED0)
#define RPG_GAMECORE_PROPCOMPONENT_INITCOMPONENT_OFFSET UNITYSDK_OFFSET(0x14B34BF0)
#define RPG_GAMECORE_PROPCOMPONENT_INITIALIZEPROPSTATE_OFFSET UNITYSDK_OFFSET(0x14B35880)
#define RPG_GAMECORE_PROPCOMPONENT_INITINVISIBLE_OFFSET UNITYSDK_OFFSET(0x14B2FC80)
#define RPG_GAMECORE_PROPCOMPONENT_INITPUZZLE_OFFSET UNITYSDK_OFFSET(0x14B2AD50)
#define RPG_GAMECORE_PROPCOMPONENT_ISDAMAGEABLEWITHENTITYTYPE_OFFSET UNITYSDK_OFFSET(0x14B28C90)
#define RPG_GAMECORE_PROPCOMPONENT_ISDAMAGEABLEWITHTYPE_OFFSET UNITYSDK_OFFSET(0x14B28D70)
#define RPG_GAMECORE_PROPCOMPONENT_ISHIDEBYPERFORMANCETYPE_OFFSET UNITYSDK_OFFSET(0x14B39990)
#define RPG_GAMECORE_PROPCOMPONENT_ISPUZZLEASYNCLOADING_OFFSET UNITYSDK_OFFSET(0x14B2AC60)
#define RPG_GAMECORE_PROPCOMPONENT_ISSTATEICONSNULL_OFFSET UNITYSDK_OFFSET(0x14B392B0)
#define RPG_GAMECORE_PROPCOMPONENT_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0x14B36240)
#define RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLEAREA_1_OFFSET UNITYSDK_OFFSET(0x14B2C960)
#define RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLEAREA_OFFSET UNITYSDK_OFFSET(0x14B2BE30)
#define RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLE_OFFSET UNITYSDK_OFFSET(0x14B2B950)
#define RPG_GAMECORE_PROPCOMPONENT_ONBEFOREDESTORY_OFFSET UNITYSDK_OFFSET(0x14B35660)
#define RPG_GAMECORE_PROPCOMPONENT_ONBEHIT_OFFSET UNITYSDK_OFFSET(0x14B375D0)
#define RPG_GAMECORE_PROPCOMPONENT_ONCREATE_OFFSET UNITYSDK_OFFSET(0x14B38430)
#define RPG_GAMECORE_PROPCOMPONENT_ONDESTRUCTIONCALLBACK_OFFSET UNITYSDK_OFFSET(0x14B356C0)
#define RPG_GAMECORE_PROPCOMPONENT_ONMODELARTLOADED_OFFSET UNITYSDK_OFFSET(0x14B2EC20)
#define RPG_GAMECORE_PROPCOMPONENT_ONMODELARTUNLOADED_OFFSET UNITYSDK_OFFSET(0x14B30220)
#define RPG_GAMECORE_PROPCOMPONENT_ONMODELROOTLOADED_OFFSET UNITYSDK_OFFSET(0x14B2E830)
#define RPG_GAMECORE_PROPCOMPONENT_ONMODELROOTUNLOADED_OFFSET UNITYSDK_OFFSET(0x14B2EAE0)
#define RPG_GAMECORE_PROPCOMPONENT_ONRECONNECTSTART_OFFSET UNITYSDK_OFFSET(0x14B3A8A0)
#define RPG_GAMECORE_PROPCOMPONENT_PLAYERLOCKABLEANIMLIMITS_OFFSET UNITYSDK_OFFSET(0x14B3C500)
#define RPG_GAMECORE_PROPCOMPONENT_PLAYERLOCKABLESPECBYCONFIG_OFFSET UNITYSDK_OFFSET(0x14B3C4A0)
#define RPG_GAMECORE_PROPCOMPONENT_POSTSOUNDEVENT_OFFSET UNITYSDK_OFFSET(0x14B30E00)
#define RPG_GAMECORE_PROPCOMPONENT_PREINITCOMPONENT_OFFSET UNITYSDK_OFFSET(0x14B34BA0)
#define RPG_GAMECORE_PROPCOMPONENT_PROPDESTRUCTION_OFFSET UNITYSDK_OFFSET(0x14B37E30)
#define RPG_GAMECORE_PROPCOMPONENT_RECOVERAFTERMISSIONFINISH_OFFSET UNITYSDK_OFFSET(0x14B362D0)
#define RPG_GAMECORE_PROPCOMPONENT_REFRESHPALYERLOCKABLE_OFFSET UNITYSDK_OFFSET(0x14B30080)
#define RPG_GAMECORE_PROPCOMPONENT_RELEASEDECALPROP_OFFSET UNITYSDK_OFFSET(0x14B30920)
#define RPG_GAMECORE_PROPCOMPONENT_REMOVESOUNDEVENT_OFFSET UNITYSDK_OFFSET(0x14B31510)
#define RPG_GAMECORE_PROPCOMPONENT_REQUIREDAYOFWEEK_OFFSET UNITYSDK_OFFSET(0x14B35410)
#define RPG_GAMECORE_PROPCOMPONENT_REQUIREFARMELEMENT_OFFSET UNITYSDK_OFFSET(0x14B35D30)
#define RPG_GAMECORE_PROPCOMPONENT_REQUIREMOVEMENT_OFFSET UNITYSDK_OFFSET(0x14B35080)
#define RPG_GAMECORE_PROPCOMPONENT_REQUIRESHADERCTRL_OFFSET UNITYSDK_OFFSET(0x14B35360)
#define RPG_GAMECORE_PROPCOMPONENT_RESETDESTRUCTION_OFFSET UNITYSDK_OFFSET(0x14B306B0)
#define RPG_GAMECORE_PROPCOMPONENT_RESETSLOTMACHINE_OFFSET UNITYSDK_OFFSET(0x14B32B90)
#define RPG_GAMECORE_PROPCOMPONENT_RESETTODEFAULT_OFFSET UNITYSDK_OFFSET(0x14B3CEE0)
#define RPG_GAMECORE_PROPCOMPONENT_ROLLBACKADVANCEINTERACT_OFFSET UNITYSDK_OFFSET(0x14B34B50)
#define RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_ICONPATH_OFFSET UNITYSDK_OFFSET(0x14B3CCE0)
#define RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_RUNTIMEID_OFFSET UNITYSDK_OFFSET(0x14B3CBB0)
#define RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_TEXTID_OFFSET UNITYSDK_OFFSET(0x14B3CBD0)
#define RPG_GAMECORE_PROPCOMPONENT_SAFEDESTROY_OFFSET UNITYSDK_OFFSET(0x14B3A1B0)
#define RPG_GAMECORE_PROPCOMPONENT_SETCANPLAYERLOCK_OFFSET UNITYSDK_OFFSET(0x14B3C000)
#define RPG_GAMECORE_PROPCOMPONENT_SETCASTEFFECTHIDESTATE_OFFSET UNITYSDK_OFFSET(0x14B3A3F0)
#define RPG_GAMECORE_PROPCOMPONENT_SETDESTROYAFTEREVENT_OFFSET UNITYSDK_OFFSET(0x14B38700)
#define RPG_GAMECORE_PROPCOMPONENT_SETENABLEBILLBOARD_OFFSET UNITYSDK_OFFSET(0x14B3AA60)
#define RPG_GAMECORE_PROPCOMPONENT_SETHINTSTATE_OFFSET UNITYSDK_OFFSET(0x14B363F0)
#define RPG_GAMECORE_PROPCOMPONENT_SETLIFETIME_OFFSET UNITYSDK_OFFSET(0x14B3C060)
#define RPG_GAMECORE_PROPCOMPONENT_SETMONOWAVINGBLOCKCONTROLFLOORID_OFFSET UNITYSDK_OFFSET(0x14B30BA0)
#define RPG_GAMECORE_PROPCOMPONENT_SETORIGINALORIENTATION_OFFSET UNITYSDK_OFFSET(0x14B2CAE0)
#define RPG_GAMECORE_PROPCOMPONENT_SETPENDINGMAZEPUZZLECHALLENGECONFIG_OFFSET UNITYSDK_OFFSET(0x14B2BD40)
#define RPG_GAMECORE_PROPCOMPONENT_SETPENDINGMAZEPUZZLESTART_OFFSET UNITYSDK_OFFSET(0x14B2BD90)
#define RPG_GAMECORE_PROPCOMPONENT_SETPROPDEF_OFFSET UNITYSDK_OFFSET(0x14B355F0)
#define RPG_GAMECORE_PROPCOMPONENT_SETPUZZLEACTIVE_OFFSET UNITYSDK_OFFSET(0x14B2BC40)
#define RPG_GAMECORE_PROPCOMPONENT_SETPUZZLE_OFFSET UNITYSDK_OFFSET(0x14B2A940)
#define RPG_GAMECORE_PROPCOMPONENT_SETSCENETVMENUID_OFFSET UNITYSDK_OFFSET(0x14B32E30)
#define RPG_GAMECORE_PROPCOMPONENT_SETSDFTEXTSCALE_OFFSET UNITYSDK_OFFSET(0x14B30D20)
#define RPG_GAMECORE_PROPCOMPONENT_SETSDFTEXT_OFFSET UNITYSDK_OFFSET(0x14B30C00)
#define RPG_GAMECORE_PROPCOMPONENT_SETSLOTMACHINE_OFFSET UNITYSDK_OFFSET(0x14B32950)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPCUSTOMEFFECTTRANSFORMPARAMS_OFFSET UNITYSDK_OFFSET(0x14B3AE50)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPCUSTOMTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36B80)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPDECALPROP_OFFSET UNITYSDK_OFFSET(0x14B2F870)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPEVENTSEQUENCE_OFFSET UNITYSDK_OFFSET(0x14B37370)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPHITBOXCOLLECTION_OFFSET UNITYSDK_OFFSET(0x14B36DF0)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPHITBOX_OFFSET UNITYSDK_OFFSET(0x14B35200)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPINTERACTIONTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36580)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPOPTIONTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B364C0)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPSERVERSYNCTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B36690)
#define RPG_GAMECORE_PROPCOMPONENT_SETUPTRIGGER_OFFSET UNITYSDK_OFFSET(0x14B3A590)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ATTACHPUZZLEBOARD_OFFSET UNITYSDK_OFFSET(0x14B2CAD0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_EFFECTHIDE_OFFSET UNITYSDK_OFFSET(0x14B3A3E0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_HITBOX_OFFSET UNITYSDK_OFFSET(0x14B3C6E0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_HP_OFFSET UNITYSDK_OFFSET(0x14B3C2B0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_INTERACTIVEOVERRIDEDATA_OFFSET UNITYSDK_OFFSET(0x14B3CDA0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_INTERACTMODE_OFFSET UNITYSDK_OFFSET(0x14B3CD80)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ISCAPTURED_OFFSET UNITYSDK_OFFSET(0x14B3CBA0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ISDESTRUCTED_OFFSET UNITYSDK_OFFSET(0x14B3C330)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ISINDESTRUCT_OFFSET UNITYSDK_OFFSET(0x14B3C310)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ISMOVEABLE_OFFSET UNITYSDK_OFFSET(0x14B3CAC0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_JSONCONFIG_OFFSET UNITYSDK_OFFSET(0x14B3C6C0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_LIFETIME_OFFSET UNITYSDK_OFFSET(0x14B3C2F0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_MAXHP_OFFSET UNITYSDK_OFFSET(0x14B3C2D0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ONCREATECONFIG_OFFSET UNITYSDK_OFFSET(0x14B3CAA0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_OWNERABILITYINSTANCE_OFFSET UNITYSDK_OFFSET(0x14B3C820)
#define RPG_GAMECORE_PROPCOMPONENT_SET_PROPNAME_OFFSET UNITYSDK_OFFSET(0x14B3CA70)
#define RPG_GAMECORE_PROPCOMPONENT_SET_PROPNAVMESHSTATECONFIG_OFFSET UNITYSDK_OFFSET(0x14B33070)
#define RPG_GAMECORE_PROPCOMPONENT_SET_PROPSTATE_OFFSET UNITYSDK_OFFSET(0x14B3C350)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ROLLSHOPREWARDRESULT_OFFSET UNITYSDK_OFFSET(0x14B318B0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_ROWREF_OFFSET UNITYSDK_OFFSET(0x14B3C6A0)
#define RPG_GAMECORE_PROPCOMPONENT_SET_STATICPROP_OFFSET UNITYSDK_OFFSET(0x14B3C680)
#define RPG_GAMECORE_PROPCOMPONENT_SET__HINTSTATE_OFFSET UNITYSDK_OFFSET(0x14B3BF80)
#define RPG_GAMECORE_PROPCOMPONENT_SHOULDPUZZLEINIT_OFFSET UNITYSDK_OFFSET(0x14B2AA10)
#define RPG_GAMECORE_PROPCOMPONENT_SHOWHINT_OFFSET UNITYSDK_OFFSET(0x14B347D0)
#define RPG_GAMECORE_PROPCOMPONENT_SPAWNMONEY_OFFSET UNITYSDK_OFFSET(0x14B33240)
#define RPG_GAMECORE_PROPCOMPONENT_STARTADVANCEINTERACT_OFFSET UNITYSDK_OFFSET(0x14B3A640)
#define RPG_GAMECORE_PROPCOMPONENT_STARTPROPINTERACT_OFFSET UNITYSDK_OFFSET(0x14B3A210)
#define RPG_GAMECORE_PROPCOMPONENT_STARTSLOTMACHINE_OFFSET UNITYSDK_OFFSET(0x14B318C0)
#define RPG_GAMECORE_PROPCOMPONENT_STOPSLOTMACHINE_OFFSET UNITYSDK_OFFSET(0x14B2E590)
#define RPG_GAMECORE_PROPCOMPONENT_STOPSTEERREQUEST_OFFSET UNITYSDK_OFFSET(0x14B2D060)
#define RPG_GAMECORE_PROPCOMPONENT_STOPTIMEREWINDSTRIKECALLBACK_OFFSET UNITYSDK_OFFSET(0x14B2DEA0)
#define RPG_GAMECORE_PROPCOMPONENT_SWITCHMATERIALGROUP_OFFSET UNITYSDK_OFFSET(0x14B32F60)
#define RPG_GAMECORE_PROPCOMPONENT_TICK_OFFSET UNITYSDK_OFFSET(0x14B35DA0)
#define RPG_GAMECORE_PROPCOMPONENT_TRYGETSLOTMACHINECONTROLLER_OFFSET UNITYSDK_OFFSET(0x14B32D20)
#define RPG_GAMECORE_PROPCOMPONENT_TRYPOSTCACHESOUNDEVENT_OFFSET UNITYSDK_OFFSET(0x14B39A40)
#define RPG_GAMECORE_PROPCOMPONENT_TRYSETUPEVENTSEQUENCE_OFFSET UNITYSDK_OFFSET(0x14B38840)
#define RPG_GAMECORE_PROPCOMPONENT_TRYSTOPCACHESOUNDEVENT_OFFSET UNITYSDK_OFFSET(0x14B316C0)
#define RPG_GAMECORE_PROPCOMPONENT_TRYTRIGGERPUZZLETUTORIALWHENINIT_OFFSET UNITYSDK_OFFSET(0x14B2AB40)
#define RPG_GAMECORE_PROPCOMPONENT_UNLOADEVENTSEQUENCE_OFFSET UNITYSDK_OFFSET(0x14B37520)
#define RPG_GAMECORE_PROPCOMPONENT_UNLOADHITBOXCOLLECTION_OFFSET UNITYSDK_OFFSET(0x14B371D0)
#define RPG_GAMECORE_PROPCOMPONENT_UNLOADHITBOX_OFFSET UNITYSDK_OFFSET(0x14B374C0)
#define RPG_GAMECORE_PROPCOMPONENT_UNLOADPUZZLEAREA_1_OFFSET UNITYSDK_OFFSET(0x14B2CA70)
#define RPG_GAMECORE_PROPCOMPONENT_UNLOADPUZZLEAREA_OFFSET UNITYSDK_OFFSET(0x14B2C0D0)
#define RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTARTROTATETO_OFFSET UNITYSDK_OFFSET(0x14B33110)
#define RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTARTROTATE_OFFSET UNITYSDK_OFFSET(0x14B33080)
#define RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTOPROTATE_OFFSET UNITYSDK_OFFSET(0x14B331D0)
#define RPG_GAMECORE_PROPCOMPONENT__APPLYCUSTOMEFFECTTRANSFORMPARAMS_OFFSET UNITYSDK_OFFSET(0x14B2FD60)
#define RPG_GAMECORE_PROPCOMPONENT__ATTACHPUZZLEOBJ_OFFSET UNITYSDK_OFFSET(0x14B2C2A0)
#define RPG_GAMECORE_PROPCOMPONENT__CCTOR_OFFSET UNITYSDK_OFFSET(0x14B3D500)
#define RPG_GAMECORE_PROPCOMPONENT__CHECKLAYER_OFFSET UNITYSDK_OFFSET(0x14B32EA0)
#define RPG_GAMECORE_PROPCOMPONENT__CTOR_OFFSET UNITYSDK_OFFSET(0x14B33370)
#define RPG_GAMECORE_PROPCOMPONENT__DELAYDOGACHAINROLLSHOP_OFFSET UNITYSDK_OFFSET(0x14B31D80)
#define RPG_GAMECORE_PROPCOMPONENT__DESTROYPUZZLEBOARD_OFFSET UNITYSDK_OFFSET(0x14B2B4B0)
#define RPG_GAMECORE_PROPCOMPONENT__DESTROYSELF_OFFSET UNITYSDK_OFFSET(0x14B36130)
#define RPG_GAMECORE_PROPCOMPONENT__FILLEVENTCONTEXT_OFFSET UNITYSDK_OFFSET(0x14B3AFD0)
#define RPG_GAMECORE_PROPCOMPONENT__GETFINALTARGETTRANSFORM_OFFSET UNITYSDK_OFFSET(0x14B2DD50)
#define RPG_GAMECORE_PROPCOMPONENT__GETHINTEFFECTATTACHPOINT_OFFSET UNITYSDK_OFFSET(0x14B3B7C0)
#define RPG_GAMECORE_PROPCOMPONENT__GETHINTEFFECTPATH_OFFSET UNITYSDK_OFFSET(0x14B3B6F0)
#define RPG_GAMECORE_PROPCOMPONENT__INITDEFAULTCUSTOMEFFECTTRANSFORMPARAMSIFNEEDED_OFFSET UNITYSDK_OFFSET(0x14B3AD00)
#define RPG_GAMECORE_PROPCOMPONENT__INITVIEWS_OFFSET UNITYSDK_OFFSET(0x14B2DFA0)
#define RPG_GAMECORE_PROPCOMPONENT__ONDESTRUCTIONFINISHED_OFFSET UNITYSDK_OFFSET(0x14B3AEB0)
#define RPG_GAMECORE_PROPCOMPONENT__ONDOGACHAINROLLSHOPSCRSP_OFFSET UNITYSDK_OFFSET(0x14B31A30)
#define RPG_GAMECORE_PROPCOMPONENT__ONENTERSTATE_OFFSET UNITYSDK_OFFSET(0x14B358E0)
#define RPG_GAMECORE_PROPCOMPONENT__ONGETPUZZLEASSET_OFFSET UNITYSDK_OFFSET(0x14B2AF30)
#define RPG_GAMECORE_PROPCOMPONENT__ONINITOWNERREF_OFFSET UNITYSDK_OFFSET(0x14B33790)
#define RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREALOADFADEINFINISH_OFFSET UNITYSDK_OFFSET(0x14B2BEE0)
#define RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREALOADFADEOUTFINISH_OFFSET UNITYSDK_OFFSET(0x14B2BA10)
#define RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREAUNLOADFADEINFINISH_OFFSET UNITYSDK_OFFSET(0x14B2C170)
#define RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREAUNLOADFADEOUTFINISH_OFFSET UNITYSDK_OFFSET(0x14B2B7F0)
#define RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEASSETLOAD_OFFSET UNITYSDK_OFFSET(0x14B2BF30)
#define RPG_GAMECORE_PROPCOMPONENT__ONSOUNDEVENTCALLBACK_OFFSET UNITYSDK_OFFSET(0x14B31640)
#define RPG_GAMECORE_PROPCOMPONENT__ONSYNCTRIGGERCHANGE_OFFSET UNITYSDK_OFFSET(0x14B3B890)
#define RPG_GAMECORE_PROPCOMPONENT__POSTSOUNDEVENT_OFFSET UNITYSDK_OFFSET(0x14B311D0)
#define RPG_GAMECORE_PROPCOMPONENT__RECORDPLAYINGSOUND_OFFSET UNITYSDK_OFFSET(0x14B31130)
#define RPG_GAMECORE_PROPCOMPONENT__SETUPSTATICFLAG_OFFSET UNITYSDK_OFFSET(0x14B354A0)
#define RPG_GAMECORE_PROPCOMPONENT__SHOWHINT_B__209_0_OFFSET UNITYSDK_OFFSET(0x14B3D580)
#define RPG_GAMECORE_PROPCOMPONENT__STARTSEQUENCE_OFFSET UNITYSDK_OFFSET(0x14B38140)
#define RPG_GAMECORE_PROPCOMPONENT__SYNCPROPSTATETOEFFECTANIMATORS_OFFSET UNITYSDK_OFFSET(0x14B3B590)
#define RPG_GAMECORE_PROPCOMPONENT__TICKSEQUENCE_OFFSET UNITYSDK_OFFSET(0x14B35F20)
#define RPG_GAMECORE_PROPCOMPONENT__TICKVIEWS_OFFSET UNITYSDK_OFFSET(0x14B2E710)
#define RPG_GAMECORE_PROPCOMPONENT__TRYDISPOSEEFFECTPLUGINCOMPONENTS_OFFSET UNITYSDK_OFFSET(0x14B30A40)
#define RPG_GAMECORE_PROPCOMPONENT__TRYRESETEFFECTPLUGINCOMPONENTS_OFFSET UNITYSDK_OFFSET(0x14B2F6A0)
#define RPG_GAMECORE_PROPCOMPONENT__TRYREVERTDEFAULTEFFECTTRANSFORMPARAMS_OFFSET UNITYSDK_OFFSET(0x14B30980)
#define RPG_GAMECORE_PROPCOMPONENT__UNINITVIEWS_OFFSET UNITYSDK_OFFSET(0x14B2E2F0)
#define RPG_GAMECORE_PROPCOMPONENT__UNLOADPUZZLEAREA_OFFSET UNITYSDK_OFFSET(0x14B2C1C0)
#define RPG_GAMECORE_PROPCOMPONENT__UPDATESTATEICONS_OFFSET UNITYSDK_OFFSET(0x14B34EA0)
#define RPG_GAMECORE_PROPCOMPONENT__UPDATESTEER_OFFSET UNITYSDK_OFFSET(0x14B2D260)
#define RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY_LATEUPDATE_OFFSET UNITYSDK_OFFSET(0x14B3D610)
#define RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY_TICK_OFFSET UNITYSDK_OFFSET(0x14B3D600)
#define RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY__ONINITOWNERREF_OFFSET UNITYSDK_OFFSET(0x14B3D5A0)

namespace RPG::GameCore
{
	inline static constexpr unsigned int PropComponent_TypeDefinitionIndex = 53584;

	class PropComponent : public ::RPG::GameCore::GameComponentBase
	{
	public:
		static ::System::String** StaticGet_TRIGGER_PATH()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(PropComponent_TypeDefinitionIndex)->GetStaticField(0x16BA0);
		}
		static ::System::Collections::Generic::List_1<::System::String*>** StaticGet__SoundEventList()
		{
			return (::System::Collections::Generic::List_1<::System::String*>**)Il2CppClass::FromTypeDefinitionIndex(PropComponent_TypeDefinitionIndex)->GetStaticField(0x16BA8);
		}
		static ::System::String** StaticGet_MazeSkillPropTriggerName()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(PropComponent_TypeDefinitionIndex)->GetStaticField(0x16BB0);
		}
		static ::System::Int32* StaticGet_MainTexPropertyID()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(PropComponent_TypeDefinitionIndex)->GetStaticField(0x8020);
		}
		static ::System::Single* StaticGet_ANGLE_TOLERANCE()
		{
			return (::System::Single*)Il2CppClass::FromTypeDefinitionIndex(PropComponent_TypeDefinitionIndex)->GetStaticField(0x8024);
		}
		::Class_2_37D832480CB327E1* _Movement; // 0x18
		::RPG::Client::SceneTV* _SceneTV; // 0x20
		::RPG::GameCore::TransformComponent* _TargetTransform; // 0x28
		::Class_2_7858266B34A2C48E* _FarmElement; // 0x30
		::System::String* _PuzzleArea; // 0x38
		::System::Collections::Generic::Dictionary_2<::System::String*, ::AkCallbackType>* _WaitPlayingOnceSoundEvent; // 0x40
		::UnityEngine::GameObject* _PuzzleAsset; // 0x48
		::UnityEngine::Coroutine* _DelayGachaHandler; // 0x50
		::System::String* _PuzzleAssetPath; // 0x58
		::System::Collections::Generic::Dictionary_2<::System::String*, ::Class_0_16E4307DCC419505_542*>* _ServerSyncTriggerName; // 0x60
		::RPG::Client::MapPropDef* _mapPropDef; // 0x68
		::Class_2_FD219B01AC2352E5* _WavingBlockControlView; // 0x70
		::RPG::GameCore::PropRow* _RowRef_k__BackingField; // 0x78
		::RPG::Client::NavMeshStateConfig* _PropNavMeshStateConfig_k__BackingField; // 0x80
		::RPG::GameCore::TransformComponent* _OwnerTransform; // 0x88
		::Class_1_43BD383C98B4C0C5_122* _DefaultCustomEffectTransformParams_Offset; // 0x90
		::System::Collections::Generic::Dictionary_2<::System::String*, ::AkCallbackType>* _CurrentSourndEvent; // 0x98
		::System::Action* _OnDestructionFinishCallback; // 0xA0
		::System::Collections::Generic::Dictionary_2<::System::String*, ::RPG::GameCore::PropButtonConfig*>* RuntimeOverridePropButtonConfigs; // 0xA8
		::System::Collections::Generic::Dictionary_2<::System::String*, ::Class_1_47F263CB5C51B1A3*>* _ServerSyncTriggerDestroy; // 0xB0
		::Class_1_83665B095F1535B5_19* _EventContext_k__BackingField; // 0xB8
		::System::Collections::Generic::List_1<::System::Int32>* _SlotResult; // 0xC0
		::System::String* _PropName_k__BackingField; // 0xC8
		::Class_1_43BD383C98B4C0C5_122* _DefaultCustomEffectTransformParams_Rotate; // 0xD0
		::RPG::Client::Effect_Transform* _EffectTransform; // 0xD8
		::System::Collections::Generic::List_1<::Class_1_E5F3FA10EC56B9A0*>* _RootModelViews; // 0xE0
		::System::Collections::Generic::Dictionary_2<::System::String*, ::AkCallbackType>* _CurrentPlayingSoundEvent; // 0xE8
		::UnityEngine::Collider* _HitBox_k__BackingField; // 0xF0
		::Class_1_2A0CAE09F52620A0* TimeRewindStrikeListener; // 0xF8
		::RPG::Client::IAssetOperation* _PuzzleAssetAsyncLoadHandle; // 0x100
		::System::String* _DefaultTriggerPath; // 0x108
		::RPG::GameCore::ColliderTriggerComponent* _TriggerComponent; // 0x110
		::Class_2_001AE252D7459BB9* _SDFTextView; // 0x118
		::Class_2_712F0D5179511052* _SceneTVView; // 0x120
		::RPG::Client::Prop::PuzzleBoardBase* _AttachPuzzleBoard_k__BackingField; // 0x128
		::Class_1_43BD383C98B4C0C5_122* _CustomEffectTransformParams; // 0x130
		::RPG::GameCore::TaskContext* _TaskContext; // 0x138
		::RPG::Client::Prop::AdvMoneyManager* _AdvMoneyManager; // 0x140
		::Il2CppArray<::Class_0_16E4307DCC419505_543*>* _ResetEffectPlugins; // 0x148
		::System::String* ExternalButtonIcon; // 0x150
		::System::Collections::Generic::List_1<::Class_1_E5F3FA10EC56B9A0_1*>* _ArtModelViews; // 0x158
		::Class_1_5FEA23DE7B72218E* _Request; // 0x160
		::Il2CppArray<::Class_3_07C3C4D2990C49EE*>* _EventSequenceList; // 0x168
		::UnityEngine::Texture* _DecalTexture; // 0x170
		::System::Collections::Generic::Dictionary_2<::System::String*, ::Class_1_56221E821F588017*>* HitBoxCollection; // 0x178
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _CurrentPlayingIDs; // 0x180
		::RPG::GameCore::PropStateConfig* _CurrentStateConfig; // 0x188
		::RPG::GameCore::TaskConfig* _InteractiveOverrideData_k__BackingField; // 0x190
		::RPG::Client::MonoDestructibleObject* _monoDesturct; // 0x198
		::RPG::GameCore::PropInitPuzzle* _PuzzleConfig; // 0x1A0
		::Class_2_F0C283D91BDD122E* _ShaderCtrl; // 0x1A8
		::Class_1_5F51D4049EA87B7B* _RewardCallback; // 0x1B0
		::RPG::Client::MaterialSwitchBehavior* _MaterialSwitchBehavior; // 0x1B8
		::RPG::GameCore::PropConfig* _JsonConfig_k__BackingField; // 0x1C0
		::UnityEngine::GameObject* _RootModel; // 0x1C8
		::Il2CppArray<::RPG::GameCore::TaskConfig*>* _OnCreateConfig_k__BackingField; // 0x1D0
		::RPG::GameCore::PropDayOfWeekComponent* _DayOfWeek; // 0x1D8
		::Class_2_911FE722F91DCE30* _WaterWheel; // 0x1E0
		::RPG::Client::MonoEffect* _HintEffect; // 0x1E8
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _muteColliderCache; // 0x1F0
		::Il2CppArray<::RPG::GameCore::PropStateIcon*>* _StateIcons; // 0x1F8
		::RPG::GameCore::TaskContext* _PuzzleContext; // 0x200
		::UnityEngine::Vector3 _HitDirection; // 0x208
		::System::UInt32 _DestroyAfterEventMask; // 0x214
		::RPG::GameCore::PropState _PrevPropState; // 0x218
		::System::Single _LifeTime_k__BackingField; // 0x21C
		::System::Single _SteerAngle; // 0x220
		::System::Single _AngleSign; // 0x224
		::System::Single _Duration; // 0x228
		::System::Boolean _CanPlayerLock; // 0x22C
		::System::Boolean IsCreateByActiveSkill; // 0x22D
		::System::Boolean _IsCaptured_k__BackingField; // 0x22E
		::System::Boolean _EffectHide_k__BackingField; // 0x22F
		::System::Single _AngleAbs; // 0x230
		::System::Int32 _EntityTag; // 0x234
		::RPG::GameCore::PropState _AdvancePropState; // 0x238
		::RPG::Client::TextID ExternalButtonText; // 0x240
		::RPG::GameCore::ETriggerHintState _HintStateValue; // 0x250
		::System::Boolean _IsTigerMachine; // 0x251
		::System::Single _DelayPlayGachaAnimTime; // 0x254
		::RPG::GameCore::FixPoint _HP_k__BackingField; // 0x258
		::RPG::Client::ReasonBool_1<::RPG::GameCore::DisableBillboardReason> _EnableBillboardReasonBool; // 0x260
		::System::Nullable_1<::System::Int32> _PropSwitchMatID; // 0x268
		::System::Boolean _usePreShow; // 0x270
		::System::Boolean _PuzzleAutoFinishChallenge; // 0x271
		::System::Boolean IsDestructInvincible; // 0x272
		::System::Boolean _PuzzleDestorying; // 0x273
		::System::Nullable_1<::RPG::GameCore::PropInteractMode> _InteractMode_k__BackingField; // 0x274
		::System::UInt32 _RollShopId; // 0x27C
		::System::Nullable_1<::System::Single> OverrideLockRaycastOffset; // 0x280
		::RPG::GameCore::RollShopGroupType _RollShopRewardResult_k__BackingField; // 0x288
		::RPG::GameCore::FixPoint _MaxHP_k__BackingField; // 0x290
		::System::Nullable_1<::System::Single> OriginalYawAngle; // 0x298
		::System::Boolean _IsMoveable_k__BackingField; // 0x2A0
		::System::Boolean _HintEffectLoading; // 0x2A1
		::System::Boolean _IsDestructed_k__BackingField; // 0x2A2
		::System::Boolean _StaticProp_k__BackingField; // 0x2A3
		::RPG::GameCore::PuzzleDeactiveTag PuzzleDeactiveTag; // 0x2A4
		::System::Boolean _TriggerEnabled; // 0x2A5
		::RPG::GameCore::PuzzleUnloadTag PuzzleUnloadTag; // 0x2A6
		::System::Boolean _IsAdvanceState; // 0x2A7
		::System::Boolean _PropPendingStartPuzzle; // 0x2A8
		::System::Boolean _IsInDestruct_k__BackingField; // 0x2A9
		::System::Boolean _PlayerLockableBase; // 0x2AA

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__CCTOR_OFFSET))();
		}

		::System::Void SetPuzzle(::RPG::GameCore::PropInitPuzzle* a1, ::RPG::GameCore::TaskContext* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropInitPuzzle*, ::RPG::GameCore::TaskContext*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETPUZZLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ClearPuzzle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_CLEARPUZZLE_OFFSET))(this);
		}

		::System::Boolean ShouldPuzzleInit()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SHOULDPUZZLEINIT_OFFSET))(this);
		}

		::System::Void TryTriggerPuzzleTutorialWhenInit(::RPG::Client::Prop::PuzzleBoardBase* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::Prop::PuzzleBoardBase*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TRYTRIGGERPUZZLETUTORIALWHENINIT_OFFSET))(this, a1);
		}

		::System::Void CancelPuzzleAsyncLoading()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_CANCELPUZZLEASYNCLOADING_OFFSET))(this);
		}

		::System::Boolean InitPuzzle(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_INITPUZZLE_OFFSET))(this, a1);
		}

		::System::Void DestroyPuzzleObj(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DESTROYPUZZLEOBJ_OFFSET))(this, a1);
		}

		::System::Void _DestroyPuzzleBoard()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__DESTROYPUZZLEBOARD_OFFSET))(this);
		}

		::System::Boolean IsPuzzleAsyncLoading()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ISPUZZLEASYNCLOADING_OFFSET))(this);
		}

		::System::Void DestoryPuzzle(::RPG::GameCore::PuzzleUnloadTag a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PuzzleUnloadTag, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DESTORYPUZZLE_OFFSET))(this, a1, a2);
		}

		::System::Boolean LoadPuzzle(::RPG::GameCore::PuzzleUnloadTag a1, ::System::Boolean a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::PuzzleUnloadTag, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLE_OFFSET))(this, a1, a2);
		}

		::RPG::GameCore::PropInitPuzzle* GetPuzzleInitConfig()
		{
			return ((::RPG::GameCore::PropInitPuzzle*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETPUZZLEINITCONFIG_OFFSET))(this);
		}

		::System::Void SetPuzzleActive(::RPG::GameCore::PuzzleDeactiveTag a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PuzzleDeactiveTag, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETPUZZLEACTIVE_OFFSET))(this, a1, a2);
		}

		::System::Void SetPendingMazePuzzleChallengeConfig(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETPENDINGMAZEPUZZLECHALLENGECONFIG_OFFSET))(this, a1);
		}

		::System::Void SetPendingMazePuzzleStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETPENDINGMAZEPUZZLESTART_OFFSET))(this);
		}

		::System::Void CancelPendingMazePuzzleStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_CANCELPENDINGMAZEPUZZLESTART_OFFSET))(this);
		}

		::System::Void _OnPuzzleAreaLoadFadeOutFinish(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREALOADFADEOUTFINISH_OFFSET))(this, a1);
		}

		::System::Collections::IEnumerator* LoadPuzzleArea(::System::Single a1, ::System::Boolean a2)
		{
			return ((::System::Collections::IEnumerator*(*)(::PVOID, ::System::Single, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLEAREA_OFFSET))(this, a1, a2);
		}

		::System::Void _OnPuzzleAreaLoadFadeInFinish(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREALOADFADEINFINISH_OFFSET))(this, a1);
		}

		::System::Boolean _OnPuzzleAssetLoad(::RPG::Client::IAssetOperation* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::IAssetOperation*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEASSETLOAD_OFFSET))(this, a1);
		}

		::System::Void _OnPuzzleAreaUnloadFadeOutFinish(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREAUNLOADFADEOUTFINISH_OFFSET))(this, a1);
		}

		::System::Collections::IEnumerator* UnloadPuzzleArea(::System::Single a1)
		{
			return ((::System::Collections::IEnumerator*(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_UNLOADPUZZLEAREA_OFFSET))(this, a1);
		}

		::System::Void _OnPuzzleAreaUnloadFadeInFinish(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONPUZZLEAREAUNLOADFADEINFINISH_OFFSET))(this, a1);
		}

		::System::Void _UnloadPuzzleArea()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__UNLOADPUZZLEAREA_OFFSET))(this);
		}

		::System::Boolean _OnGetPuzzleAsset()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONGETPUZZLEASSET_OFFSET))(this);
		}

		::System::Void _AttachPuzzleObj(::RPG::Client::Prop::PuzzleBoardBase* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::Prop::PuzzleBoardBase*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ATTACHPUZZLEOBJ_OFFSET))(this, a1);
		}

		::System::Void LoadPuzzleArea_1(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_LOADPUZZLEAREA_1_OFFSET))(this, a1);
		}

		::System::Void UnloadPuzzleArea_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_UNLOADPUZZLEAREA_1_OFFSET))(this);
		}

		::RPG::Client::Prop::PuzzleBoardBase* get_AttachPuzzleBoard()
		{
			return ((::RPG::Client::Prop::PuzzleBoardBase*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ATTACHPUZZLEBOARD_OFFSET))(this);
		}

		::System::Void set_AttachPuzzleBoard(::RPG::Client::Prop::PuzzleBoardBase* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::Prop::PuzzleBoardBase*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ATTACHPUZZLEBOARD_OFFSET))(this, a1);
		}

		::System::Void SetOriginalOrientation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETORIGINALORIENTATION_OFFSET))(this);
		}

		::System::Nullable_1<::System::Single> GetOriginalYawAngle()
		{
			return ((::System::Nullable_1<::System::Single>(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETORIGINALYAWANGLE_OFFSET))(this);
		}

		::System::Boolean AddSteerRequest(::Class_1_5FEA23DE7B72218E* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_5FEA23DE7B72218E*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ADDSTEERREQUEST_OFFSET))(this, a1);
		}

		::System::Void StopSteerRequest()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STOPSTEERREQUEST_OFFSET))(this);
		}

		::System::Void _UpdateSteer(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__UPDATESTEER_OFFSET))(this, a1);
		}

		::RPG::GameCore::TransformComponent* _GetFinalTargetTransform()
		{
			return ((::RPG::GameCore::TransformComponent*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__GETFINALTARGETTRANSFORM_OFFSET))(this);
		}

		::System::Void AddTimeRewindStrikeCallback(::RPG::GameCore::TaskContext* a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TaskContext*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ADDTIMEREWINDSTRIKECALLBACK_OFFSET))(this, a1, a2);
		}

		::System::Void StopTimeRewindStrikeCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STOPTIMEREWINDSTRIKECALLBACK_OFFSET))(this);
		}

		::System::Void DisposeTimeRewindStrikeListener()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DISPOSETIMEREWINDSTRIKELISTENER_OFFSET))(this);
		}

		::System::Void _InitViews()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__INITVIEWS_OFFSET))(this);
		}

		::System::Void _UninitViews()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__UNINITVIEWS_OFFSET))(this);
		}

		::System::Void _TickViews(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__TICKVIEWS_OFFSET))(this, a1);
		}

		::System::Void OnModelRootLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONMODELROOTLOADED_OFFSET))(this);
		}

		::System::Void OnModelRootUnloaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONMODELROOTUNLOADED_OFFSET))(this);
		}

		::System::Void OnModelArtLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONMODELARTLOADED_OFFSET))(this);
		}

		::System::Void OnModelArtUnloaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONMODELARTUNLOADED_OFFSET))(this);
		}

		::System::Void SetMonoWavingBlockControlFloorID(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETMONOWAVINGBLOCKCONTROLFLOORID_OFFSET))(this, a1);
		}

		::System::Void SetSDFText(::System::Boolean a1, ::System::UInt32 a2, ::System::String* a3, ::System::Single a4, ::System::String* a5, ::System::Int32 a6, ::System::Boolean a7, ::RPG::GameCore::SDFTextAlignType a8)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::UInt32, ::System::String*, ::System::Single, ::System::String*, ::System::Int32, ::System::Boolean, ::RPG::GameCore::SDFTextAlignType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETSDFTEXT_OFFSET))(this, a1, a2, a3, a4, a5, a6, a7, a8);
		}

		::System::Void SetSDFTextScale(::System::Boolean a1, ::System::Single a2, ::System::Single a3, ::System::Single a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Single, ::System::Single, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETSDFTEXTSCALE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void PostSoundEvent(::System::String* a1, ::AkCallbackType a2, ::System::Boolean a3, ::System::Action_1<::System::UInt32>* a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::AkCallbackType, ::System::Boolean, ::System::Action_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_POSTSOUNDEVENT_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _PostSoundEvent(::System::String* a1, ::AkCallbackType a2, ::System::Boolean a3, ::System::Action_1<::System::UInt32>* a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::AkCallbackType, ::System::Boolean, ::System::Action_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__POSTSOUNDEVENT_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void RemoveSoundEvent(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REMOVESOUNDEVENT_OFFSET))(this, a1, a2);
		}

		::System::Void _RecordPlayingSound(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__RECORDPLAYINGSOUND_OFFSET))(this, a1);
		}

		::System::Void _OnSoundEventCallback(::System::UInt32 a1, ::AkCallbackType a2, ::AkCallbackInfo* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::AkCallbackType, ::AkCallbackInfo*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONSOUNDEVENTCALLBACK_OFFSET))(this, a1, a2, a3);
		}

		::System::Void TryStopCacheSoundEvent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TRYSTOPCACHESOUNDEVENT_OFFSET))(this);
		}

		::System::Void SetupDecalProp()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPDECALPROP_OFFSET))(this);
		}

		::System::Void ReleaseDecalProp()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RELEASEDECALPROP_OFFSET))(this);
		}

		::System::Void BeginFadein()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_BEGINFADEIN_OFFSET))(this);
		}

		::System::Void InitInVisible()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_INITINVISIBLE_OFFSET))(this);
		}

		::System::Void _TryResetEffectPluginComponents(::UnityEngine::Transform* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__TRYRESETEFFECTPLUGINCOMPONENTS_OFFSET))(this, a1);
		}

		::System::Void _TryDisposeEffectPluginComponents()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__TRYDISPOSEEFFECTPLUGINCOMPONENTS_OFFSET))(this);
		}

		::RPG::GameCore::RollShopGroupType get_RollShopRewardResult()
		{
			return ((::RPG::GameCore::RollShopGroupType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ROLLSHOPREWARDRESULT_OFFSET))(this);
		}

		::System::Void set_RollShopRewardResult(::RPG::GameCore::RollShopGroupType a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::RollShopGroupType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ROLLSHOPREWARDRESULT_OFFSET))(this, a1);
		}

		::System::Void StartSlotMachine(::System::UInt32 a1, ::System::Boolean a2, ::RPG::GameCore::TaskContext* a3, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a4, ::System::Single a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean, ::RPG::GameCore::TaskContext*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STARTSLOTMACHINE_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void StopSlotMachine()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STOPSLOTMACHINE_OFFSET))(this);
		}

		::System::Void _OnDoGachaInRollShopScRsp(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONDOGACHAINROLLSHOPSCRSP_OFFSET))(this, a1);
		}

		::System::Void _DelayDoGachaInRollShop(::Class_1_0245247C127EF1B6_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_0245247C127EF1B6_1*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__DELAYDOGACHAINROLLSHOP_OFFSET))(this, a1);
		}

		::System::Single GetWheelDuration()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETWHEELDURATION_OFFSET))(this);
		}

		::RPG::Client::Wheel* GetWheelData()
		{
			return ((::RPG::Client::Wheel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETWHEELDATA_OFFSET))(this);
		}

		::UnityEngine::AnimationCurve* GetWheelCurveData()
		{
			return ((::UnityEngine::AnimationCurve*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETWHEELCURVEDATA_OFFSET))(this);
		}

		::System::Void SetSlotMachine(::System::Collections::Generic::List_1<::System::Int32>* a1, ::System::Collections::Generic::List_1<::System::Int32>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::Int32>*, ::System::Collections::Generic::List_1<::System::Int32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETSLOTMACHINE_OFFSET))(this, a1, a2);
		}

		::System::Void ResetSlotMachine()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RESETSLOTMACHINE_OFFSET))(this);
		}

		::RPG::Client::SlotMachineController* TryGetSlotMachineController()
		{
			return ((::RPG::Client::SlotMachineController*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TRYGETSLOTMACHINECONTROLLER_OFFSET))(this);
		}

		::System::Void SetSceneTVMenuID(::System::Int32 a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETSCENETVMENUID_OFFSET))(this, a1, a2);
		}

		::System::Void _CheckLayer(::System::String* a1, ::System::String* a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__CHECKLAYER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SwitchMaterialGroup(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SWITCHMATERIALGROUP_OFFSET))(this, a1);
		}

		::RPG::Client::NavMeshStateConfig* get_PropNavMeshStateConfig()
		{
			return ((::RPG::Client::NavMeshStateConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PROPNAVMESHSTATECONFIG_OFFSET))(this);
		}

		::System::Void set_PropNavMeshStateConfig(::RPG::Client::NavMeshStateConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::NavMeshStateConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_PROPNAVMESHSTATECONFIG_OFFSET))(this, a1);
		}

		::System::Void WaterWheelStartRotate(::System::Boolean a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTARTROTATE_OFFSET))(this, a1, a2);
		}

		::System::Void WaterWheelStartRotateTo(::System::Int32 a1, ::System::Int32 a2, ::System::Boolean a3, ::System::Boolean a4, ::System::Action* a5, ::System::Single a6)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32, ::System::Boolean, ::System::Boolean, ::System::Action*, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTARTROTATETO_OFFSET))(this, a1, a2, a3, a4, a5, a6);
		}

		::System::Int32 WaterWheelStopRotate(::System::Int32 a1, ::System::Action* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_WATERWHEELSTOPROTATE_OFFSET))(this, a1, a2);
		}

		::System::Void SpawnMoney(::System::UInt32 a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SPAWNMONEY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnInitOwnerRef()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONINITOWNERREF_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DISPOSE_OFFSET))(this);
		}

		::System::Void PreInitComponent(::RPG::GameCore::PropConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_PREINITCOMPONENT_OFFSET))(this, a1);
		}

		::System::Void InitComponent(::RPG::GameCore::PropRow* a1, ::RPG::GameCore::PropConfig* a2, ::RPG::GameCore::ColliderTriggerComponent* a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropRow*, ::RPG::GameCore::PropConfig*, ::RPG::GameCore::ColliderTriggerComponent*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_INITCOMPONENT_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetPropDef(::RPG::Client::MapPropDef* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::MapPropDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETPROPDEF_OFFSET))(this, a1);
		}

		::System::Void OnBeforeDestory()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONBEFOREDESTORY_OFFSET))(this);
		}

		::System::Void InitializePropState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_INITIALIZEPROPSTATE_OFFSET))(this);
		}

		::Class_2_37D832480CB327E1* RequireMovement()
		{
			return ((::Class_2_37D832480CB327E1*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REQUIREMOVEMENT_OFFSET))(this);
		}

		::Class_2_37D832480CB327E1* GetMovement()
		{
			return ((::Class_2_37D832480CB327E1*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETMOVEMENT_OFFSET))(this);
		}

		::Class_2_F0C283D91BDD122E* RequireShaderCtrl(::RPG::GameCore::PropType a1)
		{
			return ((::Class_2_F0C283D91BDD122E*(*)(::PVOID, ::RPG::GameCore::PropType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REQUIRESHADERCTRL_OFFSET))(this, a1);
		}

		::RPG::GameCore::PropDayOfWeekComponent* RequireDayOfWeek(::RPG::GameCore::PropType a1)
		{
			return ((::RPG::GameCore::PropDayOfWeekComponent*(*)(::PVOID, ::RPG::GameCore::PropType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REQUIREDAYOFWEEK_OFFSET))(this, a1);
		}

		::Class_2_7858266B34A2C48E* RequireFarmElement()
		{
			return ((::Class_2_7858266B34A2C48E*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REQUIREFARMELEMENT_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TICK_OFFSET))(this, a1);
		}

		::System::Void LateUpdate(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_LATEUPDATE_OFFSET))(this, a1);
		}

		::System::Void RecoverAfterMissionFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RECOVERAFTERMISSIONFINISH_OFFSET))(this);
		}

		::System::Void EnableTrigger(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ENABLETRIGGER_OFFSET))(this, a1);
		}

		::System::Void SetupOptionTrigger(::Class_0_16E4307DCC419505_542* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_542*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPOPTIONTRIGGER_OFFSET))(this, a1);
		}

		::System::Void SetupInteractionTrigger(::Class_0_16E4307DCC419505_542* a1, ::System::Boolean a2, ::Il2CppArray<::RPG::GameCore::EntityType>* a3)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_542*, ::System::Boolean, ::Il2CppArray<::RPG::GameCore::EntityType>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPINTERACTIONTRIGGER_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean SetupServerSyncTrigger(::System::String* a1, ::Class_0_16E4307DCC419505_542* a2, ::Class_1_47F263CB5C51B1A3* a3, ::System::Boolean a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::Class_0_16E4307DCC419505_542*, ::Class_1_47F263CB5C51B1A3*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPSERVERSYNCTRIGGER_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void DestroyServerSyncTrigger(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DESTROYSERVERSYNCTRIGGER_OFFSET))(this, a1, a2);
		}

		::System::Boolean SetupCustomTrigger(::System::String* a1, ::Class_0_16E4307DCC419505_542* a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::Class_0_16E4307DCC419505_542*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPCUSTOMTRIGGER_OFFSET))(this, a1, a2);
		}

		::System::Void DestroyCustomTrigger(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DESTROYCUSTOMTRIGGER_OFFSET))(this, a1, a2);
		}

		::Class_0_16E4307DCC419505_542* GetTrigger(::System::String* a1)
		{
			return ((::Class_0_16E4307DCC419505_542*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETTRIGGER_OFFSET))(this, a1);
		}

		::System::Void SetupHitBoxCollection(::Il2CppArray<::RPG::GameCore::SingleHitBoxConfig*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::SingleHitBoxConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPHITBOXCOLLECTION_OFFSET))(this, a1);
		}

		::System::Void UnloadHitBoxCollection()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_UNLOADHITBOXCOLLECTION_OFFSET))(this);
		}

		::System::Void SetupHitBox(::System::String* a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPHITBOX_OFFSET))(this, a1, a2);
		}

		::System::Void UnloadHitBox()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_UNLOADHITBOX_OFFSET))(this);
		}

		::System::Boolean OnBeHit(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::AttackDamageType a2, ::UnityEngine::Vector3 a3, ::UnityEngine::Collider* a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AttackDamageType, ::UnityEngine::Vector3, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONBEHIT_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void OnCreate(::RPG::GameCore::LevelGraph* a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::LevelGraph*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONCREATE_OFFSET))(this, a1, a2);
		}

		::System::Void SetDestroyAfterEvent(::RPG::GameCore::PropEventType a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropEventType, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETDESTROYAFTEREVENT_OFFSET))(this, a1, a2);
		}

		::System::Boolean GetDestroyAfterEvent(::RPG::GameCore::PropEventType a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::PropEventType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETDESTROYAFTEREVENT_OFFSET))(this, a1);
		}

		::System::Boolean IsDamageableWithType(::RPG::GameCore::AttackDamageType a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::AttackDamageType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ISDAMAGEABLEWITHTYPE_OFFSET))(this, a1);
		}

		::System::Boolean IsDamageableWithEntityType(::RPG::GameCore::EntityType a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::EntityType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ISDAMAGEABLEWITHENTITYTYPE_OFFSET))(this, a1);
		}

		::System::Void TrySetupEventSequence(::RPG::GameCore::PropEventType a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropEventType, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TRYSETUPEVENTSEQUENCE_OFFSET))(this, a1, a2);
		}

		::System::Void SetupEventSequence(::RPG::GameCore::PropEventType a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropEventType, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPEVENTSEQUENCE_OFFSET))(this, a1, a2);
		}

		::System::Void UnloadEventSequence(::RPG::GameCore::PropEventType a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropEventType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_UNLOADEVENTSEQUENCE_OFFSET))(this, a1);
		}

		::System::Void PropDestruction()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_PROPDESTRUCTION_OFFSET))(this);
		}

		::System::Boolean BeginDestruction(::System::Action* a1, ::System::Boolean a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Action*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_BEGINDESTRUCTION_OFFSET))(this, a1, a2);
		}

		::System::Boolean DestructShowBegin(::System::Action* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DESTRUCTSHOWBEGIN_OFFSET))(this, a1);
		}

		::System::Void ResetDestruction()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RESETDESTRUCTION_OFFSET))(this);
		}

		::System::String* GetCurrentStateAnchorKey()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEANCHORKEY_OFFSET))(this);
		}

		::System::Boolean IsStateIconsNull()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ISSTATEICONSNULL_OFFSET))(this);
		}

		::System::UInt32 GetCurrentStateMiniMapIcon()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEMINIMAPICON_OFFSET))(this);
		}

		::UnityEngine::Color GetCurrentStateMiniMapIconColor()
		{
			return ((::UnityEngine::Color(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEMINIMAPICONCOLOR_OFFSET))(this);
		}

		::System::UInt32 GetCurrentDailyMiniMapIcon()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYMINIMAPICON_OFFSET))(this);
		}

		::UnityEngine::Color GetCurrentDailyMiniMapIconColor()
		{
			return ((::UnityEngine::Color(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYMINIMAPICONCOLOR_OFFSET))(this);
		}

		::System::Boolean CanDailyMiniMapIconTint()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_CANDAILYMINIMAPICONTINT_OFFSET))(this);
		}

		::System::Boolean CanStateMiniMapIconTint()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_CANSTATEMINIMAPICONTINT_OFFSET))(this);
		}

		::RPG::GameCore::LevelPerformanceHideType get_HideInPerformance()
		{
			return ((::RPG::GameCore::LevelPerformanceHideType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_HIDEINPERFORMANCE_OFFSET))(this);
		}

		::System::Boolean IsHideByPerformanceType(::RPG::GameCore::ELevelPerformanceType a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::ELevelPerformanceType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ISHIDEBYPERFORMANCETYPE_OFFSET))(this, a1);
		}

		::System::Void TryPostCacheSoundEvent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_TRYPOSTCACHESOUNDEVENT_OFFSET))(this);
		}

		::System::Void SafeDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SAFEDESTROY_OFFSET))(this);
		}

		::System::Void StartPropInteract(::RPG::GameCore::PropInteractMode a1, ::RPG::GameCore::TaskConfig* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropInteractMode, ::RPG::GameCore::TaskConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STARTPROPINTERACT_OFFSET))(this, a1, a2);
		}

		::System::Void EndPropInteract()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ENDPROPINTERACT_OFFSET))(this);
		}

		::System::Boolean get_EffectHide()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_EFFECTHIDE_OFFSET))(this);
		}

		::System::Void set_EffectHide(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_EFFECTHIDE_OFFSET))(this, a1);
		}

		::System::Void SetCastEffectHideState(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETCASTEFFECTHIDESTATE_OFFSET))(this, a1);
		}

		::System::String* SetupTrigger(::System::String* a1, ::Class_0_16E4307DCC419505_542* a2, ::System::Boolean a3)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*, ::Class_0_16E4307DCC419505_542*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPTRIGGER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void DistoryTrigger(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_DISTORYTRIGGER_OFFSET))(this, a1, a2);
		}

		::System::Void StartAdvanceInteract(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_STARTADVANCEINTERACT_OFFSET))(this, a1);
		}

		::System::Void OnReconnectStart(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONRECONNECTSTART_OFFSET))(this, a1);
		}

		::System::Void RollBackAdvanceInteract()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ROLLBACKADVANCEINTERACT_OFFSET))(this);
		}

		::System::Void SetEnableBillboard(::System::Boolean a1, ::RPG::GameCore::DisableBillboardReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::DisableBillboardReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETENABLEBILLBOARD_OFFSET))(this, a1, a2);
		}

		::System::Void FinishAdvanceInteract()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_FINISHADVANCEINTERACT_OFFSET))(this);
		}

		::System::Int32 GetEntityTag()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETENTITYTAG_OFFSET))(this);
		}

		::System::Void _InitDefaultCustomEffectTransformParamsIfNeeded(::RPG::Client::Effect_Transform* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::Effect_Transform*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__INITDEFAULTCUSTOMEFFECTTRANSFORMPARAMSIFNEEDED_OFFSET))(this, a1);
		}

		::System::Void SetupCustomEffectTransformParams(::Class_1_43BD383C98B4C0C5_122* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_122*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETUPCUSTOMEFFECTTRANSFORMPARAMS_OFFSET))(this, a1);
		}

		::System::Void OnDestructionCallBack()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_ONDESTRUCTIONCALLBACK_OFFSET))(this);
		}

		::System::Void _UpdateStateIcons(::Il2CppArray<::RPG::GameCore::PropStateIcon*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::PropStateIcon*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__UPDATESTATEICONS_OFFSET))(this, a1);
		}

		::System::Void _OnDestructionFinished()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONDESTRUCTIONFINISHED_OFFSET))(this);
		}

		::System::Void _DestroySelf()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__DESTROYSELF_OFFSET))(this);
		}

		::System::Boolean _StartSequence(::RPG::GameCore::PropEventType a1, ::System::Boolean a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::PropEventType, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__STARTSEQUENCE_OFFSET))(this, a1, a2);
		}

		::System::Boolean _TickSequence(::RPG::GameCore::PropEventType a1, ::System::Single a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::PropEventType, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__TICKSEQUENCE_OFFSET))(this, a1, a2);
		}

		::System::Void _FillEventContext(::RPG::GameCore::PropEventType a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropEventType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__FILLEVENTCONTEXT_OFFSET))(this, a1);
		}

		::RPG::GameCore::PropStateIcon* GetCurrentStateIcon()
		{
			return ((::RPG::GameCore::PropStateIcon*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTSTATEICON_OFFSET))(this);
		}

		::RPG::GameCore::PropStateIcon* GetCurrentDailyIcon()
		{
			return ((::RPG::GameCore::PropStateIcon*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GETCURRENTDAILYICON_OFFSET))(this);
		}

		::System::Void _OnEnterState(::RPG::GameCore::PropState a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropState, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONENTERSTATE_OFFSET))(this, a1, a2);
		}

		::System::Void _SyncPropStateToEffectAnimators(::UnityEngine::Animator* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Animator*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__SYNCPROPSTATETOEFFECTANIMATORS_OFFSET))(this, a1);
		}

		::System::Void ShowHint(::System::Boolean a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SHOWHINT_OFFSET))(this, a1, a2);
		}

		::System::String* _GetHintEffectPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__GETHINTEFFECTPATH_OFFSET))(this);
		}

		::System::String* _GetHintEffectAttachPoint()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__GETHINTEFFECTATTACHPOINT_OFFSET))(this);
		}

		::System::Void _SetupStaticFlag()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__SETUPSTATICFLAG_OFFSET))(this);
		}

		::System::Void _OnSyncTriggerChange(::Class_0_16E4307DCC419505_401* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_401*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__ONSYNCTRIGGERCHANGE_OFFSET))(this, a1);
		}

		::System::Void SetHintState(::RPG::GameCore::ETriggerHintState a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ETriggerHintState, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETHINTSTATE_OFFSET))(this, a1, a2);
		}

		::System::Void SetCanPlayerLock(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETCANPLAYERLOCK_OFFSET))(this, a1);
		}

		::System::Void SetLifeTime(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SETLIFETIME_OFFSET))(this, a1);
		}

		::System::Void _TryRevertDefaultEffectTransformParams()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__TRYREVERTDEFAULTEFFECTTRANSFORMPARAMS_OFFSET))(this);
		}

		static ::System::Void ApplyCustomEffectTransformParams_Offset(::RPG::Client::Effect_Transform* a1, ::Class_1_43BD383C98B4C0C5_122* a2)
		{
			return ((::System::Void(*)(::RPG::Client::Effect_Transform*, ::Class_1_43BD383C98B4C0C5_122*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_APPLYCUSTOMEFFECTTRANSFORMPARAMS_OFFSET_OFFSET))(a1, a2);
		}

		static ::System::Void ApplyCustomEffectTransformParams_Rotate(::RPG::Client::Effect_Transform* a1, ::Class_1_43BD383C98B4C0C5_122* a2)
		{
			return ((::System::Void(*)(::RPG::Client::Effect_Transform*, ::Class_1_43BD383C98B4C0C5_122*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_APPLYCUSTOMEFFECTTRANSFORMPARAMS_ROTATE_OFFSET))(a1, a2);
		}

		::System::Void _ApplyCustomEffectTransformParams()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__APPLYCUSTOMEFFECTTRANSFORMPARAMS_OFFSET))(this);
		}

		::RPG::GameCore::FixPoint get_HP()
		{
			return ((::RPG::GameCore::FixPoint(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_HP_OFFSET))(this);
		}

		::System::Void set_HP(::RPG::GameCore::FixPoint a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FixPoint))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_HP_OFFSET))(this, a1);
		}

		::RPG::GameCore::FixPoint get_MaxHP()
		{
			return ((::RPG::GameCore::FixPoint(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_MAXHP_OFFSET))(this);
		}

		::System::Void set_MaxHP(::RPG::GameCore::FixPoint a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FixPoint))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_MAXHP_OFFSET))(this, a1);
		}

		::System::Single get_LifeTime()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_LIFETIME_OFFSET))(this);
		}

		::System::Void set_LifeTime(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_LIFETIME_OFFSET))(this, a1);
		}

		::System::Boolean get_IsInDestruct()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISINDESTRUCT_OFFSET))(this);
		}

		::System::Void set_IsInDestruct(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ISINDESTRUCT_OFFSET))(this, a1);
		}

		::System::Boolean get_IsDestructed()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISDESTRUCTED_OFFSET))(this);
		}

		::System::Void set_IsDestructed(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ISDESTRUCTED_OFFSET))(this, a1);
		}

		::System::Boolean get_IsPreShowDestruct()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISPRESHOWDESTRUCT_OFFSET))(this);
		}

		::RPG::GameCore::PropState get_PropState()
		{
			return ((::RPG::GameCore::PropState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PROPSTATE_OFFSET))(this);
		}

		::System::Void set_PropState(::RPG::GameCore::PropState a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropState))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_PROPSTATE_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_PropTextIDName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PROPTEXTIDNAME_OFFSET))(this);
		}

		::System::Boolean PlayerLockableSpecByConfig()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_PLAYERLOCKABLESPECBYCONFIG_OFFSET))(this);
		}

		::System::Boolean PlayerLockableAnimLimits()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_PLAYERLOCKABLEANIMLIMITS_OFFSET))(this);
		}

		::System::Void RefreshPalyerLockable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_REFRESHPALYERLOCKABLE_OFFSET))(this);
		}

		::System::Boolean get_RealtimePlayerLockable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_REALTIMEPLAYERLOCKABLE_OFFSET))(this);
		}

		::System::Boolean get_PlayerLockable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PLAYERLOCKABLE_OFFSET))(this);
		}

		::RPG::GameCore::PropStateConfig* get_CurStateConfig()
		{
			return ((::RPG::GameCore::PropStateConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_CURSTATECONFIG_OFFSET))(this);
		}

		::System::Boolean get_StaticProp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_STATICPROP_OFFSET))(this);
		}

		::System::Void set_StaticProp(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_STATICPROP_OFFSET))(this, a1);
		}

		::RPG::GameCore::PropRow* get_RowRef()
		{
			return ((::RPG::GameCore::PropRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ROWREF_OFFSET))(this);
		}

		::System::Void set_RowRef(::RPG::GameCore::PropRow* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropRow*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ROWREF_OFFSET))(this, a1);
		}

		::RPG::GameCore::PropConfig* get_JsonConfig()
		{
			return ((::RPG::GameCore::PropConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_JSONCONFIG_OFFSET))(this);
		}

		::System::Void set_JsonConfig(::RPG::GameCore::PropConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::PropConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_JSONCONFIG_OFFSET))(this, a1);
		}

		::UnityEngine::Collider* get_HitBox()
		{
			return ((::UnityEngine::Collider*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_HITBOX_OFFSET))(this);
		}

		::System::Void set_HitBox(::UnityEngine::Collider* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_HITBOX_OFFSET))(this, a1);
		}

		::System::Boolean get_IsDamageable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISDAMAGEABLE_OFFSET))(this);
		}

		::System::UInt32 get_ServerEntityID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_SERVERENTITYID_OFFSET))(this);
		}

		::System::Boolean get_IsLifeRunOut()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISLIFERUNOUT_OFFSET))(this);
		}

		::UnityEngine::Vector3 get_Scale()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_SCALE_OFFSET))(this);
		}

		::RPG::Client::MapPropDef* get_MapPropDef()
		{
			return ((::RPG::Client::MapPropDef*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_MAPPROPDEF_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_358* get_OwnerAbilityInstance()
		{
			return ((::Class_0_16E4307DCC419505_358*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_OWNERABILITYINSTANCE_OFFSET))(this);
		}

		::System::Void set_OwnerAbilityInstance(::Class_0_16E4307DCC419505_358* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_358*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_OWNERABILITYINSTANCE_OFFSET))(this, a1);
		}

		::System::String* get_PropName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PROPNAME_OFFSET))(this);
		}

		::System::Void set_PropName(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_PROPNAME_OFFSET))(this, a1);
		}

		::Class_1_83665B095F1535B5_19* get_EventContext()
		{
			return ((::Class_1_83665B095F1535B5_19*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_EVENTCONTEXT_OFFSET))(this);
		}

		::Il2CppArray<::RPG::GameCore::TaskConfig*>* get_OnCreateConfig()
		{
			return ((::Il2CppArray<::RPG::GameCore::TaskConfig*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ONCREATECONFIG_OFFSET))(this);
		}

		::System::Void set_OnCreateConfig(::Il2CppArray<::RPG::GameCore::TaskConfig*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ONCREATECONFIG_OFFSET))(this, a1);
		}

		::System::Boolean get_IsDestructResource()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISDESTRUCTRESOURCE_OFFSET))(this);
		}

		::RPG::GameCore::PropType get_PropType()
		{
			return ((::RPG::GameCore::PropType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_PROPTYPE_OFFSET))(this);
		}

		::System::Boolean get_IsMoveable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISMOVEABLE_OFFSET))(this);
		}

		::System::Void set_IsMoveable(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ISMOVEABLE_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_InteractTitle()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTTITLE_OFFSET))(this);
		}

		::RPG::GameCore::JsonEnum* get_InteractIconType()
		{
			return ((::RPG::GameCore::JsonEnum*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTICONTYPE_OFFSET))(this);
		}

		::System::Boolean get_EnableBillboard()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ENABLEBILLBOARD_OFFSET))(this);
		}

		::System::Boolean get_IsCaptured()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISCAPTURED_OFFSET))(this);
		}

		::System::Void set_IsCaptured(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_ISCAPTURED_OFFSET))(this, a1);
		}

		::System::UInt32 RPG_GameCore_IPropInteractionInfo_get_RuntimeID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_RUNTIMEID_OFFSET))(this);
		}

		::RPG::Client::TextID RPG_GameCore_IPropInteractionInfo_get_TextID()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_TEXTID_OFFSET))(this);
		}

		::System::String* RPG_GameCore_IPropInteractionInfo_get_IconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RPG_GAMECORE_IPROPINTERACTIONINFO_GET_ICONPATH_OFFSET))(this);
		}

		::System::Nullable_1<::RPG::GameCore::PropInteractMode> get_InteractMode()
		{
			return ((::System::Nullable_1<::RPG::GameCore::PropInteractMode>(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTMODE_OFFSET))(this);
		}

		::System::Void set_InteractMode(::System::Nullable_1<::RPG::GameCore::PropInteractMode> a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Nullable_1<::RPG::GameCore::PropInteractMode>))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_INTERACTMODE_OFFSET))(this, a1);
		}

		::RPG::GameCore::TaskConfig* get_InteractiveOverrideData()
		{
			return ((::RPG::GameCore::TaskConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_INTERACTIVEOVERRIDEDATA_OFFSET))(this);
		}

		::System::Void set_InteractiveOverrideData(::RPG::GameCore::TaskConfig* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TaskConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET_INTERACTIVEOVERRIDEDATA_OFFSET))(this, a1);
		}

		::System::UInt32 get_CocoonID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_COCOONID_OFFSET))(this);
		}

		::System::Boolean get_IsDayOfWeekProp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET_ISDAYOFWEEKPROP_OFFSET))(this);
		}

		::RPG::GameCore::ETriggerHintState get__HintState()
		{
			return ((::RPG::GameCore::ETriggerHintState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_GET__HINTSTATE_OFFSET))(this);
		}

		::System::Void set__HintState(::RPG::GameCore::ETriggerHintState a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ETriggerHintState))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_SET__HINTSTATE_OFFSET))(this, a1);
		}

		::System::Void ResetToDefault()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT_RESETTODEFAULT_OFFSET))(this);
		}

		::System::Void _ShowHint_b__209_0(::RPG::Client::MonoEffect* a1, ::RPG::Client::TriggerEffectCallbackParams a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::MonoEffect*, ::RPG::Client::TriggerEffectCallbackParams))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT__SHOWHINT_B__209_0_OFFSET))(this, a1, a2);
		}

		::System::Void __iFixBaseProxy__OnInitOwnerRef()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY__ONINITOWNERREF_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY_TICK_OFFSET))(this, a1);
		}

		::System::Void __iFixBaseProxy_LateUpdate(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_PROPCOMPONENT___IFIXBASEPROXY_LATEUPDATE_OFFSET))(this, a1);
		}
	};
}
