#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_7A22A3DBEEDD1F80;
namespace RPG::GameCore { class TargetSeqOperation; }

#define RPG_GAMECORE_TARGETSEQOPERATION___C__CCTOR_OFFSET UNITYSDK_OFFSET(0x177DE5B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C__CTOR_OFFSET UNITYSDK_OFFSET(0x177DE5E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_0_OFFSET UNITYSDK_OFFSET(0x177DE5F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_100_OFFSET UNITYSDK_OFFSET(0x177E30C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_101_OFFSET UNITYSDK_OFFSET(0x177E3130)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_102_OFFSET UNITYSDK_OFFSET(0x177E31F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_103_OFFSET UNITYSDK_OFFSET(0x177E32D0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_104_OFFSET UNITYSDK_OFFSET(0x177E3390)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_105_OFFSET UNITYSDK_OFFSET(0x177E3450)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_106_OFFSET UNITYSDK_OFFSET(0x177E3510)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_107_OFFSET UNITYSDK_OFFSET(0x177E3610)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_108_OFFSET UNITYSDK_OFFSET(0x177E3710)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_109_OFFSET UNITYSDK_OFFSET(0x177E37E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_10_OFFSET UNITYSDK_OFFSET(0x177DEBE0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_110_OFFSET UNITYSDK_OFFSET(0x177E3840)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_111_OFFSET UNITYSDK_OFFSET(0x177E3940)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_112_OFFSET UNITYSDK_OFFSET(0x177E3990)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_113_OFFSET UNITYSDK_OFFSET(0x177E3A80)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_114_OFFSET UNITYSDK_OFFSET(0x177E3AE0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_115_OFFSET UNITYSDK_OFFSET(0x177E3B90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_116_OFFSET UNITYSDK_OFFSET(0x177E3C70)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_117_OFFSET UNITYSDK_OFFSET(0x177E3CC0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_118_OFFSET UNITYSDK_OFFSET(0x177E3D50)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_119_OFFSET UNITYSDK_OFFSET(0x177E3E00)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_11_OFFSET UNITYSDK_OFFSET(0x177DECA0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_120_OFFSET UNITYSDK_OFFSET(0x177E3EB0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_121_OFFSET UNITYSDK_OFFSET(0x177E3F60)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_122_OFFSET UNITYSDK_OFFSET(0x177E4060)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_123_OFFSET UNITYSDK_OFFSET(0x177E4160)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_124_OFFSET UNITYSDK_OFFSET(0x177E41F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_125_OFFSET UNITYSDK_OFFSET(0x177E42F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_126_OFFSET UNITYSDK_OFFSET(0x177E4380)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_127_OFFSET UNITYSDK_OFFSET(0x177E4430)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_128_OFFSET UNITYSDK_OFFSET(0x177E44C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_129_OFFSET UNITYSDK_OFFSET(0x177E4510)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_12_OFFSET UNITYSDK_OFFSET(0x177DED30)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_130_OFFSET UNITYSDK_OFFSET(0x177E45E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_131_OFFSET UNITYSDK_OFFSET(0x177E4670)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_132_OFFSET UNITYSDK_OFFSET(0x177E4760)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_133_OFFSET UNITYSDK_OFFSET(0x177E4810)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_134_OFFSET UNITYSDK_OFFSET(0x177E48F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_135_OFFSET UNITYSDK_OFFSET(0x177E4980)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_136_OFFSET UNITYSDK_OFFSET(0x177E4A10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_137_OFFSET UNITYSDK_OFFSET(0x177E4B10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_138_OFFSET UNITYSDK_OFFSET(0x177E4BA0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_139_OFFSET UNITYSDK_OFFSET(0x177E4C80)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_13_OFFSET UNITYSDK_OFFSET(0x177DEDF0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_140_OFFSET UNITYSDK_OFFSET(0x177E4D10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_141_OFFSET UNITYSDK_OFFSET(0x177E4DA0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_142_OFFSET UNITYSDK_OFFSET(0x177E4EA0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_143_OFFSET UNITYSDK_OFFSET(0x177E4F30)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_144_OFFSET UNITYSDK_OFFSET(0x177E4FE0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_145_OFFSET UNITYSDK_OFFSET(0x177E5090)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_146_OFFSET UNITYSDK_OFFSET(0x177E5120)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_147_OFFSET UNITYSDK_OFFSET(0x177E51B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_148_OFFSET UNITYSDK_OFFSET(0x177E5240)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_149_OFFSET UNITYSDK_OFFSET(0x177E52B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_14_OFFSET UNITYSDK_OFFSET(0x177DEEB0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_150_OFFSET UNITYSDK_OFFSET(0x177E53C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_151_OFFSET UNITYSDK_OFFSET(0x177E55C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_152_OFFSET UNITYSDK_OFFSET(0x177E5770)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_153_OFFSET UNITYSDK_OFFSET(0x177E5900)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_154_OFFSET UNITYSDK_OFFSET(0x177E5B10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_155_OFFSET UNITYSDK_OFFSET(0x177E5D00)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_156_OFFSET UNITYSDK_OFFSET(0x177E5EE0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_157_OFFSET UNITYSDK_OFFSET(0x177E60F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_158_OFFSET UNITYSDK_OFFSET(0x177E6300)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_159_OFFSET UNITYSDK_OFFSET(0x177E6490)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_15_OFFSET UNITYSDK_OFFSET(0x177DEF70)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_160_OFFSET UNITYSDK_OFFSET(0x177E6680)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_161_OFFSET UNITYSDK_OFFSET(0x177E6870)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_162_OFFSET UNITYSDK_OFFSET(0x177E6A10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_163_OFFSET UNITYSDK_OFFSET(0x177E6C10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_164_OFFSET UNITYSDK_OFFSET(0x177E6E10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_165_OFFSET UNITYSDK_OFFSET(0x177E6FB0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_166_OFFSET UNITYSDK_OFFSET(0x177E7140)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_167_OFFSET UNITYSDK_OFFSET(0x177E7280)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_16_OFFSET UNITYSDK_OFFSET(0x177DF050)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_17_OFFSET UNITYSDK_OFFSET(0x177DF110)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_18_OFFSET UNITYSDK_OFFSET(0x177DF180)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_19_OFFSET UNITYSDK_OFFSET(0x177DF260)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_1_OFFSET UNITYSDK_OFFSET(0x177DE660)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_20_OFFSET UNITYSDK_OFFSET(0x177DF2F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_21_OFFSET UNITYSDK_OFFSET(0x177DF380)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_22_OFFSET UNITYSDK_OFFSET(0x177DF410)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_23_OFFSET UNITYSDK_OFFSET(0x177DF480)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_24_OFFSET UNITYSDK_OFFSET(0x177DF560)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_25_OFFSET UNITYSDK_OFFSET(0x177DF5D0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_26_OFFSET UNITYSDK_OFFSET(0x177DF640)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_27_OFFSET UNITYSDK_OFFSET(0x177DF700)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_28_OFFSET UNITYSDK_OFFSET(0x177DF840)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_29_OFFSET UNITYSDK_OFFSET(0x177DF900)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_2_OFFSET UNITYSDK_OFFSET(0x177DE6F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_30_OFFSET UNITYSDK_OFFSET(0x177DF9E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_31_OFFSET UNITYSDK_OFFSET(0x177DFAA0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_32_OFFSET UNITYSDK_OFFSET(0x177DFB60)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_33_OFFSET UNITYSDK_OFFSET(0x177DFBD0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_34_OFFSET UNITYSDK_OFFSET(0x177DFC60)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_35_OFFSET UNITYSDK_OFFSET(0x177DFD60)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_36_OFFSET UNITYSDK_OFFSET(0x177DFE20)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_37_OFFSET UNITYSDK_OFFSET(0x177DFF20)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_38_OFFSET UNITYSDK_OFFSET(0x177DFF90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_39_OFFSET UNITYSDK_OFFSET(0x177E0070)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_3_OFFSET UNITYSDK_OFFSET(0x177DE760)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_40_OFFSET UNITYSDK_OFFSET(0x177E0130)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_41_OFFSET UNITYSDK_OFFSET(0x177E01A0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_42_OFFSET UNITYSDK_OFFSET(0x177E0260)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_43_OFFSET UNITYSDK_OFFSET(0x177E0320)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_44_OFFSET UNITYSDK_OFFSET(0x177E0420)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_45_OFFSET UNITYSDK_OFFSET(0x177E0470)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_46_OFFSET UNITYSDK_OFFSET(0x177E0530)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_47_OFFSET UNITYSDK_OFFSET(0x177E05F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_48_OFFSET UNITYSDK_OFFSET(0x177E06B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_49_OFFSET UNITYSDK_OFFSET(0x177E0770)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_4_OFFSET UNITYSDK_OFFSET(0x177DE7F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_50_OFFSET UNITYSDK_OFFSET(0x177E0890)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_51_OFFSET UNITYSDK_OFFSET(0x177E09B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_52_OFFSET UNITYSDK_OFFSET(0x177E0AD0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_53_OFFSET UNITYSDK_OFFSET(0x177E0BF0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_54_OFFSET UNITYSDK_OFFSET(0x177E0CD0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_55_OFFSET UNITYSDK_OFFSET(0x177E0DB0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_56_OFFSET UNITYSDK_OFFSET(0x177E0E90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_57_OFFSET UNITYSDK_OFFSET(0x177E0F50)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_58_OFFSET UNITYSDK_OFFSET(0x177E1010)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_59_OFFSET UNITYSDK_OFFSET(0x177E10D0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_5_OFFSET UNITYSDK_OFFSET(0x177DE820)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_60_OFFSET UNITYSDK_OFFSET(0x177E1190)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_61_OFFSET UNITYSDK_OFFSET(0x177E1270)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_62_OFFSET UNITYSDK_OFFSET(0x177E1330)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_63_OFFSET UNITYSDK_OFFSET(0x177E1410)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_64_OFFSET UNITYSDK_OFFSET(0x177E1530)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_65_OFFSET UNITYSDK_OFFSET(0x177E1650)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_66_OFFSET UNITYSDK_OFFSET(0x177E1730)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_67_OFFSET UNITYSDK_OFFSET(0x177E17F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_68_OFFSET UNITYSDK_OFFSET(0x177E18D0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_69_OFFSET UNITYSDK_OFFSET(0x177E19B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_6_OFFSET UNITYSDK_OFFSET(0x177DE8B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_70_OFFSET UNITYSDK_OFFSET(0x177E1A90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_71_OFFSET UNITYSDK_OFFSET(0x177E1B50)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_72_OFFSET UNITYSDK_OFFSET(0x177E1C30)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_73_OFFSET UNITYSDK_OFFSET(0x177E1CF0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_74_OFFSET UNITYSDK_OFFSET(0x177E1DB0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_75_OFFSET UNITYSDK_OFFSET(0x177E1E40)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_76_OFFSET UNITYSDK_OFFSET(0x177E1F00)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_77_OFFSET UNITYSDK_OFFSET(0x177E1FE0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_78_OFFSET UNITYSDK_OFFSET(0x177E20A0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_79_OFFSET UNITYSDK_OFFSET(0x177E21A0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_7_OFFSET UNITYSDK_OFFSET(0x177DE920)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_80_OFFSET UNITYSDK_OFFSET(0x177E2260)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_81_OFFSET UNITYSDK_OFFSET(0x177E2320)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_82_OFFSET UNITYSDK_OFFSET(0x177E23E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_83_OFFSET UNITYSDK_OFFSET(0x177E24C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_84_OFFSET UNITYSDK_OFFSET(0x177E2530)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_85_OFFSET UNITYSDK_OFFSET(0x177E25F0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_86_OFFSET UNITYSDK_OFFSET(0x177E26B0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_87_OFFSET UNITYSDK_OFFSET(0x177E27D0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_88_OFFSET UNITYSDK_OFFSET(0x177E2890)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_89_OFFSET UNITYSDK_OFFSET(0x177E2900)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_8_OFFSET UNITYSDK_OFFSET(0x177DE9E0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_90_OFFSET UNITYSDK_OFFSET(0x177E29C0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_91_OFFSET UNITYSDK_OFFSET(0x177E2A80)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_92_OFFSET UNITYSDK_OFFSET(0x177E2B40)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_93_OFFSET UNITYSDK_OFFSET(0x177E2C20)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_94_OFFSET UNITYSDK_OFFSET(0x177E2C90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_95_OFFSET UNITYSDK_OFFSET(0x177E2D50)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_96_OFFSET UNITYSDK_OFFSET(0x177E2E10)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_97_OFFSET UNITYSDK_OFFSET(0x177E2ED0)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_98_OFFSET UNITYSDK_OFFSET(0x177E2F90)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_99_OFFSET UNITYSDK_OFFSET(0x177E3000)
#define RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_9_OFFSET UNITYSDK_OFFSET(0x177DEAA0)

namespace RPG::GameCore
{
	inline static constexpr unsigned int TargetSeqOperation___c_TypeDefinitionIndex = 22015;

	class TargetSeqOperation___c : public ::System::Object
	{
	public:
		static ::RPG::GameCore::TargetSeqOperation___c** StaticGet___9()
		{
			return (::RPG::GameCore::TargetSeqOperation___c**)Il2CppClass::FromTypeDefinitionIndex(TargetSeqOperation___c_TypeDefinitionIndex)->GetStaticField(0x167C0);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C__CCTOR_OFFSET))();
		}

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C__CTOR_OFFSET))(this);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_0(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_0_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_1(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_1_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_2(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_2_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_3(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_3_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_4(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_4_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_5(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_5_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_6(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_6_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_7(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_7_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_8(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_8_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_9(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_9_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_10(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_10_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_11(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_11_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_12(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_12_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_13(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_13_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_14(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_14_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_15(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_15_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_16(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_16_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_17(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_17_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_18(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_18_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_19(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_19_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_20(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_20_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_21(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_21_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_22(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_22_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_23(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_23_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_24(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_24_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_25(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_25_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_26(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_26_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_27(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_27_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_28(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_28_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_29(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_29_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_30(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_30_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_31(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_31_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_32(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_32_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_33(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_33_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_34(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_34_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_35(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_35_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_36(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_36_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_37(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_37_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_38(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_38_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_39(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_39_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_40(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_40_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_41(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_41_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_42(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_42_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_43(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_43_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_44(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_44_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_45(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_45_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_46(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_46_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_47(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_47_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_48(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_48_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_49(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_49_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_50(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_50_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_51(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_51_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_52(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_52_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_53(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_53_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_54(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_54_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_55(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_55_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_56(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_56_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_57(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_57_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_58(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_58_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_59(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_59_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_60(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_60_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_61(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_61_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_62(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_62_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_63(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_63_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_64(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_64_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_65(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_65_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_66(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_66_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_67(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_67_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_68(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_68_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_69(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_69_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_70(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_70_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_71(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_71_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_72(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_72_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_73(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_73_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_74(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_74_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_75(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_75_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_76(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_76_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_77(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_77_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_78(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_78_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_79(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_79_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_80(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_80_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_81(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_81_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_82(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_82_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_83(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_83_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_84(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_84_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_85(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_85_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_86(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_86_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_87(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_87_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_88(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_88_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_89(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_89_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_90(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_90_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_91(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_91_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_92(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_92_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_93(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_93_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_94(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_94_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_95(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_95_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_96(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_96_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_97(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_97_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_98(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_98_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_99(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_99_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_100(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_100_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_101(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_101_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_102(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_102_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_103(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_103_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_104(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_104_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_105(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_105_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_106(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_106_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_107(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_107_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_108(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_108_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_109(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_109_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_110(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_110_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_111(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_111_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_112(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_112_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_113(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_113_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_114(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_114_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_115(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_115_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_116(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_116_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_117(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_117_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_118(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_118_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_119(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_119_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_120(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_120_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_121(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_121_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_122(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_122_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_123(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_123_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_124(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_124_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_125(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_125_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_126(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_126_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_127(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_127_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_128(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_128_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_129(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_129_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_130(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_130_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_131(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_131_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_132(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_132_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_133(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_133_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_134(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_134_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_135(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_135_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_136(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_136_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_137(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_137_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_138(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_138_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_139(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_139_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_140(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_140_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_141(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_141_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_142(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_142_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_143(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_143_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_144(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_144_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_145(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_145_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_146(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_146_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_147(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_147_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_148(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_148_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_149(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_149_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_150(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_150_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_151(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_151_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_152(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_152_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_153(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_153_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_154(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_154_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_155(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_155_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_156(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_156_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_157(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_157_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_158(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_158_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_159(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_159_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_160(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_160_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_161(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_161_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_162(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_162_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_163(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_163_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_164(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_164_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_165(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_165_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_166(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_166_OFFSET))(this, array);
		}

		::RPG::GameCore::TargetSeqOperation* __cctor_b__4_167(::Class_1_7A22A3DBEEDD1F80* array)
		{
			return ((::RPG::GameCore::TargetSeqOperation*(*)(::PVOID, ::Class_1_7A22A3DBEEDD1F80*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TARGETSEQOPERATION___C___CCTOR_B__4_167_OFFSET))(this, array);
		}
	};
}
