#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/SwordTraining/SwordTrainingGameRecordType.h"
#include "unitysdk/System/Object.h"

#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_ACTIONID_OFFSET UNITYSDK_OFFSET(0xA517390)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_CHANGEVAL_OFFSET UNITYSDK_OFFSET(0xA517350)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_LASTDAY_OFFSET UNITYSDK_OFFSET(0xA5173D0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_LASTSECTION_OFFSET UNITYSDK_OFFSET(0xA5173B0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_OLDVALUE_OFFSET UNITYSDK_OFFSET(0xA5173F0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_ORIGINLEVEL_OFFSET UNITYSDK_OFFSET(0xA517370)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_STATUSTYPEINT_OFFSET UNITYSDK_OFFSET(0xA517330)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_ACTIONID_OFFSET UNITYSDK_OFFSET(0xA5173A0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_CHANGEVAL_OFFSET UNITYSDK_OFFSET(0xA517360)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_LASTDAY_OFFSET UNITYSDK_OFFSET(0xA5173E0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_LASTSECTION_OFFSET UNITYSDK_OFFSET(0xA5173C0)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_OLDVALUE_OFFSET UNITYSDK_OFFSET(0xA517400)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_ORIGINLEVEL_OFFSET UNITYSDK_OFFSET(0xA517380)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_STATUSTYPEINT_OFFSET UNITYSDK_OFFSET(0xA517340)
#define RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO__CTOR_OFFSET UNITYSDK_OFFSET(0xA517410)

namespace RPG::Client::SwordTraining
{
	inline static constexpr unsigned int SwordTrainingGameRecordInfo_TypeDefinitionIndex = 61603;

	class SwordTrainingGameRecordInfo : public ::System::Object
	{
	public:
		::System::Int32 _RecordParam2; // 0x10
		::System::Int32 _RecordParam1; // 0x14
		::RPG::Client::SwordTraining::SwordTrainingGameRecordType RecordType; // 0x18

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO__CTOR_OFFSET))(this);
		}

		::System::UInt32 get_StatusTypeInt()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_STATUSTYPEINT_OFFSET))(this);
		}

		::System::Void set_StatusTypeInt(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_STATUSTYPEINT_OFFSET))(this, value);
		}

		::System::Int32 get_ChangeVal()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_CHANGEVAL_OFFSET))(this);
		}

		::System::Void set_ChangeVal(::System::Int32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_CHANGEVAL_OFFSET))(this, value);
		}

		::System::UInt32 get_OriginLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_ORIGINLEVEL_OFFSET))(this);
		}

		::System::Void set_OriginLevel(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_ORIGINLEVEL_OFFSET))(this, value);
		}

		::System::UInt32 get_ActionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_ACTIONID_OFFSET))(this);
		}

		::System::Void set_ActionID(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_ACTIONID_OFFSET))(this, value);
		}

		::System::UInt32 get_LastSection()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_LASTSECTION_OFFSET))(this);
		}

		::System::Void set_LastSection(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_LASTSECTION_OFFSET))(this, value);
		}

		::System::UInt32 get_LastDay()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_LASTDAY_OFFSET))(this);
		}

		::System::Void set_LastDay(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_LASTDAY_OFFSET))(this, value);
		}

		::System::UInt32 get_OldValue()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_GET_OLDVALUE_OFFSET))(this);
		}

		::System::Void set_OldValue(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_SWORDTRAINING_SWORDTRAININGGAMERECORDINFO_SET_OLDVALUE_OFFSET))(this, value);
		}
	};
}
