#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Epic/OnlineServices/Handle.h"
#include "unitysdk/Epic/OnlineServices/Result.h"

namespace System { class String; }

#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_CANCELREQUEST_OFFSET UNITYSDK_OFFSET(0x1A3BD370)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_GETFILENAME_OFFSET UNITYSDK_OFFSET(0x1A3BD470)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_GETFILEREQUESTSTATE_OFFSET UNITYSDK_OFFSET(0x1A3BD3F0)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_RELEASE_OFFSET UNITYSDK_OFFSET(0x1A3BD690)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST__CTOR_1_OFFSET UNITYSDK_OFFSET(0x1A3BD360)
#define EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST__CTOR_OFFSET UNITYSDK_OFFSET(0x1A3BD350)

namespace Epic::OnlineServices::PlayerDataStorage
{
	inline static constexpr unsigned int PlayerDataStorageFileTransferRequest_TypeDefinitionIndex = 42472;

	class PlayerDataStorageFileTransferRequest : public ::Epic::OnlineServices::Handle
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST__CTOR_OFFSET))(this);
		}

		::System::Void _ctor_1(::System::IntPtr a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::IntPtr))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST__CTOR_1_OFFSET))(this, a1);
		}

		::Epic::OnlineServices::Result CancelRequest()
		{
			return ((::Epic::OnlineServices::Result(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_CANCELREQUEST_OFFSET))(this);
		}

		::Epic::OnlineServices::Result GetFileRequestState()
		{
			return ((::Epic::OnlineServices::Result(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_GETFILEREQUESTSTATE_OFFSET))(this);
		}

		::Epic::OnlineServices::Result GetFilename(::System::String*& a1)
		{
			return ((::Epic::OnlineServices::Result(*)(::PVOID, ::System::String*&))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_GETFILENAME_OFFSET))(this, a1);
		}

		::System::Void Release()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + EPIC_ONLINESERVICES_PLAYERDATASTORAGE_PLAYERDATASTORAGEFILETRANSFERREQUEST_RELEASE_OFFSET))(this);
		}
	};
}
