#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_0A3761FE34514D6C_43.h"
#include "unitysdk/RPG/Client/ActivityIdleLive/EquipUiData.h"
#include "unitysdk/RPG/Client/ActivityIdleLive/IdleLiveDecimal.h"
#include "unitysdk/RPG/Client/ActivityIdleLive/SlotUiData.h"
#include "unitysdk/RPG/Client/BaseModule.h"
#include "unitysdk/RPG/GameCore/ILBattleAvatarTag.h"
#include "unitysdk/RPG/GameCore/IdleLiveAvatarPropertyType.h"

class Class_0_16E4307DCC419505_617;
class Class_1_014C66952F2D60FA;
class Class_1_075C34D03AFA1215_55;
class Class_1_0AC743E88BB51C0B;
class Class_1_1CBA230307F9C289_30;
class Class_1_21C7581DFE99F091_46;
class Class_1_21C7581DFE99F091_47;
class Class_1_2BE37F50413FF023;
class Class_1_3D47BC6DE43C43F3;
class Class_1_668FE281FA72D3E8_11;
class Class_1_6CF570E1464558AD;
class Class_1_963E317C37FB5E9A_13;
class Class_1_9645B0775BC8A72D;
class Class_1_98F510457EDFDB86;
class Class_1_A0F414D2CF643E56;
class Class_1_C2235B147ECDF4BD;
class Class_1_D17272E82AE804C2_102;
class Class_1_D17272E82AE804C2_478;
class Class_1_D1E0AD3915BCCF29_53;
class Class_1_EFF6ABE3B36522D9_2;
class Class_1_F91AD0C5A85E4AFA_13;
class Class_1_FBDFBC4C2F16CDD1_1;
namespace Google::Protobuf::Collections { template <typename T> class RepeatedField_1; }
namespace RPG::Client { class ActivityData; }
namespace RPG::Client { class CommonActivityLightConeRewardData; }
namespace RPG::Client { class ItemDisplayData; }
namespace RPG::Client { class ScheduleData; }
namespace RPG::Client { class ScheduleTask; }
namespace RPG::Client::ActivityIdleLive { class AmphoreusTarotBuff; }
namespace RPG::Client::ActivityIdleLive { class CaptainData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveAvatarConfig; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveAvatarInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveAvatarPromotionBaseData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveAvatarPropertyItem; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveAvatarTagConfig; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveBaseTeamInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveChestData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveDungeonInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveEquipmentData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveGachaInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveQuestData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveQuestTreeInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveQuestTreeItemData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveTeamAvatarData; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveTeamInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveTeamRecommendInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveTeamSlotInfo; }
namespace RPG::Client::ActivityIdleLive { class IdleLiveTechTreeInfo; }
namespace RPG::Client::ActivityIdleLive { class LiveRoomInfo; }
namespace RPG::Client::ActivityIdleLive { class SpEquipSlotInfo; }
namespace RPG::Client::ActivityIdleLive { class SpSlotUiData; }
namespace RPG::Client::ActivityIdleLive { class SpecialEquip; }
namespace RPG::Client::ActivityIdleLive { class StoryLine; }
namespace System { class Object; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CANCELPREUPDATEDEQUIPS_OFFSET UNITYSDK_OFFSET(0x1731EFA0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CHECKISUNLOCKBYID_OFFSET UNITYSDK_OFFSET(0x17321950)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CREATEAVATARPROPERTYITEM_OFFSET UNITYSDK_OFFSET(0x1731D910)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CREATEAVATARTAGCONFIG_OFFSET UNITYSDK_OFFSET(0x1731D480)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ENTERGAME_OFFSET UNITYSDK_OFFSET(0x17323CE0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETACTIVITYDATA_OFFSET UNITYSDK_OFFSET(0x1731C280)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLAVATARPROPERTYITEMCONFIGS_OFFSET UNITYSDK_OFFSET(0x1731D820)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLEQUIPPEDNORMALEQUIPSCOPY_OFFSET UNITYSDK_OFFSET(0x1731ED20)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLEQUIPPEDSPEQUIPSCOPY_OFFSET UNITYSDK_OFFSET(0x1731ECC0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLSPEQUIPSCOPY_OFFSET UNITYSDK_OFFSET(0x173134F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLSPSLOTUIDATA_OFFSET UNITYSDK_OFFSET(0x1731F440)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARCONFIG_OFFSET UNITYSDK_OFFSET(0x1731D4D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATAREQUIPPEDSPEQUIPINFO_OFFSET UNITYSDK_OFFSET(0x1731F6E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROMOTIONCONFIG_OFFSET UNITYSDK_OFFSET(0x1731D990)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROMOTIONDATABYSTAR_OFFSET UNITYSDK_OFFSET(0x1731DBE0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROPERTYITEMCONFIG_OFFSET UNITYSDK_OFFSET(0x1731D640)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARSTARBYID_OFFSET UNITYSDK_OFFSET(0x1731E500)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCAPTAINCOUNT_OFFSET UNITYSDK_OFFSET(0x173263B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCAPTAINONEBASEDRANK_OFFSET UNITYSDK_OFFSET(0x1730F870)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCORRECTAVATARIDBYGENDER_OFFSET UNITYSDK_OFFSET(0x1731D6D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCURCHAPTERFINALACTREWARD_OFFSET UNITYSDK_OFFSET(0x173208C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETEQUIPUIDATABYSLOT_OFFSET UNITYSDK_OFFSET(0x1731F4D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETEXTRAPOWERBYEQUIP_OFFSET UNITYSDK_OFFSET(0x173200E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFINALACTCOSTTIMESEC_OFFSET UNITYSDK_OFFSET(0x17320270)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFIRSTMESSAGEID_OFFSET UNITYSDK_OFFSET(0x17321850)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFIRSTMESSAGESTARTCONTENTID_OFFSET UNITYSDK_OFFSET(0x173218B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETSLOTUIDATABYSLOT_OFFSET UNITYSDK_OFFSET(0x1731F3B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETSPEQUIPSLOTINFO_OFFSET UNITYSDK_OFFSET(0x1731D420)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETTOPFIRSTTHREECAPTAINICONS_OFFSET UNITYSDK_OFFSET(0x17326410)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETTOTALPROPERTYDIC_OFFSET UNITYSDK_OFFSET(0x1731F350)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETUNREADMESSAGECNT_OFFSET UNITYSDK_OFFSET(0x17321800)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ALLCAPTAINS_OFFSET UNITYSDK_OFFSET(0x173263A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_AMPHOREUSBUFF_OFFSET UNITYSDK_OFFSET(0x17322930)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_AVATARINFO_OFFSET UNITYSDK_OFFSET(0x1731E680)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_BATTLEPOWERRAW_OFFSET UNITYSDK_OFFSET(0x173163C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_BATTLEPOWER_OFFSET UNITYSDK_OFFSET(0x17321CD0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHAPTERRECORDS_OFFSET UNITYSDK_OFFSET(0x17322910)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHESTPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E720)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHEST_OFFSET UNITYSDK_OFFSET(0x1731E700)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CLOSEDGIFTS_OFFSET UNITYSDK_OFFSET(0x17320D10)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CLOSEDMESSAGES_OFFSET UNITYSDK_OFFSET(0x17320D20)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CRYSTALPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E740)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_DUNGEONINFO_OFFSET UNITYSDK_OFFSET(0x1731E780)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_EVENTID_OFFSET UNITYSDK_OFFSET(0x173228D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_GACHAINFO_OFFSET UNITYSDK_OFFSET(0x17320CF0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_HASRECEIVEDGETDATARSP_OFFSET UNITYSDK_OFFSET(0x173233E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ISRECORDNODEFINISHED_OFFSET UNITYSDK_OFFSET(0x173228F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ISSHOWPOWERCHANGETOAST_OFFSET UNITYSDK_OFFSET(0x17321E20)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_LIGHTCONEREWARD_OFFSET UNITYSDK_OFFSET(0x1731C6D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_LIVEROOMINFO_OFFSET UNITYSDK_OFFSET(0x173219C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_NORMALCHATPHASE_OFFSET UNITYSDK_OFFSET(0x17308560)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_POPPEDMESSAGES_OFFSET UNITYSDK_OFFSET(0x17320D30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_QUESTTREEINFO_OFFSET UNITYSDK_OFFSET(0x17322870)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_QUEST_OFFSET UNITYSDK_OFFSET(0x17320D40)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RAWPROTOPENDINGEQUIP_OFFSET UNITYSDK_OFFSET(0x1731ECA0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECOMMENDINFO_OFFSET UNITYSDK_OFFSET(0x1731E6E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECORDCHAPTERINDEX_OFFSET UNITYSDK_OFFSET(0x17322890)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECORDNODEINDEX_OFFSET UNITYSDK_OFFSET(0x173228B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_SLOTINFO_OFFSET UNITYSDK_OFFSET(0x1731E6C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_STORYLINE_OFFSET UNITYSDK_OFFSET(0x17322920)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMINFO_OFFSET UNITYSDK_OFFSET(0x1731E6A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMPOWERRAW_OFFSET UNITYSDK_OFFSET(0x17321CF0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMPOWER_OFFSET UNITYSDK_OFFSET(0x17321D70)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TECHTREEINFO_OFFSET UNITYSDK_OFFSET(0x173233C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TICKETPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E760)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_UNLOCKEDINTERACTIONS_OFFSET UNITYSDK_OFFSET(0x17320D70)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_UNREADMESSAGES_OFFSET UNITYSDK_OFFSET(0x17320D60)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_HASANYIDLELIVEAVATARNEW_OFFSET UNITYSDK_OFFSET(0x1731E370)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_INIT_OFFSET UNITYSDK_OFFSET(0x17323400)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISALLLIGHTCONEREWARDTAKEN_OFFSET UNITYSDK_OFFSET(0x1731C350)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISALLTIMELIMITREWARDTAKEN_OFFSET UNITYSDK_OFFSET(0x1731C3A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISCHAPTERFINALACTPLAYED_OFFSET UNITYSDK_OFFSET(0x173232C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISDUNGEONNEW_OFFSET UNITYSDK_OFFSET(0x1731E7A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISEQUIPQUESTFINISHED_OFFSET UNITYSDK_OFFSET(0x173224E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISFRIENDBANNED_OFFSET UNITYSDK_OFFSET(0x1731E8F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARHASSEEN_OFFSET UNITYSDK_OFFSET(0x1731E090)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARLONGPRESSTIPSHOW_OFFSET UNITYSDK_OFFSET(0x1731DDC0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARNEW_OFFSET UNITYSDK_OFFSET(0x1731E1A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARSTARUPHASSEEN_OFFSET UNITYSDK_OFFSET(0x17320A70)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISREACHMAXCOUNT_OFFSET UNITYSDK_OFFSET(0x17320BB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWLIGHTCONEREWARDNEW_OFFSET UNITYSDK_OFFSET(0x1731C470)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWLIGHTCONEREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0x1731C420)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWTIMELIMITREWARDNEW_OFFSET UNITYSDK_OFFSET(0x1731C550)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSPEQUIPALREADYGOT_OFFSET UNITYSDK_OFFSET(0x1731F2F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSPSLOTFULL_OFFSET UNITYSDK_OFFSET(0x17320060)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISTAROTFIRSTANIMPLAYED_OFFSET UNITYSDK_OFFSET(0x1731BBF0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ONLOGINFINISH_OFFSET UNITYSDK_OFFSET(0x17323C90)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_PREUPDATEEQUIPBYQUESTTREEITEMDATA_OFFSET UNITYSDK_OFFSET(0x1731EF40)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_PREUPDATEEQUIP_OFFSET UNITYSDK_OFFSET(0x1731EEE0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_RECORDFINALACTSTARTTIME_OFFSET UNITYSDK_OFFSET(0x17320170)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETDUNGEONSEEN_OFFSET UNITYSDK_OFFSET(0x1731EB90)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETIDLELIVEAVATARLONGPRESSTIPSHOW_OFFSET UNITYSDK_OFFSET(0x1731DE60)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETIDLELIVEAVATARSEEN_OFFSET UNITYSDK_OFFSET(0x1731E250)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETISIDLELIVEAVATARSTARUPHASSEEN_OFFSET UNITYSDK_OFFSET(0x17320B10)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETISSHOWPOWERCHANGETOAST_OFFSET UNITYSDK_OFFSET(0x17321E30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETLIGHTCONEREWARDNEWSEEN_OFFSET UNITYSDK_OFFSET(0x1731C4F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETTAROTFIRSTANIMPLAYED_OFFSET UNITYSDK_OFFSET(0x1731BDB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETTIMELIMITREWARDNEWSEEN_OFFSET UNITYSDK_OFFSET(0x1731C5F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_AMPHOREUSBUFF_OFFSET UNITYSDK_OFFSET(0x17322940)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_AVATARINFO_OFFSET UNITYSDK_OFFSET(0x1731E690)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_BATTLEPOWER_OFFSET UNITYSDK_OFFSET(0x17321CE0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CHESTPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E730)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CHEST_OFFSET UNITYSDK_OFFSET(0x1731E710)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CRYSTALPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E750)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_DUNGEONINFO_OFFSET UNITYSDK_OFFSET(0x1731E790)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_EVENTID_OFFSET UNITYSDK_OFFSET(0x173228E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_GACHAINFO_OFFSET UNITYSDK_OFFSET(0x17320D00)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_HASRECEIVEDGETDATARSP_OFFSET UNITYSDK_OFFSET(0x173233F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_ISRECORDNODEFINISHED_OFFSET UNITYSDK_OFFSET(0x17322900)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_LIGHTCONEREWARD_OFFSET UNITYSDK_OFFSET(0x1731C6E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_QUESTTREEINFO_OFFSET UNITYSDK_OFFSET(0x17322880)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_QUEST_OFFSET UNITYSDK_OFFSET(0x17320D50)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RAWPROTOPENDINGEQUIP_OFFSET UNITYSDK_OFFSET(0x1731ECB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECOMMENDINFO_OFFSET UNITYSDK_OFFSET(0x1731E6F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECORDCHAPTERINDEX_OFFSET UNITYSDK_OFFSET(0x173228A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECORDNODEINDEX_OFFSET UNITYSDK_OFFSET(0x173228C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_SLOTINFO_OFFSET UNITYSDK_OFFSET(0x1731E6D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TEAMINFO_OFFSET UNITYSDK_OFFSET(0x1731E6B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TECHTREEINFO_OFFSET UNITYSDK_OFFSET(0x173233D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TICKETPERHOUR_OFFSET UNITYSDK_OFFSET(0x1731E770)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETEQUIPBYSLOT_OFFSET UNITYSDK_OFFSET(0x1731F740)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETEQUIPUIDATAPROVIDERBYSLOT_OFFSET UNITYSDK_OFFSET(0x1731F680)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETGOTSPEQUIPBYID_OFFSET UNITYSDK_OFFSET(0x1731ED80)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETSPEQUIPEQUIPPED_OFFSET UNITYSDK_OFFSET(0x1731F130)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETSPEQUIPOWNED_OFFSET UNITYSDK_OFFSET(0x1731F1D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYREPLACESPEQUIP_OFFSET UNITYSDK_OFFSET(0x1731F090)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_UPDATEEQUIP_OFFSET UNITYSDK_OFFSET(0x1731EE80)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE_UPDATESPEQUIPDICT_OFFSET UNITYSDK_OFFSET(0x1731F030)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ADDMESSAGETOUNREADLIST_OFFSET UNITYSDK_OFFSET(0x17321540)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x17323D60)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__CTOR_OFFSET UNITYSDK_OFFSET(0x17326550)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__HASANYIDLELIVEAVATARNEW_B__29_0_OFFSET UNITYSDK_OFFSET(0x17326D00)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITAVATARCONFIGDIC_OFFSET UNITYSDK_OFFSET(0x1731C760)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITAVATARCONFIG_OFFSET UNITYSDK_OFFSET(0x1731C6F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITCAPTAINS_OFFSET UNITYSDK_OFFSET(0x173243C0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITDEFAULTCHATPHASE_OFFSET UNITYSDK_OFFSET(0x17322950)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITEQUIPQUESTIDS_OFFSET UNITYSDK_OFFSET(0x17322540)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITEQUIPSBYSERVER_OFFSET UNITYSDK_OFFSET(0x1731F7A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITFINALACTDICT_OFFSET UNITYSDK_OFFSET(0x173203A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITGACHA_OFFSET UNITYSDK_OFFSET(0x173209B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITLIGHTCONEREWARD_OFFSET UNITYSDK_OFFSET(0x1731C650)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITREQ_OFFSET UNITYSDK_OFFSET(0x17323680)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITTEAMINFOMODIFIERSOURCE_OFFSET UNITYSDK_OFFSET(0x1731CDB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INIT_B__228_0_OFFSET UNITYSDK_OFFSET(0x17326D90)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONDOGACHASCRSP_OFFSET UNITYSDK_OFFSET(0x17326100)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONDRESSSPECIALEQUIPSCRSP_OFFSET UNITYSDK_OFFSET(0x17325D70)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONENDDUNGEONSCRSP_OFFSET UNITYSDK_OFFSET(0x17325740)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONFINISHCHAPTERFINALACT_OFFSET UNITYSDK_OFFSET(0x17323200)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETDATASCRSP_OFFSET UNITYSDK_OFFSET(0x17324160)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETFRIENDDUNGEONINFOSCRSP_OFFSET UNITYSDK_OFFSET(0x17325BB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETFRIENDNEWASSISTREWARDSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x17325C60)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONHANDLEPENDINGEQUIPSCRSP_OFFSET UNITYSDK_OFFSET(0x173259A0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONPOWERCHANGE_OFFSET UNITYSDK_OFFSET(0x17321E80)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONREPLACETEAMCSRSP_OFFSET UNITYSDK_OFFSET(0x173246D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSCHEDULECLOSE_OFFSET UNITYSDK_OFFSET(0x17323C30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSTARTDUNGEONSCRSP_OFFSET UNITYSDK_OFFSET(0x17325670)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSTARTNODEBATTLESCRSP_OFFSET UNITYSDK_OFFSET(0x173257F0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSYNCCHANGECSNOTIFY_OFFSET UNITYSDK_OFFSET(0x17324780)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKEASSISTREWARDSCRSP_OFFSET UNITYSDK_OFFSET(0x17325AB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKECONTENTSCRSP_OFFSET UNITYSDK_OFFSET(0x17325A30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKEQUESTEQUIPCSRSP_OFFSET UNITYSDK_OFFSET(0x173261B0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTECHTREECHANGENODESTATECSRSP_OFFSET UNITYSDK_OFFSET(0x173258E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONUPDATECUSTOMINFOSCRSP_OFFSET UNITYSDK_OFFSET(0x17321AD0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONUPGRADETEAMSLOTCSRSP_OFFSET UNITYSDK_OFFSET(0x173262E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__RESETLIVEROOMTITLE_OFFSET UNITYSDK_OFFSET(0x17321C70)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__SORTCAPTAINBYTOTALSCDESCEND_OFFSET UNITYSDK_OFFSET(0x173254E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEADDAVATARINFO_OFFSET UNITYSDK_OFFSET(0x1731E620)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEAVATARINFO_OFFSET UNITYSDK_OFFSET(0x1731E580)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECAPTAIN_OFFSET UNITYSDK_OFFSET(0x173252E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECHAPTERBYPROTO_OFFSET UNITYSDK_OFFSET(0x17322A30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECHAPTERRECORDDATA_OFFSET UNITYSDK_OFFSET(0x17322FB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECLOSEDMESSAGES_OFFSET UNITYSDK_OFFSET(0x17321170)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECONTENTBYCONTENTAUTODELIVERY_OFFSET UNITYSDK_OFFSET(0x173215E0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECONTENTBYTAKECONTENTRSP_OFFSET UNITYSDK_OFFSET(0x17321670)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEDROPRATE_OFFSET UNITYSDK_OFFSET(0x17324670)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEFINISHEDGIFTS_OFFSET UNITYSDK_OFFSET(0x17320EB0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEINTERACTIONSBYSERVER_OFFSET UNITYSDK_OFFSET(0x17320D80)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATELIVEROOMBYSERVER_OFFSET UNITYSDK_OFFSET(0x173219D0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEMAXFINISHEDNODEDATA_OFFSET UNITYSDK_OFFSET(0x17322F50)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATERECORDDATA_OFFSET UNITYSDK_OFFSET(0x17322EE0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATETASK_OFFSET UNITYSDK_OFFSET(0x17321720)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY_INIT_OFFSET UNITYSDK_OFFSET(0x17326DA0)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY_ONLOGINFINISH_OFFSET UNITYSDK_OFFSET(0x17326E30)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x17326E90)
#define RPG_CLIENT_ACTIVITYIDLELIVEMODULE___ONFINISHCHAPTERFINALACT_B__216_0_OFFSET UNITYSDK_OFFSET(0x17326D40)

namespace RPG::Client
{
	inline static constexpr unsigned int ActivityIdleLiveModule_TypeDefinitionIndex = 56754;

	class ActivityIdleLiveModule : public ::RPG::Client::BaseModule
	{
	public:
		::RPG::Client::ActivityIdleLive::IdleLiveGachaInfo* _GachaInfo_k__BackingField; // 0x10
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _ClosedGifts_k__BackingField; // 0x18
		::RPG::Client::ActivityIdleLive::IdleLiveTeamInfo* _TeamInfo_k__BackingField; // 0x20
		::RPG::Client::CommonActivityLightConeRewardData* _LightConeReward_k__BackingField; // 0x28
		::RPG::Client::ActivityIdleLive::IdleLiveChestData* _Chest_k__BackingField; // 0x30
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _FinshedEquipQuestIDs; // 0x38
		::RPG::Client::ActivityIdleLive::IdleLiveTeamRecommendInfo* _RecommendInfo_k__BackingField; // 0x40
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::System::UInt32>*>* _AvatarPromotionIDDic; // 0x48
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _FemaleAvatarIdMap; // 0x50
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*>* _FinalActRewardDisplayData; // 0x58
		::System::Collections::Generic::List_1<::Class_1_6CF570E1464558AD*>* _ChapterRecords; // 0x60
		::RPG::Client::ActivityIdleLive::IdleLiveAvatarInfo* _AvatarInfo_k__BackingField; // 0x68
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _ClosedMessages_k__BackingField; // 0x70
		::RPG::Client::ActivityIdleLive::IdleLiveDungeonInfo* _DungeonInfo_k__BackingField; // 0x78
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::IdleLiveAvatarPropertyType, ::Class_1_3D47BC6DE43C43F3*>* _AvatarPropertyItemConfigDic; // 0x80
		::RPG::Client::ActivityIdleLive::AmphoreusTarotBuff* _AmphoreusBuff_k__BackingField; // 0x88
		::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeInfo* _QuestTreeInfo_k__BackingField; // 0x90
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _MaleAvatarIdMap; // 0x98
		::RPG::Client::ActivityIdleLive::IdleLiveTechTreeInfo* _TechTreeInfo_k__BackingField; // 0xA0
		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::CaptainData*>* _AllCaptains; // 0xA8
		::RPG::Client::ScheduleTask* _WaitCloseScheduleTask; // 0xB0
		::System::Collections::Generic::List_1<::System::UInt32>* _UnlockedInteractions_k__BackingField; // 0xB8
		::RPG::Client::ActivityIdleLive::IdleLiveQuestData* _Quest_k__BackingField; // 0xC0
		::RPG::Client::ActivityIdleLive::LiveRoomInfo* _LiveRoomInfo_k__BackingField; // 0xC8
		::Class_1_9645B0775BC8A72D* _EquipmentProvider; // 0xD0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityIdleLive::IdleLiveAvatarConfig*>* _AvatarConfigDic; // 0xD8
		::RPG::Client::ActivityIdleLive::IdleLiveTeamSlotInfo* _SlotInfo_k__BackingField; // 0xE0
		::System::Collections::Generic::List_1<::System::UInt32>* _UnReadMessages_k__BackingField; // 0xE8
		::Class_1_963E317C37FB5E9A_13* _RawProtoPendingEquip_k__BackingField; // 0xF0
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _PoppedMessages_k__BackingField; // 0xF8
		::RPG::Client::ActivityIdleLive::StoryLine* _StoryLine; // 0x100
		::System::UInt32 _RecordNodeIndex_k__BackingField; // 0x108
		::System::UInt32 _DefaultChatPhase; // 0x10C
		::System::UInt32 _CrystalPerHour_k__BackingField; // 0x110
		::System::UInt32 _FinalActStartTimestamp; // 0x114
		::System::UInt32 _ChestPerHour_k__BackingField; // 0x118
		::System::UInt32 _TicketPerHour_k__BackingField; // 0x11C
		::System::UInt32 _RecordChapterIndex_k__BackingField; // 0x120
		::System::UInt32 _MaxFinishedNode; // 0x124
		::System::UInt32 _EventId_k__BackingField; // 0x128
		::System::UInt64 _BattlePower_k__BackingField; // 0x130
		::System::UInt32 _MaxReachedNode; // 0x138
		::System::UInt32 _MaxReachedChapter; // 0x13C
		::System::Boolean _IsShowPowerChangeToast; // 0x140
		::System::Boolean _HasReceivedGetDataRsp_k__BackingField; // 0x141
		::System::Boolean _IsRecordNodeFinished_k__BackingField; // 0x142
		::System::UInt32 _MaxFinishedChapter; // 0x144

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__CTOR_OFFSET))(this);
		}

		::RPG::Client::ActivityData* GetActivityData()
		{
			return ((::RPG::Client::ActivityData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETACTIVITYDATA_OFFSET))(this);
		}

		::System::Boolean IsAllLightConeRewardTaken()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISALLLIGHTCONEREWARDTAKEN_OFFSET))(this);
		}

		::System::Boolean IsAllTimeLimitRewardTaken()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISALLTIMELIMITREWARDTAKEN_OFFSET))(this);
		}

		::System::Boolean IsShowLightConeRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWLIGHTCONEREWARDREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowLightConeRewardNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWLIGHTCONEREWARDNEW_OFFSET))(this);
		}

		::System::Void SetLightConeRewardNewSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETLIGHTCONEREWARDNEWSEEN_OFFSET))(this);
		}

		::System::Boolean IsShowTimeLimitRewardNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSHOWTIMELIMITREWARDNEW_OFFSET))(this);
		}

		::System::Void SetTimeLimitRewardNewSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETTIMELIMITREWARDNEWSEEN_OFFSET))(this);
		}

		::System::Void _InitLightConeReward()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITLIGHTCONEREWARD_OFFSET))(this);
		}

		::RPG::Client::CommonActivityLightConeRewardData* get_LightConeReward()
		{
			return ((::RPG::Client::CommonActivityLightConeRewardData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_LIGHTCONEREWARD_OFFSET))(this);
		}

		::System::Void set_LightConeReward(::RPG::Client::CommonActivityLightConeRewardData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::CommonActivityLightConeRewardData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_LIGHTCONEREWARD_OFFSET))(this, value);
		}

		::System::Void _InitAvatarConfig()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITAVATARCONFIG_OFFSET))(this);
		}

		::System::Void _InitAvatarConfigDic()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITAVATARCONFIGDIC_OFFSET))(this);
		}

		::System::Void _InitTeamInfoModifierSource()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITTEAMINFOMODIFIERSOURCE_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveAvatarTagConfig* CreateAvatarTagConfig(::RPG::GameCore::ILBattleAvatarTag tag)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveAvatarTagConfig*(*)(::PVOID, ::RPG::GameCore::ILBattleAvatarTag))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CREATEAVATARTAGCONFIG_OFFSET))(this, tag);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveAvatarConfig* GetAvatarConfig(::System::UInt32 avatarId)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveAvatarConfig*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARCONFIG_OFFSET))(this, avatarId);
		}

		::Class_1_3D47BC6DE43C43F3* GetAvatarPropertyItemConfig(::RPG::GameCore::IdleLiveAvatarPropertyType type)
		{
			return ((::Class_1_3D47BC6DE43C43F3*(*)(::PVOID, ::RPG::GameCore::IdleLiveAvatarPropertyType))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROPERTYITEMCONFIG_OFFSET))(this, type);
		}

		::System::UInt32 GetCorrectAvatarIDByGender(::System::UInt32 avatarId)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCORRECTAVATARIDBYGENDER_OFFSET))(this, avatarId);
		}

		::System::Collections::Generic::List_1<::Class_1_3D47BC6DE43C43F3*>* GetAllAvatarPropertyItemConfigs()
		{
			return ((::System::Collections::Generic::List_1<::Class_1_3D47BC6DE43C43F3*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLAVATARPROPERTYITEMCONFIGS_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveAvatarPropertyItem* CreateAvatarPropertyItem(::RPG::GameCore::IdleLiveAvatarPropertyType type, ::RPG::Client::ActivityIdleLive::IdleLiveDecimal value)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveAvatarPropertyItem*(*)(::PVOID, ::RPG::GameCore::IdleLiveAvatarPropertyType, ::RPG::Client::ActivityIdleLive::IdleLiveDecimal))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CREATEAVATARPROPERTYITEM_OFFSET))(this, type, value);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::IdleLiveAvatarPromotionBaseData*>* GetAvatarPromotionConfig(::System::UInt32 avatarId)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::IdleLiveAvatarPromotionBaseData*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROMOTIONCONFIG_OFFSET))(this, avatarId);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveAvatarPromotionBaseData* GetAvatarPromotionDataByStar(::System::UInt32 avatarID, ::System::UInt32 star)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveAvatarPromotionBaseData*(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARPROMOTIONDATABYSTAR_OFFSET))(this, avatarID, star);
		}

		::System::Boolean IsIdleLiveAvatarLongPressTipShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARLONGPRESSTIPSHOW_OFFSET))(this);
		}

		::System::Void SetIdleLiveAvatarLongPressTipShow()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETIDLELIVEAVATARLONGPRESSTIPSHOW_OFFSET))(this);
		}

		::System::Boolean IsIdleLiveAvatarHasSeen(::System::UInt32 avatarId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARHASSEEN_OFFSET))(this, avatarId);
		}

		::System::Boolean IsIdleLiveAvatarNew(::System::UInt32 avatarId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARNEW_OFFSET))(this, avatarId);
		}

		::System::Void SetIdleLiveAvatarSeen(::System::UInt32 avatarId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETIDLELIVEAVATARSEEN_OFFSET))(this, avatarId);
		}

		::System::Boolean HasAnyIdleLiveAvatarNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_HASANYIDLELIVEAVATARNEW_OFFSET))(this);
		}

		::System::UInt32 GetAvatarStarById(::System::UInt32 avatarId)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATARSTARBYID_OFFSET))(this, avatarId);
		}

		::System::Void _UpdateAvatarInfo(::Class_1_0AC743E88BB51C0B* info)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_0AC743E88BB51C0B*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEAVATARINFO_OFFSET))(this, info);
		}

		::System::Void _UpdateAddAvatarInfo(::Class_1_D17272E82AE804C2_478* avatar)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D17272E82AE804C2_478*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEADDAVATARINFO_OFFSET))(this, avatar);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveAvatarInfo* get_AvatarInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveAvatarInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_AVATARINFO_OFFSET))(this);
		}

		::System::Void set_AvatarInfo(::RPG::Client::ActivityIdleLive::IdleLiveAvatarInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveAvatarInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_AVATARINFO_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveTeamInfo* get_TeamInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveTeamInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMINFO_OFFSET))(this);
		}

		::System::Void set_TeamInfo(::RPG::Client::ActivityIdleLive::IdleLiveTeamInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveTeamInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TEAMINFO_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveTeamSlotInfo* get_SlotInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveTeamSlotInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_SLOTINFO_OFFSET))(this);
		}

		::System::Void set_SlotInfo(::RPG::Client::ActivityIdleLive::IdleLiveTeamSlotInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveTeamSlotInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_SLOTINFO_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveTeamRecommendInfo* get_RecommendInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveTeamRecommendInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECOMMENDINFO_OFFSET))(this);
		}

		::System::Void set_RecommendInfo(::RPG::Client::ActivityIdleLive::IdleLiveTeamRecommendInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveTeamRecommendInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECOMMENDINFO_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveChestData* get_Chest()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveChestData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHEST_OFFSET))(this);
		}

		::System::Void set_Chest(::RPG::Client::ActivityIdleLive::IdleLiveChestData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveChestData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CHEST_OFFSET))(this, value);
		}

		::System::UInt32 get_ChestPerHour()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHESTPERHOUR_OFFSET))(this);
		}

		::System::Void set_ChestPerHour(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CHESTPERHOUR_OFFSET))(this, value);
		}

		::System::UInt32 get_CrystalPerHour()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CRYSTALPERHOUR_OFFSET))(this);
		}

		::System::Void set_CrystalPerHour(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_CRYSTALPERHOUR_OFFSET))(this, value);
		}

		::System::UInt32 get_TicketPerHour()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TICKETPERHOUR_OFFSET))(this);
		}

		::System::Void set_TicketPerHour(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TICKETPERHOUR_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveDungeonInfo* get_DungeonInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveDungeonInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_DUNGEONINFO_OFFSET))(this);
		}

		::System::Void set_DungeonInfo(::RPG::Client::ActivityIdleLive::IdleLiveDungeonInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveDungeonInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_DUNGEONINFO_OFFSET))(this, value);
		}

		::System::Boolean IsDungeonNew(::System::UInt32 dungeonId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISDUNGEONNEW_OFFSET))(this, dungeonId);
		}

		::System::Boolean IsFriendBanned(::System::UInt32 uid)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISFRIENDBANNED_OFFSET))(this, uid);
		}

		::System::Void SetDungeonSeen(::System::UInt32 dungeonId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETDUNGEONSEEN_OFFSET))(this, dungeonId);
		}

		::Class_1_963E317C37FB5E9A_13* get_RawProtoPendingEquip()
		{
			return ((::Class_1_963E317C37FB5E9A_13*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RAWPROTOPENDINGEQUIP_OFFSET))(this);
		}

		::System::Void set_RawProtoPendingEquip(::Class_1_963E317C37FB5E9A_13* value)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_963E317C37FB5E9A_13*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RAWPROTOPENDINGEQUIP_OFFSET))(this, value);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpecialEquip*>* GetAllSpEquipsCopy()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpecialEquip*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLSPEQUIPSCOPY_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpecialEquip*>* GetAllEquippedSpEquipsCopy()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpecialEquip*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLEQUIPPEDSPEQUIPSCOPY_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData*>* GetAllEquippedNormalEquipsCopy()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLEQUIPPEDNORMALEQUIPSCOPY_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::SpecialEquip* TryGetGotSpEquipById(::System::UInt32 spEquipId)
		{
			return ((::RPG::Client::ActivityIdleLive::SpecialEquip*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETGOTSPEQUIPBYID_OFFSET))(this, spEquipId);
		}

		::System::Void UpdateEquip(::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData* newEquip)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_UPDATEEQUIP_OFFSET))(this, newEquip);
		}

		::System::Void PreUpdateEquip(::Class_1_A0F414D2CF643E56* newProtoEquip)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_A0F414D2CF643E56*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_PREUPDATEEQUIP_OFFSET))(this, newProtoEquip);
		}

		::System::Void PreUpdateEquipByQuestTreeItemData(::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeItemData* newQuestTreeItemData)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_PREUPDATEEQUIPBYQUESTTREEITEMDATA_OFFSET))(this, newQuestTreeItemData);
		}

		::System::Void CancelPreUpdatedEquips()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CANCELPREUPDATEDEQUIPS_OFFSET))(this);
		}

		::System::Void UpdateSpEquipDict(::RPG::Client::ActivityIdleLive::SpecialEquip* equip)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::SpecialEquip*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_UPDATESPEQUIPDICT_OFFSET))(this, equip);
		}

		::System::Void TryReplaceSpEquip(::RPG::Client::ActivityIdleLive::SpecialEquip* equip)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::SpecialEquip*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYREPLACESPEQUIP_OFFSET))(this, equip);
		}

		::RPG::Client::ActivityIdleLive::SpecialEquip* TryGetSpEquipEquipped(::RPG::Client::ActivityIdleLive::SpecialEquip* spEquip)
		{
			return ((::RPG::Client::ActivityIdleLive::SpecialEquip*(*)(::PVOID, ::RPG::Client::ActivityIdleLive::SpecialEquip*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETSPEQUIPEQUIPPED_OFFSET))(this, spEquip);
		}

		::RPG::Client::ActivityIdleLive::SpecialEquip* TryGetSpEquipOwned(::RPG::Client::ActivityIdleLive::SpecialEquip* spEquip)
		{
			return ((::RPG::Client::ActivityIdleLive::SpecialEquip*(*)(::PVOID, ::RPG::Client::ActivityIdleLive::SpecialEquip*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETSPEQUIPOWNED_OFFSET))(this, spEquip);
		}

		::System::Boolean IsSpEquipAlreadyGot(::RPG::Client::ActivityIdleLive::SpecialEquip* spEquip)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::ActivityIdleLive::SpecialEquip*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSPEQUIPALREADYGOT_OFFSET))(this, spEquip);
		}

		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::IdleLiveAvatarPropertyType, ::RPG::Client::ActivityIdleLive::IdleLiveDecimal>* GetTotalPropertyDic()
		{
			return ((::System::Collections::Generic::Dictionary_2<::RPG::GameCore::IdleLiveAvatarPropertyType, ::RPG::Client::ActivityIdleLive::IdleLiveDecimal>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETTOTALPROPERTYDIC_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::SlotUiData GetSlotUiDataBySlot(::System::UInt32 slotIndex)
		{
			return ((::RPG::Client::ActivityIdleLive::SlotUiData(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETSLOTUIDATABYSLOT_OFFSET))(this, slotIndex);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpSlotUiData*>* GetAllSpSlotUiData(::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo* teamInfo)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::SpSlotUiData*>*(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETALLSPSLOTUIDATA_OFFSET))(this, teamInfo);
		}

		::RPG::Client::ActivityIdleLive::EquipUiData GetEquipUiDataBySlot(::System::UInt32 slotIndex)
		{
			return ((::RPG::Client::ActivityIdleLive::EquipUiData(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETEQUIPUIDATABYSLOT_OFFSET))(this, slotIndex);
		}

		::System::Collections::Generic::List_1<::Class_1_014C66952F2D60FA*>* GetAvatarEquippedSpEquipInfo(::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo* teamInfo)
		{
			return ((::System::Collections::Generic::List_1<::Class_1_014C66952F2D60FA*>*(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETAVATAREQUIPPEDSPEQUIPINFO_OFFSET))(this, teamInfo);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData* TryGetEquipBySlot(::System::UInt32 slotId)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveEquipmentData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETEQUIPBYSLOT_OFFSET))(this, slotId);
		}

		::Class_0_16E4307DCC419505_617* TryGetEquipUiDataProviderBySlot(::System::UInt32 slotId)
		{
			return ((::Class_0_16E4307DCC419505_617*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_TRYGETEQUIPUIDATAPROVIDERBYSLOT_OFFSET))(this, slotId);
		}

		::System::Void _InitEquipsByServer(::Class_1_98F510457EDFDB86* serverEquipInfo)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_98F510457EDFDB86*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITEQUIPSBYSERVER_OFFSET))(this, serverEquipInfo);
		}

		::System::Boolean IsSpSlotFull()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISSPSLOTFULL_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::SpEquipSlotInfo* GetSpEquipSlotInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::SpEquipSlotInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETSPEQUIPSLOTINFO_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveDecimal GetExtraPowerByEquip(::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo* teamInfo)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveDecimal(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveBaseTeamInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETEXTRAPOWERBYEQUIP_OFFSET))(this, teamInfo);
		}

		::System::Void RecordFinalActStartTime()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_RECORDFINALACTSTARTTIME_OFFSET))(this);
		}

		::System::UInt32 GetFinalActCostTimeSec()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFINALACTCOSTTIMESEC_OFFSET))(this);
		}

		::System::Void _InitFinalActDict()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITFINALACTDICT_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* GetCurChapterFinalActReward()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCURCHAPTERFINALACTREWARD_OFFSET))(this);
		}

		::System::Void _InitGacha()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITGACHA_OFFSET))(this);
		}

		::System::Boolean IsIdleLiveAvatarStarUpHasSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISIDLELIVEAVATARSTARUPHASSEEN_OFFSET))(this);
		}

		::System::Void SetIsIdleLiveAvatarStarUpHasSeen(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETISIDLELIVEAVATARSTARUPHASSEEN_OFFSET))(this, value);
		}

		::System::Boolean IsReachMaxCount()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISREACHMAXCOUNT_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveGachaInfo* get_GachaInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveGachaInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_GACHAINFO_OFFSET))(this);
		}

		::System::Void set_GachaInfo(::RPG::Client::ActivityIdleLive::IdleLiveGachaInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveGachaInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_GACHAINFO_OFFSET))(this, value);
		}

		::System::Collections::Generic::HashSet_1<::System::UInt32>* get_ClosedGifts()
		{
			return ((::System::Collections::Generic::HashSet_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CLOSEDGIFTS_OFFSET))(this);
		}

		::System::Collections::Generic::HashSet_1<::System::UInt32>* get_ClosedMessages()
		{
			return ((::System::Collections::Generic::HashSet_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CLOSEDMESSAGES_OFFSET))(this);
		}

		::System::Collections::Generic::HashSet_1<::System::UInt32>* get_PoppedMessages()
		{
			return ((::System::Collections::Generic::HashSet_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_POPPEDMESSAGES_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveQuestData* get_Quest()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveQuestData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_QUEST_OFFSET))(this);
		}

		::System::Void set_Quest(::RPG::Client::ActivityIdleLive::IdleLiveQuestData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveQuestData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_QUEST_OFFSET))(this, value);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_UnReadMessages()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_UNREADMESSAGES_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_UnlockedInteractions()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_UNLOCKEDINTERACTIONS_OFFSET))(this);
		}

		::System::Void _UpdateInteractionsByServer(::Class_1_2BE37F50413FF023* protoInteractions, ::Class_1_075C34D03AFA1215_55* protoUnlocks)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2BE37F50413FF023*, ::Class_1_075C34D03AFA1215_55*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEINTERACTIONSBYSERVER_OFFSET))(this, protoInteractions, protoUnlocks);
		}

		::System::Void _UpdateFinishedGifts(::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>* interactions)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEFINISHEDGIFTS_OFFSET))(this, interactions);
		}

		::System::Void _UpdateClosedMessages(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_21C7581DFE99F091_47*>* interactions)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_21C7581DFE99F091_47*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECLOSEDMESSAGES_OFFSET))(this, interactions);
		}

		::System::Void _UpdateContentByContentAutoDelivery(::Class_1_1CBA230307F9C289_30* autoDelivery)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_1CBA230307F9C289_30*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECONTENTBYCONTENTAUTODELIVERY_OFFSET))(this, autoDelivery);
		}

		::System::Void _UpdateContentByTakeContentRsp(::Enum_3_0A3761FE34514D6C_43 type, ::System::UInt32 contentId)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_0A3761FE34514D6C_43, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECONTENTBYTAKECONTENTRSP_OFFSET))(this, type, contentId);
		}

		::System::Void _AddMessageToUnreadList(::System::UInt32 messageId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ADDMESSAGETOUNREADLIST_OFFSET))(this, messageId);
		}

		::System::Void _UpdateTask(::Class_1_668FE281FA72D3E8_11* serverTask)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_668FE281FA72D3E8_11*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATETASK_OFFSET))(this, serverTask);
		}

		::System::Int32 GetUnReadMessageCnt()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETUNREADMESSAGECNT_OFFSET))(this);
		}

		::System::UInt32 GetFirstMessageId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFIRSTMESSAGEID_OFFSET))(this);
		}

		::System::UInt32 GetFirstMessageStartContentID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETFIRSTMESSAGESTARTCONTENTID_OFFSET))(this);
		}

		::System::Boolean CheckIsUnlockById(::System::UInt32 unlockId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_CHECKISUNLOCKBYID_OFFSET))(this, unlockId);
		}

		::RPG::Client::ActivityIdleLive::LiveRoomInfo* get_LiveRoomInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::LiveRoomInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_LIVEROOMINFO_OFFSET))(this);
		}

		::System::Void _UpdateLiveRoomByServer(::Class_1_F91AD0C5A85E4AFA_13* protoLiveRoom)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F91AD0C5A85E4AFA_13*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATELIVEROOMBYSERVER_OFFSET))(this, protoLiveRoom);
		}

		::System::Void _OnUpdateCustomInfoScRsp(::System::UInt16 cmdId, ::System::Object* rspObj)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONUPDATECUSTOMINFOSCRSP_OFFSET))(this, cmdId, rspObj);
		}

		::System::Void _ResetLiveRoomTitle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__RESETLIVEROOMTITLE_OFFSET))(this);
		}

		::System::UInt64 get_BattlePower()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_BATTLEPOWER_OFFSET))(this);
		}

		::System::Void set_BattlePower(::System::UInt64 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt64))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_BATTLEPOWER_OFFSET))(this, value);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveDecimal get_BattlePowerRaw()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveDecimal(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_BATTLEPOWERRAW_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveDecimal get_TeamPowerRaw()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveDecimal(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMPOWERRAW_OFFSET))(this);
		}

		::System::UInt64 get_TeamPower()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TEAMPOWER_OFFSET))(this);
		}

		::System::Boolean get_IsShowPowerChangeToast()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ISSHOWPOWERCHANGETOAST_OFFSET))(this);
		}

		::System::Void SetIsShowPowerChangeToast(::System::Boolean isShow)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETISSHOWPOWERCHANGETOAST_OFFSET))(this, isShow);
		}

		::System::Void _OnPowerChange(::Class_1_FBDFBC4C2F16CDD1_1* powerChange)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FBDFBC4C2F16CDD1_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONPOWERCHANGE_OFFSET))(this, powerChange);
		}

		::System::Boolean IsEquipQuestFinished(::System::UInt32 questID)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISEQUIPQUESTFINISHED_OFFSET))(this, questID);
		}

		::System::Void _InitEquipQuestIDs(::Class_1_98F510457EDFDB86* equipMgrInfo)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_98F510457EDFDB86*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITEQUIPQUESTIDS_OFFSET))(this, equipMgrInfo);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeInfo* get_QuestTreeInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_QUESTTREEINFO_OFFSET))(this);
		}

		::System::Void set_QuestTreeInfo(::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveQuestTreeInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_QUESTTREEINFO_OFFSET))(this, value);
		}

		::System::UInt32 get_RecordChapterIndex()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECORDCHAPTERINDEX_OFFSET))(this);
		}

		::System::Void set_RecordChapterIndex(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECORDCHAPTERINDEX_OFFSET))(this, value);
		}

		::System::UInt32 get_RecordNodeIndex()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_RECORDNODEINDEX_OFFSET))(this);
		}

		::System::Void set_RecordNodeIndex(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_RECORDNODEINDEX_OFFSET))(this, value);
		}

		::System::UInt32 get_NormalChatPhase()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_NORMALCHATPHASE_OFFSET))(this);
		}

		::System::UInt32 get_EventId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_EVENTID_OFFSET))(this);
		}

		::System::Void set_EventId(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_EVENTID_OFFSET))(this, value);
		}

		::System::Boolean get_IsRecordNodeFinished()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ISRECORDNODEFINISHED_OFFSET))(this);
		}

		::System::Void set_IsRecordNodeFinished(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_ISRECORDNODEFINISHED_OFFSET))(this, value);
		}

		::System::Collections::Generic::List_1<::Class_1_6CF570E1464558AD*>* get_ChapterRecords()
		{
			return ((::System::Collections::Generic::List_1<::Class_1_6CF570E1464558AD*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_CHAPTERRECORDS_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::StoryLine* get_StoryLine()
		{
			return ((::RPG::Client::ActivityIdleLive::StoryLine*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_STORYLINE_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::AmphoreusTarotBuff* get_AmphoreusBuff()
		{
			return ((::RPG::Client::ActivityIdleLive::AmphoreusTarotBuff*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_AMPHOREUSBUFF_OFFSET))(this);
		}

		::System::Void set_AmphoreusBuff(::RPG::Client::ActivityIdleLive::AmphoreusTarotBuff* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::AmphoreusTarotBuff*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_AMPHOREUSBUFF_OFFSET))(this, value);
		}

		::System::Void _InitDefaultChatPhase()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITDEFAULTCHATPHASE_OFFSET))(this);
		}

		::System::Void _UpdateChapterByProto(::Class_1_C2235B147ECDF4BD* serverChapterInfo)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_C2235B147ECDF4BD*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECHAPTERBYPROTO_OFFSET))(this, serverChapterInfo);
		}

		::System::Void _UpdateMaxFinishedNodeData(::System::UInt32 chapterId, ::System::UInt32 nodeId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEMAXFINISHEDNODEDATA_OFFSET))(this, chapterId, nodeId);
		}

		::System::Void _UpdateRecordData(::Class_1_21C7581DFE99F091_46* serverNodeRecord)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_21C7581DFE99F091_46*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATERECORDDATA_OFFSET))(this, serverNodeRecord);
		}

		::System::Void _UpdateChapterRecordData(::Class_1_EFF6ABE3B36522D9_2* serverChapterRecord)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_EFF6ABE3B36522D9_2*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECHAPTERRECORDDATA_OFFSET))(this, serverChapterRecord);
		}

		::System::Void _OnFinishChapterFinalAct(::System::UInt16 cmdId, ::System::Object* rspObj)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONFINISHCHAPTERFINALACT_OFFSET))(this, cmdId, rspObj);
		}

		::System::Boolean IsChapterFinalActPlayed(::System::UInt32 chapterId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISCHAPTERFINALACTPLAYED_OFFSET))(this, chapterId);
		}

		::System::Boolean IsTarotFirstAnimPlayed(::System::UInt32 cardId)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ISTAROTFIRSTANIMPLAYED_OFFSET))(this, cardId);
		}

		::System::Void SetTarotFirstAnimPlayed(::System::UInt32 cardId)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SETTAROTFIRSTANIMPLAYED_OFFSET))(this, cardId);
		}

		::RPG::Client::ActivityIdleLive::IdleLiveTechTreeInfo* get_TechTreeInfo()
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveTechTreeInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_TECHTREEINFO_OFFSET))(this);
		}

		::System::Void set_TechTreeInfo(::RPG::Client::ActivityIdleLive::IdleLiveTechTreeInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveTechTreeInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_TECHTREEINFO_OFFSET))(this, value);
		}

		::System::Boolean get_HasReceivedGetDataRsp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_HASRECEIVEDGETDATARSP_OFFSET))(this);
		}

		::System::Void set_HasReceivedGetDataRsp(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_SET_HASRECEIVEDGETDATARSP_OFFSET))(this, value);
		}

		::System::Void Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_INIT_OFFSET))(this);
		}

		::System::Void _InitReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITREQ_OFFSET))(this);
		}

		::System::Void _OnScheduleClose(::RPG::Client::ScheduleData* scheduleData)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ScheduleData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSCHEDULECLOSE_OFFSET))(this, scheduleData);
		}

		::System::Void OnLoginFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ONLOGINFINISH_OFFSET))(this);
		}

		::System::Void EnterGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_ENTERGAME_OFFSET))(this);
		}

		::System::Void _AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void _OnGetDataScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETDATASCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _UpdateDropRate(::Class_1_D1E0AD3915BCCF29_53* info)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D1E0AD3915BCCF29_53*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATEDROPRATE_OFFSET))(this, info);
		}

		::System::Void _OnReplaceTeamCsRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONREPLACETEAMCSRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnSyncChangeCsNotify(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSYNCCHANGECSNOTIFY_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnStartDungeonScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSTARTDUNGEONSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnEndDungeonScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONENDDUNGEONSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnStartNodeBattleScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONSTARTNODEBATTLESCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnTechTreeChangeNodeStateCsRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTECHTREECHANGENODESTATECSRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnHandlePendingEquipScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONHANDLEPENDINGEQUIPSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnTakeContentScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKECONTENTSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnTakeAssistRewardScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKEASSISTREWARDSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnGetFriendDungeonInfoScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETFRIENDDUNGEONINFOSCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnGetFriendNewAssistRewardScNotify(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONGETFRIENDNEWASSISTREWARDSCNOTIFY_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnDressSpecialEquipScRsp(::System::UInt16 cmdId, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONDRESSSPECIALEQUIPSCRSP_OFFSET))(this, cmdId, rspObject);
		}

		::System::Void _OnDoGachaScRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONDOGACHASCRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnTakeQuestEquipCsRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONTAKEQUESTEQUIPCSRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Void _OnUpgradeTeamSlotCsRsp(::System::UInt16 cmdID, ::System::Object* rspObject)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__ONUPGRADETEAMSLOTCSRSP_OFFSET))(this, cmdID, rspObject);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::CaptainData*>* get_AllCaptains()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ActivityIdleLive::CaptainData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GET_ALLCAPTAINS_OFFSET))(this);
		}

		::System::UInt32 GetCaptainCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCAPTAINCOUNT_OFFSET))(this);
		}

		::System::Int32 GetCaptainOneBasedRank(::System::UInt32 senderId)
		{
			return ((::System::Int32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETCAPTAINONEBASEDRANK_OFFSET))(this, senderId);
		}

		::System::Collections::Generic::List_1<::System::String*>* GetTopFirstThreeCaptainIcons()
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE_GETTOPFIRSTTHREECAPTAINICONS_OFFSET))(this);
		}

		::System::Void _SortCaptainByTotalScDescend()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__SORTCAPTAINBYTOTALSCDESCEND_OFFSET))(this);
		}

		::System::Void _InitCaptains(::Class_1_2BE37F50413FF023* contentMgrInfo)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2BE37F50413FF023*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INITCAPTAINS_OFFSET))(this, contentMgrInfo);
		}

		::System::Void _UpdateCaptain(::Class_1_D17272E82AE804C2_102* kvp, ::System::Boolean needSort)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D17272E82AE804C2_102*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__UPDATECAPTAIN_OFFSET))(this, kvp, needSort);
		}

		::System::Boolean _HasAnyIdleLiveAvatarNew_b__29_0(::RPG::Client::ActivityIdleLive::IdleLiveTeamAvatarData* avatar)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveTeamAvatarData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__HASANYIDLELIVEAVATARNEW_B__29_0_OFFSET))(this, avatar);
		}

		::System::Boolean __OnFinishChapterFinalAct_b__216_0(::Class_1_6CF570E1464558AD* x)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_6CF570E1464558AD*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE___ONFINISHCHAPTERFINALACT_B__216_0_OFFSET))(this, x);
		}

		::System::Void _Init_b__228_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE__INIT_B__228_0_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY_INIT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_OnLoginFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY_ONLOGINFINISH_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVEMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET))(this);
		}
	};
}
