#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_DB663931210BBC27_14.h"
#include "unitysdk/RPG/Client/AlleyEventInfo.h"
#include "unitysdk/RPG/Client/AlleyLineDirectionEnum.h"
#include "unitysdk/RPG/Client/AlleyModule_ActivityRaidAlleyLogExtraInfo.h"
#include "unitysdk/RPG/Client/BaseModule.h"
#include "unitysdk/RPG/GameCore/GridTypeEnum.h"
#include "unitysdk/UnityEngine/Vector2Int.h"

class Class_1_097D93F83453E9A1;
class Class_1_2CC11CDCB897D481;
class Class_1_412B349691B63094_1;
class Class_1_668FE281FA72D3E8_2;
class Class_1_7FF19F6206AF6DD7_6;
class Class_1_827373C1CEDFE355;
class Class_1_9940F9E16DD482B4;
namespace Google::Protobuf::Collections { template <typename T> class RepeatedField_1; }
namespace RPG::Client { class ActivityRaidAlleyOrderData; }
namespace RPG::Client { class ActivityRaidAlleySpecialOrderData; }
namespace RPG::Client { class AlleyConstValue; }
namespace RPG::Client { class AlleyGoodData; }
namespace RPG::Client { class AlleyGridItemData; }
namespace RPG::Client { class AlleyOrderData; }
namespace RPG::Client { class AlleyPlacingShipResult; }
namespace RPG::Client { class AlleyShipData; }
namespace RPG::Client { class AlleySpecialOrderData; }
namespace RPG::Client { class AlleyTransportHandler; }
namespace RPG::Client { class ClientAlleyLogisticsScore; }
namespace RPG::Client { class MainMissionData; }
namespace RPG::Client::Promises { class Promise; }
namespace RPG::GameCore { class AlleyActivityQuestRow; }
namespace RPG::GameCore { class AlleyDeskTalkRow; }
namespace RPG::GameCore { class AlleyMapGridConfig; }
namespace RPG::GameCore { class AlleyMapRewardRow; }
namespace RPG::GameCore { class AlleyPackGoodItemConfig; }
namespace System { class Object; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class IReadOnlyList_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_ALLEYMODULE_CACHELASTORDERID_OFFSET UNITYSDK_OFFSET(0x16E55330)
#define RPG_CLIENT_ALLEYMODULE_CANPAYSTAMP_OFFSET UNITYSDK_OFFSET(0x16E48B30)
#define RPG_CLIENT_ALLEYMODULE_CANRECEIVEAVATARREWARD_OFFSET UNITYSDK_OFFSET(0x16E48990)
#define RPG_CLIENT_ALLEYMODULE_CANRECEIVEQUESTREWARD_OFFSET UNITYSDK_OFFSET(0x16E48A50)
#define RPG_CLIENT_ALLEYMODULE_CANRECEIVERENOWNREWARD_OFFSET UNITYSDK_OFFSET(0x16E48C90)
#define RPG_CLIENT_ALLEYMODULE_CANRECEIVETABQUESTREWARD_OFFSET UNITYSDK_OFFSET(0x16E50A80)
#define RPG_CLIENT_ALLEYMODULE_CANSHOWPACKNEWORDEREVENT_OFFSET UNITYSDK_OFFSET(0x16E516C0)
#define RPG_CLIENT_ALLEYMODULE_CHECKALLEYGRIDCANPOPUPTIP_OFFSET UNITYSDK_OFFSET(0x16E5D1D0)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASLINEPATHCOORDSLIST_OFFSET UNITYSDK_OFFSET(0x16E5FD10)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWBUFFTIPBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5B2F0)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWBUFFTIP_OFFSET UNITYSDK_OFFSET(0x16E5B180)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWSHOPTIPBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5AC30)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWSHOPTIP_OFFSET UNITYSDK_OFFSET(0x16E5AAC0)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWTRANSPORTINFO_OFFSET UNITYSDK_OFFSET(0x16E49760)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWUNCLICKEDBUFFTIPBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5B7F0)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASNEWUNCLICKEDBUFFTIP_OFFSET UNITYSDK_OFFSET(0x16E5B680)
#define RPG_CLIENT_ALLEYMODULE_CHECKHASUNSEENSTAGEINFOPAGE_OFFSET UNITYSDK_OFFSET(0x16E50FB0)
#define RPG_CLIENT_ALLEYMODULE_CHECKISLINEDATACHANGEDBYMAPLAYER_OFFSET UNITYSDK_OFFSET(0x16E5D670)
#define RPG_CLIENT_ALLEYMODULE_CHECKISNEEDLOCALSAVE_OFFSET UNITYSDK_OFFSET(0x16E60080)
#define RPG_CLIENT_ALLEYMODULE_CHECKLINECOMPLETEDSTATEBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5FAC0)
#define RPG_CLIENT_ALLEYMODULE_CHECKLINECOMPLETEDSTATE_OFFSET UNITYSDK_OFFSET(0x16E5EB30)
#define RPG_CLIENT_ALLEYMODULE_CHECKMAPGRIDISCLICKED_OFFSET UNITYSDK_OFFSET(0x16E5BB90)
#define RPG_CLIENT_ALLEYMODULE_CHECKMAPGRIDNEEDPOPUPTIP_OFFSET UNITYSDK_OFFSET(0x16E5D2F0)
#define RPG_CLIENT_ALLEYMODULE_CHECKSHOPHASLINE_OFFSET UNITYSDK_OFFSET(0x16E61400)
#define RPG_CLIENT_ALLEYMODULE_CLEARALLEYTRANSPORTMAPDATA_OFFSET UNITYSDK_OFFSET(0x16E5D130)
#define RPG_CLIENT_ALLEYMODULE_CLEARLASTORDERID_OFFSET UNITYSDK_OFFSET(0x16E55420)
#define RPG_CLIENT_ALLEYMODULE_CLEARNEWALLEYGOODDATALIST_OFFSET UNITYSDK_OFFSET(0x16E55510)
#define RPG_CLIENT_ALLEYMODULE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x16E54300)
#define RPG_CLIENT_ALLEYMODULE_GETACTIVITYRAIDALLEYORDERDATA_OFFSET UNITYSDK_OFFSET(0x16E4B510)
#define RPG_CLIENT_ALLEYMODULE_GETACTIVITYRAIDALLEYSPECIALORDERDATA_OFFSET UNITYSDK_OFFSET(0x16E4B800)
#define RPG_CLIENT_ALLEYMODULE_GETALLENERGYCOUNT_OFFSET UNITYSDK_OFFSET(0x16E5E920)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYGRIDITEMDATALISTBYTYPE_OFFSET UNITYSDK_OFFSET(0x16E5A890)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYLAYERBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E59C50)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYMAPGRIDPREFABPATH_OFFSET UNITYSDK_OFFSET(0x16E5BF10)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYMAPIDBYLAYER_OFFSET UNITYSDK_OFFSET(0x16E59B30)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYMAPIDBYSHOPID_OFFSET UNITYSDK_OFFSET(0x16E621A0)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYMAPLINEDATA_OFFSET UNITYSDK_OFFSET(0x16E5D030)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYPACKGOODITEMCONFIG_OFFSET UNITYSDK_OFFSET(0x16E4B050)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYPACKSHIPCONFIG_OFFSET UNITYSDK_OFFSET(0x16E54D50)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYSPECIALORDERDATA_OFFSET UNITYSDK_OFFSET(0x16E54BA0)
#define RPG_CLIENT_ALLEYMODULE_GETALLEYTRANSPORTSHOWLAYER_OFFSET UNITYSDK_OFFSET(0x16E61560)
#define RPG_CLIENT_ALLEYMODULE_GETALLSHOPLISTBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5BFF0)
#define RPG_CLIENT_ALLEYMODULE_GETCONNECTSHOPIDBYBUFFDATA_OFFSET UNITYSDK_OFFSET(0x16E610D0)
#define RPG_CLIENT_ALLEYMODULE_GETCONNECTSHOPIDBYDOCKDATA_OFFSET UNITYSDK_OFFSET(0x16E60D30)
#define RPG_CLIENT_ALLEYMODULE_GETCURSTAGETARGETFUNDS_OFFSET UNITYSDK_OFFSET(0x16E4CE60)
#define RPG_CLIENT_ALLEYMODULE_GETCURTRACKMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E48D30)
#define RPG_CLIENT_ALLEYMODULE_GETCURURGENTMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E4CB40)
#define RPG_CLIENT_ALLEYMODULE_GETDRAWLINEENDPOINTPOSITIONEXCLUDEZERO_OFFSET UNITYSDK_OFFSET(0x16E60A10)
#define RPG_CLIENT_ALLEYMODULE_GETDRAWLINEENDPOINTPOSITION_OFFSET UNITYSDK_OFFSET(0x16E607F0)
#define RPG_CLIENT_ALLEYMODULE_GETENERGYCOUNTBYLINEDATA_OFFSET UNITYSDK_OFFSET(0x16E5F2A0)
#define RPG_CLIENT_ALLEYMODULE_GETENERGYCOUNT_OFFSET UNITYSDK_OFFSET(0x16E5EE80)
#define RPG_CLIENT_ALLEYMODULE_GETEVENTACTIVEMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E4C930)
#define RPG_CLIENT_ALLEYMODULE_GETEVENTMISSIONDATA_OFFSET UNITYSDK_OFFSET(0x16E4C890)
#define RPG_CLIENT_ALLEYMODULE_GETFINISHEDEVENTIDS_OFFSET UNITYSDK_OFFSET(0x16E49050)
#define RPG_CLIENT_ALLEYMODULE_GETGOODBELONGSHOPID_OFFSET UNITYSDK_OFFSET(0x16E4ACC0)
#define RPG_CLIENT_ALLEYMODULE_GETGOODSPROFITBYGOODSID_OFFSET UNITYSDK_OFFSET(0x16E5F7E0)
#define RPG_CLIENT_ALLEYMODULE_GETGRADEIDBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E59D50)
#define RPG_CLIENT_ALLEYMODULE_GETLASTORDERID_OFFSET UNITYSDK_OFFSET(0x16E55480)
#define RPG_CLIENT_ALLEYMODULE_GETLINEBUFFGRIDITEMDATALIST_OFFSET UNITYSDK_OFFSET(0x16E5CC90)
#define RPG_CLIENT_ALLEYMODULE_GETLINETRIGGERBYSHOPID_OFFSET UNITYSDK_OFFSET(0x16E61CE0)
#define RPG_CLIENT_ALLEYMODULE_GETLOGISTICSSCOREBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E620B0)
#define RPG_CLIENT_ALLEYMODULE_GETNEWALLEYGOODDATALIST_OFFSET UNITYSDK_OFFSET(0x16E554D0)
#define RPG_CLIENT_ALLEYMODULE_GETNEWGOODSIDS_OFFSET UNITYSDK_OFFSET(0x16E51B50)
#define RPG_CLIENT_ALLEYMODULE_GETNEWTIPSHOPIDBYMAPID_OFFSET UNITYSDK_OFFSET(0x16E5AFC0)
#define RPG_CLIENT_ALLEYMODULE_GETPACKUNSEENORDEREVENTID_OFFSET UNITYSDK_OFFSET(0x16E49560)
#define RPG_CLIENT_ALLEYMODULE_GETSHOWALLEYMAPREWARDROWLISTBYLAYER_OFFSET UNITYSDK_OFFSET(0x16E5FE40)
#define RPG_CLIENT_ALLEYMODULE_GETTRANSPORTBIRDNUM_OFFSET UNITYSDK_OFFSET(0x16E5F700)
#define RPG_CLIENT_ALLEYMODULE_GETUNLOCKALLEYMAPLAYERLIST_OFFSET UNITYSDK_OFFSET(0x16E59A70)
#define RPG_CLIENT_ALLEYMODULE_GETUNSEENEVENTIDS_OFFSET UNITYSDK_OFFSET(0x16E50C40)
#define RPG_CLIENT_ALLEYMODULE_GETUNSEENSPECIALORDERID_OFFSET UNITYSDK_OFFSET(0x16E510F0)
#define RPG_CLIENT_ALLEYMODULE_GET_ACITIVITYRAIDALLEYORDERDATADICT_OFFSET UNITYSDK_OFFSET(0x16E4B720)
#define RPG_CLIENT_ALLEYMODULE_GET_ACITIVITYRAIDALLEYSPECIALORDERDATADICT_OFFSET UNITYSDK_OFFSET(0x16E4BA00)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYACTIVITYPANELSEEN_OFFSET UNITYSDK_OFFSET(0x16E487B0)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYAVATARREWARDSEEN_OFFSET UNITYSDK_OFFSET(0x16E488F0)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYCONSTVALUE_OFFSET UNITYSDK_OFFSET(0x16E588D0)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYCURRENCYCONFIGID_OFFSET UNITYSDK_OFFSET(0x16E57A00)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYGOODPROFITINCREASEDICT_OFFSET UNITYSDK_OFFSET(0x16E589A0)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYQUESTREWARDSEEN_OFFSET UNITYSDK_OFFSET(0x16E48850)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYSHOPPROFITINCREASEDICT_OFFSET UNITYSDK_OFFSET(0x16E58980)
#define RPG_CLIENT_ALLEYMODULE_GET_ALLEYSPECIALORDERDATADICT_OFFSET UNITYSDK_OFFSET(0x16E588F0)
#define RPG_CLIENT_ALLEYMODULE_GET_AVATARREWARDQUEST_OFFSET UNITYSDK_OFFSET(0x16E51EA0)
#define RPG_CLIENT_ALLEYMODULE_GET_CACHENEWUNLOCKORDER_OFFSET UNITYSDK_OFFSET(0x16E50260)
#define RPG_CLIENT_ALLEYMODULE_GET_CACHERESULTEVENTID_OFFSET UNITYSDK_OFFSET(0x16E50220)
#define RPG_CLIENT_ALLEYMODULE_GET_CACHERESULTMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E50240)
#define RPG_CLIENT_ALLEYMODULE_GET_CURACCEPTEDSIDEEVENTCOUNT_OFFSET UNITYSDK_OFFSET(0x16E58A50)
#define RPG_CLIENT_ALLEYMODULE_GET_CURMAINEVENTSTAGE_OFFSET UNITYSDK_OFFSET(0x16E58A10)
#define RPG_CLIENT_ALLEYMODULE_GET_CURORDERDATA_OFFSET UNITYSDK_OFFSET(0x16E58900)
#define RPG_CLIENT_ALLEYMODULE_GET_CURRENOWNLEVEL_OFFSET UNITYSDK_OFFSET(0x16E589D0)
#define RPG_CLIENT_ALLEYMODULE_GET_CURTRANSPORTSCORE_OFFSET UNITYSDK_OFFSET(0x16E664F0)
#define RPG_CLIENT_ALLEYMODULE_GET_FINISHEDNORMALORDERNUM_OFFSET UNITYSDK_OFFSET(0x16E58960)
#define RPG_CLIENT_ALLEYMODULE_GET_FOCUSCAMERATIME_OFFSET UNITYSDK_OFFSET(0x16E66530)
#define RPG_CLIENT_ALLEYMODULE_GET_FUNDS_OFFSET UNITYSDK_OFFSET(0x16E589C0)
#define RPG_CLIENT_ALLEYMODULE_GET_GOODSREWARDROWS_OFFSET UNITYSDK_OFFSET(0x16E51E90)
#define RPG_CLIENT_ALLEYMODULE_GET_LEVELREWARDIDS_OFFSET UNITYSDK_OFFSET(0x16E50210)
#define RPG_CLIENT_ALLEYMODULE_GET_LEVELTARGETS_OFFSET UNITYSDK_OFFSET(0x16E50200)
#define RPG_CLIENT_ALLEYMODULE_GET_LOGICRANDOM_OFFSET UNITYSDK_OFFSET(0x16E588B0)
#define RPG_CLIENT_ALLEYMODULE_GET_MAINEVENTS_OFFSET UNITYSDK_OFFSET(0x16E58A70)
#define RPG_CLIENT_ALLEYMODULE_GET_MAXFINISHEDMAINEVENTSTAGE_OFFSET UNITYSDK_OFFSET(0x16E58A30)
#define RPG_CLIENT_ALLEYMODULE_GET_MAXLEVEL_OFFSET UNITYSDK_OFFSET(0x16E501E0)
#define RPG_CLIENT_ALLEYMODULE_GET_MAXTRANSPORTSCORE_OFFSET UNITYSDK_OFFSET(0x16E66510)
#define RPG_CLIENT_ALLEYMODULE_GET_ORDERPROFITINCREASE_OFFSET UNITYSDK_OFFSET(0x16E58920)
#define RPG_CLIENT_ALLEYMODULE_GET_RENOWNREWARDTAKENINFO_OFFSET UNITYSDK_OFFSET(0x16E589F0)
#define RPG_CLIENT_ALLEYMODULE_GET_SIDEEVENTS_OFFSET UNITYSDK_OFFSET(0x16E58A80)
#define RPG_CLIENT_ALLEYMODULE_GET_TRANSPORTRESULTNEWEVENTID_OFFSET UNITYSDK_OFFSET(0x16E664D0)
#define RPG_CLIENT_ALLEYMODULE_GET_TRANSPORTREWARDROWS_OFFSET UNITYSDK_OFFSET(0x16E51E80)
#define RPG_CLIENT_ALLEYMODULE_GET_UNFINISHEDNORMALORDERNUM_OFFSET UNITYSDK_OFFSET(0x16E58940)
#define RPG_CLIENT_ALLEYMODULE_HASREWARD_OFFSET UNITYSDK_OFFSET(0x16E50650)
#define RPG_CLIENT_ALLEYMODULE_INIT_OFFSET UNITYSDK_OFFSET(0x16E530C0)
#define RPG_CLIENT_ALLEYMODULE_ISALLEYMAPUNLOCKBYLAYER_OFFSET UNITYSDK_OFFSET(0x16E59AC0)
#define RPG_CLIENT_ALLEYMODULE_ISALLEYSHOPUNLOCK_OFFSET UNITYSDK_OFFSET(0x16E59F00)
#define RPG_CLIENT_ALLEYMODULE_ISALLSHOPLINECOMPLETED_OFFSET UNITYSDK_OFFSET(0x16E5F950)
#define RPG_CLIENT_ALLEYMODULE_ISCURSTAGETARGETFINISHED_OFFSET UNITYSDK_OFFSET(0x16E4CFB0)
#define RPG_CLIENT_ALLEYMODULE_LOADALLEYPACKGOODITEMCONFIG_OFFSET UNITYSDK_OFFSET(0x16E54C50)
#define RPG_CLIENT_ALLEYMODULE_PRINTALLACTIVEANDCLOSEDEVENTIDS_OFFSET UNITYSDK_OFFSET(0x16E4D3D0)
#define RPG_CLIENT_ALLEYMODULE_PRINTEVENTINFO_OFFSET UNITYSDK_OFFSET(0x16E4D100)
#define RPG_CLIENT_ALLEYMODULE_RANDOMGETTALKID_OFFSET UNITYSDK_OFFSET(0x16E51EC0)
#define RPG_CLIENT_ALLEYMODULE_RANDOMGETTALKSENTENCEID_OFFSET UNITYSDK_OFFSET(0x16E525B0)
#define RPG_CLIENT_ALLEYMODULE_RECORDALLSPECIALORDERIDS_OFFSET UNITYSDK_OFFSET(0x16E513A0)
#define RPG_CLIENT_ALLEYMODULE_RECORDPACKSEENSTAGE_OFFSET UNITYSDK_OFFSET(0x16E51970)
#define RPG_CLIENT_ALLEYMODULE_RECORDPACKUNSEENORDEREVENTID_OFFSET UNITYSDK_OFFSET(0x16E51710)
#define RPG_CLIENT_ALLEYMODULE_RECORDSPECIALORDERID_OFFSET UNITYSDK_OFFSET(0x16E515A0)
#define RPG_CLIENT_ALLEYMODULE_REFRESHALLEYINFO_OFFSET UNITYSDK_OFFSET(0x16E54F30)
#define RPG_CLIENT_ALLEYMODULE_REFRESHALLMISSIONDATA_OFFSET UNITYSDK_OFFSET(0x16E4C700)
#define RPG_CLIENT_ALLEYMODULE_REPORTACTIVITYRAIDBEGIN_OFFSET UNITYSDK_OFFSET(0x16E4BAE0)
#define RPG_CLIENT_ALLEYMODULE_REPORTACTIVITYRAIDEND_OFFSET UNITYSDK_OFFSET(0x16E4BCB0)
#define RPG_CLIENT_ALLEYMODULE_RESETALLTALKROWPRIORITY_OFFSET UNITYSDK_OFFSET(0x16E52910)
#define RPG_CLIENT_ALLEYMODULE_SENDGETSAVELOGISTICSMAPCSREQ_OFFSET UNITYSDK_OFFSET(0x16E5E810)
#define RPG_CLIENT_ALLEYMODULE_SETALLEYSHOPLINEPATHCOORDSLIST_OFFSET UNITYSDK_OFFSET(0x16E5C090)
#define RPG_CLIENT_ALLEYMODULE_SETALLEYTRANSPORTHANDLER_OFFSET UNITYSDK_OFFSET(0x16E5F790)
#define RPG_CLIENT_ALLEYMODULE_SETEVENTSEEN_OFFSET UNITYSDK_OFFSET(0x16E50E20)
#define RPG_CLIENT_ALLEYMODULE_SETMAPGRIDCLICKEDSTATE_OFFSET UNITYSDK_OFFSET(0x16E5BCE0)
#define RPG_CLIENT_ALLEYMODULE_SETMAPGRIDPOPUPTIPSTATE_OFFSET UNITYSDK_OFFSET(0x16E5D440)
#define RPG_CLIENT_ALLEYMODULE_SETTALKROWPRIORITY_OFFSET UNITYSDK_OFFSET(0x16E526D0)
#define RPG_CLIENT_ALLEYMODULE_SET_ALLEYCONSTVALUE_OFFSET UNITYSDK_OFFSET(0x16E588E0)
#define RPG_CLIENT_ALLEYMODULE_SET_ALLEYGOODPROFITINCREASEDICT_OFFSET UNITYSDK_OFFSET(0x16E589B0)
#define RPG_CLIENT_ALLEYMODULE_SET_ALLEYSHOPPROFITINCREASEDICT_OFFSET UNITYSDK_OFFSET(0x16E58990)
#define RPG_CLIENT_ALLEYMODULE_SET_AVATARREWARDQUEST_OFFSET UNITYSDK_OFFSET(0x16E51EB0)
#define RPG_CLIENT_ALLEYMODULE_SET_CACHENEWUNLOCKORDER_OFFSET UNITYSDK_OFFSET(0x16E50270)
#define RPG_CLIENT_ALLEYMODULE_SET_CACHERESULTEVENTID_OFFSET UNITYSDK_OFFSET(0x16E50230)
#define RPG_CLIENT_ALLEYMODULE_SET_CACHERESULTMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E50250)
#define RPG_CLIENT_ALLEYMODULE_SET_CURACCEPTEDSIDEEVENTCOUNT_OFFSET UNITYSDK_OFFSET(0x16E58A60)
#define RPG_CLIENT_ALLEYMODULE_SET_CURMAINEVENTSTAGE_OFFSET UNITYSDK_OFFSET(0x16E58A20)
#define RPG_CLIENT_ALLEYMODULE_SET_CURORDERDATA_OFFSET UNITYSDK_OFFSET(0x16E58910)
#define RPG_CLIENT_ALLEYMODULE_SET_CURRENOWNLEVEL_OFFSET UNITYSDK_OFFSET(0x16E589E0)
#define RPG_CLIENT_ALLEYMODULE_SET_CURTRANSPORTSCORE_OFFSET UNITYSDK_OFFSET(0x16E66500)
#define RPG_CLIENT_ALLEYMODULE_SET_FINISHEDNORMALORDERNUM_OFFSET UNITYSDK_OFFSET(0x16E58970)
#define RPG_CLIENT_ALLEYMODULE_SET_FUNDS_OFFSET UNITYSDK_OFFSET(0x16E573E0)
#define RPG_CLIENT_ALLEYMODULE_SET_LOGICRANDOM_OFFSET UNITYSDK_OFFSET(0x16E588C0)
#define RPG_CLIENT_ALLEYMODULE_SET_MAXFINISHEDMAINEVENTSTAGE_OFFSET UNITYSDK_OFFSET(0x16E58A40)
#define RPG_CLIENT_ALLEYMODULE_SET_MAXLEVEL_OFFSET UNITYSDK_OFFSET(0x16E501F0)
#define RPG_CLIENT_ALLEYMODULE_SET_MAXTRANSPORTSCORE_OFFSET UNITYSDK_OFFSET(0x16E66520)
#define RPG_CLIENT_ALLEYMODULE_SET_ORDERPROFITINCREASE_OFFSET UNITYSDK_OFFSET(0x16E58930)
#define RPG_CLIENT_ALLEYMODULE_SET_RENOWNREWARDTAKENINFO_OFFSET UNITYSDK_OFFSET(0x16E58A00)
#define RPG_CLIENT_ALLEYMODULE_SET_TRANSPORTRESULTNEWEVENTID_OFFSET UNITYSDK_OFFSET(0x16E664E0)
#define RPG_CLIENT_ALLEYMODULE_SET_UNFINISHEDNORMALORDERNUM_OFFSET UNITYSDK_OFFSET(0x16E58950)
#define RPG_CLIENT_ALLEYMODULE_SHOWPACKUNSEENSTAGE_OFFSET UNITYSDK_OFFSET(0x16E51870)
#define RPG_CLIENT_ALLEYMODULE_TRIGGERRANDOMTALK_OFFSET UNITYSDK_OFFSET(0x16E52960)
#define RPG_CLIENT_ALLEYMODULE_TRYGENERATEALLEYMAPGRIDDATA_OFFSET UNITYSDK_OFFSET(0x16E58A90)
#define RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYACTIVITYPANELSEEN_OFFSET UNITYSDK_OFFSET(0x16E50840)
#define RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYAVATARREWARDSEEN_OFFSET UNITYSDK_OFFSET(0x16E50900)
#define RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYQUESTREWARDSEEN_OFFSET UNITYSDK_OFFSET(0x16E509C0)
#define RPG_CLIENT_ALLEYMODULE_TRYSENDLOGISTICSGAMECSREQ_OFFSET UNITYSDK_OFFSET(0x16E5DEE0)
#define RPG_CLIENT_ALLEYMODULE_TRYSHOWNEWSHOPANDBUFFTIPDIALOG_OFFSET UNITYSDK_OFFSET(0x16E59F60)
#define RPG_CLIENT_ALLEYMODULE_TRYSTARTALLEYEVENT_OFFSET UNITYSDK_OFFSET(0x16E55010)
#define RPG_CLIENT_ALLEYMODULE_TRYSUBMITSTAMP_OFFSET UNITYSDK_OFFSET(0x16E550C0)
#define RPG_CLIENT_ALLEYMODULE_TRYTAKEEVENTREWARD_OFFSET UNITYSDK_OFFSET(0x16E55280)
#define RPG_CLIENT_ALLEYMODULE_TRYTAKERENOWNREWARD_OFFSET UNITYSDK_OFFSET(0x16E551D0)
#define RPG_CLIENT_ALLEYMODULE__ADDNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0x16E57E90)
#define RPG_CLIENT_ALLEYMODULE__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x16E555B0)
#define RPG_CLIENT_ALLEYMODULE__CACHEFINISHEDEVENT_OFFSET UNITYSDK_OFFSET(0x16E4FB40)
#define RPG_CLIENT_ALLEYMODULE__COMPARESIDEEVENT_OFFSET UNITYSDK_OFFSET(0x16E4FC50)
#define RPG_CLIENT_ALLEYMODULE__COMPARETALKROW_OFFSET UNITYSDK_OFFSET(0x16E53040)
#define RPG_CLIENT_ALLEYMODULE__CTOR_OFFSET UNITYSDK_OFFSET(0x16E66540)
#define RPG_CLIENT_ALLEYMODULE__DISPOSEALLEYTRANSPORT_OFFSET UNITYSDK_OFFSET(0x16E546A0)
#define RPG_CLIENT_ALLEYMODULE__FRESHEVENTCLOSE_OFFSET UNITYSDK_OFFSET(0x16E4F630)
#define RPG_CLIENT_ALLEYMODULE__FRESHEVENTINFO_OFFSET UNITYSDK_OFFSET(0x16E4F240)
#define RPG_CLIENT_ALLEYMODULE__GETALLEYACTIVITYPREMISSIONDATA_OFFSET UNITYSDK_OFFSET(0x16E4EDC0)
#define RPG_CLIENT_ALLEYMODULE__GETALLSHOWINGEVENTS_OFFSET UNITYSDK_OFFSET(0x16E4F080)
#define RPG_CLIENT_ALLEYMODULE__GETBUFFDATAFROMCOORD_OFFSET UNITYSDK_OFFSET(0x16E5F530)
#define RPG_CLIENT_ALLEYMODULE__GETDIRECTIONBYTWOVECTOR2INT_OFFSET UNITYSDK_OFFSET(0x16E5CFB0)
#define RPG_CLIENT_ALLEYMODULE__GETEVENTSTAGEPRIORITY_OFFSET UNITYSDK_OFFSET(0x16E4FEF0)
#define RPG_CLIENT_ALLEYMODULE__GETGOODSPROFITRATIO_OFFSET UNITYSDK_OFFSET(0x16E5F870)
#define RPG_CLIENT_ALLEYMODULE__GETLOGISTICSMAPLIST_OFFSET UNITYSDK_OFFSET(0x16E5DFD0)
#define RPG_CLIENT_ALLEYMODULE__GETNEXPOSBYDIRECTION_OFFSET UNITYSDK_OFFSET(0x16E663E0)
#define RPG_CLIENT_ALLEYMODULE__GETRANDOMVALIDTALKIDWITHWEIGHT_OFFSET UNITYSDK_OFFSET(0x16E524B0)
#define RPG_CLIENT_ALLEYMODULE__GETRENOWNREWARDTAKENINFOARRAY_OFFSET UNITYSDK_OFFSET(0x16E4EC90)
#define RPG_CLIENT_ALLEYMODULE__GETSIDEEVENTMAXACCEPTTIME_OFFSET UNITYSDK_OFFSET(0x16E4FBC0)
#define RPG_CLIENT_ALLEYMODULE__GETTRANSITIONSAVEID_OFFSET UNITYSDK_OFFSET(0x16E5AA50)
#define RPG_CLIENT_ALLEYMODULE__GETUNLOCKALLEYSHOPLINECOMPLATESTATE_OFFSET UNITYSDK_OFFSET(0x16E603B0)
#define RPG_CLIENT_ALLEYMODULE__INITALLEYTRANSPORT_OFFSET UNITYSDK_OFFSET(0x16E53C70)
#define RPG_CLIENT_ALLEYMODULE__INITEVENTINFO_OFFSET UNITYSDK_OFFSET(0x16E4DCC0)
#define RPG_CLIENT_ALLEYMODULE__INITLIMITEDREWARDQUESTINFO_OFFSET UNITYSDK_OFFSET(0x16E502D0)
#define RPG_CLIENT_ALLEYMODULE__INITPERIPHERALDATA_OFFSET UNITYSDK_OFFSET(0x16E4D850)
#define RPG_CLIENT_ALLEYMODULE__INITREDDOTDATA_OFFSET UNITYSDK_OFFSET(0x16E50280)
#define RPG_CLIENT_ALLEYMODULE__INITRENOWNINFO_OFFSET UNITYSDK_OFFSET(0x16E4D8B0)
#define RPG_CLIENT_ALLEYMODULE__INITSHIPLIST_OFFSET UNITYSDK_OFFSET(0x16E53650)
#define RPG_CLIENT_ALLEYMODULE__INITSHOPGOODMAPPING_OFFSET UNITYSDK_OFFSET(0x16E53940)
#define RPG_CLIENT_ALLEYMODULE__INITSTAGEINFO_OFFSET UNITYSDK_OFFSET(0x16E4E970)
#define RPG_CLIENT_ALLEYMODULE__INITTALKDATA_OFFSET UNITYSDK_OFFSET(0x16E52E80)
#define RPG_CLIENT_ALLEYMODULE__ISHIDDENEVENT_OFFSET UNITYSDK_OFFSET(0x16E4F000)
#define RPG_CLIENT_ALLEYMODULE__ISMAINEVENT_OFFSET UNITYSDK_OFFSET(0x16E4D2E0)
#define RPG_CLIENT_ALLEYMODULE__ISNEWUNSEENSIDEEVENT_OFFSET UNITYSDK_OFFSET(0x16E4FF50)
#define RPG_CLIENT_ALLEYMODULE__LOADTALKDATA_OFFSET UNITYSDK_OFFSET(0x16E51F20)
#define RPG_CLIENT_ALLEYMODULE__ONACTIVITYRAIDPLACINGGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16E4C540)
#define RPG_CLIENT_ALLEYMODULE__ONADVENTUREPHASEENTEREDBYTRANSPORT_OFFSET UNITYSDK_OFFSET(0x16E583C0)
#define RPG_CLIENT_ALLEYMODULE__ONADVENTUREPHASEENTERED_OFFSET UNITYSDK_OFFSET(0x16E58370)
#define RPG_CLIENT_ALLEYMODULE__ONALLEYEVENTCHANGENOTIFY_OFFSET UNITYSDK_OFFSET(0x16E57A90)
#define RPG_CLIENT_ALLEYMODULE__ONALLEYTAKEEVENTREWARDSCRSP_OFFSET UNITYSDK_OFFSET(0x16E57E00)
#define RPG_CLIENT_ALLEYMODULE__ONCMDALLEYFUNDSSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16E57830)
#define RPG_CLIENT_ALLEYMODULE__ONCMDALLEYORDERCHANGEDSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16E577C0)
#define RPG_CLIENT_ALLEYMODULE__ONCMDALLEYPLACINGGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16E574C0)
#define RPG_CLIENT_ALLEYMODULE__ONCMDALLEYSHIPMENTEVENTEFFECTSSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16E57A20)
#define RPG_CLIENT_ALLEYMODULE__ONCMDGETSAVELOGISTICSMAPSCRSP_OFFSET UNITYSDK_OFFSET(0x16E63FF0)
#define RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16E63440)
#define RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSINFOSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16E62950)
#define RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSSCOREREWARDSYNCINFOSCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16E62560)
#define RPG_CLIENT_ALLEYMODULE__ONFINISHMAINMISSIONBYTRANSPORT_OFFSET UNITYSDK_OFFSET(0x16E58530)
#define RPG_CLIENT_ALLEYMODULE__ONFINISHMAINMISSION_OFFSET UNITYSDK_OFFSET(0x16E584D0)
#define RPG_CLIENT_ALLEYMODULE__ONFINISHSTAGEMAINMISSION_OFFSET UNITYSDK_OFFSET(0x16E50050)
#define RPG_CLIENT_ALLEYMODULE__ONGETALLEYINFOSCRSP_OFFSET UNITYSDK_OFFSET(0x16E55E30)
#define RPG_CLIENT_ALLEYMODULE__ONPRESTIGELEVELUPSCRSP_OFFSET UNITYSDK_OFFSET(0x16E57CB0)
#define RPG_CLIENT_ALLEYMODULE__ONREDDOTREFRESHMISSIONID_OFFSET UNITYSDK_OFFSET(0x16E587E0)
#define RPG_CLIENT_ALLEYMODULE__ONTAKEPRESTIGEREWARDSCRSP_OFFSET UNITYSDK_OFFSET(0x16E57D40)
#define RPG_CLIENT_ALLEYMODULE__POSTPROCESSSIDEEVENTDATA_OFFSET UNITYSDK_OFFSET(0x16E4F9B0)
#define RPG_CLIENT_ALLEYMODULE__PREPARETASKMAINMISSIONDATA_OFFSET UNITYSDK_OFFSET(0x16E58190)
#define RPG_CLIENT_ALLEYMODULE__SENDINITREQUEST_OFFSET UNITYSDK_OFFSET(0x16E58070)
#define RPG_CLIENT_ALLEYMODULE__SETVALIDTALKIDSCACHE_OFFSET UNITYSDK_OFFSET(0x16E52240)
#define RPG_CLIENT_ALLEYMODULE__SYNCLOGISTICSMAPLIST_OFFSET UNITYSDK_OFFSET(0x16E55FB0)
#define RPG_CLIENT_ALLEYMODULE__SYNCORDERINFO_OFFSET UNITYSDK_OFFSET(0x16E56A10)
#define RPG_CLIENT_ALLEYMODULE__SYNCSHIPMENTEVENTEFFECTS_OFFSET UNITYSDK_OFFSET(0x16E56DF0)
#define RPG_CLIENT_ALLEYMODULE__TRYGENERATEALLEYMAPGRIDDATA_OFFSET UNITYSDK_OFFSET(0x16E58AE0)
#define RPG_CLIENT_ALLEYMODULE__TRYINITALLEYTRANSPORTDATADICT_OFFSET UNITYSDK_OFFSET(0x16E64080)
#define RPG_CLIENT_ALLEYMODULE__TRYINITSERVERDIRECTIONLISTDICT_OFFSET UNITYSDK_OFFSET(0x16E63EE0)
#define RPG_CLIENT_ALLEYMODULE__TRYINITTEMPALLEYMAPLINEDATALISTDICT_OFFSET UNITYSDK_OFFSET(0x16E5C9F0)
#define RPG_CLIENT_ALLEYMODULE__UNINITALLEYTRANSPORT_OFFSET UNITYSDK_OFFSET(0x16E66480)
#define RPG_CLIENT_ALLEYMODULE__UNINITPERIPHERALDATA_OFFSET UNITYSDK_OFFSET(0x16E4EB50)
#define RPG_CLIENT_ALLEYMODULE__UNINITREDDOTDATA_OFFSET UNITYSDK_OFFSET(0x16E50590)
#define RPG_CLIENT_ALLEYMODULE__UNINITTALKDATA_OFFSET UNITYSDK_OFFSET(0x16E52F90)
#define RPG_CLIENT_ALLEYMODULE__UPDATESHOPGOODSANDLINEDATABYSERVER_OFFSET UNITYSDK_OFFSET(0x16E643C0)
#define RPG_CLIENT_ALLEYMODULE__UPDATESHOPGOODSANDLINEDATA_OFFSET UNITYSDK_OFFSET(0x16E62460)
#define RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY_DISPOSE_OFFSET UNITYSDK_OFFSET(0x16E66AB0)
#define RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY_INIT_OFFSET UNITYSDK_OFFSET(0x16E66A30)
#define RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY__ADDNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0x16E66B20)
#define RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x16E66AC0)
#define RPG_CLIENT_ALLEYMODULE___ONADVENTUREPHASEENTEREDBYTRANSPORT_B__315_0_OFFSET UNITYSDK_OFFSET(0x16E66840)

namespace RPG::Client
{
	inline static constexpr unsigned int AlleyModule_TypeDefinitionIndex = 58225;

	class AlleyModule : public ::RPG::Client::BaseModule
	{
	public:
		// static const ::System::String* _LogActivityRaidGameKey; // 0x0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _MapID2GradeIDDict; // 0x10
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*>* _AllAlleyShopItemDataListDict; // 0x18
		::System::Collections::Generic::List_1<::RPG::Client::AlleyGoodData*>* _CachedAlleyGoodDataList; // 0x20
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::AlleyPackGoodItemConfig*>* _AlleyPackGoodItemConfigDict; // 0x28
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleyOrderData*>* _AcitivityRaidAlleyOrderDataDict; // 0x30
		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* _MainEvents_k__BackingField; // 0x38
		::System::Collections::Generic::List_1<::System::UInt32>* _LevelTargets_k__BackingField; // 0x40
		::System::Collections::Generic::List_1<::System::UInt32>* _LevelRewardIDs_k__BackingField; // 0x48
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::HashSet_1<::System::UInt32>*>* _AlleyShopGoodMappingDict; // 0x50
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*>* _UnlcokAlleyShopItemDataListDict; // 0x58
		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyDeskTalkRow*>* _SortedTalkRows; // 0x60
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::AlleySpecialOrderData*>* _AlleySpecialOrderDataDict; // 0x68
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*>* _UnlcokAlleyDockItemDataListDict; // 0x70
		::Class_1_827373C1CEDFE355* _LogicRandom_k__BackingField; // 0x78
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::AlleyMapGridConfig*>* _AlleyMapGridConfigDict; // 0x80
		::RPG::Client::AlleyTransportHandler* _AlleyTransportHandler; // 0x88
		::RPG::Client::AlleyOrderData* _CurOrderData_k__BackingField; // 0x90
		::System::Collections::Generic::List_1<::System::UInt32>* _UnlockAlleyMapLayerList; // 0x98
		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* _MainEvents; // 0xA0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Boolean>* _UnlockAlleyShopLineComplateStateDict; // 0xA8
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*>* _UnlcokAlleyTutorialItemDataListDict; // 0xB0
		::System::Collections::Generic::HashSet_1<::System::UInt32>* _UnlockAlleyShopIDSet; // 0xB8
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::System::UInt32>*>* _ServerDirectionListDict; // 0xC0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::GameCore::AlleyPackGoodItemConfig*>* _AlleyPackShipConfigDict; // 0xC8
		::System::Collections::Generic::List_1<::System::UInt32>* _ValidTalkWeightsCache; // 0xD0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _AlleyShopProfitIncreaseDict_k__BackingField; // 0xD8
		::System::Collections::Generic::List_1<::System::UInt32>* _CachedLastAlleyOrderDataIDList; // 0xE0
		::System::Collections::Generic::List_1<::System::UInt32>* _CachedIDLists; // 0xE8
		::Il2CppArray<::System::Boolean>* _RenownRewardTakenInfo_k__BackingField; // 0xF0
		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>* _GoodsRewardRows_k__BackingField; // 0xF8
		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* _SideEvents_k__BackingField; // 0x100
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::System::Collections::Generic::List_1<::System::UInt32>*>*>* _AllEventMissionIDs; // 0x108
		::System::Collections::Generic::List_1<::System::UInt32>* _AllMissionIDs; // 0x110
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleySpecialOrderData*>* _AcitivityRaidAlleySpecialOrderDataDict; // 0x118
		::System::Collections::Generic::List_1<::System::UInt32>* _ValidTalkIDsCache; // 0x120
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _AlleyGoodProfitIncreaseDict_k__BackingField; // 0x128
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _UnlockAlleyFloorMapDict; // 0x130
		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>* _TransportRewardRows_k__BackingField; // 0x138
		::RPG::Client::AlleyPlacingShipResult* AlleyPlacingShipResult; // 0x140
		::System::Collections::Generic::List_1<::System::UInt32>* _StageHintMissionIDs; // 0x148
		::RPG::Client::AlleyConstValue* _AlleyConstValue_k__BackingField; // 0x150
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::Class_1_9940F9E16DD482B4*>*>* _TempAlleyMapLineDataListDict; // 0x158
		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* _SideEvents; // 0x160
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ClientAlleyLogisticsScore*>* _AlleyMapLogisticsScoreDict; // 0x168
		::System::Collections::Generic::List_1<::RPG::Client::AlleyShipData*>* _AlleyShipList; // 0x170
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*>* _UnlcokAlleyBuffItemDataListDict; // 0x178
		::System::UInt32 _SpecialEventMissionID; // 0x180
		::System::UInt32 _CurRenownLevel_k__BackingField; // 0x184
		::System::Int32 _LogStartTimeStamp; // 0x188
		::System::UInt32 _CurTransportScore; // 0x18C
		::System::Int32 _MaxFinishedMainEventStage_k__BackingField; // 0x190
		::System::UInt32 _CacheResultEventID_k__BackingField; // 0x194
		::System::UInt32 _UnFinishedNormalOrderNum_k__BackingField; // 0x198
		::System::Boolean _IsDataLoaded; // 0x19C
		::System::UInt32 _HiddenTransportLayer; // 0x1A0
		::System::UInt32 _FinishedNormalOrderNum_k__BackingField; // 0x1A4
		::System::UInt32 _CurAcceptedSideEventCount_k__BackingField; // 0x1A8
		::System::Single _FocusCameraTime; // 0x1AC
		::System::UInt32 _MaxLevel_k__BackingField; // 0x1B0
		::System::UInt32 _LogGroupID; // 0x1B4
		::System::UInt32 _MapUnLockMainMisionID; // 0x1B8
		::System::UInt32 _MaxTransportScore; // 0x1BC
		::System::UInt32 _AvatarRewardQuest_k__BackingField; // 0x1C0
		::System::Int32 _CurMainEventStage_k__BackingField; // 0x1C4
		::System::UInt32 _CurFunds; // 0x1C8
		::System::UInt32 _CacheResultMissionID_k__BackingField; // 0x1CC
		::System::UInt32 _OrderProfitIncrease_k__BackingField; // 0x1D0
		::System::UInt32 _TransportResultNewEventID; // 0x1D4
		::System::UInt32 _TalkWeightSumCache; // 0x1D8
		::System::UInt32 _CacheNewUnlockOrder_k__BackingField; // 0x1DC

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__CTOR_OFFSET))(this);
		}

		::RPG::Client::ActivityRaidAlleyOrderData* GetActivityRaidAlleyOrderData(::System::UInt32 a1)
		{
			return ((::RPG::Client::ActivityRaidAlleyOrderData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETACTIVITYRAIDALLEYORDERDATA_OFFSET))(this, a1);
		}

		::RPG::Client::ActivityRaidAlleySpecialOrderData* GetActivityRaidAlleySpecialOrderData(::System::UInt32 a1)
		{
			return ((::RPG::Client::ActivityRaidAlleySpecialOrderData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETACTIVITYRAIDALLEYSPECIALORDERDATA_OFFSET))(this, a1);
		}

		::System::Void ReportActivityRaidBegin(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_REPORTACTIVITYRAIDBEGIN_OFFSET))(this, a1);
		}

		::System::Void ReportActivityRaidEnd(::RPG::Client::AlleyModule_ActivityRaidAlleyLogExtraInfo a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyModule_ActivityRaidAlleyLogExtraInfo))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_REPORTACTIVITYRAIDEND_OFFSET))(this, a1);
		}

		::System::Void _OnActivityRaidPlacingGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONACTIVITYRAIDPLACINGGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleyOrderData*>* get_AcitivityRaidAlleyOrderDataDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleyOrderData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ACITIVITYRAIDALLEYORDERDATADICT_OFFSET))(this);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleySpecialOrderData*>* get_AcitivityRaidAlleySpecialOrderDataDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ActivityRaidAlleySpecialOrderData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ACITIVITYRAIDALLEYSPECIALORDERDATADICT_OFFSET))(this);
		}

		::RPG::Client::Promises::Promise* RefreshAllMissionData()
		{
			return ((::RPG::Client::Promises::Promise*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_REFRESHALLMISSIONDATA_OFFSET))(this);
		}

		::RPG::Client::MainMissionData* GetEventMissionData(::System::UInt32 a1)
		{
			return ((::RPG::Client::MainMissionData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETEVENTMISSIONDATA_OFFSET))(this, a1);
		}

		::System::UInt32 GetEventActiveMissionID(::RPG::Client::AlleyEventInfo a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::RPG::Client::AlleyEventInfo))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETEVENTACTIVEMISSIONID_OFFSET))(this, a1);
		}

		::System::UInt32 GetCurUrgentMissionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETCURURGENTMISSIONID_OFFSET))(this);
		}

		::System::UInt32 GetCurTrackMissionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETCURTRACKMISSIONID_OFFSET))(this);
		}

		::System::UInt32 GetCurStageTargetFunds()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETCURSTAGETARGETFUNDS_OFFSET))(this);
		}

		::System::Boolean IsCurStageTargetFinished()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_ISCURSTAGETARGETFINISHED_OFFSET))(this);
		}

		::System::Void PrintEventInfo(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_PRINTEVENTINFO_OFFSET))(this, a1);
		}

		::System::Void PrintAllActiveAndClosedEventIDs()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_PRINTALLACTIVEANDCLOSEDEVENTIDS_OFFSET))(this);
		}

		::System::Void _InitPeripheralData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITPERIPHERALDATA_OFFSET))(this);
		}

		::System::Void _UnInitPeripheralData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UNINITPERIPHERALDATA_OFFSET))(this);
		}

		::System::Void _GetRenownRewardTakenInfoArray(::System::Collections::Generic::List_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETRENOWNREWARDTAKENINFOARRAY_OFFSET))(this, a1);
		}

		::System::Void _GetAlleyActivityPreMissionData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETALLEYACTIVITYPREMISSIONDATA_OFFSET))(this);
		}

		::System::Void _InitRenownInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITRENOWNINFO_OFFSET))(this);
		}

		::System::Void _InitEventInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITEVENTINFO_OFFSET))(this);
		}

		::System::Void _InitStageInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITSTAGEINFO_OFFSET))(this);
		}

		::System::Boolean _IsMainEvent(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ISMAINEVENT_OFFSET))(this, a1);
		}

		::System::Boolean _IsHiddenEvent(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ISHIDDENEVENT_OFFSET))(this, a1);
		}

		::System::Void _GetAllShowingEvents(::System::Collections::Generic::List_1<::Class_1_668FE281FA72D3E8_2*>* a1, ::System::Collections::Generic::List_1<::System::UInt32>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_1_668FE281FA72D3E8_2*>*, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETALLSHOWINGEVENTS_OFFSET))(this, a1, a2);
		}

		::System::Void _FreshEventInfo(::Class_1_668FE281FA72D3E8_2* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_668FE281FA72D3E8_2*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__FRESHEVENTINFO_OFFSET))(this, a1, a2);
		}

		::System::Void _FreshEventClose(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__FRESHEVENTCLOSE_OFFSET))(this, a1, a2);
		}

		::System::UInt32 _GetSideEventMaxAcceptTime(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETSIDEEVENTMAXACCEPTTIME_OFFSET))(this, a1);
		}

		::System::Void _PostProcessSideEventData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__POSTPROCESSSIDEEVENTDATA_OFFSET))(this);
		}

		::System::Int32 _CompareSideEvent(::RPG::Client::AlleyEventInfo a1, ::RPG::Client::AlleyEventInfo a2)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::Client::AlleyEventInfo, ::RPG::Client::AlleyEventInfo))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__COMPARESIDEEVENT_OFFSET))(this, a1, a2);
		}

		::System::UInt32 _GetEventStagePriority(::Enum_3_DB663931210BBC27_14 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::Enum_3_DB663931210BBC27_14))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETEVENTSTAGEPRIORITY_OFFSET))(this, a1);
		}

		::System::Void _CacheFinishedEvent(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__CACHEFINISHEDEVENT_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFinishStageMainMission(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONFINISHSTAGEMAINMISSION_OFFSET))(this, a1);
		}

		::System::UInt32 get_MaxLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_MAXLEVEL_OFFSET))(this);
		}

		::System::Void set_MaxLevel(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_MAXLEVEL_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_LevelTargets()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_LEVELTARGETS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_LevelRewardIDs()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_LEVELREWARDIDS_OFFSET))(this);
		}

		::System::UInt32 get_CacheResultEventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CACHERESULTEVENTID_OFFSET))(this);
		}

		::System::Void set_CacheResultEventID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CACHERESULTEVENTID_OFFSET))(this, a1);
		}

		::System::UInt32 get_CacheResultMissionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CACHERESULTMISSIONID_OFFSET))(this);
		}

		::System::Void set_CacheResultMissionID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CACHERESULTMISSIONID_OFFSET))(this, a1);
		}

		::System::UInt32 get_CacheNewUnlockOrder()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CACHENEWUNLOCKORDER_OFFSET))(this);
		}

		::System::Void set_CacheNewUnlockOrder(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CACHENEWUNLOCKORDER_OFFSET))(this, a1);
		}

		::System::Void _InitRedDotData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITREDDOTDATA_OFFSET))(this);
		}

		::System::Void _UnInitRedDotData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UNINITREDDOTDATA_OFFSET))(this);
		}

		::System::Void _InitLimitedRewardQuestInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITLIMITEDREWARDQUESTINFO_OFFSET))(this);
		}

		::System::Boolean HasReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_HASREWARD_OFFSET))(this);
		}

		::System::Void TryMarkAlleyActivityPanelSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYACTIVITYPANELSEEN_OFFSET))(this);
		}

		::System::Void TryMarkAlleyAvatarRewardSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYAVATARREWARDSEEN_OFFSET))(this);
		}

		::System::Void TryMarkAlleyQuestRewardSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYMARKALLEYQUESTREWARDSEEN_OFFSET))(this);
		}

		::System::Boolean CanReceiveAvatarReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANRECEIVEAVATARREWARD_OFFSET))(this);
		}

		::System::Boolean CanReceiveTabQuestReward(::System::Int32 a1, ::System::Int32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANRECEIVETABQUESTREWARD_OFFSET))(this, a1, a2);
		}

		::System::Boolean CanReceiveQuestReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANRECEIVEQUESTREWARD_OFFSET))(this);
		}

		::System::Boolean CanPayStamp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANPAYSTAMP_OFFSET))(this);
		}

		::System::Boolean CanReceiveRenownReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANRECEIVERENOWNREWARD_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetUnseenEventIDs()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETUNSEENEVENTIDS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetFinishedEventIDs()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETFINISHEDEVENTIDS_OFFSET))(this);
		}

		::System::Void SetEventSeen(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETEVENTSEEN_OFFSET))(this, a1);
		}

		::System::Boolean CheckHasUnseenStageInfoPage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASUNSEENSTAGEINFOPAGE_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetUnseenSpecialOrderID()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETUNSEENSPECIALORDERID_OFFSET))(this);
		}

		::System::Void RecordAllSpecialOrderIDs()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RECORDALLSPECIALORDERIDS_OFFSET))(this);
		}

		::System::Void RecordSpecialOrderID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RECORDSPECIALORDERID_OFFSET))(this, a1);
		}

		::System::Boolean CanShowPackNewOrderEvent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CANSHOWPACKNEWORDEREVENT_OFFSET))(this);
		}

		::System::UInt32 GetPackUnSeenOrderEventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETPACKUNSEENORDEREVENTID_OFFSET))(this);
		}

		::System::Void RecordPackUnSeenOrderEventID()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RECORDPACKUNSEENORDEREVENTID_OFFSET))(this);
		}

		::System::Boolean ShowPackUnSeenStage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SHOWPACKUNSEENSTAGE_OFFSET))(this);
		}

		::System::Void RecordPackSeenStage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RECORDPACKSEENSTAGE_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetNewGoodsIDs(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETNEWGOODSIDS_OFFSET))(this, a1);
		}

		::System::Boolean _IsNewUnseenSideEvent(::RPG::Client::AlleyEventInfo a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::AlleyEventInfo))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ISNEWUNSEENSIDEEVENT_OFFSET))(this, a1);
		}

		::System::Boolean get_AlleyActivityPanelSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYACTIVITYPANELSEEN_OFFSET))(this);
		}

		::System::Boolean get_AlleyAvatarRewardSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYAVATARREWARDSEEN_OFFSET))(this);
		}

		::System::Boolean get_AlleyQuestRewardSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYQUESTREWARDSEEN_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>* get_TransportRewardRows()
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_TRANSPORTREWARDROWS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>* get_GoodsRewardRows()
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::AlleyActivityQuestRow*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_GOODSREWARDROWS_OFFSET))(this);
		}

		::System::UInt32 get_AvatarRewardQuest()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_AVATARREWARDQUEST_OFFSET))(this);
		}

		::System::Void set_AvatarRewardQuest(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_AVATARREWARDQUEST_OFFSET))(this, a1);
		}

		::System::UInt32 RandomGetTalkID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RANDOMGETTALKID_OFFSET))(this);
		}

		::System::String* RandomGetTalkSentenceID(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RANDOMGETTALKSENTENCEID_OFFSET))(this, a1);
		}

		::System::Void SetTalkRowPriority(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETTALKROWPRIORITY_OFFSET))(this, a1, a2);
		}

		::System::Void ResetAllTalkRowPriority()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_RESETALLTALKROWPRIORITY_OFFSET))(this);
		}

		::System::Void TriggerRandomTalk()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRIGGERRANDOMTALK_OFFSET))(this);
		}

		::System::Void _InitTalkData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITTALKDATA_OFFSET))(this);
		}

		::System::Void _UnInitTalkData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UNINITTALKDATA_OFFSET))(this);
		}

		::System::Void _LoadTalkData(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__LOADTALKDATA_OFFSET))(this, a1);
		}

		::System::Int32 _CompareTalkRow(::RPG::GameCore::AlleyDeskTalkRow* a1, ::RPG::GameCore::AlleyDeskTalkRow* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::GameCore::AlleyDeskTalkRow*, ::RPG::GameCore::AlleyDeskTalkRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__COMPARETALKROW_OFFSET))(this, a1, a2);
		}

		::System::Void _SetValidTalkIDsCache()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__SETVALIDTALKIDSCACHE_OFFSET))(this);
		}

		::System::UInt32 _GetRandomValidTalkIDWithWeight()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETRANDOMVALIDTALKIDWITHWEIGHT_OFFSET))(this);
		}

		::System::Void Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_INIT_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_DISPOSE_OFFSET))(this);
		}

		::RPG::Client::AlleySpecialOrderData* GetAlleySpecialOrderData(::System::UInt32 a1)
		{
			return ((::RPG::Client::AlleySpecialOrderData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYSPECIALORDERDATA_OFFSET))(this, a1);
		}

		::RPG::GameCore::AlleyPackGoodItemConfig* GetAlleyPackGoodItemConfig(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::AlleyPackGoodItemConfig*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYPACKGOODITEMCONFIG_OFFSET))(this, a1);
		}

		::RPG::GameCore::AlleyPackGoodItemConfig* GetAlleyPackShipConfig(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::AlleyPackGoodItemConfig*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYPACKSHIPCONFIG_OFFSET))(this, a1);
		}

		::RPG::GameCore::AlleyPackGoodItemConfig* LoadAlleyPackGoodItemConfig(::System::String* a1)
		{
			return ((::RPG::GameCore::AlleyPackGoodItemConfig*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_LOADALLEYPACKGOODITEMCONFIG_OFFSET))(this, a1);
		}

		::System::UInt32 GetGoodBelongShopID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETGOODBELONGSHOPID_OFFSET))(this, a1);
		}

		::System::Void RefreshAlleyInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_REFRESHALLEYINFO_OFFSET))(this);
		}

		::System::Void TryStartAlleyEvent(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYSTARTALLEYEVENT_OFFSET))(this, a1);
		}

		::System::Void TrySubmitStamp()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYSUBMITSTAMP_OFFSET))(this);
		}

		::System::Void TryTakeRenownReward(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYTAKERENOWNREWARD_OFFSET))(this, a1);
		}

		::System::Void TryTakeEventReward(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYTAKEEVENTREWARD_OFFSET))(this, a1);
		}

		::System::Void CacheLastOrderID()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CACHELASTORDERID_OFFSET))(this);
		}

		::System::Void ClearLastOrderID()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CLEARLASTORDERID_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetLastOrderID()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETLASTORDERID_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyGoodData*>* GetNewAlleyGoodDataList()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyGoodData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETNEWALLEYGOODDATALIST_OFFSET))(this);
		}

		::System::Void ClearNewAlleyGoodDataList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CLEARNEWALLEYGOODDATALIST_OFFSET))(this);
		}

		::System::Void _AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void _OnGetAlleyInfoScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONGETALLEYINFOSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdAlleyPlacingGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDALLEYPLACINGGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdAlleyOrderChangedScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDALLEYORDERCHANGEDSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdAlleyFundsScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDALLEYFUNDSSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdAlleyShipmentEventEffectsScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDALLEYSHIPMENTEVENTEFFECTSSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnAlleyEventChangeNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONALLEYEVENTCHANGENOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnPrestigeLevelUpScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONPRESTIGELEVELUPSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnTakePrestigeRewardScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONTAKEPRESTIGEREWARDSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnAlleyTakeEventRewardScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONALLEYTAKEEVENTREWARDSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _AddNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ADDNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _SendInitRequest()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__SENDINITREQUEST_OFFSET))(this);
		}

		::System::Void _PrepareTaskMainMissionData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__PREPARETASKMAINMISSIONDATA_OFFSET))(this);
		}

		::System::Void _InitShipList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITSHIPLIST_OFFSET))(this);
		}

		::System::Void _InitShopGoodMapping()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITSHOPGOODMAPPING_OFFSET))(this);
		}

		::System::Void _SyncShipmentEventEffects(::Class_1_2CC11CDCB897D481* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2CC11CDCB897D481*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__SYNCSHIPMENTEVENTEFFECTS_OFFSET))(this, a1);
		}

		::System::Void _SyncOrderInfo(::Class_1_097D93F83453E9A1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_097D93F83453E9A1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__SYNCORDERINFO_OFFSET))(this, a1);
		}

		::System::Void _OnAdventurePhaseEntered(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONADVENTUREPHASEENTERED_OFFSET))(this, a1);
		}

		::System::Void _OnFinishMainMission(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONFINISHMAINMISSION_OFFSET))(this, a1);
		}

		::System::Void _OnReddotRefreshMissionID(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONREDDOTREFRESHMISSIONID_OFFSET))(this, a1);
		}

		::Class_1_827373C1CEDFE355* get_LogicRandom()
		{
			return ((::Class_1_827373C1CEDFE355*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_LOGICRANDOM_OFFSET))(this);
		}

		::System::Void set_LogicRandom(::Class_1_827373C1CEDFE355* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_827373C1CEDFE355*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_LOGICRANDOM_OFFSET))(this, a1);
		}

		::RPG::Client::AlleyConstValue* get_AlleyConstValue()
		{
			return ((::RPG::Client::AlleyConstValue*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYCONSTVALUE_OFFSET))(this);
		}

		::System::Void set_AlleyConstValue(::RPG::Client::AlleyConstValue* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyConstValue*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_ALLEYCONSTVALUE_OFFSET))(this, a1);
		}

		::System::UInt32 get_AlleyCurrencyConfigID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYCURRENCYCONFIGID_OFFSET))(this);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::AlleySpecialOrderData*>* get_AlleySpecialOrderDataDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::AlleySpecialOrderData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYSPECIALORDERDATADICT_OFFSET))(this);
		}

		::RPG::Client::AlleyOrderData* get_CurOrderData()
		{
			return ((::RPG::Client::AlleyOrderData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CURORDERDATA_OFFSET))(this);
		}

		::System::Void set_CurOrderData(::RPG::Client::AlleyOrderData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyOrderData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CURORDERDATA_OFFSET))(this, a1);
		}

		::System::UInt32 get_OrderProfitIncrease()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ORDERPROFITINCREASE_OFFSET))(this);
		}

		::System::Void set_OrderProfitIncrease(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_ORDERPROFITINCREASE_OFFSET))(this, a1);
		}

		::System::UInt32 get_UnFinishedNormalOrderNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_UNFINISHEDNORMALORDERNUM_OFFSET))(this);
		}

		::System::Void set_UnFinishedNormalOrderNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_UNFINISHEDNORMALORDERNUM_OFFSET))(this, a1);
		}

		::System::UInt32 get_FinishedNormalOrderNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_FINISHEDNORMALORDERNUM_OFFSET))(this);
		}

		::System::Void set_FinishedNormalOrderNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_FINISHEDNORMALORDERNUM_OFFSET))(this, a1);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* get_AlleyShopProfitIncreaseDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYSHOPPROFITINCREASEDICT_OFFSET))(this);
		}

		::System::Void set_AlleyShopProfitIncreaseDict(::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_ALLEYSHOPPROFITINCREASEDICT_OFFSET))(this, a1);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* get_AlleyGoodProfitIncreaseDict()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_ALLEYGOODPROFITINCREASEDICT_OFFSET))(this);
		}

		::System::Void set_AlleyGoodProfitIncreaseDict(::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_ALLEYGOODPROFITINCREASEDICT_OFFSET))(this, a1);
		}

		::System::UInt32 get_Funds()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_FUNDS_OFFSET))(this);
		}

		::System::Void set_Funds(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_FUNDS_OFFSET))(this, a1);
		}

		::System::UInt32 get_CurRenownLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CURRENOWNLEVEL_OFFSET))(this);
		}

		::System::Void set_CurRenownLevel(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CURRENOWNLEVEL_OFFSET))(this, a1);
		}

		::Il2CppArray<::System::Boolean>* get_RenownRewardTakenInfo()
		{
			return ((::Il2CppArray<::System::Boolean>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_RENOWNREWARDTAKENINFO_OFFSET))(this);
		}

		::System::Void set_RenownRewardTakenInfo(::Il2CppArray<::System::Boolean>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Boolean>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_RENOWNREWARDTAKENINFO_OFFSET))(this, a1);
		}

		::System::Int32 get_CurMainEventStage()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CURMAINEVENTSTAGE_OFFSET))(this);
		}

		::System::Void set_CurMainEventStage(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CURMAINEVENTSTAGE_OFFSET))(this, a1);
		}

		::System::Int32 get_MaxFinishedMainEventStage()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_MAXFINISHEDMAINEVENTSTAGE_OFFSET))(this);
		}

		::System::Void set_MaxFinishedMainEventStage(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_MAXFINISHEDMAINEVENTSTAGE_OFFSET))(this, a1);
		}

		::System::UInt32 get_CurAcceptedSideEventCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CURACCEPTEDSIDEEVENTCOUNT_OFFSET))(this);
		}

		::System::Void set_CurAcceptedSideEventCount(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CURACCEPTEDSIDEEVENTCOUNT_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* get_MainEvents()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_MAINEVENTS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>* get_SideEvents()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyEventInfo>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_SIDEEVENTS_OFFSET))(this);
		}

		::System::Void TryGenerateAlleyMapGridData(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYGENERATEALLEYMAPGRIDDATA_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetUnlockAlleyMapLayerList()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETUNLOCKALLEYMAPLAYERLIST_OFFSET))(this);
		}

		::System::Boolean IsAlleyMapUnlockByLayer(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_ISALLEYMAPUNLOCKBYLAYER_OFFSET))(this, a1);
		}

		::System::UInt32 GetAlleyMapIDByLayer(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYMAPIDBYLAYER_OFFSET))(this, a1);
		}

		::System::UInt32 GetAlleyLayerByMapID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYLAYERBYMAPID_OFFSET))(this, a1);
		}

		::System::UInt32 GetGradeIDByMapID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETGRADEIDBYMAPID_OFFSET))(this, a1);
		}

		::System::Boolean IsAlleyShopUnlock(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_ISALLEYSHOPUNLOCK_OFFSET))(this, a1);
		}

		::System::Boolean TryShowNewShopAndBuffTipDialog(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYSHOWNEWSHOPANDBUFFTIPDIALOG_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckHasNewShopTip()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWSHOPTIP_OFFSET))(this);
		}

		::System::Boolean CheckHasNewShopTipByMapID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWSHOPTIPBYMAPID_OFFSET))(this, a1);
		}

		::System::UInt32 GetNewTipShopIDByMapID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETNEWTIPSHOPIDBYMAPID_OFFSET))(this, a1);
		}

		::System::Boolean CheckHasNewBuffTip()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWBUFFTIP_OFFSET))(this);
		}

		::System::Boolean CheckHasNewBuffTipByMapID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWBUFFTIPBYMAPID_OFFSET))(this, a1);
		}

		::System::Boolean CheckHasNewUnClickedBuffTip()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWUNCLICKEDBUFFTIP_OFFSET))(this);
		}

		::System::Boolean CheckHasNewUnClickedBuffTipByMapID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWUNCLICKEDBUFFTIPBYMAPID_OFFSET))(this, a1);
		}

		::System::Boolean CheckMapGridIsClicked(::RPG::Client::AlleyGridItemData* a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::AlleyGridItemData*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKMAPGRIDISCLICKED_OFFSET))(this, a1, a2);
		}

		::System::Void SetMapGridClickedState(::RPG::Client::AlleyGridItemData* a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyGridItemData*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETMAPGRIDCLICKEDSTATE_OFFSET))(this, a1, a2);
		}

		::System::String* GetAlleyMapGridPrefabPath(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYMAPGRIDPREFABPATH_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>* GetAllShopListByMapID(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLSHOPLISTBYMAPID_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>* GetAlleyGridItemDataListByType(::System::UInt32 a1, ::RPG::GameCore::GridTypeEnum a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*(*)(::PVOID, ::System::UInt32, ::RPG::GameCore::GridTypeEnum))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYGRIDITEMDATALISTBYTYPE_OFFSET))(this, a1, a2);
		}

		::System::Void SetAlleyShopLinePathCoordsList(::System::UInt32 a1, ::System::UInt32 a2, ::System::Collections::Generic::IReadOnlyList_1<::UnityEngine::Vector2Int>* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Collections::Generic::IReadOnlyList_1<::UnityEngine::Vector2Int>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETALLEYSHOPLINEPATHCOORDSLIST_OFFSET))(this, a1, a2, a3);
		}

		::Class_1_9940F9E16DD482B4* GetAlleyMapLineData(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::Class_1_9940F9E16DD482B4*(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYMAPLINEDATA_OFFSET))(this, a1, a2);
		}

		::System::Void ClearAlleyTransportMapData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CLEARALLEYTRANSPORTMAPDATA_OFFSET))(this);
		}

		::System::Boolean CheckAlleyGridCanPopUpTip(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKALLEYGRIDCANPOPUPTIP_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckMapGridNeedPopUpTip(::RPG::Client::AlleyGridItemData* a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::AlleyGridItemData*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKMAPGRIDNEEDPOPUPTIP_OFFSET))(this, a1, a2);
		}

		::System::Void SetMapGridPopUpTipState(::RPG::Client::AlleyGridItemData* a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyGridItemData*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETMAPGRIDPOPUPTIPSTATE_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckHasNewTransportInfo()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASNEWTRANSPORTINFO_OFFSET))(this);
		}

		::System::Boolean CheckIsLineDataChangedByMapLayer(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKISLINEDATACHANGEDBYMAPLAYER_OFFSET))(this, a1);
		}

		::System::Void TrySendLogisticsGameCsReq(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_TRYSENDLOGISTICSGAMECSREQ_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SendGetSaveLogisticsMapCsReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SENDGETSAVELOGISTICSMAPCSREQ_OFFSET))(this);
		}

		::System::Int32 GetAllEnergyCount(::System::UInt32 a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLENERGYCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 GetEnergyCountByLineData(::System::UInt32 a1, ::System::Collections::Generic::List_1<::UnityEngine::Vector2Int>* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::System::UInt32, ::System::Collections::Generic::List_1<::UnityEngine::Vector2Int>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETENERGYCOUNTBYLINEDATA_OFFSET))(this, a1, a2);
		}

		::System::Int32 GetEnergyCount(::System::UInt32 a1, ::System::UInt32 a2, ::System::Collections::Generic::List_1<::UnityEngine::Vector2Int>* a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Collections::Generic::List_1<::UnityEngine::Vector2Int>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETENERGYCOUNT_OFFSET))(this, a1, a2, a3);
		}

		::System::UInt32 GetTransportBirdNum(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETTRANSPORTBIRDNUM_OFFSET))(this, a1, a2);
		}

		::System::Void SetAlleyTransportHandler(::RPG::Client::AlleyTransportHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::AlleyTransportHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SETALLEYTRANSPORTHANDLER_OFFSET))(this, a1);
		}

		::System::UInt32 GetGoodsProfitByGoodsID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETGOODSPROFITBYGOODSID_OFFSET))(this, a1);
		}

		::System::Boolean IsAllShopLineCompleted()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_ISALLSHOPLINECOMPLETED_OFFSET))(this);
		}

		::System::Boolean CheckLineCompletedStateByMapID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKLINECOMPLETEDSTATEBYMAPID_OFFSET))(this, a1);
		}

		::System::Boolean CheckLineCompletedState(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKLINECOMPLETEDSTATE_OFFSET))(this, a1, a2);
		}

		::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>* GetLineBuffGridItemDataList(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::AlleyGridItemData*>*(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETLINEBUFFGRIDITEMDATALIST_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckHasLinePathCoordsList(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKHASLINEPATHCOORDSLIST_OFFSET))(this, a1, a2);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::AlleyMapRewardRow*>* GetShowAlleyMapRewardRowListByLayer(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::AlleyMapRewardRow*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETSHOWALLEYMAPREWARDROWLISTBYLAYER_OFFSET))(this, a1);
		}

		::System::Boolean CheckIsNeedLocalSave()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKISNEEDLOCALSAVE_OFFSET))(this);
		}

		::UnityEngine::Vector2Int GetDrawLineEndPointPosition(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::UnityEngine::Vector2Int(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETDRAWLINEENDPOINTPOSITION_OFFSET))(this, a1, a2);
		}

		::UnityEngine::Vector2Int GetDrawLineEndPointPositionExcludeZero(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::UnityEngine::Vector2Int(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETDRAWLINEENDPOINTPOSITIONEXCLUDEZERO_OFFSET))(this, a1, a2);
		}

		::System::UInt32 GetConnectShopIDByDockData(::System::UInt32 a1, ::RPG::Client::AlleyGridItemData* a2)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32, ::RPG::Client::AlleyGridItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETCONNECTSHOPIDBYDOCKDATA_OFFSET))(this, a1, a2);
		}

		::System::UInt32 GetConnectShopIDByBuffData(::System::UInt32 a1, ::RPG::Client::AlleyGridItemData* a2)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32, ::RPG::Client::AlleyGridItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETCONNECTSHOPIDBYBUFFDATA_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckShopHasLine(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_CHECKSHOPHASLINE_OFFSET))(this, a1, a2);
		}

		::System::UInt32 GetAlleyTransportShowLayer()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYTRANSPORTSHOWLAYER_OFFSET))(this);
		}

		::System::String* GetLineTriggerByShopID(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETLINETRIGGERBYSHOPID_OFFSET))(this, a1);
		}

		::RPG::Client::ClientAlleyLogisticsScore* GetLogisticsScoreByMapID(::System::UInt32 a1)
		{
			return ((::RPG::Client::ClientAlleyLogisticsScore*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETLOGISTICSSCOREBYMAPID_OFFSET))(this, a1);
		}

		::System::UInt32 GetAlleyMapIDByShopID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GETALLEYMAPIDBYSHOPID_OFFSET))(this, a1);
		}

		::System::Void _SyncLogisticsMapList(::Class_1_412B349691B63094_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_412B349691B63094_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__SYNCLOGISTICSMAPLIST_OFFSET))(this, a1);
		}

		::System::Void _OnCmdLogisticsScoreRewardSyncInfoScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSSCOREREWARDSYNCINFOSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdLogisticsInfoScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSINFOSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdLogisticsGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDLOGISTICSGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdGetSaveLogisticsMapScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONCMDGETSAVELOGISTICSMAPSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _UpdateShopGoodsAndLineData(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_7FF19F6206AF6DD7_6*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_7FF19F6206AF6DD7_6*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UPDATESHOPGOODSANDLINEDATA_OFFSET))(this, a1);
		}

		::System::Void _UpdateShopGoodsAndLineDataByServer(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_7FF19F6206AF6DD7_6*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_7FF19F6206AF6DD7_6*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UPDATESHOPGOODSANDLINEDATABYSERVER_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::Class_1_7FF19F6206AF6DD7_6*>* _GetLogisticsMapList(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Collections::Generic::List_1<::Class_1_7FF19F6206AF6DD7_6*>*(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETLOGISTICSMAPLIST_OFFSET))(this, a1, a2);
		}

		::System::Void _TryInitAlleyTransportDataDict()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__TRYINITALLEYTRANSPORTDATADICT_OFFSET))(this);
		}

		::System::Void _TryInitTempAlleyMapLineDataListDict(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__TRYINITTEMPALLEYMAPLINEDATALISTDICT_OFFSET))(this, a1, a2);
		}

		::System::Void _TryInitServerDirectionListDict(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__TRYINITSERVERDIRECTIONLISTDICT_OFFSET))(this, a1);
		}

		::System::Void _InitAlleyTransport()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__INITALLEYTRANSPORT_OFFSET))(this);
		}

		::System::Void _UnInitAlleyTransport()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__UNINITALLEYTRANSPORT_OFFSET))(this);
		}

		::System::Void _DisposeAlleyTransport(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__DISPOSEALLEYTRANSPORT_OFFSET))(this, a1);
		}

		::System::Void _TryGenerateAlleyMapGridData(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__TRYGENERATEALLEYMAPGRIDDATA_OFFSET))(this, a1);
		}

		::RPG::Client::AlleyLineDirectionEnum _GetDirectionByTwoVector2Int(::UnityEngine::Vector2Int a1, ::UnityEngine::Vector2Int a2)
		{
			return ((::RPG::Client::AlleyLineDirectionEnum(*)(::PVOID, ::UnityEngine::Vector2Int, ::UnityEngine::Vector2Int))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETDIRECTIONBYTWOVECTOR2INT_OFFSET))(this, a1, a2);
		}

		::UnityEngine::Vector2Int _GetNexPosByDirection(::RPG::Client::AlleyLineDirectionEnum a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::UnityEngine::Vector2Int(*)(::PVOID, ::RPG::Client::AlleyLineDirectionEnum, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETNEXPOSBYDIRECTION_OFFSET))(this, a1, a2, a3);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Boolean>* _GetUnlockAlleyShopLineComplateState()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Boolean>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETUNLOCKALLEYSHOPLINECOMPLATESTATE_OFFSET))(this);
		}

		::System::Single _GetGoodsProfitRatio(::System::UInt32 a1)
		{
			return ((::System::Single(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETGOODSPROFITRATIO_OFFSET))(this, a1);
		}

		::RPG::Client::AlleyGridItemData* _GetBuffDataFromCoord(::System::UInt32 a1, ::UnityEngine::Vector2Int a2)
		{
			return ((::RPG::Client::AlleyGridItemData*(*)(::PVOID, ::System::UInt32, ::UnityEngine::Vector2Int))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETBUFFDATAFROMCOORD_OFFSET))(this, a1, a2);
		}

		::System::UInt32 _GetTransitionSaveID(::RPG::Client::AlleyGridItemData* a1, ::System::UInt32 a2)
		{
			return ((::System::UInt32(*)(::PVOID, ::RPG::Client::AlleyGridItemData*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__GETTRANSITIONSAVEID_OFFSET))(this, a1, a2);
		}

		::System::Void _OnAdventurePhaseEnteredByTransport(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONADVENTUREPHASEENTEREDBYTRANSPORT_OFFSET))(this, a1);
		}

		::System::Void _OnFinishMainMissionByTransport(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE__ONFINISHMAINMISSIONBYTRANSPORT_OFFSET))(this, a1);
		}

		::System::UInt32 get_TransportResultNewEventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_TRANSPORTRESULTNEWEVENTID_OFFSET))(this);
		}

		::System::Void set_TransportResultNewEventID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_TRANSPORTRESULTNEWEVENTID_OFFSET))(this, a1);
		}

		::System::UInt32 get_CurTransportScore()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_CURTRANSPORTSCORE_OFFSET))(this);
		}

		::System::Void set_CurTransportScore(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_CURTRANSPORTSCORE_OFFSET))(this, a1);
		}

		::System::UInt32 get_MaxTransportScore()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_MAXTRANSPORTSCORE_OFFSET))(this);
		}

		::System::Void set_MaxTransportScore(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_SET_MAXTRANSPORTSCORE_OFFSET))(this, a1);
		}

		::System::Single get_FocusCameraTime()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE_GET_FOCUSCAMERATIME_OFFSET))(this);
		}

		::System::Void __OnAdventurePhaseEnteredByTransport_b__315_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE___ONADVENTUREPHASEENTEREDBYTRANSPORT_B__315_0_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY_INIT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY_DISPOSE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__AddNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ALLEYMODULE___IFIXBASEPROXY__ADDNOTIFYHANDLERS_OFFSET))(this);
		}
	};
}
