#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/AvatarSkinType.h"
#include "unitysdk/System/Object.h"

namespace RPG::GameCore { class AvatarRow; }
namespace RPG::GameCore { class AvatarSkinRow; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }

#define RPG_CLIENT_AVATAREXTENDSKINDATA_CREATE_OFFSET UNITYSDK_OFFSET(0x8CD7EA0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ACTIONAVATARHEADICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9900)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ADVDEFAULTAVATARHEADICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9AB0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ADVPLAYERPREFABPATH_OFFSET UNITYSDK_OFFSET(0x8CD9A90)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AUDIOEVENTTAG_OFFSET UNITYSDK_OFFSET(0x8CD9CB0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINBGIMGPATH_OFFSET UNITYSDK_OFFSET(0x8CD99C0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINFRONTIMGPATH_OFFSET UNITYSDK_OFFSET(0x8CD99E0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINIMGPATH_OFFSET UNITYSDK_OFFSET(0x8CD99A0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTININTROTEXT_OFFSET UNITYSDK_OFFSET(0x8CD9A20)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARDROPOFFSET_OFFSET UNITYSDK_OFFSET(0x8CD9A00)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARID_OFFSET UNITYSDK_OFFSET(0x8CD9B90)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARMINIICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD98E0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARNAMEONDROPSKIN_OFFSET UNITYSDK_OFFSET(0x8CD9C60)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARNAME_OFFSET UNITYSDK_OFFSET(0x8CD9B60)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARROW_OFFSET UNITYSDK_OFFSET(0x8CD9830)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSELFSHOWOFFSET_OFFSET UNITYSDK_OFFSET(0x8CD9B10)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSIDEICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD98C0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSKINID_OFFSET UNITYSDK_OFFSET(0x8CD97F0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSKINNAME_OFFSET UNITYSDK_OFFSET(0x8CD9850)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_CHARACTERSKINOVERRIDECONFIGPATH_OFFSET UNITYSDK_OFFSET(0x8CD9C90)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DEFAULTAVATARHEADICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD98A0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DEFAULTAVATARMODELPATH_OFFSET UNITYSDK_OFFSET(0x8CD9880)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DRESSEDSKINID_OFFSET UNITYSDK_OFFSET(0x8CD9AF0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DRESSICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9CD0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_FREESTYLECHARACTERID_OFFSET UNITYSDK_OFFSET(0x8CD9A70)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_INTRODUCEID_OFFSET UNITYSDK_OFFSET(0x8CD9810)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_MANIKINJSONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9AD0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_PLAYERCARDID_OFFSET UNITYSDK_OFFSET(0x8CD9A50)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_PLAYERCARDTITLETEXT_OFFSET UNITYSDK_OFFSET(0x8CD9C30)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SHOPBGPATH_OFFSET UNITYSDK_OFFSET(0x8CD9C10)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SHOPRECOMMENDTABBGPATH_OFFSET UNITYSDK_OFFSET(0x8CD9BF0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SIDEAVATARHEADICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9960)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINDESC_OFFSET UNITYSDK_OFFSET(0x8CD9B30)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINITEMAVATARICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9740)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINROW_OFFSET UNITYSDK_OFFSET(0x8CD97D0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINTYPE_OFFSET UNITYSDK_OFFSET(0x8CD9BB0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_UIAVATARMODELPATH_OFFSET UNITYSDK_OFFSET(0x8CD9940)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ULTRASKILLCUTINPREFABPATH_OFFSET UNITYSDK_OFFSET(0x8CD9920)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_VIDEOID_OFFSET UNITYSDK_OFFSET(0x8CD9BD0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_GET_WAITINGAVATARHEADICONPATH_OFFSET UNITYSDK_OFFSET(0x8CD9980)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_MAPTOSKINRES_OFFSET UNITYSDK_OFFSET(0x8CD9D40)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_SET_AVATARROW_OFFSET UNITYSDK_OFFSET(0x8CD9840)
#define RPG_CLIENT_AVATAREXTENDSKINDATA_SET_SKINROW_OFFSET UNITYSDK_OFFSET(0x8CD97E0)
#define RPG_CLIENT_AVATAREXTENDSKINDATA__ADDSKINRESMAP_OFFSET UNITYSDK_OFFSET(0x8CD9690)
#define RPG_CLIENT_AVATAREXTENDSKINDATA__BUILDSKINRESMAP_OFFSET UNITYSDK_OFFSET(0x8CD7F70)
#define RPG_CLIENT_AVATAREXTENDSKINDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x8CD7F60)

namespace RPG::Client
{
	inline static constexpr unsigned int AvatarExtendSkinData_TypeDefinitionIndex = 49643;

	class AvatarExtendSkinData : public ::System::Object
	{
	public:
		::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>* _SkinResMap; // 0x10
		::RPG::GameCore::AvatarRow* _AvatarRow_k__BackingField; // 0x18
		::RPG::GameCore::AvatarSkinRow* _SkinRow_k__BackingField; // 0x20

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::AvatarExtendSkinData* Create(::System::UInt32 avatarSkinRowId)
		{
			return ((::RPG::Client::AvatarExtendSkinData*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_CREATE_OFFSET))(avatarSkinRowId);
		}

		::System::Void _BuildSkinResMap()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA__BUILDSKINRESMAP_OFFSET))(this);
		}

		::System::Void _AddSkinResMap(::System::String* originPath, ::System::String* realPath)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA__ADDSKINRESMAP_OFFSET))(this, originPath, realPath);
		}

		::RPG::GameCore::AvatarSkinRow* get_SkinRow()
		{
			return ((::RPG::GameCore::AvatarSkinRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINROW_OFFSET))(this);
		}

		::System::Void set_SkinRow(::RPG::GameCore::AvatarSkinRow* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::AvatarSkinRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_SET_SKINROW_OFFSET))(this, value);
		}

		::System::UInt32 get_AvatarSkinId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSKINID_OFFSET))(this);
		}

		::System::UInt32 get_IntroduceId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_INTRODUCEID_OFFSET))(this);
		}

		::RPG::GameCore::AvatarRow* get_AvatarRow()
		{
			return ((::RPG::GameCore::AvatarRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARROW_OFFSET))(this);
		}

		::System::Void set_AvatarRow(::RPG::GameCore::AvatarRow* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::AvatarRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_SET_AVATARROW_OFFSET))(this, value);
		}

		::RPG::Client::TextID get_AvatarSkinName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSKINNAME_OFFSET))(this);
		}

		::System::String* get_DefaultAvatarModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DEFAULTAVATARMODELPATH_OFFSET))(this);
		}

		::System::String* get_DefaultAvatarHeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DEFAULTAVATARHEADICONPATH_OFFSET))(this);
		}

		::System::String* get_AvatarSideIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSIDEICONPATH_OFFSET))(this);
		}

		::System::String* get_AvatarMiniIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARMINIICONPATH_OFFSET))(this);
		}

		::System::String* get_ActionAvatarHeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ACTIONAVATARHEADICONPATH_OFFSET))(this);
		}

		::System::String* get_UltraSkillCutInPrefabPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ULTRASKILLCUTINPREFABPATH_OFFSET))(this);
		}

		::System::String* get_UIAvatarModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_UIAVATARMODELPATH_OFFSET))(this);
		}

		::System::String* get_SideAvatarHeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SIDEAVATARHEADICONPATH_OFFSET))(this);
		}

		::System::String* get_WaitingAvatarHeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_WAITINGAVATARHEADICONPATH_OFFSET))(this);
		}

		::System::String* get_AvatarCutinImgPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINIMGPATH_OFFSET))(this);
		}

		::System::String* get_AvatarCutinBgImgPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINBGIMGPATH_OFFSET))(this);
		}

		::System::String* get_AvatarCutinFrontImgPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTINFRONTIMGPATH_OFFSET))(this);
		}

		::Il2CppArray<::System::Single>* get_AvatarDropOffset()
		{
			return ((::Il2CppArray<::System::Single>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARDROPOFFSET_OFFSET))(this);
		}

		::RPG::Client::TextID get_AvatarCutinIntroText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARCUTININTROTEXT_OFFSET))(this);
		}

		::System::UInt32 get_PlayerCardID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_PLAYERCARDID_OFFSET))(this);
		}

		::System::String* get_FreeStyleCharacterID()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_FREESTYLECHARACTERID_OFFSET))(this);
		}

		::System::String* get_AdvPlayerPrefabPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ADVPLAYERPREFABPATH_OFFSET))(this);
		}

		::System::String* get_AdvDefaultAvatarHeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_ADVDEFAULTAVATARHEADICONPATH_OFFSET))(this);
		}

		::System::String* get_ManikinJsonPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_MANIKINJSONPATH_OFFSET))(this);
		}

		::System::UInt32 get_DressedSkinID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DRESSEDSKINID_OFFSET))(this);
		}

		::System::String* get_SkinItemAvatarIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINITEMAVATARICONPATH_OFFSET))(this);
		}

		::Il2CppArray<::System::Single>* get_AvatarSelfShowOffset()
		{
			return ((::Il2CppArray<::System::Single>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARSELFSHOWOFFSET_OFFSET))(this);
		}

		::RPG::Client::TextID get_SkinDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINDESC_OFFSET))(this);
		}

		::RPG::Client::TextID get_AvatarName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARNAME_OFFSET))(this);
		}

		::System::UInt32 get_AvatarId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARID_OFFSET))(this);
		}

		::RPG::GameCore::AvatarSkinType get_SkinType()
		{
			return ((::RPG::GameCore::AvatarSkinType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SKINTYPE_OFFSET))(this);
		}

		::System::UInt32 get_VideoId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_VIDEOID_OFFSET))(this);
		}

		::System::String* get_ShopRecommendTabBgPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SHOPRECOMMENDTABBGPATH_OFFSET))(this);
		}

		::System::String* get_ShopBgPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_SHOPBGPATH_OFFSET))(this);
		}

		::RPG::Client::TextID get_PlayerCardTitleText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_PLAYERCARDTITLETEXT_OFFSET))(this);
		}

		::RPG::Client::TextID get_AvatarNameOnDropSkin()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AVATARNAMEONDROPSKIN_OFFSET))(this);
		}

		::System::String* get_CharacterSkinOverrideConfigPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_CHARACTERSKINOVERRIDECONFIGPATH_OFFSET))(this);
		}

		::System::String* get_AudioEventTag()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_AUDIOEVENTTAG_OFFSET))(this);
		}

		::System::String* get_DressIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_GET_DRESSICONPATH_OFFSET))(this);
		}

		::System::String* MapToSkinRes(::System::String* originPath)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_AVATAREXTENDSKINDATA_MAPTOSKINRES_OFFSET))(this, originPath);
		}
	};
}
