#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_0_16E4307DCC419505_265;
namespace RPG::Client { class BattleLineupGamePhase; }
namespace RPG::Client { class BattleLineupGamePhase___c__DisplayClass9_0; }

#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x14709F50)
#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_RPG_WORK_IASYNCWORKSTEPRESULT__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x1470A2C0)
#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x1470A320)
#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x1470A2D0)
#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x14709F40)
#define RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9__CTOR_OFFSET UNITYSDK_OFFSET(0x14708E40)

namespace RPG::Client
{
	inline static constexpr unsigned int BattleLineupGamePhase___EnterReplayWithMazeInfoNextFrame_d__9_TypeDefinitionIndex = 56250;

	class BattleLineupGamePhase___EnterReplayWithMazeInfoNextFrame_d__9 : public ::System::Object
	{
	public:
		::RPG::Client::BattleLineupGamePhase* __4__this; // 0x10
		::RPG::Client::BattleLineupGamePhase___c__DisplayClass9_0* __8__1; // 0x18
		::Class_0_16E4307DCC419505_265* __2__current; // 0x20
		::System::Int32 __1__state; // 0x28

		::System::Void _ctor(::System::Int32 __1__state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9__CTOR_OFFSET))(this, __1__state);
		}

		::System::Void System_IDisposable_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
		}

		::System::Boolean MoveNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_MOVENEXT_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_265* System_Collections_Generic_IEnumerator_RPG_Work_IAsyncWorkStepResult__get_Current()
		{
			return ((::Class_0_16E4307DCC419505_265*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_RPG_WORK_IASYNCWORKSTEPRESULT__GET_CURRENT_OFFSET))(this);
		}

		::System::Void System_Collections_IEnumerator_Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
		}

		::System::Object* System_Collections_IEnumerator_get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLELINEUPGAMEPHASE___ENTERREPLAYWITHMAZEINFONEXTFRAME_D__9_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
		}
	};
}
