#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/BattleAssetPreload_AssetPreloadGroup.h"
#include "unitysdk/RPG/GameCore/PlaneType.h"

namespace RPG::GameCore { class AdventureCommonEffectsPreloadConfig; }
namespace System { class String; }

#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xF3B2CB0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xF3B2DB0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xF3B2C30)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xF3B2D40)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFORESWITCHMAP_OFFSET UNITYSDK_OFFSET(0xF3B2BA0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHPETASSETS_OFFSET UNITYSDK_OFFSET(0xF3A0F10)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHPLANEEFFECT_OFFSET UNITYSDK_OFFSET(0xF3B2820)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__ADDPETASSETS_OFFSET UNITYSDK_OFFSET(0xF3B21C0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__ADDPLANEEFFECT_OFFSET UNITYSDK_OFFSET(0xF3B1F20)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET UNITYSDK_OFFSET(0xF3B1D40)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0xF3B1B20)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__CTOR_OFFSET UNITYSDK_OFFSET(0xF3B2E20)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xF3B30A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xF3B3200)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0xF3B2FF0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERBATTLE_OFFSET UNITYSDK_OFFSET(0xF3B3150)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORESWITCHMAP_OFFSET UNITYSDK_OFFSET(0xF3B2FB0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET UNITYSDK_OFFSET(0xF3B2F70)
#define RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0xF3B2F30)

namespace RPG::Client
{
	inline static constexpr unsigned int BattleAssetPreload_PreBattleAssetPreloadGroup_TypeDefinitionIndex = 55040;

	class BattleAssetPreload_PreBattleAssetPreloadGroup : public ::RPG::Client::BattleAssetPreload_AssetPreloadGroup
	{
	public:
		// static const ::System::String* COMMON_ASSET; // 0x0
		// static const ::System::String* COMMON_EFFECT; // 0x0
		// static const ::System::String* PET_ASSET_TYPE; // 0x0
		// static const ::System::String* PLANE_EFFECT_TYPE; // 0x0
		::System::UInt32 _CurPetSummonUnitID; // 0x58
		::RPG::GameCore::PlaneType _LastPlaneType; // 0x5C

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__CTOR_OFFSET))(this);
		}

		::System::Void _CollectResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET))(this);
		}

		::System::Void _CollectResourceImplForCollectionMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET))(this);
		}

		::System::Void RefreshPlaneEffect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHPLANEEFFECT_OFFSET))(this);
		}

		::System::Void RefreshPetAssets()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHPETASSETS_OFFSET))(this);
		}

		::System::Void _AddPlaneEffect(::RPG::GameCore::AdventureCommonEffectsPreloadConfig* config)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::AdventureCommonEffectsPreloadConfig*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__ADDPLANEEFFECT_OFFSET))(this, config);
		}

		::System::Void _AddPetAssets(::System::UInt32 summonUnitID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP__ADDPETASSETS_OFFSET))(this, summonUnitID);
		}

		::System::Void RefreshBeforeSwitchMap()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFORESWITCHMAP_OFFSET))(this);
		}

		::System::Void RefreshBeforeEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshBeforeEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__CollectResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPL_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__CollectResourceImplForCollectionMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPLFORCOLLECTIONMODE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeSwitchMap()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORESWITCHMAP_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshAfterEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERBATTLE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshAfterEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_PREBATTLEASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERBATTLE_OFFSET))(this);
		}
	};
}
