#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/BattleAssetPreload_CharacterPreloadGroupBase.h"

namespace RPG::AvatarSystem { class IAvatar; }
namespace RPG::Client { class BattleAssetPreload_ServantAssetPreloadGroup; }
namespace RPG::GameCore { class AvatarEffectsPreloadItem; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }

#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_AVATARID_OFFSET UNITYSDK_OFFSET(0x15CC2A10)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_ISENABLE_OFFSET UNITYSDK_OFFSET(0x15CC2A20)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_SERVANTGROUP_OFFSET UNITYSDK_OFFSET(0x15CC2A90)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_MAPASSETPATH_OFFSET UNITYSDK_OFFSET(0x15CC7070)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC5A70)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC6E10)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC59A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC6190)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFORELEAVEADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC60A0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFORELEAVEBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC6FA0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHENPCB07_OFFSET UNITYSDK_OFFSET(0x15CC3490)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHINADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC5E60)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_UPDATEAVATARDATA_OFFSET UNITYSDK_OFFSET(0x15CC32C0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0x15CC3A50)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__CTOR_OFFSET UNITYSDK_OFFSET(0x15CC7330)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__GETDEFAULTADVMODELPATH_OFFSET UNITYSDK_OFFSET(0x15CC72D0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__GETDEFAULTBATTLEMODELPATH_OFFSET UNITYSDK_OFFSET(0x15CC7150)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ISTEAMLEADERASSET_OFFSET UNITYSDK_OFFSET(0x15CC5BE0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ONDISPOSE_OFFSET UNITYSDK_OFFSET(0x15CC3920)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ONINITIALIZE_OFFSET UNITYSDK_OFFSET(0x15CC2AA0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__REGISTERINBATTLEASSET_OFFSET UNITYSDK_OFFSET(0x15CC3B80)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__REGISTERINMAZEASSETS_OFFSET UNITYSDK_OFFSET(0x15CC4EB0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__RELEASERESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0x15CC5660)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__TRYFETCHAVATARDATA_OFFSET UNITYSDK_OFFSET(0x15CC2E30)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_GET_ISENABLE_OFFSET UNITYSDK_OFFSET(0x15CC75D0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_MAPASSETPATH_OFFSET UNITYSDK_OFFSET(0x15CC7C40)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC7890)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC7B00)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC77C0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC7A50)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORELEAVEADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC79C0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORELEAVEBATTLE_OFFSET UNITYSDK_OFFSET(0x15CC7BB0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHINADVENTURE_OFFSET UNITYSDK_OFFSET(0x15CC7960)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0x15CC76D0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__GETDEFAULTADVMODELPATH_OFFSET UNITYSDK_OFFSET(0x15CC7D20)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__GETDEFAULTBATTLEMODELPATH_OFFSET UNITYSDK_OFFSET(0x15CC7CA0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__ONDISPOSE_OFFSET UNITYSDK_OFFSET(0x15CC7630)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__ONINITIALIZE_OFFSET UNITYSDK_OFFSET(0x15CC75F0)
#define RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__RELEASERESOURCEIMPL_OFFSET UNITYSDK_OFFSET(0x15CC7710)

namespace RPG::Client
{
	inline static constexpr unsigned int BattleAssetPreload_AvatarAssetPreloadGroup_TypeDefinitionIndex = 55766;

	class BattleAssetPreload_AvatarAssetPreloadGroup : public ::RPG::Client::BattleAssetPreload_CharacterPreloadGroupBase
	{
	public:
		::RPG::Client::BattleAssetPreload_ServantAssetPreloadGroup* _ServantGroup; // 0xA8
		::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>* _EquipResMap; // 0xB0
		::System::String* _EquipResMapConfigPath; // 0xB8
		::RPG::AvatarSystem::IAvatar* _Avatar; // 0xC0
		::RPG::GameCore::AvatarEffectsPreloadItem* _EffectPreloadConfig; // 0xC8
		::System::UInt32 _SkinID; // 0xD0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__CTOR_OFFSET))(this);
		}

		::System::UInt32 get_AvatarID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_AVATARID_OFFSET))(this);
		}

		::System::Boolean get_IsEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_ISENABLE_OFFSET))(this);
		}

		::RPG::Client::BattleAssetPreload_ServantAssetPreloadGroup* get_ServantGroup()
		{
			return ((::RPG::Client::BattleAssetPreload_ServantAssetPreloadGroup*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_GET_SERVANTGROUP_OFFSET))(this);
		}

		::System::Void _OnInitialize()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ONINITIALIZE_OFFSET))(this);
		}

		::System::Void UpdateAvatarData(::RPG::AvatarSystem::IAvatar* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::AvatarSystem::IAvatar*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_UPDATEAVATARDATA_OFFSET))(this, a1);
		}

		::System::Boolean RefreshENpcB07(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHENPCB07_OFFSET))(this, a1);
		}

		::System::Void _TryFetchAvatarData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__TRYFETCHAVATARDATA_OFFSET))(this);
		}

		::System::Void _OnDispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ONDISPOSE_OFFSET))(this);
		}

		::System::Void _CollectResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__COLLECTRESOURCEIMPL_OFFSET))(this);
		}

		::System::Void _ReleaseResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__RELEASERESOURCEIMPL_OFFSET))(this);
		}

		::System::Void _RegisterInBattleAsset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__REGISTERINBATTLEASSET_OFFSET))(this);
		}

		::System::Void _RegisterInMazeAssets()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__REGISTERINMAZEASSETS_OFFSET))(this);
		}

		::System::Void RefreshBeforeEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFOREENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHAFTERENTERADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshInAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHINADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshBeforeLeaveAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFORELEAVEADVENTURE_OFFSET))(this);
		}

		::System::Void RefreshBeforeEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFOREENTERBATTLE_OFFSET))(this);
		}

		::System::Void RefreshAfterEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHAFTERENTERBATTLE_OFFSET))(this);
		}

		::System::Void RefreshBeforeLeaveBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_REFRESHBEFORELEAVEBATTLE_OFFSET))(this);
		}

		::System::String* MapAssetPath(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP_MAPASSETPATH_OFFSET))(this, a1);
		}

		::System::String* _GetDefaultBattleModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__GETDEFAULTBATTLEMODELPATH_OFFSET))(this);
		}

		::System::String* _GetDefaultAdvModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__GETDEFAULTADVMODELPATH_OFFSET))(this);
		}

		::System::Boolean _IsTeamLeaderAsset()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP__ISTEAMLEADERASSET_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_get_IsEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_GET_ISENABLE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnInitialize()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__ONINITIALIZE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnDispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__ONDISPOSE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__CollectResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__COLLECTRESOURCEIMPL_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__ReleaseResourceImpl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__RELEASERESOURCEIMPL_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshAfterEnterAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshInAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHINADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeLeaveAdventure()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORELEAVEADVENTURE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFOREENTERBATTLE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshAfterEnterBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHAFTERENTERBATTLE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_RefreshBeforeLeaveBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_REFRESHBEFORELEAVEBATTLE_OFFSET))(this);
		}

		::System::String* __iFixBaseProxy_MapAssetPath(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY_MAPASSETPATH_OFFSET))(this, a1);
		}

		::System::String* __iFixBaseProxy__GetDefaultBattleModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__GETDEFAULTBATTLEMODELPATH_OFFSET))(this);
		}

		::System::String* __iFixBaseProxy__GetDefaultAdvModelPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLEASSETPRELOAD_AVATARASSETPRELOADGROUP___IFIXBASEPROXY__GETDEFAULTADVMODELPATH_OFFSET))(this);
		}
	};
}
