#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ActivityPanelData.h"

namespace RPG::Client { class ChessRogueRedDotFilter; }

#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_GET__CHESSROGUEACTIVITYGOTOMISSIONCLICKED_OFFSET UNITYSDK_OFFSET(0x1886A830)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_GET__CHESSROGUEMAINPAGESEEN_OFFSET UNITYSDK_OFFSET(0x1886A8D0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISACTIVITYUNLOCKED_OFFSET UNITYSDK_OFFSET(0x1886A770)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISGUIDEMISSIONFINISHED_OFFSET UNITYSDK_OFFSET(0x1886A7D0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x1886A1C0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_SHOULDSHOWGUIDEMISSIONREDDOT_OFFSET UNITYSDK_OFFSET(0x1886A2E0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_SHOULDSHOWMAINPAGENOTSEENREDDOT_OFFSET UNITYSDK_OFFSET(0x1886A460)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA_UPDATEFULLCOMPLETESTATUS_OFFSET UNITYSDK_OFFSET(0x1886A180)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x1886A170)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONACTIVITYENDEDCUSTOM_OFFSET UNITYSDK_OFFSET(0x1886ABF0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONACTIVITYOPENEDCUSTOM_OFFSET UNITYSDK_OFFSET(0x1886AAB0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONMISSIONDATAREADY_OFFSET UNITYSDK_OFFSET(0x1886AC40)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__SHOULDSHOWREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0x1886A600)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__TRYINITREDDOTFILTER_OFFSET UNITYSDK_OFFSET(0x1886A230)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA__TRYPREPAREMISSION_OFFSET UNITYSDK_OFFSET(0x1886A970)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x1886AD00)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY_UPDATEFULLCOMPLETESTATUS_OFFSET UNITYSDK_OFFSET(0x1886ACA0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY__ONACTIVITYENDEDCUSTOM_OFFSET UNITYSDK_OFFSET(0x1886ADC0)
#define RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY__ONACTIVITYOPENEDCUSTOM_OFFSET UNITYSDK_OFFSET(0x1886AD60)

namespace RPG::Client
{
	inline static constexpr unsigned int ChessRogueActivityData_TypeDefinitionIndex = 57603;

	class ChessRogueActivityData : public ::RPG::Client::ActivityPanelData
	{
	public:
		::RPG::Client::ChessRogueRedDotFilter* _RedDotFilter; // 0xA0
		::System::Boolean _IsGuideMissionFinishedCache; // 0xA8
		::System::Boolean _IsInitMissionPrepared; // 0xA9
		::System::Boolean _IsActivityUnlockedCache; // 0xAA

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Void UpdateFullCompleteStatus()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_UPDATEFULLCOMPLETESTATUS_OFFSET))(this);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean ShouldShowGuideMissionRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_SHOULDSHOWGUIDEMISSIONREDDOT_OFFSET))(this);
		}

		::System::Boolean ShouldShowMainPageNotSeenRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_SHOULDSHOWMAINPAGENOTSEENREDDOT_OFFSET))(this);
		}

		::System::Boolean IsActivityUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISACTIVITYUNLOCKED_OFFSET))(this);
		}

		::System::Boolean IsGuideMissionFinished()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_ISGUIDEMISSIONFINISHED_OFFSET))(this);
		}

		::System::Void _OnActivityOpenedCustom()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONACTIVITYOPENEDCUSTOM_OFFSET))(this);
		}

		::System::Void _OnActivityEndedCustom()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONACTIVITYENDEDCUSTOM_OFFSET))(this);
		}

		::System::Boolean _ShouldShowRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__SHOULDSHOWREWARDREDDOT_OFFSET))(this);
		}

		::System::Void _TryPrepareMission()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__TRYPREPAREMISSION_OFFSET))(this);
		}

		::System::Void _OnMissionDataReady()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__ONMISSIONDATAREADY_OFFSET))(this);
		}

		::System::Void _TryInitRedDotFilter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA__TRYINITREDDOTFILTER_OFFSET))(this);
		}

		::System::Boolean get__ChessRogueActivityGotoMissionClicked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_GET__CHESSROGUEACTIVITYGOTOMISSIONCLICKED_OFFSET))(this);
		}

		::System::Boolean get__ChessRogueMainPageSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA_GET__CHESSROGUEMAINPAGESEEN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_UpdateFullCompleteStatus()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY_UPDATEFULLCOMPLETESTATUS_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnActivityOpenedCustom()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY__ONACTIVITYOPENEDCUSTOM_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnActivityEndedCustom()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEACTIVITYDATA___IFIXBASEPROXY__ONACTIVITYENDEDCUSTOM_OFFSET))(this);
		}
	};
}
