#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/BaseClockParkGameState.h"

#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ENABLEDICEPLACEMENT_OFFSET UNITYSDK_OFFSET(0x94025E0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_FINISHROUND_OFFSET UNITYSDK_OFFSET(0x94019D0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISDICETOLOCKCHAPTER_OFFSET UNITYSDK_OFFSET(0x94022F0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSELECTEDFALSEENDCHAPTER_OFFSET UNITYSDK_OFFSET(0x9401FE0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSELECTEDTRUEENDCHAPTER_OFFSET UNITYSDK_OFFSET(0x9401CD0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSHOWDICEPLACEMENT_OFFSET UNITYSDK_OFFSET(0x94025A0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISTRUEENDBRANCHUNLOCK_OFFSET UNITYSDK_OFFSET(0x9401B90)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__CTOR_OFFSET UNITYSDK_OFFSET(0x9401800)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__ISCHAPTERLEADTOFALSEENDING_OFFSET UNITYSDK_OFFSET(0x94021F0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__ISCHAPTERLEADTOTRUEENDING_OFFSET UNITYSDK_OFFSET(0x9401EE0)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_ENABLEDICEPLACEMENT_OFFSET UNITYSDK_OFFSET(0x9402700)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_FINISHROUND_OFFSET UNITYSDK_OFFSET(0x9402620)
#define RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_ISSHOWDICEPLACEMENT_OFFSET UNITYSDK_OFFSET(0x9402690)

namespace RPG::Client
{
	inline static constexpr unsigned int ClockParkInstance_ClockParkBranchSelectState_TypeDefinitionIndex = 49866;

	class ClockParkInstance_ClockParkBranchSelectState : public ::RPG::Client::BaseClockParkGameState
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__CTOR_OFFSET))(this);
		}

		::System::Boolean FinishRound()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_FINISHROUND_OFFSET))(this);
		}

		::System::Boolean IsTrueEndBranchUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISTRUEENDBRANCHUNLOCK_OFFSET))(this);
		}

		::System::Boolean IsSelectedTrueEndChapter()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSELECTEDTRUEENDCHAPTER_OFFSET))(this);
		}

		::System::Boolean IsSelectedFalseEndChapter()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSELECTEDFALSEENDCHAPTER_OFFSET))(this);
		}

		::System::Boolean IsDiceToLockChapter(::System::Int32 diceIndex)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISDICETOLOCKCHAPTER_OFFSET))(this, diceIndex);
		}

		::System::Boolean _IsChapterLeadToFalseEnding(::System::UInt32 chapterID)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__ISCHAPTERLEADTOFALSEENDING_OFFSET))(this, chapterID);
		}

		::System::Boolean _IsChapterLeadToTrueEnding(::System::UInt32 chapterID)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE__ISCHAPTERLEADTOTRUEENDING_OFFSET))(this, chapterID);
		}

		::System::Boolean IsShowDicePlacement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ISSHOWDICEPLACEMENT_OFFSET))(this);
		}

		::System::Boolean EnableDicePlacement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE_ENABLEDICEPLACEMENT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_FinishRound()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_FINISHROUND_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowDicePlacement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_ISSHOWDICEPLACEMENT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_EnableDicePlacement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CLOCKPARKINSTANCE_CLOCKPARKBRANCHSELECTSTATE___IFIXBASEPROXY_ENABLEDICEPLACEMENT_OFFSET))(this);
		}
	};
}
