#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_4608E37A1B3D374A_15.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/ActivityRank.h"
#include "unitysdk/RPG/GameCore/AttackDamageType.h"
#include "unitysdk/System/Object.h"

class Class_1_352A8B3482C80E7D_18;
namespace RPG::Client { class FightFestPlayerInfo; }
namespace RPG::Client { class FightFestRaceData; }
namespace RPG::GameCore { class FightFestChallengeRow; }
namespace RPG::GameCore { class FightFestStageInfoRow; }
namespace System { class String; }

#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_BATTLETARGETLIST_OFFSET UNITYSDK_OFFSET(0x924D010)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGEID_OFFSET UNITYSDK_OFFSET(0x924C920)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGENAME_OFFSET UNITYSDK_OFFSET(0x924CF80)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFDES_OFFSET UNITYSDK_OFFSET(0x924CF30)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFID_OFFSET UNITYSDK_OFFSET(0x924CEC0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFNAME_OFFSET UNITYSDK_OFFSET(0x924CF00)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_EVENTID_OFFSET UNITYSDK_OFFSET(0x924CEA0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_FIGUREPATH_OFFSET UNITYSDK_OFFSET(0x924D100)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASRECORD_OFFSET UNITYSDK_OFFSET(0x924CA50)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASREWARDCANTAKE_OFFSET UNITYSDK_OFFSET(0x924CB80)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISFINISHALLQUEST_OFFSET UNITYSDK_OFFSET(0x924CCE0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISSEENUNLOCK_OFFSET UNITYSDK_OFFSET(0x924CA70)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISUNLOCK_OFFSET UNITYSDK_OFFSET(0x924C980)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALFIGUREPATH_OFFSET UNITYSDK_OFFSET(0x924D0E0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALSTAGENAME_OFFSET UNITYSDK_OFFSET(0x924D0B0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_PREVIEWMONSTERLIST_OFFSET UNITYSDK_OFFSET(0x924CFB0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTGROUPID_OFFSET UNITYSDK_OFFSET(0x924CFF0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTIDLIST_OFFSET UNITYSDK_OFFSET(0x924CCC0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RACEDATA_OFFSET UNITYSDK_OFFSET(0x924CE60)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RANK_OFFSET UNITYSDK_OFFSET(0x924C940)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RECOMMADNATURE_OFFSET UNITYSDK_OFFSET(0x924CFD0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RIVALINFO_OFFSET UNITYSDK_OFFSET(0x924CE80)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ROW_OFFSET UNITYSDK_OFFSET(0x924CE20)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_SPECIALAVATARLIST_OFFSET UNITYSDK_OFFSET(0x924CF60)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STAGEINFOROW_OFFSET UNITYSDK_OFFSET(0x924CE40)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STORYDESC_OFFSET UNITYSDK_OFFSET(0x924D080)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0x924C960)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TUTORIALID_OFFSET UNITYSDK_OFFSET(0x924D030)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UIENTERBATTLEAREAID_OFFSET UNITYSDK_OFFSET(0x924CEE0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKSUBMISSIONID_OFFSET UNITYSDK_OFFSET(0x924CA30)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKTIPS_OFFSET UNITYSDK_OFFSET(0x924D050)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_CHALLENGEID_OFFSET UNITYSDK_OFFSET(0x924C930)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_HASRECORD_OFFSET UNITYSDK_OFFSET(0x924CA60)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RACEDATA_OFFSET UNITYSDK_OFFSET(0x924CE70)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RANK_OFFSET UNITYSDK_OFFSET(0x924C950)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RIVALINFO_OFFSET UNITYSDK_OFFSET(0x924CE90)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_ROW_OFFSET UNITYSDK_OFFSET(0x924CE30)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_STAGEINFOROW_OFFSET UNITYSDK_OFFSET(0x924CE50)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_TURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0x924C970)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXRANK_OFFSET UNITYSDK_OFFSET(0x924C860)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXTURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0x924C8D0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNC_OFFSET UNITYSDK_OFFSET(0x924C770)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x924C660)

namespace RPG::Client
{
	inline static constexpr unsigned int FightFestChallengeLevelData_TypeDefinitionIndex = 50954;

	class FightFestChallengeLevelData : public ::System::Object
	{
	public:
		::RPG::Client::FightFestPlayerInfo* _RivalInfo_k__BackingField; // 0x10
		::RPG::GameCore::FightFestStageInfoRow* _StageInfoRow_k__BackingField; // 0x18
		::RPG::GameCore::FightFestChallengeRow* _Row_k__BackingField; // 0x20
		::RPG::Client::FightFestRaceData* _RaceData_k__BackingField; // 0x28
		::System::UInt32 _TurnLeftCount_k__BackingField; // 0x30
		::System::UInt32 _ChallengeID_k__BackingField; // 0x34
		::RPG::GameCore::ActivityRank _Rank_k__BackingField; // 0x38
		::System::Boolean _HasRecord_k__BackingField; // 0x3C

		::System::Void _ctor(::System::UInt32 id)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA__CTOR_OFFSET))(this, id);
		}

		::System::Void Sync(::Class_1_352A8B3482C80E7D_18* challenge)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_352A8B3482C80E7D_18*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNC_OFFSET))(this, challenge);
		}

		::System::Void SyncHistoryMaxRank(::Enum_3_4608E37A1B3D374A_15 rank)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_4608E37A1B3D374A_15))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXRANK_OFFSET))(this, rank);
		}

		::System::Void SyncHistoryMaxTurnLeftCount(::System::UInt32 turnLeftCount)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXTURNLEFTCOUNT_OFFSET))(this, turnLeftCount);
		}

		::System::UInt32 get_ChallengeID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGEID_OFFSET))(this);
		}

		::System::Void set_ChallengeID(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_CHALLENGEID_OFFSET))(this, value);
		}

		::RPG::GameCore::ActivityRank get_Rank()
		{
			return ((::RPG::GameCore::ActivityRank(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RANK_OFFSET))(this);
		}

		::System::Void set_Rank(::RPG::GameCore::ActivityRank value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ActivityRank))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RANK_OFFSET))(this, value);
		}

		::System::UInt32 get_TurnLeftCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TURNLEFTCOUNT_OFFSET))(this);
		}

		::System::Void set_TurnLeftCount(::System::UInt32 value)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_TURNLEFTCOUNT_OFFSET))(this, value);
		}

		::System::Boolean get_IsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISUNLOCK_OFFSET))(this);
		}

		::System::UInt32 get_UnlockSubMissionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKSUBMISSIONID_OFFSET))(this);
		}

		::System::Boolean get_HasRecord()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASRECORD_OFFSET))(this);
		}

		::System::Void set_HasRecord(::System::Boolean value)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_HASRECORD_OFFSET))(this, value);
		}

		::System::Boolean get_IsSeenUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISSEENUNLOCK_OFFSET))(this);
		}

		::System::Boolean get_HasRewardCanTake()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASREWARDCANTAKE_OFFSET))(this);
		}

		::System::Boolean get_IsFinishAllQuest()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISFINISHALLQUEST_OFFSET))(this);
		}

		::RPG::GameCore::FightFestChallengeRow* get_Row()
		{
			return ((::RPG::GameCore::FightFestChallengeRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ROW_OFFSET))(this);
		}

		::System::Void set_Row(::RPG::GameCore::FightFestChallengeRow* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FightFestChallengeRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_ROW_OFFSET))(this, value);
		}

		::RPG::GameCore::FightFestStageInfoRow* get_StageInfoRow()
		{
			return ((::RPG::GameCore::FightFestStageInfoRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STAGEINFOROW_OFFSET))(this);
		}

		::System::Void set_StageInfoRow(::RPG::GameCore::FightFestStageInfoRow* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FightFestStageInfoRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_STAGEINFOROW_OFFSET))(this, value);
		}

		::RPG::Client::FightFestRaceData* get_RaceData()
		{
			return ((::RPG::Client::FightFestRaceData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RACEDATA_OFFSET))(this);
		}

		::System::Void set_RaceData(::RPG::Client::FightFestRaceData* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FightFestRaceData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RACEDATA_OFFSET))(this, value);
		}

		::RPG::Client::FightFestPlayerInfo* get_RivalInfo()
		{
			return ((::RPG::Client::FightFestPlayerInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RIVALINFO_OFFSET))(this);
		}

		::System::Void set_RivalInfo(::RPG::Client::FightFestPlayerInfo* value)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FightFestPlayerInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RIVALINFO_OFFSET))(this, value);
		}

		::System::UInt32 get_EventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_EVENTID_OFFSET))(this);
		}

		::System::UInt32 get_EnvironmentBuffID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFID_OFFSET))(this);
		}

		::System::UInt32 get_UIEnterBattleAreaID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UIENTERBATTLEAREAID_OFFSET))(this);
		}

		::RPG::Client::TextID get_EnvironmentBuffName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFNAME_OFFSET))(this);
		}

		::RPG::Client::TextID get_EnvironmentBuffDes()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFDES_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_SpecialAvatarList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_SPECIALAVATARLIST_OFFSET))(this);
		}

		::RPG::Client::TextID get_ChallengeName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGENAME_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_PreviewMonsterList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_PREVIEWMONSTERLIST_OFFSET))(this);
		}

		::Il2CppArray<::RPG::GameCore::AttackDamageType>* get_RecommadNature()
		{
			return ((::Il2CppArray<::RPG::GameCore::AttackDamageType>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RECOMMADNATURE_OFFSET))(this);
		}

		::System::UInt32 get_QuestGroupID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTGROUPID_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_QuestIDList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTIDLIST_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_BattleTargetList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_BATTLETARGETLIST_OFFSET))(this);
		}

		::System::UInt32 get_TutorialID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TUTORIALID_OFFSET))(this);
		}

		::RPG::Client::TextID get_UnlockTips()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKTIPS_OFFSET))(this);
		}

		::RPG::Client::TextID get_StoryDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STORYDESC_OFFSET))(this);
		}

		::RPG::Client::TextID get_OriginalStageName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALSTAGENAME_OFFSET))(this);
		}

		::System::String* get_OriginalFigurePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALFIGUREPATH_OFFSET))(this);
		}

		::System::String* get_FigurePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_FIGUREPATH_OFFSET))(this);
		}
	};
}
