#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_0A3761FE34514D6C_36.h"
#include "unitysdk/RPG/Client/BaseModule.h"
#include "unitysdk/RPG/Client/FiveDimModule_OverridableVariable_1.h"
#include "unitysdk/RPG/Client/FiveDimTransitionStatus.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/FiveDimExitType.h"
#include "unitysdk/RPG/GameCore/FiveDimAvatarMoveAbility.h"
#include "unitysdk/RPG/GameCore/FiveDimGameplayMode.h"
#include "unitysdk/Struct_2_D80CFC559D4BCFA6.h"
#include "unitysdk/Struct_2_F01DF3CDCF3FD7AC.h"
#include "unitysdk/Struct_2_FC595D1A561D8C6F.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/UnityEngine/Quaternion.h"
#include "unitysdk/UnityEngine/Rect.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_1_20D743894CDF214D_1;
class Class_1_43BD383C98B4C0C5_149;
class Class_1_76FC7D9EAE4C806C;
class Class_1_A810E08D2BDEB9C4;
class Class_1_D17272E82AE804C2_333;
class Class_1_D17272E82AE804C2_334;
class Class_1_D17272E82AE804C2_335;
class Class_1_D17272E82AE804C2_337;
class Class_1_F91AD0C5A85E4AFA_9;
class Class_3_07C3C4D2990C49EE;
namespace RPG::Client { class FiveDimGameInstance; }
namespace RPG::Client { class FiveDimJumpDisplayInfo; }
namespace RPG::Client { class FiveDimSkillDisplayInfo; }
namespace RPG::Client { class FiveDimTrainModeDisplayInfos; }
namespace RPG::Client { class ItemDisplayData; }
namespace RPG::Client { class LittleWheelSelectConfig; }
namespace RPG::Client { class UIFrameCapture; }
namespace RPG::Client::ChenLingGameBoy { class ChenLingGameBoyPlayerRankingListInfo; }
namespace RPG::Client::ChenLingGameBoy { class ChenLingGameBoyPuzzleData; }
namespace RPG::Client::LittleGame::FiveDim { class FiveDimFluteDataManager; }
namespace RPG::Client::LittleGame::FiveDim { class SidePuzzleTargetData; }
namespace RPG::Client::Promises { class IPromise; }
namespace RPG::Client::Promises { template <typename T> class IPromise_1; }
namespace RPG::Client::Promises { template <typename T> class Promise_1; }
namespace RPG::GameCore { class FiveDimGameConfig; }
namespace RPG::GameCore { class FiveDimLevelSettings; }
namespace RPG::GameCore { class FiveDimMoveConfig; }
namespace RPG::GameCore { class GameEntity; }
namespace System { class Object; }
namespace System { class String; }
namespace System { template <typename T> class Action_1; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class Camera; }
namespace UnityEngine { class Texture; }
namespace UnityEngine { class Transform; }

#define RPG_CLIENT_FIVEDIMMODULE_ADD_ONMONEYWEEKLYLIMITREACHED_OFFSET UNITYSDK_OFFSET(0x16BB7380)
#define RPG_CLIENT_FIVEDIMMODULE_APPLYFLUTEWITHSWITCHLINE_OFFSET UNITYSDK_OFFSET(0x16BB55C0)
#define RPG_CLIENT_FIVEDIMMODULE_APPLYFLUTE_OFFSET UNITYSDK_OFFSET(0x16BB52D0)
#define RPG_CLIENT_FIVEDIMMODULE_CHENLINGCAPTUREFRAME_OFFSET UNITYSDK_OFFSET(0x16BB1B40)
#define RPG_CLIENT_FIVEDIMMODULE_CLEARNETWORKDATA_OFFSET UNITYSDK_OFFSET(0x16BB9830)
#define RPG_CLIENT_FIVEDIMMODULE_CLOSETRANSITIONVIEW_OFFSET UNITYSDK_OFFSET(0x16BB0780)
#define RPG_CLIENT_FIVEDIMMODULE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x16BBB920)
#define RPG_CLIENT_FIVEDIMMODULE_ENTERCHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB3F50)
#define RPG_CLIENT_FIVEDIMMODULE_ENTERCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0x16BB3210)
#define RPG_CLIENT_FIVEDIMMODULE_EXITCHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB4380)
#define RPG_CLIENT_FIVEDIMMODULE_EXITFIVEDIMGAME_OFFSET UNITYSDK_OFFSET(0x16BAE2C0)
#define RPG_CLIENT_FIVEDIMMODULE_EXITTYPETONETWORKLEAVETYPE_OFFSET UNITYSDK_OFFSET(0x16BB9090)
#define RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERJUMPDISPLAYINFO_OFFSET UNITYSDK_OFFSET(0x16BBB800)
#define RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERSKILLDISPLAYINFO_OFFSET UNITYSDK_OFFSET(0x16BBB2D0)
#define RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERSRANKINGINFO_OFFSET UNITYSDK_OFFSET(0x16BB3CF0)
#define RPG_CLIENT_FIVEDIMMODULE_FETCHTRAINMODEDISPLAYINFOS_OFFSET UNITYSDK_OFFSET(0x16BBAE50)
#define RPG_CLIENT_FIVEDIMMODULE_FINISHFIVEDIMACHIEVEMENT_OFFSET UNITYSDK_OFFSET(0x16BBC450)
#define RPG_CLIENT_FIVEDIMMODULE_FINISHFIVEDIMMINIGAME_OFFSET UNITYSDK_OFFSET(0x16BB5CE0)
#define RPG_CLIENT_FIVEDIMMODULE_FINISHFLUTE_OFFSET UNITYSDK_OFFSET(0x16BB5200)
#define RPG_CLIENT_FIVEDIMMODULE_GETCHENLINGGAMEBOYPUZZLEDATA_OFFSET UNITYSDK_OFFSET(0x16BB3700)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEHIGHSCORE_OFFSET UNITYSDK_OFFSET(0x16BB64D0)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEID_OFFSET UNITYSDK_OFFSET(0x16BB68F0)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEONETIMEREWARDS_1_OFFSET UNITYSDK_OFFSET(0x16BB6D30)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEONETIMEREWARDS_OFFSET UNITYSDK_OFFSET(0x16BB6C80)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEPREVIEWREWARDS_OFFSET UNITYSDK_OFFSET(0x16BB6F90)
#define RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMESCORETARGETS_OFFSET UNITYSDK_OFFSET(0x16BB6A40)
#define RPG_CLIENT_FIVEDIMMODULE_GETSETTLEMENTTEXTURE_OFFSET UNITYSDK_OFFSET(0x16BB4D70)
#define RPG_CLIENT_FIVEDIMMODULE_GET_CANUSECAMERAOBSERVE_OFFSET UNITYSDK_OFFSET(0x16BBC5E0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_CHENLINGGAMEBOYPUZZLEDATA_OFFSET UNITYSDK_OFFSET(0x16BB3C70)
#define RPG_CLIENT_FIVEDIMMODULE_GET_CURRENTGAMEINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BBC5B0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_CURRENTPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBACD0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_FIVEDIMJOYSTICKDEBUGSHOW_OFFSET UNITYSDK_OFFSET(0x16BBCAA0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_GAMEDIFFICULTY_OFFSET UNITYSDK_OFFSET(0x16BBC640)
#define RPG_CLIENT_FIVEDIMMODULE_GET_GAMELEVELCONFIG_OFFSET UNITYSDK_OFFSET(0x16BBC6A0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_INPUTJOYSTICKTYPE_OFFSET UNITYSDK_OFFSET(0x16BBC9F0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_INSTANCE_OFFSET UNITYSDK_OFFSET(0x16BA0280)
#define RPG_CLIENT_FIVEDIMMODULE_GET_INWALLREVERSEINPUTCD_OFFSET UNITYSDK_OFFSET(0x16BBC8A0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_ISINCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0x16BB4FF0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_ISINFIVEDIMGAME_OFFSET UNITYSDK_OFFSET(0x16BAE4B0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_ISMONEYWEEKLYLIMITREACHED_OFFSET UNITYSDK_OFFSET(0x16BB7F00)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MAXJUMPENERGY_OFFSET UNITYSDK_OFFSET(0x16BBC5D0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MONEYITEMID_OFFSET UNITYSDK_OFFSET(0x16BB7D20)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MONEYNUM_OFFSET UNITYSDK_OFFSET(0x16BB7E00)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MONEYWEEKLYLIMIT_OFFSET UNITYSDK_OFFSET(0x16BB7970)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MONEYWEEKLYNUM_OFFSET UNITYSDK_OFFSET(0x16BB7EE0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MOVECONFIG_OFFSET UNITYSDK_OFFSET(0x16BBC770)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MOVEINPUTDEADZONE_OFFSET UNITYSDK_OFFSET(0x16BBC7D0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_MOVEINPUTHORIZONTALANGLE_OFFSET UNITYSDK_OFFSET(0x16BBC980)
#define RPG_CLIENT_FIVEDIMMODULE_GET_OUTWALLREVERSEINPUTCD_OFFSET UNITYSDK_OFFSET(0x16BBC910)
#define RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBAD30)
#define RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGPLAYER3DINFO_OFFSET UNITYSDK_OFFSET(0x16BBADF0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGSERVERPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBAD90)
#define RPG_CLIENT_FIVEDIMMODULE_GET_PLAYERSKILLUPGRADED_OFFSET UNITYSDK_OFFSET(0x16BBB680)
#define RPG_CLIENT_FIVEDIMMODULE_GET_PUZZLEDATA_OFFSET UNITYSDK_OFFSET(0x16BBAE30)
#define RPG_CLIENT_FIVEDIMMODULE_GET_SHOULDREVERSEINPUTDEADZONE_OFFSET UNITYSDK_OFFSET(0x16BBC840)
#define RPG_CLIENT_FIVEDIMMODULE_GET_SIDEPUZZLETARGETDATA_OFFSET UNITYSDK_OFFSET(0x16BBCA70)
#define RPG_CLIENT_FIVEDIMMODULE_GET_SKILLPANELCONFIGID_OFFSET UNITYSDK_OFFSET(0x16BBB4F0)
#define RPG_CLIENT_FIVEDIMMODULE_GET_USEDIRECTIONBTN_OFFSET UNITYSDK_OFFSET(0x16BBCA60)
#define RPG_CLIENT_FIVEDIMMODULE_GET_USEPOLARCOORDINATES_OFFSET UNITYSDK_OFFSET(0x16BBCA90)
#define RPG_CLIENT_FIVEDIMMODULE_GET__DEFAULTSKILLPANELCONFIGID_OFFSET UNITYSDK_OFFSET(0x16BBB5A0)
#define RPG_CLIENT_FIVEDIMMODULE_INIT_OFFSET UNITYSDK_OFFSET(0x16BBAEB0)
#define RPG_CLIENT_FIVEDIMMODULE_INVOKEREACHMAXTIMELIMITSEQUENCE_OFFSET UNITYSDK_OFFSET(0x16BB4A90)
#define RPG_CLIENT_FIVEDIMMODULE_ISFLUTEAPPLIED_OFFSET UNITYSDK_OFFSET(0x16BB5740)
#define RPG_CLIENT_FIVEDIMMODULE_ISFLUTEBUTTONENABLE_OFFSET UNITYSDK_OFFSET(0x16BB51B0)
#define RPG_CLIENT_FIVEDIMMODULE_ISFLUTEFINISHED_OFFSET UNITYSDK_OFFSET(0x16BB5100)
#define RPG_CLIENT_FIVEDIMMODULE_ISFLUTEVALID_OFFSET UNITYSDK_OFFSET(0x16BB5090)
#define RPG_CLIENT_FIVEDIMMODULE_LEAVECHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB4470)
#define RPG_CLIENT_FIVEDIMMODULE_NOTIFYDISPLAYREWARDS_OFFSET UNITYSDK_OFFSET(0x16BB7B30)
#define RPG_CLIENT_FIVEDIMMODULE_ONENTERGAME_OFFSET UNITYSDK_OFFSET(0x16BA94F0)
#define RPG_CLIENT_FIVEDIMMODULE_ONEXITCHENLINGGAMEBOYGAMEENTRANCE_OFFSET UNITYSDK_OFFSET(0x16BB48D0)
#define RPG_CLIENT_FIVEDIMMODULE_ONEXITGAME_OFFSET UNITYSDK_OFFSET(0x16BAA100)
#define RPG_CLIENT_FIVEDIMMODULE_OPENTRANSITIONVIEW_OFFSET UNITYSDK_OFFSET(0x16BB0640)
#define RPG_CLIENT_FIVEDIMMODULE_RECOVERMINIGAMEFCV_OFFSET UNITYSDK_OFFSET(0x16BB7240)
#define RPG_CLIENT_FIVEDIMMODULE_RELEASEFRAME_OFFSET UNITYSDK_OFFSET(0x16BB4DC0)
#define RPG_CLIENT_FIVEDIMMODULE_REMOVE_ONMONEYWEEKLYLIMITREACHED_OFFSET UNITYSDK_OFFSET(0x16BB73E0)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTADDMONEY_OFFSET UNITYSDK_OFFSET(0x16BB7440)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTENTERGAME_OFFSET UNITYSDK_OFFSET(0x16BB8840)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTGAMEDATA_OFFSET UNITYSDK_OFFSET(0x16BB8FA0)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTLEAVEGAME_OFFSET UNITYSDK_OFFSET(0x16BAE900)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTNETWORKFINISHCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0x16BB3940)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTTRANSFER_OFFSET UNITYSDK_OFFSET(0x16BB93C0)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTUPDATEPLAYEREXTRAABILITY_OFFSET UNITYSDK_OFFSET(0x16BA02D0)
#define RPG_CLIENT_FIVEDIMMODULE_REQUESTUPDATETWODIMPLAYERINFO_OFFSET UNITYSDK_OFFSET(0x16BB90F0)
#define RPG_CLIENT_FIVEDIMMODULE_REQUIRECHENLINGGAMEBOYDATA_OFFSET UNITYSDK_OFFSET(0x16BB38B0)
#define RPG_CLIENT_FIVEDIMMODULE_RESETCHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB41F0)
#define RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGCHEATINPUTKEYREQ_OFFSET UNITYSDK_OFFSET(0x16BB9700)
#define RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGCHEATMODEREQ_OFFSET UNITYSDK_OFFSET(0x16BB9790)
#define RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGGAMEBOYCHANGESETTINGSCSREQ_OFFSET UNITYSDK_OFFSET(0x16BB92B0)
#define RPG_CLIENT_FIVEDIMMODULE_SETCHENLINGGAMEBOYTIMEPAUSED_OFFSET UNITYSDK_OFFSET(0x16BB49B0)
#define RPG_CLIENT_FIVEDIMMODULE_SETCURRENTACTIVEFLUTEID_OFFSET UNITYSDK_OFFSET(0x16BB5160)
#define RPG_CLIENT_FIVEDIMMODULE_SETMAXJUMPENERGY_OFFSET UNITYSDK_OFFSET(0x16BBA840)
#define RPG_CLIENT_FIVEDIMMODULE_SETMOVEABILITYENABLED_OFFSET UNITYSDK_OFFSET(0x16BBB1E0)
#define RPG_CLIENT_FIVEDIMMODULE_SETPLAYERSKILLUPGRADED_OFFSET UNITYSDK_OFFSET(0x16BBB260)
#define RPG_CLIENT_FIVEDIMMODULE_SET_CURRENTGAMEINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BBC5C0)
#define RPG_CLIENT_FIVEDIMMODULE_SET_CURRENTPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBAD00)
#define RPG_CLIENT_FIVEDIMMODULE_SET_FIVEDIMJOYSTICKDEBUGSHOW_OFFSET UNITYSDK_OFFSET(0x16BBCAB0)
#define RPG_CLIENT_FIVEDIMMODULE_SET_INPUTJOYSTICKTYPE_OFFSET UNITYSDK_OFFSET(0x16BBCA00)
#define RPG_CLIENT_FIVEDIMMODULE_SET_ISMONEYWEEKLYLIMITREACHED_OFFSET UNITYSDK_OFFSET(0x16BB7F10)
#define RPG_CLIENT_FIVEDIMMODULE_SET_MONEYNUM_OFFSET UNITYSDK_OFFSET(0x16BB78C0)
#define RPG_CLIENT_FIVEDIMMODULE_SET_MONEYWEEKLYNUM_OFFSET UNITYSDK_OFFSET(0x16BB7EF0)
#define RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBAD60)
#define RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGPLAYER3DINFO_OFFSET UNITYSDK_OFFSET(0x16BBAE10)
#define RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGSERVERPLAYER2DINFO_OFFSET UNITYSDK_OFFSET(0x16BBADC0)
#define RPG_CLIENT_FIVEDIMMODULE_SET_PUZZLEDATA_OFFSET UNITYSDK_OFFSET(0x16BBAE40)
#define RPG_CLIENT_FIVEDIMMODULE_SET_SIDEPUZZLETARGETDATA_OFFSET UNITYSDK_OFFSET(0x16BBCA80)
#define RPG_CLIENT_FIVEDIMMODULE_TRYAUTOSHOW_OFFSET UNITYSDK_OFFSET(0x16BBB720)
#define RPG_CLIENT_FIVEDIMMODULE__ADDMINIGAMEPACKEDHANDLERS_OFFSET UNITYSDK_OFFSET(0x16BB5F90)
#define RPG_CLIENT_FIVEDIMMODULE__ADDNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0x16BBBB40)
#define RPG_CLIENT_FIVEDIMMODULE__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x16BB7F20)
#define RPG_CLIENT_FIVEDIMMODULE__CREATELITTLEWHEELSELECTCONFIG_OFFSET UNITYSDK_OFFSET(0x16BBB9C0)
#define RPG_CLIENT_FIVEDIMMODULE__CTOR_OFFSET UNITYSDK_OFFSET(0x16BBCB10)
#define RPG_CLIENT_FIVEDIMMODULE__EXECUTEENTERGAMESEQUENCE_OFFSET UNITYSDK_OFFSET(0x16BB4E30)
#define RPG_CLIENT_FIVEDIMMODULE__EXECUTEEXITGAMESEQUENCE_OFFSET UNITYSDK_OFFSET(0x16BB4F10)
#define RPG_CLIENT_FIVEDIMMODULE__FROMNETWORKDATA_OFFSET UNITYSDK_OFFSET(0x16BB9D40)
#define RPG_CLIENT_FIVEDIMMODULE__FROMPROTOPOSITION_OFFSET UNITYSDK_OFFSET(0x16BBAB60)
#define RPG_CLIENT_FIVEDIMMODULE__FROMPROTOROTATION_OFFSET UNITYSDK_OFFSET(0x16BBAC00)
#define RPG_CLIENT_FIVEDIMMODULE__GETSCREENRECT_OFFSET UNITYSDK_OFFSET(0x16BB4B70)
#define RPG_CLIENT_FIVEDIMMODULE__INITGAMECONFIG_OFFSET UNITYSDK_OFFSET(0x16BBB190)
#define RPG_CLIENT_FIVEDIMMODULE__LEAVECHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB44C0)
#define RPG_CLIENT_FIVEDIMMODULE__LOADGAMECONFIG_OFFSET UNITYSDK_OFFSET(0x16BBC2A0)
#define RPG_CLIENT_FIVEDIMMODULE__NOTIFYDISPLAYREWARDS_OFFSET UNITYSDK_OFFSET(0x16BB7B80)
#define RPG_CLIENT_FIVEDIMMODULE__ONADVENTUREPHASEEND_OFFSET UNITYSDK_OFFSET(0x16BBC110)
#define RPG_CLIENT_FIVEDIMMODULE__ONCHENLINGGAMEBOYGETFRIENDRANKINGINFOSCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA550)
#define RPG_CLIENT_FIVEDIMMODULE__ONENTERFIVEDIMGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16BB98C0)
#define RPG_CLIENT_FIVEDIMMODULE__ONFINISHCHENLINGGAMEBOYSCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA610)
#define RPG_CLIENT_FIVEDIMMODULE__ONFINISHFIVEDIMMINIGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16BB6120)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMFLUTEDATACHANGENOTIFY_OFFSET UNITYSDK_OFFSET(0x16BB5B80)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMGAMEDATAUPDATESCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16BB99F0)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMGAMETRANSFERSCRSP_OFFSET UNITYSDK_OFFSET(0x16BB9F20)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMJUMPENERGYCHANGESCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16BBA890)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMMONEYCHANGESCNOTIFY_OFFSET UNITYSDK_OFFSET(0x16BB7A50)
#define RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMONMAINPAGERETURNTOP_OFFSET UNITYSDK_OFFSET(0x16BBC160)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETCHENLINGGAMEBOYDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA480)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMFLUTEDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BB5A20)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMGAMEDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA7A0)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMINIGAMEDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BB6610)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMONEYDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BB7830)
#define RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMONEYSCRSP_OFFSET UNITYSDK_OFFSET(0x16BB75B0)
#define RPG_CLIENT_FIVEDIMMODULE__ONHIDESIDEPUZZLETARGET_OFFSET UNITYSDK_OFFSET(0x16BBBFC0)
#define RPG_CLIENT_FIVEDIMMODULE__ONLEAVEFIVEDIMGAMESCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA080)
#define RPG_CLIENT_FIVEDIMMODULE__ONMAPCREATED_OFFSET UNITYSDK_OFFSET(0x16BBC1B0)
#define RPG_CLIENT_FIVEDIMMODULE__ONSHOWSIDEPUZZLETARGET_OFFSET UNITYSDK_OFFSET(0x16BBBEA0)
#define RPG_CLIENT_FIVEDIMMODULE__ONUPDATEFIVEDIMGAMEDATASCRSP_OFFSET UNITYSDK_OFFSET(0x16BBA390)
#define RPG_CLIENT_FIVEDIMMODULE__ONUPDATESIDEPUZZLETARGET_OFFSET UNITYSDK_OFFSET(0x16BBC010)
#define RPG_CLIENT_FIVEDIMMODULE__REQUESTQUITCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0x16BB43D0)
#define RPG_CLIENT_FIVEDIMMODULE__RESETCHENLINGGAMEBOYINSTANCE_OFFSET UNITYSDK_OFFSET(0x16BB42E0)
#define RPG_CLIENT_FIVEDIMMODULE__SENDMINIGAMEINITREQUEST_OFFSET UNITYSDK_OFFSET(0x16BB6560)
#define RPG_CLIENT_FIVEDIMMODULE__SENDMONEYINITREQUEST_OFFSET UNITYSDK_OFFSET(0x16BB7500)
#define RPG_CLIENT_FIVEDIMMODULE__SETCAMERARECT_OFFSET UNITYSDK_OFFSET(0x16BB4CF0)
#define RPG_CLIENT_FIVEDIMMODULE__SHOWDISPLAYREWARDS_OFFSET UNITYSDK_OFFSET(0x16BB7630)
#define RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_1_OFFSET UNITYSDK_OFFSET(0x16BB8B60)
#define RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_2_OFFSET UNITYSDK_OFFSET(0x16BB8BE0)
#define RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_3_OFFSET UNITYSDK_OFFSET(0x16BB8CF0)
#define RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_4_OFFSET UNITYSDK_OFFSET(0x16BBAAD0)
#define RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_OFFSET UNITYSDK_OFFSET(0x16BBA930)
#define RPG_CLIENT_FIVEDIMMODULE__TRYUPDATECLIENTPOSVERSION_OFFSET UNITYSDK_OFFSET(0x16BB9B30)
#define RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY_DISPOSE_OFFSET UNITYSDK_OFFSET(0x16BBCD90)
#define RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY_INIT_OFFSET UNITYSDK_OFFSET(0x16BBCD10)
#define RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY__ADDNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0x16BBCDA0)
#define RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0x16BBCCB0)

namespace RPG::Client
{
	inline static constexpr unsigned int FiveDimModule_TypeDefinitionIndex = 60004;

	class FiveDimModule : public ::RPG::Client::BaseModule
	{
	public:
		// static const ::System::UInt32 INVALID_FLUTE_ID = 0x0; // 0x0
		// static const ::System::UInt32 _EMPTY_REWARD_ID = 0x64; // 0x0
		// static const ::System::String* MiniGameSetResultDialogPath; // 0x0
		// static const ::System::UInt32 _FUNC_ENTRANCE_LIST_ID = 0x17; // 0x0
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPuzzleData*>* _ChenLingGameBoyPuzzleDataDir; // 0x10
		::RPG::Client::LittleGame::FiveDim::SidePuzzleTargetData* _SidePuzzleTargetData_k__BackingField; // 0x18
		::RPG::Client::Promises::Promise_1<::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPlayerRankingListInfo*>* _FetchFriendRankingInfoPromise; // 0x20
		::System::Action_1<::System::Boolean>* OnMoneyWeeklyLimitReached; // 0x28
		::Class_3_07C3C4D2990C49EE* _ReachMaxTimeLimitSequence; // 0x30
		::Class_3_07C3C4D2990C49EE* _ExitChenLingGameSequence; // 0x38
		::Class_3_07C3C4D2990C49EE* _EnterChenLingGameSequence; // 0x40
		::System::Action_1<::Class_1_D17272E82AE804C2_337*>* OnFiveDimGameTransferScRsp; // 0x48
		::System::Collections::Generic::HashSet_1<::System::UInt32>* ValidTeleportFluteIDs; // 0x50
		::System::Collections::Generic::HashSet_1<::System::UInt32>* FinishedFluteIDs; // 0x58
		::System::String* GameSerialNumber; // 0x60
		::System::Action_1<::Class_1_D17272E82AE804C2_335*>* OnLeaveFiveDimGameScRsp; // 0x68
		::System::Action_1<::Class_1_D17272E82AE804C2_334*>* OnEnterFiveDimGameScRsp; // 0x70
		::RPG::Client::UIFrameCapture* _FrameCapture; // 0x78
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _MiniGameHighScores; // 0x80
		::RPG::Client::LittleGame::FiveDim::FiveDimFluteDataManager* FluteDataManager; // 0x88
		::RPG::GameCore::FiveDimGameConfig* _GameConfig; // 0x90
		::UnityEngine::Texture* _SettlementTexture; // 0x98
		::Class_3_07C3C4D2990C49EE* _ExitSequence; // 0xA0
		::RPG::Client::FiveDimGameInstance* _CurrentGameInstance_k__BackingField; // 0xA8
		::Class_1_43BD383C98B4C0C5_149* _PuzzleData_k__BackingField; // 0xB0
		::System::Nullable_1<::Struct_2_FC595D1A561D8C6F> _PendingPlayer3DInfo_k__BackingField; // 0xB8
		::RPG::Client::FiveDimTransitionStatus TransitionStatus; // 0xD8
		::System::UInt32 _MaxJumpEnergy; // 0xDC
		::RPG::Client::FiveDimModule_OverridableVariable_1<::RPG::GameCore::FiveDimAvatarMoveAbility> _MoveAbility; // 0xE0
		::System::UInt32 _MoneyWeeklyNum_k__BackingField; // 0xEC
		::System::Single _CaptureFrameRadio; // 0xF0
		::System::UInt32 _InputJoyStickType; // 0xF4
		::System::Nullable_1<::Struct_2_F01DF3CDCF3FD7AC> _PendingServerPlayer2DInfo_k__BackingField; // 0xF8
		::System::UInt32 _FiveDimInputID; // 0x128
		::System::Int32 _TimerIndex; // 0x12C
		::Struct_2_F01DF3CDCF3FD7AC _CurrentPlayer2DInfo_k__BackingField; // 0x130
		::Struct_2_F01DF3CDCF3FD7AC _PendingPlayer2DInfo_k__BackingField; // 0x15C
		::System::UInt32 _RewardShowCount; // 0x188
		::System::UInt32 CurrentActiveFluteID; // 0x18C
		::System::Boolean IncontrolUseDeadZoneValue; // 0x190
		::System::Boolean _IsMoneyWeeklyLimitReached_k__BackingField; // 0x191
		::System::Boolean _FiveDimJoyStickDebugShow; // 0x192

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__CTOR_OFFSET))(this);
		}

		::RPG::Client::Promises::IPromise* EnterChenLingGameBoy(::System::UInt32 a1, ::Class_3_07C3C4D2990C49EE* a2, ::Class_3_07C3C4D2990C49EE* a3, ::Class_3_07C3C4D2990C49EE* a4, ::Class_3_07C3C4D2990C49EE* a5, ::RPG::GameCore::GameEntity* a6, ::UnityEngine::Transform* a7, ::UnityEngine::Transform* a8)
		{
			return ((::RPG::Client::Promises::IPromise*(*)(::PVOID, ::System::UInt32, ::Class_3_07C3C4D2990C49EE*, ::Class_3_07C3C4D2990C49EE*, ::Class_3_07C3C4D2990C49EE*, ::Class_3_07C3C4D2990C49EE*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Transform*, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ENTERCHENLINGGAMEBOY_OFFSET))(this, a1, a2, a3, a4, a5, a6, a7, a8);
		}

		::System::Void RequireChenLingGameBoyData(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUIRECHENLINGGAMEBOYDATA_OFFSET))(this, a1);
		}

		::System::Void RequestNetworkFinishChenLingGameBoy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTNETWORKFINISHCHENLINGGAMEBOY_OFFSET))(this);
		}

		::RPG::Client::Promises::IPromise_1<::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPlayerRankingListInfo*>* FetchPlayersRankingInfo(::System::UInt32 a1)
		{
			return ((::RPG::Client::Promises::IPromise_1<::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPlayerRankingListInfo*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERSRANKINGINFO_OFFSET))(this, a1);
		}

		::System::Void EnterChenLingGameBoyInstance(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ENTERCHENLINGGAMEBOYINSTANCE_OFFSET))(this, a1);
		}

		::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPuzzleData* GetChenLingGameBoyPuzzleData(::System::UInt32 a1)
		{
			return ((::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPuzzleData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETCHENLINGGAMEBOYPUZZLEDATA_OFFSET))(this, a1);
		}

		::System::Void ResetChenLingGameBoyInstance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_RESETCHENLINGGAMEBOYINSTANCE_OFFSET))(this);
		}

		::System::Void ExitChenLingGameBoyInstance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_EXITCHENLINGGAMEBOYINSTANCE_OFFSET))(this);
		}

		::System::Void LeaveChenLingGameBoyInstance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_LEAVECHENLINGGAMEBOYINSTANCE_OFFSET))(this);
		}

		::System::Void OnExitChenLingGameBoyGameEntrance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ONEXITCHENLINGGAMEBOYGAMEENTRANCE_OFFSET))(this);
		}

		::System::Void SetChenLingGameBoyTimePaused(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SETCHENLINGGAMEBOYTIMEPAUSED_OFFSET))(this, a1);
		}

		::System::Void InvokeReachMaxTimeLimitSequence()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_INVOKEREACHMAXTIMELIMITSEQUENCE_OFFSET))(this);
		}

		::System::Void ChenLingCaptureFrame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_CHENLINGCAPTUREFRAME_OFFSET))(this);
		}

		::UnityEngine::Rect _GetScreenRect()
		{
			return ((::UnityEngine::Rect(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__GETSCREENRECT_OFFSET))(this);
		}

		::System::Void _SetCameraRect(::UnityEngine::Camera* a1, ::UnityEngine::Rect a2)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Camera*, ::UnityEngine::Rect))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__SETCAMERARECT_OFFSET))(this, a1, a2);
		}

		::UnityEngine::Texture* GetSettlementTexture()
		{
			return ((::UnityEngine::Texture*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETSETTLEMENTTEXTURE_OFFSET))(this);
		}

		::System::Void ReleaseFrame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_RELEASEFRAME_OFFSET))(this);
		}

		::System::Void _LeaveChenLingGameBoyInstance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__LEAVECHENLINGGAMEBOYINSTANCE_OFFSET))(this);
		}

		::System::Void _RequestQuitChenLingGameBoy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__REQUESTQUITCHENLINGGAMEBOY_OFFSET))(this);
		}

		::System::Void _ResetChenLingGameBoyInstance()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__RESETCHENLINGGAMEBOYINSTANCE_OFFSET))(this);
		}

		::System::Void _ExecuteEnterGameSequence()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__EXECUTEENTERGAMESEQUENCE_OFFSET))(this);
		}

		::System::Void _ExecuteExitGameSequence()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__EXECUTEEXITGAMESEQUENCE_OFFSET))(this);
		}

		::System::Boolean get_IsInChenLingGameBoy()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_ISINCHENLINGGAMEBOY_OFFSET))(this);
		}

		::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPuzzleData* get_ChenLingGameBoyPuzzleData()
		{
			return ((::RPG::Client::ChenLingGameBoy::ChenLingGameBoyPuzzleData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_CHENLINGGAMEBOYPUZZLEDATA_OFFSET))(this);
		}

		::System::Boolean IsFluteValid(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ISFLUTEVALID_OFFSET))(this, a1);
		}

		::System::Boolean IsFluteFinished(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ISFLUTEFINISHED_OFFSET))(this, a1);
		}

		::System::Void SetCurrentActiveFluteID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SETCURRENTACTIVEFLUTEID_OFFSET))(this, a1);
		}

		::System::Boolean IsFluteButtonEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ISFLUTEBUTTONENABLE_OFFSET))(this);
		}

		::System::Void FinishFlute(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FINISHFLUTE_OFFSET))(this, a1);
		}

		::System::Void ApplyFlute(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_APPLYFLUTE_OFFSET))(this, a1);
		}

		::System::Void ApplyFluteWithSwitchLine(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_APPLYFLUTEWITHSWITCHLINE_OFFSET))(this, a1);
		}

		::System::Boolean IsFluteApplied(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ISFLUTEAPPLIED_OFFSET))(this, a1);
		}

		::System::Void _OnGetFiveDimFluteDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMFLUTEDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFiveDimFluteDataChangeNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMFLUTEDATACHANGENOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void FinishFiveDimMiniGame(::System::UInt32 a1, ::System::String* a2, ::Struct_2_D80CFC559D4BCFA6& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::String*, ::Struct_2_D80CFC559D4BCFA6&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FINISHFIVEDIMMINIGAME_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _AddMiniGamePackedHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ADDMINIGAMEPACKEDHANDLERS_OFFSET))(this);
		}

		::System::Void _OnFinishFiveDimMiniGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFINISHFIVEDIMMINIGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _SendMiniGameInitRequest()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__SENDMINIGAMEINITREQUEST_OFFSET))(this);
		}

		::System::Void _OnGetFiveDimMiniGameDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMINIGAMEDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::UInt32 GetMiniGameID(::RPG::GameCore::FiveDimGameplayMode a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::RPG::GameCore::FiveDimGameplayMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEID_OFFSET))(this, a1);
		}

		::System::UInt32 GetMiniGameHighScore(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEHIGHSCORE_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* GetMiniGameScoreTargets(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMESCORETARGETS_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* GetMiniGameOneTimeRewards(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEONETIMEREWARDS_OFFSET))(this, a1, a2);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* GetMiniGameOneTimeRewards_1(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEONETIMEREWARDS_1_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* GetMiniGamePreviewRewards()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GETMINIGAMEPREVIEWREWARDS_OFFSET))(this);
		}

		::System::Void RecoverMiniGameFCV()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_RECOVERMINIGAMEFCV_OFFSET))(this);
		}

		::System::Void add_OnMoneyWeeklyLimitReached(::System::Action_1<::System::Boolean>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Boolean>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ADD_ONMONEYWEEKLYLIMITREACHED_OFFSET))(this, a1);
		}

		::System::Void remove_OnMoneyWeeklyLimitReached(::System::Action_1<::System::Boolean>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Boolean>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REMOVE_ONMONEYWEEKLYLIMITREACHED_OFFSET))(this, a1);
		}

		::System::Void RequestAddMoney(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTADDMONEY_OFFSET))(this, a1);
		}

		::System::Void _SendMoneyInitRequest()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__SENDMONEYINITREQUEST_OFFSET))(this);
		}

		::System::Void _OnGetFiveDimMoneyScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMONEYSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGetFiveDimMoneyDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMMONEYDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFiveDimMoneyChangeScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMMONEYCHANGESCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void NotifyDisplayRewards(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_NOTIFYDISPLAYREWARDS_OFFSET))(this, a1);
		}

		::System::Void _ShowDisplayRewards(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__SHOWDISPLAYREWARDS_OFFSET))(this, a1);
		}

		::System::Void _NotifyDisplayRewards()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__NOTIFYDISPLAYREWARDS_OFFSET))(this);
		}

		::System::UInt32 get_MoneyNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MONEYNUM_OFFSET))(this);
		}

		::System::Void set_MoneyNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_MONEYNUM_OFFSET))(this, a1);
		}

		::System::UInt32 get_MoneyWeeklyNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MONEYWEEKLYNUM_OFFSET))(this);
		}

		::System::Void set_MoneyWeeklyNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_MONEYWEEKLYNUM_OFFSET))(this, a1);
		}

		::System::Boolean get_IsMoneyWeeklyLimitReached()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_ISMONEYWEEKLYLIMITREACHED_OFFSET))(this);
		}

		::System::Void set_IsMoneyWeeklyLimitReached(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_ISMONEYWEEKLYLIMITREACHED_OFFSET))(this, a1);
		}

		::System::UInt32 get_MoneyItemID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MONEYITEMID_OFFSET))(this);
		}

		::System::UInt32 get_MoneyWeeklyLimit()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MONEYWEEKLYLIMIT_OFFSET))(this);
		}

		::System::Void _AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void RequestEnterGame(::Struct_2_F01DF3CDCF3FD7AC a1, ::Struct_2_FC595D1A561D8C6F a2)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_F01DF3CDCF3FD7AC, ::Struct_2_FC595D1A561D8C6F))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTENTERGAME_OFFSET))(this, a1, a2);
		}

		::System::Void RequestGameData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTGAMEDATA_OFFSET))(this);
		}

		::System::Void RequestLeaveGame(::Struct_2_FC595D1A561D8C6F a1, ::RPG::Client::LittleGame::FiveDim::FiveDimExitType a2, ::System::UInt32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_FC595D1A561D8C6F, ::RPG::Client::LittleGame::FiveDim::FiveDimExitType, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTLEAVEGAME_OFFSET))(this, a1, a2, a3);
		}

		::Enum_3_0A3761FE34514D6C_36 ExitTypeToNetworkLeaveType(::RPG::Client::LittleGame::FiveDim::FiveDimExitType a1)
		{
			return ((::Enum_3_0A3761FE34514D6C_36(*)(::PVOID, ::RPG::Client::LittleGame::FiveDim::FiveDimExitType))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_EXITTYPETONETWORKLEAVETYPE_OFFSET))(this, a1);
		}

		::System::Void RequestUpdateTwoDimPlayerInfo(::Struct_2_F01DF3CDCF3FD7AC a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTUPDATETWODIMPLAYERINFO_OFFSET))(this, a1);
		}

		::System::Void RequestUpdatePlayerExtraAbility(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTUPDATEPLAYEREXTRAABILITY_OFFSET))(this, a1);
		}

		::System::Void SendChenLingGameBoyChangeSettingsCsReq(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGGAMEBOYCHANGESETTINGSCSREQ_OFFSET))(this, a1);
		}

		::System::Void RequestTransfer(::Struct_2_F01DF3CDCF3FD7AC a1, ::RPG::Client::LittleGame::FiveDim::FiveDimExitType a2, ::System::UInt32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_F01DF3CDCF3FD7AC, ::RPG::Client::LittleGame::FiveDim::FiveDimExitType, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_REQUESTTRANSFER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SendChenLingCheatInputKeyReq(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGCHEATINPUTKEYREQ_OFFSET))(this, a1);
		}

		::System::Void SendChenLingCheatModeReq(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SENDCHENLINGCHEATMODEREQ_OFFSET))(this, a1, a2);
		}

		::System::Void ClearNetworkData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_CLEARNETWORKDATA_OFFSET))(this);
		}

		::System::Void _OnEnterFiveDimGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONENTERFIVEDIMGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFiveDimGameDataUpdateScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMGAMEDATAUPDATESCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFiveDimGameTransferScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMGAMETRANSFERSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnLeaveFiveDimGameScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONLEAVEFIVEDIMGAMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnUpdateFiveDimGameDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONUPDATEFIVEDIMGAMEDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGetChenLingGameBoyDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETCHENLINGGAMEBOYDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnChenLingGameBoyGetFriendRankingInfoScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONCHENLINGGAMEBOYGETFRIENDRANKINGINFOSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFinishChenLingGameBoyScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFINISHCHENLINGGAMEBOYSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGetFiveDimGameDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONGETFIVEDIMGAMEDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnFiveDimJumpEnergyChangeScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMJUMPENERGYCHANGESCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _TryUpdateClientPosVersion(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TRYUPDATECLIENTPOSVERSION_OFFSET))(this, a1);
		}

		static ::System::Void _ToNetworkData(::Class_1_F91AD0C5A85E4AFA_9* a1, ::Struct_2_F01DF3CDCF3FD7AC a2)
		{
			return ((::System::Void(*)(::Class_1_F91AD0C5A85E4AFA_9*, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_OFFSET))(a1, a2);
		}

		static ::System::Void _ToNetworkData_1(::Class_1_D17272E82AE804C2_333* a1, ::Struct_2_F01DF3CDCF3FD7AC a2)
		{
			return ((::System::Void(*)(::Class_1_D17272E82AE804C2_333*, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_1_OFFSET))(a1, a2);
		}

		static ::System::Void _ToNetworkData_2(::Class_1_A810E08D2BDEB9C4* a1, ::Struct_2_F01DF3CDCF3FD7AC a2)
		{
			return ((::System::Void(*)(::Class_1_A810E08D2BDEB9C4*, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_2_OFFSET))(a1, a2);
		}

		static ::System::Void _ToNetworkData_3(::Class_1_20D743894CDF214D_1* a1, ::UnityEngine::Vector3 a2, ::UnityEngine::Quaternion a3)
		{
			return ((::System::Void(*)(::Class_1_20D743894CDF214D_1*, ::UnityEngine::Vector3, ::UnityEngine::Quaternion))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_3_OFFSET))(a1, a2, a3);
		}

		static ::System::Void _ToNetworkData_4(::Class_1_76FC7D9EAE4C806C* a1, ::UnityEngine::Vector3 a2)
		{
			return ((::System::Void(*)(::Class_1_76FC7D9EAE4C806C*, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__TONETWORKDATA_4_OFFSET))(a1, a2);
		}

		static ::Struct_2_F01DF3CDCF3FD7AC _FromNetworkData(::Class_1_F91AD0C5A85E4AFA_9* a1)
		{
			return ((::Struct_2_F01DF3CDCF3FD7AC(*)(::Class_1_F91AD0C5A85E4AFA_9*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__FROMNETWORKDATA_OFFSET))(a1);
		}

		static ::UnityEngine::Vector3 _FromProtoPosition(::Class_1_76FC7D9EAE4C806C* a1)
		{
			return ((::UnityEngine::Vector3(*)(::Class_1_76FC7D9EAE4C806C*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__FROMPROTOPOSITION_OFFSET))(a1);
		}

		static ::UnityEngine::Quaternion _FromProtoRotation(::Class_1_76FC7D9EAE4C806C* a1)
		{
			return ((::UnityEngine::Quaternion(*)(::Class_1_76FC7D9EAE4C806C*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__FROMPROTOROTATION_OFFSET))(a1);
		}

		::Struct_2_F01DF3CDCF3FD7AC get_CurrentPlayer2DInfo()
		{
			return ((::Struct_2_F01DF3CDCF3FD7AC(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_CURRENTPLAYER2DINFO_OFFSET))(this);
		}

		::System::Void set_CurrentPlayer2DInfo(::Struct_2_F01DF3CDCF3FD7AC a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_CURRENTPLAYER2DINFO_OFFSET))(this, a1);
		}

		::Struct_2_F01DF3CDCF3FD7AC get_PendingPlayer2DInfo()
		{
			return ((::Struct_2_F01DF3CDCF3FD7AC(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGPLAYER2DINFO_OFFSET))(this);
		}

		::System::Void set_PendingPlayer2DInfo(::Struct_2_F01DF3CDCF3FD7AC a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_F01DF3CDCF3FD7AC))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGPLAYER2DINFO_OFFSET))(this, a1);
		}

		::System::Nullable_1<::Struct_2_F01DF3CDCF3FD7AC> get_PendingServerPlayer2DInfo()
		{
			return ((::System::Nullable_1<::Struct_2_F01DF3CDCF3FD7AC>(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGSERVERPLAYER2DINFO_OFFSET))(this);
		}

		::System::Void set_PendingServerPlayer2DInfo(::System::Nullable_1<::Struct_2_F01DF3CDCF3FD7AC> a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Nullable_1<::Struct_2_F01DF3CDCF3FD7AC>))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGSERVERPLAYER2DINFO_OFFSET))(this, a1);
		}

		::System::Nullable_1<::Struct_2_FC595D1A561D8C6F> get_PendingPlayer3DInfo()
		{
			return ((::System::Nullable_1<::Struct_2_FC595D1A561D8C6F>(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_PENDINGPLAYER3DINFO_OFFSET))(this);
		}

		::System::Void set_PendingPlayer3DInfo(::System::Nullable_1<::Struct_2_FC595D1A561D8C6F> a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Nullable_1<::Struct_2_FC595D1A561D8C6F>))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_PENDINGPLAYER3DINFO_OFFSET))(this, a1);
		}

		::Class_1_43BD383C98B4C0C5_149* get_PuzzleData()
		{
			return ((::Class_1_43BD383C98B4C0C5_149*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_PUZZLEDATA_OFFSET))(this);
		}

		::System::Void set_PuzzleData(::Class_1_43BD383C98B4C0C5_149* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_149*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_PUZZLEDATA_OFFSET))(this, a1);
		}

		::System::Void FetchTrainModeDisplayInfos(::RPG::Client::FiveDimTrainModeDisplayInfos* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimTrainModeDisplayInfos*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FETCHTRAINMODEDISPLAYINFOS_OFFSET))(this, a1);
		}

		::System::Void OpenTransitionView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_OPENTRANSITIONVIEW_OFFSET))(this);
		}

		::System::Void CloseTransitionView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_CLOSETRANSITIONVIEW_OFFSET))(this);
		}

		::System::Void Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_INIT_OFFSET))(this);
		}

		::System::Void SetMoveAbilityEnabled(::RPG::GameCore::FiveDimAvatarMoveAbility a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimAvatarMoveAbility, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SETMOVEABILITYENABLED_OFFSET))(this, a1, a2);
		}

		::System::Void SetPlayerSkillUpgraded(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SETPLAYERSKILLUPGRADED_OFFSET))(this, a1);
		}

		::System::Void SetMaxJumpEnergy(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SETMAXJUMPENERGY_OFFSET))(this, a1);
		}

		::System::Void ExitFiveDimGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_EXITFIVEDIMGAME_OFFSET))(this);
		}

		::System::Void FetchPlayerSkillDisplayInfo(::RPG::Client::FiveDimSkillDisplayInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimSkillDisplayInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERSKILLDISPLAYINFO_OFFSET))(this, a1);
		}

		::System::Void TryAutoShow()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_TRYAUTOSHOW_OFFSET))(this);
		}

		::System::Void FetchPlayerJumpDisplayInfo(::RPG::Client::FiveDimJumpDisplayInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimJumpDisplayInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FETCHPLAYERJUMPDISPLAYINFO_OFFSET))(this, a1);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_DISPOSE_OFFSET))(this);
		}

		::System::Void OnEnterGame(::RPG::Client::FiveDimGameInstance* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimGameInstance*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ONENTERGAME_OFFSET))(this, a1);
		}

		::System::Void OnExitGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_ONEXITGAME_OFFSET))(this);
		}

		::System::Void _AddNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ADDNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _OnShowSidePuzzleTarget(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONSHOWSIDEPUZZLETARGET_OFFSET))(this, a1);
		}

		::System::Void _OnHideSidePuzzleTarget(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONHIDESIDEPUZZLETARGET_OFFSET))(this, a1);
		}

		::System::Void _OnUpdateSidePuzzleTarget(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONUPDATESIDEPUZZLETARGET_OFFSET))(this, a1);
		}

		::System::Void _OnAdventurePhaseEnd(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONADVENTUREPHASEEND_OFFSET))(this, a1);
		}

		::System::Void _OnFiveDimOnMainPageReturnTop(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONFIVEDIMONMAINPAGERETURNTOP_OFFSET))(this, a1);
		}

		::System::Void _OnMapCreated(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__ONMAPCREATED_OFFSET))(this, a1);
		}

		::System::Void _InitGameConfig()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__INITGAMECONFIG_OFFSET))(this);
		}

		::System::Void _LoadGameConfig()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__LOADGAMECONFIG_OFFSET))(this);
		}

		::RPG::Client::LittleWheelSelectConfig* _CreateLittleWheelSelectConfig()
		{
			return ((::RPG::Client::LittleWheelSelectConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE__CREATELITTLEWHEELSELECTCONFIG_OFFSET))(this);
		}

		::System::Void FinishFiveDimAchievement(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_FINISHFIVEDIMACHIEVEMENT_OFFSET))(this, a1);
		}

		::RPG::Client::FiveDimGameInstance* get_CurrentGameInstance()
		{
			return ((::RPG::Client::FiveDimGameInstance*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_CURRENTGAMEINSTANCE_OFFSET))(this);
		}

		::System::Void set_CurrentGameInstance(::RPG::Client::FiveDimGameInstance* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimGameInstance*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_CURRENTGAMEINSTANCE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsInFiveDimGame()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_ISINFIVEDIMGAME_OFFSET))(this);
		}

		::System::Boolean get_PlayerSkillUpgraded()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_PLAYERSKILLUPGRADED_OFFSET))(this);
		}

		::System::UInt32 get_MaxJumpEnergy()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MAXJUMPENERGY_OFFSET))(this);
		}

		::System::Boolean get_CanUseCameraObserve()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_CANUSECAMERAOBSERVE_OFFSET))(this);
		}

		::System::UInt32 get_GameDifficulty()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_GAMEDIFFICULTY_OFFSET))(this);
		}

		::RPG::GameCore::FiveDimLevelSettings* get_GameLevelConfig()
		{
			return ((::RPG::GameCore::FiveDimLevelSettings*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_GAMELEVELCONFIG_OFFSET))(this);
		}

		::System::UInt32 get_SkillPanelConfigID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_SKILLPANELCONFIGID_OFFSET))(this);
		}

		::RPG::GameCore::FiveDimMoveConfig* get_MoveConfig()
		{
			return ((::RPG::GameCore::FiveDimMoveConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MOVECONFIG_OFFSET))(this);
		}

		::System::Single get_MoveInputDeadZone()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MOVEINPUTDEADZONE_OFFSET))(this);
		}

		::System::Boolean get_ShouldReverseInputDeadZone()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_SHOULDREVERSEINPUTDEADZONE_OFFSET))(this);
		}

		::System::Single get_InWallReverseInputCD()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_INWALLREVERSEINPUTCD_OFFSET))(this);
		}

		::System::Single get_OutWallReverseInputCD()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_OUTWALLREVERSEINPUTCD_OFFSET))(this);
		}

		::System::Single get_MoveInputHorizontalAngle()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_MOVEINPUTHORIZONTALANGLE_OFFSET))(this);
		}

		static ::RPG::Client::FiveDimModule* get_Instance()
		{
			return ((::RPG::Client::FiveDimModule*(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_INSTANCE_OFFSET))();
		}

		::System::UInt32 get__DefaultSkillPanelConfigID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET__DEFAULTSKILLPANELCONFIGID_OFFSET))(this);
		}

		::System::UInt32 get_InputJoyStickType()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_INPUTJOYSTICKTYPE_OFFSET))(this);
		}

		::System::Void set_InputJoyStickType(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_INPUTJOYSTICKTYPE_OFFSET))(this, a1);
		}

		::System::Boolean get_UseDirectionBtn()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_USEDIRECTIONBTN_OFFSET))(this);
		}

		::RPG::Client::LittleGame::FiveDim::SidePuzzleTargetData* get_SidePuzzleTargetData()
		{
			return ((::RPG::Client::LittleGame::FiveDim::SidePuzzleTargetData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_SIDEPUZZLETARGETDATA_OFFSET))(this);
		}

		::System::Void set_SidePuzzleTargetData(::RPG::Client::LittleGame::FiveDim::SidePuzzleTargetData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::LittleGame::FiveDim::SidePuzzleTargetData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_SIDEPUZZLETARGETDATA_OFFSET))(this, a1);
		}

		::System::Boolean get_UsePolarCoordinates()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_USEPOLARCOORDINATES_OFFSET))(this);
		}

		::System::Boolean get_FiveDimJoyStickDebugShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_GET_FIVEDIMJOYSTICKDEBUGSHOW_OFFSET))(this);
		}

		::System::Void set_FiveDimJoyStickDebugShow(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE_SET_FIVEDIMJOYSTICKDEBUGSHOW_OFFSET))(this, a1);
		}

		::System::Void __iFixBaseProxy__AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY_INIT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY_DISPOSE_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__AddNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMMODULE___IFIXBASEPROXY__ADDNOTIFYHANDLERS_OFFSET))(this);
		}
	};
}
