#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ActivityPanelData.h"

namespace System { class Object; }

#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_HASREWARDTOTAKE_OFFSET UNITYSDK_OFFSET(0x19562B30)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISFUNCTIONBTNFIRSTNEW_OFFSET UNITYSDK_OFFSET(0x16030A70)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWDAILYREDDOT_OFFSET UNITYSDK_OFFSET(0x160309D0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWGOTOREDDOT_OFFSET UNITYSDK_OFFSET(0x16030320)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNEWREDDOT_OFFSET UNITYSDK_OFFSET(0x16030690)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNEWSEASONBTNNEW_OFFSET UNITYSDK_OFFSET(0x16030420)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x16030280)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWSCOREREDDOTNEW_OFFSET UNITYSDK_OFFSET(0x16030770)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWTRAITQUESTREDDOTNEW_OFFSET UNITYSDK_OFFSET(0x16030910)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_SETFUNCTIONBTNFIRSTSEEN_OFFSET UNITYSDK_OFFSET(0x195628D0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA_SETNEWSEASONBTNSEEN_OFFSET UNITYSDK_OFFSET(0x19562730)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEDIVISIONREWARD_OFFSET UNITYSDK_OFFSET(0x19563420)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEEXPREWARD_OFFSET UNITYSDK_OFFSET(0x19562E10)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEGUIDEBOOKREWARD_OFFSET UNITYSDK_OFFSET(0x195631B0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEHANDBOOKREWARD_OFFSET UNITYSDK_OFFSET(0x19563320)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEQUESTREWARD_OFFSET UNITYSDK_OFFSET(0x19563020)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKETRAITREWARD_OFFSET UNITYSDK_OFFSET(0x19562EE0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEWEEKLYREWARD_OFFSET UNITYSDK_OFFSET(0x195633D0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x16030210)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__HASREWARDTOTAKEEXPLICIT_OFFSET UNITYSDK_OFFSET(0x19562BB0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__HASREWARDTOTAKEIMPLICIT_OFFSET UNITYSDK_OFFSET(0x19562C00)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWNEWWEEKSCOREREDDOT_OFFSET UNITYSDK_OFFSET(0x195629F0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWTAKEREWARDEXPLICITREDDOT_OFFSET UNITYSDK_OFFSET(0x19562CA0)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWTAKEREWARDIMPLICITREDDOT_OFFSET UNITYSDK_OFFSET(0x19562D70)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ONTAKEEXPREWARD_OFFSET UNITYSDK_OFFSET(0x19563560)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA___IFIXBASEPROXY_ISSHOWNEWREDDOT_OFFSET UNITYSDK_OFFSET(0x19563620)
#define RPG_CLIENT_GRIDFIGHTACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x195635C0)

namespace RPG::Client
{
	inline static constexpr unsigned int GridFightActivityData_TypeDefinitionIndex = 57622;

	class GridFightActivityData : public ::RPG::Client::ActivityPanelData
	{
	public:
		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNewRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNEWREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowGoToRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWGOTOREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowDailyRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWDAILYREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNewSeasonBtnNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWNEWSEASONBTNNEW_OFFSET))(this);
		}

		::System::Boolean IsShowScoreRedDotNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWSCOREREDDOTNEW_OFFSET))(this);
		}

		::System::Boolean IsShowTraitQuestRedDotNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISSHOWTRAITQUESTREDDOTNEW_OFFSET))(this);
		}

		::System::Boolean IsFunctionBtnFirstNew()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_ISFUNCTIONBTNFIRSTNEW_OFFSET))(this);
		}

		::System::Void SetNewSeasonBtnSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_SETNEWSEASONBTNSEEN_OFFSET))(this);
		}

		::System::Void SetFunctionBtnFirstSeen(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_SETFUNCTIONBTNFIRSTSEEN_OFFSET))(this, a1);
		}

		::System::Boolean _IsShowNewWeekScoreRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWNEWWEEKSCOREREDDOT_OFFSET))(this);
		}

		static ::System::Boolean HasRewardToTake()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA_HASREWARDTOTAKE_OFFSET))();
		}

		::System::Boolean _IsShowTakeRewardExplicitRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWTAKEREWARDEXPLICITREDDOT_OFFSET))(this);
		}

		::System::Boolean _IsShowTakeRewardImplicitRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ISSHOWTAKEREWARDIMPLICITREDDOT_OFFSET))(this);
		}

		static ::System::Boolean _HasRewardToTakeExplicit()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__HASREWARDTOTAKEEXPLICIT_OFFSET))();
		}

		static ::System::Boolean _HasRewardToTakeImplicit()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__HASREWARDTOTAKEIMPLICIT_OFFSET))();
		}

		static ::System::Boolean _CanTakeQuestReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEQUESTREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeDivisionReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEDIVISIONREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeExpReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEEXPREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeHandbookReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEHANDBOOKREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeTraitReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKETRAITREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeGuideBookReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEGUIDEBOOKREWARD_OFFSET))();
		}

		static ::System::Boolean _CanTakeWeeklyReward()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__CANTAKEWEEKLYREWARD_OFFSET))();
		}

		::System::Void _OnTakeExpReward(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA__ONTAKEEXPREWARD_OFFSET))(this, a1);
		}

		::System::Boolean __iFixBaseProxy_IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowNewRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTACTIVITYDATA___IFIXBASEPROXY_ISSHOWNEWREDDOT_OFFSET))(this);
		}
	};
}
