#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_41E07A9DDAB7FC78.h"
#include "unitysdk/Enum_3_75A5C8C4100A8E33_1.h"

class Class_1_BD3679861BD0C676;
class Class_1_DF43B7EB585E1585;
class Class_1_ECA6A21F0048224D;
class Class_1_FA4F4A67B1C04320_350;
namespace RPG::Client { class GridFightBonusResultData; }
namespace System::Collections::Generic { template <typename T> class IList_1; }

#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_ISCONCERNEDWITH_OFFSET UNITYSDK_OFFSET(0x9335DC0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEADDITEM_OFFSET UNITYSDK_OFFSET(0x9336130)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEADDROLE_OFFSET UNITYSDK_OFFSET(0x9336070)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEBEFORE_OFFSET UNITYSDK_OFFSET(0x9335E10)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATECOIN_OFFSET UNITYSDK_OFFSET(0x9335FA0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEITEM_OFFSET UNITYSDK_OFFSET(0x9335F40)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATELEVELANDEXP_OFFSET UNITYSDK_OFFSET(0x9336000)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEORB_OFFSET UNITYSDK_OFFSET(0x93360D0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATESHOP_OFFSET UNITYSDK_OFFSET(0x9336190)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER__CTOR_OFFSET UNITYSDK_OFFSET(0x93361F0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_ISCONCERNEDWITH_OFFSET UNITYSDK_OFFSET(0x9336200)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEADDITEM_OFFSET UNITYSDK_OFFSET(0x9336510)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEADDROLE_OFFSET UNITYSDK_OFFSET(0x9336430)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEBEFORE_OFFSET UNITYSDK_OFFSET(0x9336270)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATECOIN_OFFSET UNITYSDK_OFFSET(0x9336350)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEITEM_OFFSET UNITYSDK_OFFSET(0x93362E0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATELEVELANDEXP_OFFSET UNITYSDK_OFFSET(0x93363C0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEORB_OFFSET UNITYSDK_OFFSET(0x93364A0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATESHOP_OFFSET UNITYSDK_OFFSET(0x9336580)

namespace RPG::Client
{
	inline static constexpr unsigned int GridFightBonusServerData_EliteBonusSummarizer_TypeDefinitionIndex = 51200;

	class GridFightBonusServerData_EliteBonusSummarizer : public ::Class_1_41E07A9DDAB7FC78
	{
	public:
		::RPG::Client::GridFightBonusResultData* _ResultData; // 0x10

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER__CTOR_OFFSET))(this);
		}

		::System::Boolean IsConcernedWith(::Enum_3_75A5C8C4100A8E33_1 srcType)
		{
			return ((::System::Boolean(*)(::PVOID, ::Enum_3_75A5C8C4100A8E33_1))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_ISCONCERNEDWITH_OFFSET))(this, srcType);
		}

		::System::Void UpdateBefore(::Enum_3_75A5C8C4100A8E33_1 srcType, ::System::Collections::Generic::IList_1<::System::UInt32>* srcParamList)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_75A5C8C4100A8E33_1, ::System::Collections::Generic::IList_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEBEFORE_OFFSET))(this, srcType, srcParamList);
		}

		::System::Void UpdateItem(::Class_1_ECA6A21F0048224D* itemUpdate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ECA6A21F0048224D*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEITEM_OFFSET))(this, itemUpdate);
		}

		::System::Void UpdateCoin(::System::UInt32 coin)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATECOIN_OFFSET))(this, coin);
		}

		::System::Void UpdateLevelAndExp(::System::UInt32 level, ::System::UInt32 exp)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATELEVELANDEXP_OFFSET))(this, level, exp);
		}

		::System::Void UpdateAddRole(::Class_1_BD3679861BD0C676* role)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BD3679861BD0C676*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEADDROLE_OFFSET))(this, role);
		}

		::System::Void UpdateOrb(::Class_1_FA4F4A67B1C04320_350* orbUpdate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FA4F4A67B1C04320_350*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEORB_OFFSET))(this, orbUpdate);
		}

		::System::Void UpdateAddItem(::Class_1_ECA6A21F0048224D* itemUpdate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ECA6A21F0048224D*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATEADDITEM_OFFSET))(this, itemUpdate);
		}

		::System::Void UpdateShop(::Class_1_DF43B7EB585E1585* shopUpdate)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_DF43B7EB585E1585*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER_UPDATESHOP_OFFSET))(this, shopUpdate);
		}

		::System::Boolean __iFixBaseProxy_IsConcernedWith(::Enum_3_75A5C8C4100A8E33_1 P0)
		{
			return ((::System::Boolean(*)(::PVOID, ::Enum_3_75A5C8C4100A8E33_1))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_ISCONCERNEDWITH_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateBefore(::Enum_3_75A5C8C4100A8E33_1 P0, ::System::Collections::Generic::IList_1<::System::UInt32>* P1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_75A5C8C4100A8E33_1, ::System::Collections::Generic::IList_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEBEFORE_OFFSET))(this, P0, P1);
		}

		::System::Void __iFixBaseProxy_UpdateItem(::Class_1_ECA6A21F0048224D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ECA6A21F0048224D*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEITEM_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateCoin(::System::UInt32 P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATECOIN_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateLevelAndExp(::System::UInt32 P0, ::System::UInt32 P1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATELEVELANDEXP_OFFSET))(this, P0, P1);
		}

		::System::Void __iFixBaseProxy_UpdateAddRole(::Class_1_BD3679861BD0C676* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BD3679861BD0C676*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEADDROLE_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateOrb(::Class_1_FA4F4A67B1C04320_350* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FA4F4A67B1C04320_350*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEORB_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateAddItem(::Class_1_ECA6A21F0048224D* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ECA6A21F0048224D*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATEADDITEM_OFFSET))(this, P0);
		}

		::System::Void __iFixBaseProxy_UpdateShop(::Class_1_DF43B7EB585E1585* P0)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_DF43B7EB585E1585*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_ELITEBONUSSUMMARIZER___IFIXBASEPROXY_UPDATESHOP_OFFSET))(this, P0);
		}
	};
}
