#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TABehaviorBase.h"
#include "unitysdk/UnityEngine/Vector3.h"

namespace RPG::Client { class MonoEffectRandomRotation; }

#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET UNITYSDK_OFFSET(0x9CF3680)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET UNITYSDK_OFFSET(0x9CF2D50)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET UNITYSDK_OFFSET(0x9CF2DB0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET UNITYSDK_OFFSET(0x9CF2E10)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET UNITYSDK_OFFSET(0x9CF2E70)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET UNITYSDK_OFFSET(0x9CF2CF0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_1_OFFSET UNITYSDK_OFFSET(0x9CF3730)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_2_OFFSET UNITYSDK_OFFSET(0x9CF3790)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_3_OFFSET UNITYSDK_OFFSET(0x9CF37F0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_4_OFFSET UNITYSDK_OFFSET(0x9CF3850)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_5_OFFSET UNITYSDK_OFFSET(0x9CF38C0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_OFFSET UNITYSDK_OFFSET(0x9CF36D0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET UNITYSDK_OFFSET(0x9CF2450)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_E69AA2E64A20143D_OFFSET UNITYSDK_OFFSET(0x9CF2F30)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_E7EF6BC52B28648C_OFFSET UNITYSDK_OFFSET(0x9CF24F0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_TICK_OFFSET UNITYSDK_OFFSET(0x9CF2ED0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR__CTOR_OFFSET UNITYSDK_OFFSET(0x9CF36C0)
#define RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR___IFIXBASEPROXY_TICK_OFFSET UNITYSDK_OFFSET(0x9CF3930)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectRandomRotationContorlBehaviorlBehavior_TypeDefinitionIndex = 57611;

	class MonoEffectRandomRotationContorlBehaviorlBehavior : public ::RPG::Client::TABehaviorBase
	{
	public:
		::UnityEngine::Vector3 RotateSpeed; // 0x38
		::System::Single RandomX; // 0x44
		::System::Single RandomY; // 0x48
		::System::Single RandomZ; // 0x4C
		::UnityEngine::Vector3 AxisX; // 0x50
		::UnityEngine::Vector3 AxisY; // 0x5C
		::UnityEngine::Vector3 AxisZ; // 0x68

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR__CTOR_OFFSET))(this);
		}

		::System::Void Method_3_9681042564541CD6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_TICK_OFFSET))(this, a1);
		}

		::System::Void Method_3_E7EF6BC52B28648C()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_E7EF6BC52B28648C_OFFSET))(this);
		}

		::System::Void Method_3_E69AA2E64A20143D()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_E69AA2E64A20143D_OFFSET))(this);
		}

		::RPG::Client::MonoEffectRandomRotation* get__OwnerMonoPlugin()
		{
			return ((::RPG::Client::MonoEffectRandomRotation*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_1_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_2_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_3_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_4_OFFSET))(this);
		}

		::System::Void Method_3_5790A55946AA509D_5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR_METHOD_3_5790A55946AA509D_5_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Tick(::System::Single P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTRANDOMROTATIONCONTORLBEHAVIORLBEHAVIOR___IFIXBASEPROXY_TICK_OFFSET))(this, P0);
		}
	};
}
