#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/MonoEffectPluginBase.h"

class Class_2_7F95A4F14F646B44;
namespace RPG::Client { class MatTexItem; }

#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x9809E20)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x980A030)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DISABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0x9809F70)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DISPOSEPLUGIN_OFFSET UNITYSDK_OFFSET(0x9809FB0)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_ENABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0x9809F30)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_IGNOREINEDITOR_OFFSET UNITYSDK_OFFSET(0x9809DE0)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_RESETPLUGIN_OFFSET UNITYSDK_OFFSET(0x9809EE0)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON__CTOR_OFFSET UNITYSDK_OFFSET(0x980A0C0)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x980A140)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x980A260)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_DISABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0x980A200)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_ENABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0x980A1A0)
#define RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_IGNOREINEDITOR_OFFSET UNITYSDK_OFFSET(0x980A0D0)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectPluginTargetHeadIcon_TypeDefinitionIndex = 55817;

	class MonoEffectPluginTargetHeadIcon : public ::RPG::Client::MonoEffectPluginBase
	{
	public:
		::Il2CppArray<::RPG::Client::MatTexItem*>* MatTexMapping; // 0x28
		::Class_2_7F95A4F14F646B44* Field_6_1; // 0x30

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON__CTOR_OFFSET))(this);
		}

		::System::Boolean IgnoreInEditor()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_IGNOREINEDITOR_OFFSET))(this);
		}

		::System::Void AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void ResetPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_RESETPLUGIN_OFFSET))(this);
		}

		::System::Void EnablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_ENABLEPLUGIN_OFFSET))(this);
		}

		::System::Void DisablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DISABLEPLUGIN_OFFSET))(this);
		}

		::System::Void DisposePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DISPOSEPLUGIN_OFFSET))(this);
		}

		::System::Void DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IgnoreInEditor()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_IGNOREINEDITOR_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_EnablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_ENABLEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_DisablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_DISABLEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINTARGETHEADICON___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET))(this);
		}
	};
}
