#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/MonoEffectPluginBase.h"

class Class_2_A9D6E9C3BFC6E74E;
namespace RPG::Client { class DelayEnableGameObject; }

#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3D980)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3DA60)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_DISPOSEPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3DBA0)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_IGNOREINEDITOR_OFFSET UNITYSDK_OFFSET(0x15A3D940)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_RESETPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3DB40)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_TICK_OFFSET UNITYSDK_OFFSET(0x15A3DBE0)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN__CTOR_OFFSET UNITYSDK_OFFSET(0x15A3DC50)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3DCA0)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x15A3DCE0)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_IGNOREINEDITOR_OFFSET UNITYSDK_OFFSET(0x15A3DC60)
#define RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_TICK_OFFSET UNITYSDK_OFFSET(0x15A3DD20)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectPluginDelayEnableChildren_TypeDefinitionIndex = 65500;

	class MonoEffectPluginDelayEnableChildren : public ::RPG::Client::MonoEffectPluginBase
	{
	public:
		::Il2CppArray<::RPG::Client::DelayEnableGameObject*>* Targets; // 0x28
		::Class_2_A9D6E9C3BFC6E74E* Field_6_1; // 0x30

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN__CTOR_OFFSET))(this);
		}

		::System::Boolean IgnoreInEditor()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_IGNOREINEDITOR_OFFSET))(this);
		}

		::System::Void AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Void ResetPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_RESETPLUGIN_OFFSET))(this);
		}

		::System::Void DisposePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_DISPOSEPLUGIN_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN_TICK_OFFSET))(this, a1);
		}

		::System::Boolean __iFixBaseProxy_IgnoreInEditor()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_IGNOREINEDITOR_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINDELAYENABLECHILDREN___IFIXBASEPROXY_TICK_OFFSET))(this, a1);
		}
	};
}
