#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_2_D8BF172965D3ACFC_CharaProp.h"
#include "unitysdk/Class_2_D8BF172965D3ACFC_FaceProp.h"
#include "unitysdk/Class_2_D8BF172965D3ACFC_HairProp.h"
#include "unitysdk/Class_2_D8BF172965D3ACFC_OtherProp.h"
#include "unitysdk/RPG/Client/MonoEffectPluginCharaOverlayMatBase.h"

class Class_2_D8BF172965D3ACFC;

#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x97E53A0)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x97E5480)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_1290EA767C459179_OFFSET UNITYSDK_OFFSET(0x97E5250)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_30D1209326FA87FC_OFFSET UNITYSDK_OFFSET(0x97E5170)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_8BCB3191E6BEE7CB_OFFSET UNITYSDK_OFFSET(0x97E5100)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_8F7825DAFFB9B517_OFFSET UNITYSDK_OFFSET(0x97E5610)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_A239DF324AF4215D_OFFSET UNITYSDK_OFFSET(0x97E5690)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_D78B51BFDA4B8B32_OFFSET UNITYSDK_OFFSET(0x97E5620)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER__CTOR_OFFSET UNITYSDK_OFFSET(0x97E5550)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x97E5740)
#define RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x97E5780)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectPluginCharaPropOverlayManager_TypeDefinitionIndex = 55684;

	class MonoEffectPluginCharaPropOverlayManager : public ::RPG::Client::MonoEffectPluginCharaOverlayMatBase
	{
	public:
		::Class_2_D8BF172965D3ACFC_CharaProp CharaProps; // 0x218
		::Class_2_D8BF172965D3ACFC_FaceProp FaceProps; // 0x21C
		::Class_2_D8BF172965D3ACFC_HairProp HairProps; // 0x220
		::Class_2_D8BF172965D3ACFC_OtherProp OtherProps; // 0x224
		::Class_2_D8BF172965D3ACFC* Field_8_4; // 0x228

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER__CTOR_OFFSET))(this);
		}

		::System::Void Method_8_8BCB3191E6BEE7CB()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_8BCB3191E6BEE7CB_OFFSET))(this);
		}

		::System::Void Method_8_30D1209326FA87FC()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_30D1209326FA87FC_OFFSET))(this);
		}

		::System::Void Method_8_1290EA767C459179()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_1290EA767C459179_OFFSET))(this);
		}

		::System::Void AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Void Method_8_8F7825DAFFB9B517()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_8F7825DAFFB9B517_OFFSET))(this);
		}

		::System::Void Method_8_D78B51BFDA4B8B32()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_D78B51BFDA4B8B32_OFFSET))(this);
		}

		::System::Void Method_8_A239DF324AF4215D()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER_METHOD_8_A239DF324AF4215D_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCHARAPROPOVERLAYMANAGER___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET))(this);
		}
	};
}
