#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/MonoEffectPluginBase.h"

class Class_2_C8D9009897BCA1C3;
namespace RPG::Client { class CableProcedural; }

#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C4670)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C4700)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_DISPOSEPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C45E0)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_ENDOFLATETICK_OFFSET UNITYSDK_OFFSET(0x97C47C0)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_GET_BEHAVIOR_OFFSET UNITYSDK_OFFSET(0x97C4830)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_RESETPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C4550)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL__CTOR_OFFSET UNITYSDK_OFFSET(0x97C4840)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C4850)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET UNITYSDK_OFFSET(0x97C4890)
#define RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_ENDOFLATETICK_OFFSET UNITYSDK_OFFSET(0x97C48D0)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectPluginCableProcedural_TypeDefinitionIndex = 55748;

	class MonoEffectPluginCableProcedural : public ::RPG::Client::MonoEffectPluginBase
	{
	public:
		::RPG::Client::CableProcedural* CableProcedural; // 0x28
		::Class_2_C8D9009897BCA1C3* Field_6_1; // 0x30

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL__CTOR_OFFSET))(this);
		}

		::System::Void ResetPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_RESETPLUGIN_OFFSET))(this);
		}

		::System::Void DisposePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_DISPOSEPLUGIN_OFFSET))(this);
		}

		::System::Void AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Void EndOfLateTick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_ENDOFLATETICK_OFFSET))(this, a1);
		}

		::Class_2_C8D9009897BCA1C3* get_Behavior()
		{
			return ((::Class_2_C8D9009897BCA1C3*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL_GET_BEHAVIOR_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_DestroyPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_DESTROYPLUGIN_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy_EndOfLateTick(::System::Single P0)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINCABLEPROCEDURAL___IFIXBASEPROXY_ENDOFLATETICK_OFFSET))(this, P0);
		}
	};
}
