#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ActivityPanelData.h"

#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISFINISHCONDITIONSCOMPLETED_OFFSET UNITYSDK_OFFSET(0x9DC7FE0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC88D0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNEWREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC86E0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNOPASSNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC83E0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC8130)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__CHECKISTUTORIALMISSIONCOMPLETE_OFFSET UNITYSDK_OFFSET(0x9DC80A0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x9DC7FD0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMNEWREDDOTSHOW_OFFSET UNITYSDK_OFFSET(0x9DC8890)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMNOPASSREDDOTSHOW_OFFSET UNITYSDK_OFFSET(0x9DC8510)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMREDDOTSHOW_OFFSET UNITYSDK_OFFSET(0x9DC8260)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISFINISHCONDITIONSCOMPLETED_OFFSET UNITYSDK_OFFSET(0x9DC89E0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC8B70)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNEWREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC8AD0)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNOPASSNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC8A60)
#define RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0x9DC89F0)

namespace RPG::Client
{
	inline static constexpr unsigned int ResidentAetherDivideActivityData_TypeDefinitionIndex = 48977;

	class ResidentAetherDivideActivityData : public ::RPG::Client::ActivityPanelData
	{
	public:
		::System::Void _ctor(::System::UInt32 ID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__CTOR_OFFSET))(this, ID);
		}

		::System::Boolean IsFinishConditionsCompleted()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISFINISHCONDITIONSCOMPLETED_OFFSET))(this);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNoPassNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNOPASSNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowNewRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWNEWREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowMappingInfoRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET))(this);
		}

		::System::Boolean _IsCustomRedDotShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMREDDOTSHOW_OFFSET))(this);
		}

		::System::Boolean _IsCustomNoPassRedDotShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMNOPASSREDDOTSHOW_OFFSET))(this);
		}

		::System::Boolean _IsCustomNewRedDotShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__ISCUSTOMNEWREDDOTSHOW_OFFSET))(this);
		}

		::System::Boolean _CheckIsTutorialMissionComplete()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA__CHECKISTUTORIALMISSIONCOMPLETE_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsFinishConditionsCompleted()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISFINISHCONDITIONSCOMPLETED_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowNoPassNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNOPASSNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowNewRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWNEWREDDOT_OFFSET))(this);
		}

		::System::Boolean __iFixBaseProxy_IsShowMappingInfoRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTAETHERDIVIDEACTIVITYDATA___IFIXBASEPROXY_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET))(this);
		}
	};
}
