#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_DB663931210BBC27_60.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/RogueTournMarkType.h"
#include "unitysdk/RPG/GameCore/RogueTournRoomType.h"
#include "unitysdk/System/Object.h"

class Class_1_02098A44CBBFEEE1_1;
namespace System { class String; }

#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GETDEBUGINFO_OFFSET UNITYSDK_OFFSET(0x16F116C0)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ICONPATH_OFFSET UNITYSDK_OFFSET(0x16F117C0)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_MARKTYPE_OFFSET UNITYSDK_OFFSET(0x16F11760)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_NAME_OFFSET UNITYSDK_OFFSET(0x16F11780)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMID_OFFSET UNITYSDK_OFFSET(0x16F11730)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMINDEX_OFFSET UNITYSDK_OFFSET(0x16F11740)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMTYPE_OFFSET UNITYSDK_OFFSET(0x16F11750)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_STATUS_OFFSET UNITYSDK_OFFSET(0x16F11770)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_TOASTICONPATH_OFFSET UNITYSDK_OFFSET(0x16F117D0)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_SYNC_OFFSET UNITYSDK_OFFSET(0x16F11650)
#define RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA__CTOR_OFFSET UNITYSDK_OFFSET(0x16F11090)

namespace RPG::Client
{
	inline static constexpr unsigned int RogueTournClassicGameLevelUndeterminedRoomData_TypeDefinitionIndex = 62337;

	class RogueTournClassicGameLevelUndeterminedRoomData : public ::System::Object
	{
	public:
		::System::UInt32 _RoomIndex; // 0x10
		::System::UInt32 _RoomID; // 0x14
		::Enum_3_DB663931210BBC27_60 _Status; // 0x18

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA__CTOR_OFFSET))(this);
		}

		::System::Void Sync(::Class_1_02098A44CBBFEEE1_1* proto)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_02098A44CBBFEEE1_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_SYNC_OFFSET))(this, proto);
		}

		::System::String* GetDebugInfo()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GETDEBUGINFO_OFFSET))(this);
		}

		::System::UInt32 get_RoomID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMID_OFFSET))(this);
		}

		::System::UInt32 get_RoomIndex()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMINDEX_OFFSET))(this);
		}

		::RPG::GameCore::RogueTournRoomType get_RoomType()
		{
			return ((::RPG::GameCore::RogueTournRoomType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ROOMTYPE_OFFSET))(this);
		}

		::RPG::GameCore::RogueTournMarkType get_MarkType()
		{
			return ((::RPG::GameCore::RogueTournMarkType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_MARKTYPE_OFFSET))(this);
		}

		::Enum_3_DB663931210BBC27_60 get_Status()
		{
			return ((::Enum_3_DB663931210BBC27_60(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_STATUS_OFFSET))(this);
		}

		::RPG::Client::TextID get_Name()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_NAME_OFFSET))(this);
		}

		::System::String* get_IconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_ICONPATH_OFFSET))(this);
		}

		::System::String* get_ToastIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUETOURNCLASSICGAMELEVELUNDETERMINEDROOMDATA_GET_TOASTICONPATH_OFFSET))(this);
		}
	};
}
