#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace UnityEngine::Formats::Alembic::Exporter { class AlembicExporter; }

#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x18BF7C70)
#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_OBJECT__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x18BF7D50)
#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x18BF7DB0)
#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x18BF7D60)
#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x18BF7C60)
#define UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18__CTOR_OFFSET UNITYSDK_OFFSET(0x18BF6270)

namespace UnityEngine::Formats::Alembic::Exporter
{
	inline static constexpr unsigned int AlembicExporter__ProcessRecording_d__18_TypeDefinitionIndex = 40886;

	class AlembicExporter__ProcessRecording_d__18 : public ::System::Object
	{
	public:
		::System::Object* __2__current; // 0x10
		::UnityEngine::Formats::Alembic::Exporter::AlembicExporter* __4__this; // 0x18
		::System::Int32 __1__state; // 0x20

		::System::Void _ctor(::System::Int32 __1__state)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18__CTOR_OFFSET))(this, __1__state);
		}

		::System::Void System_IDisposable_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
		}

		::System::Boolean MoveNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_MOVENEXT_OFFSET))(this);
		}

		::System::Object* System_Collections_Generic_IEnumerator_System_Object__get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_OBJECT__GET_CURRENT_OFFSET))(this);
		}

		::System::Void System_Collections_IEnumerator_Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
		}

		::System::Object* System_Collections_IEnumerator_get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_FORMATS_ALEMBIC_EXPORTER_ALEMBICEXPORTER__PROCESSRECORDING_D__18_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
		}
	};
}
