#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Sofa/BaseViewModel.h"

class Class_1_2FDE33CCAE591AA8;
class Class_1_50AC12A2F890597C;
class Class_1_5F4D64A4B97E38F9;

#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_CREATE_OFFSET UNITYSDK_OFFSET(0x18AFB9C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ISDETAILBTNON_OFFSET UNITYSDK_OFFSET(0x18AFC000)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ISSPEEDUPBTNON_OFFSET UNITYSDK_OFFSET(0x18AFC010)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ONCLICKDETAILBTNCOMMAND_OFFSET UNITYSDK_OFFSET(0x18AFBFC0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ONCLICKSPEEDUPBTNCOMMAND_OFFSET UNITYSDK_OFFSET(0x18AFBFE0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ISDETAILBTNON_OFFSET UNITYSDK_OFFSET(0x18AFBDD0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ISSPEEDUPBTNON_OFFSET UNITYSDK_OFFSET(0x18AFBC80)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ONCLICKDETAILBTNCOMMAND_OFFSET UNITYSDK_OFFSET(0x18AFBFD0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ONCLICKSPEEDUPBTNCOMMAND_OFFSET UNITYSDK_OFFSET(0x18AFBFF0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0x18AFBB40)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__INIT_OFFSET UNITYSDK_OFFSET(0x18AFBB60)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__ONCLICKDETAILBTN_OFFSET UNITYSDK_OFFSET(0x18AFBD10)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__ONCLICKSPEEDUPBTN_OFFSET UNITYSDK_OFFSET(0x18AFBE60)

namespace RPG::Client::ChenLingFes
{
	inline static constexpr unsigned int ChenLingFesGameplayFunctionBtnViewModel_TypeDefinitionIndex = 74033;

	class ChenLingFesGameplayFunctionBtnViewModel : public ::Sofa::BaseViewModel
	{
	public:
		::Class_1_2FDE33CCAE591AA8* _OnClickSpeedUpBtnCommand_k__BackingField; // 0x20
		::Class_1_50AC12A2F890597C* _GameplayBridge; // 0x28
		::Class_1_2FDE33CCAE591AA8* _OnClickDetailBtnCommand_k__BackingField; // 0x30
		::Class_1_5F4D64A4B97E38F9* _Messenger; // 0x38
		::System::Boolean _IsSpeedUpBtnOn; // 0x40
		::System::Boolean _IsDetailBtnOn; // 0x41

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::ChenLingFes::ChenLingFesGameplayFunctionBtnViewModel* Create(::Class_1_50AC12A2F890597C* a1, ::Class_1_5F4D64A4B97E38F9* a2)
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayFunctionBtnViewModel*(*)(::Class_1_50AC12A2F890597C*, ::Class_1_5F4D64A4B97E38F9*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_CREATE_OFFSET))(a1, a2);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__INIT_OFFSET))(this);
		}

		::System::Void _OnClickDetailBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__ONCLICKDETAILBTN_OFFSET))(this);
		}

		::System::Void _OnClickSpeedUpBtn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL__ONCLICKSPEEDUPBTN_OFFSET))(this);
		}

		::Class_1_2FDE33CCAE591AA8* get_OnClickDetailBtnCommand()
		{
			return ((::Class_1_2FDE33CCAE591AA8*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ONCLICKDETAILBTNCOMMAND_OFFSET))(this);
		}

		::System::Void set_OnClickDetailBtnCommand(::Class_1_2FDE33CCAE591AA8* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2FDE33CCAE591AA8*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ONCLICKDETAILBTNCOMMAND_OFFSET))(this, a1);
		}

		::Class_1_2FDE33CCAE591AA8* get_OnClickSpeedUpBtnCommand()
		{
			return ((::Class_1_2FDE33CCAE591AA8*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ONCLICKSPEEDUPBTNCOMMAND_OFFSET))(this);
		}

		::System::Void set_OnClickSpeedUpBtnCommand(::Class_1_2FDE33CCAE591AA8* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_2FDE33CCAE591AA8*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ONCLICKSPEEDUPBTNCOMMAND_OFFSET))(this, a1);
		}

		::System::Boolean get_IsDetailBtnOn()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ISDETAILBTNON_OFFSET))(this);
		}

		::System::Void set_IsDetailBtnOn(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ISDETAILBTNON_OFFSET))(this, a1);
		}

		::System::Boolean get_IsSpeedUpBtnOn()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_GET_ISSPEEDUPBTNON_OFFSET))(this);
		}

		::System::Void set_IsSpeedUpBtnOn(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYFUNCTIONBTNVIEWMODEL_SET_ISSPEEDUPBTNON_OFFSET))(this, a1);
		}
	};
}
