#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Sofa/BaseSofaWindow.h"

class Class_1_96EDC22AC7BC5724;
namespace RPG::Client::Challenge::Tierce { class ChallengeTierceBadgeNoticeControl; }

#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW_GET__TYPEDDATACONTEXT_OFFSET UNITYSDK_OFFSET(0x18FC3450)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW_SET__TYPEDDATACONTEXT_OFFSET UNITYSDK_OFFSET(0x18FC34D0)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__CTOR_OFFSET UNITYSDK_OFFSET(0x18FC34E0)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONBINDVIEWMODEL_OFFSET UNITYSDK_OFFSET(0x18FC3630)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONINCONTROLEXIT_OFFSET UNITYSDK_OFFSET(0x18FC3970)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONINITIALIZECOMPONENT_OFFSET UNITYSDK_OFFSET(0x18FC3580)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONBINDVIEWMODEL_OFFSET UNITYSDK_OFFSET(0x18FC3B60)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONINCONTROLEXIT_OFFSET UNITYSDK_OFFSET(0x18FC3BC0)
#define RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONINITIALIZECOMPONENT_OFFSET UNITYSDK_OFFSET(0x18FC3B00)

namespace RPG::Client::Challenge::Tierce
{
	inline static constexpr unsigned int ChallengeTierceBadgeNoticeWindow_TypeDefinitionIndex = 74176;

	class ChallengeTierceBadgeNoticeWindow : public ::Sofa::BaseSofaWindow
	{
	public:
		::RPG::Client::Challenge::Tierce::ChallengeTierceBadgeNoticeControl* _Content; // 0x40

		::System::Void _ctor(::Class_1_96EDC22AC7BC5724* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_96EDC22AC7BC5724*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__CTOR_OFFSET))(this, a1);
		}

		::Class_1_96EDC22AC7BC5724* get__TypedDataContext()
		{
			return ((::Class_1_96EDC22AC7BC5724*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW_GET__TYPEDDATACONTEXT_OFFSET))(this);
		}

		::System::Void set__TypedDataContext(::Class_1_96EDC22AC7BC5724* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_96EDC22AC7BC5724*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW_SET__TYPEDDATACONTEXT_OFFSET))(this, a1);
		}

		::System::Void _OnInitializeComponent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONINITIALIZECOMPONENT_OFFSET))(this);
		}

		::System::Void _OnBindViewModel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONBINDVIEWMODEL_OFFSET))(this);
		}

		::System::Void _OnInControlExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW__ONINCONTROLEXIT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnInitializeComponent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONINITIALIZECOMPONENT_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnBindViewModel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONBINDVIEWMODEL_OFFSET))(this);
		}

		::System::Void __iFixBaseProxy__OnInControlExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHALLENGE_TIERCE_CHALLENGETIERCEBADGENOTICEWINDOW___IFIXBASEPROXY__ONINCONTROLEXIT_OFFSET))(this);
		}
	};
}
