#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/UI/UIStateCtrl/BaseAction.h"

namespace RPG::Client { class UIStateCtrl; }
namespace System { class String; }

#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_GET_CURRENTCOSTTIME_OFFSET UNITYSDK_OFFSET(0x17FE88D0)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_16480B1867AF51ED_OFFSET UNITYSDK_OFFSET(0x17FE8470)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0x17FE8890)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_39590AB2089F9F4D_OFFSET UNITYSDK_OFFSET(0x17FE8630)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_4343F372F34C05BF_OFFSET UNITYSDK_OFFSET(0x17FE8550)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_45CCDE687DEEF3B6_OFFSET UNITYSDK_OFFSET(0x17FE8770)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_8A1C979A2319B852_OFFSET UNITYSDK_OFFSET(0x17FE8910)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_CA373AA1C7054598_OFFSET UNITYSDK_OFFSET(0x17FE8710)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_SET_CURRENTCOSTTIME_OFFSET UNITYSDK_OFFSET(0x17FE88E0)
#define RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION__CTOR_OFFSET UNITYSDK_OFFSET(0x17FE88F0)

namespace RPG::Client::UI::UIStateCtrl
{
	inline static constexpr unsigned int AsyncAction_TypeDefinitionIndex = 69147;

	class AsyncAction : public ::RPG::Client::UI::UIStateCtrl::BaseAction
	{
	public:
		::System::Single Duration; // 0x20
		::System::Single _CurrentCostTime_k__BackingField; // 0x24

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION__CTOR_OFFSET))(this);
		}

		::System::Void Method_2_16480B1867AF51ED(::RPG::Client::UIStateCtrl* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::UIStateCtrl*))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_16480B1867AF51ED_OFFSET))(this, a1);
		}

		::System::Void Method_2_4343F372F34C05BF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_4343F372F34C05BF_OFFSET))(this);
		}

		::System::Void Method_2_39590AB2089F9F4D(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_39590AB2089F9F4D_OFFSET))(this, a1);
		}

		::System::Void Method_2_CA373AA1C7054598()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_CA373AA1C7054598_OFFSET))(this);
		}

		::System::String* Method_2_45CCDE687DEEF3B6()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_45CCDE687DEEF3B6_OFFSET))(this);
		}

		::System::Boolean Method_2_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_391A84BCD9F51317_OFFSET))(this);
		}

		::System::Single get_CurrentCostTime()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_GET_CURRENTCOSTTIME_OFFSET))(this);
		}

		::System::Void set_CurrentCostTime(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_SET_CURRENTCOSTTIME_OFFSET))(this, a1);
		}

		::System::Void Method_2_8A1C979A2319B852(::RPG::Client::UIStateCtrl* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::UIStateCtrl*))((::PBYTE)hIl2Cpp + RPG_CLIENT_UI_UISTATECTRL_ASYNCACTION_METHOD_2_8A1C979A2319B852_OFFSET))(this, a1);
		}
	};
}
