#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_737E9F3E232B5664.h"
#include "unitysdk/Enum_3_4608E37A1B3D374A_20.h"

class Class_1_120319518E6F6581_50;
class Class_1_481283E0067B5773;
class Class_1_4CF8088A158DCE25_48;
class Class_1_732AF221927F3BE0_1;
class Class_1_9D5608F598A30CAC_21;
class Class_1_E85FDBE62E39A5EA_11;
class Class_1_E9FAC3539FD8861A_14;
class Class_1_FA4F4A67B1C04320_459;
class Class_1_FA4F4A67B1C04320_466;
class Class_1_FA4F4A67B1C04320_468;
namespace RPG::Client::MVVM::Model { class LimaoNewsModule; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_REFRESHLIMAONEWSOFFICESURVEYWITHFILTER_OFFSET UNITYSDK_OFFSET(0x95B73F0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSCOMPLETEOFFICESURVEYLISTCSREQ_OFFSET UNITYSDK_OFFSET(0x95B7650)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTEVENTCSREQ_OFFSET UNITYSDK_OFFSET(0x95B8150)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTMESSAGECSREQ_OFFSET UNITYSDK_OFFSET(0x95B71D0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTREPLYCSREQ_OFFSET UNITYSDK_OFFSET(0x95B7A60)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSGETDATA_OFFSET UNITYSDK_OFFSET(0x95B7300)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSETMAINPAGEFLAGCSREQ_OFFSET UNITYSDK_OFFSET(0x95B7C20)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSUBMITISSUECSREQ_OFFSET UNITYSDK_OFFSET(0x95B76E0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSUBMITPOSTCSREQ_OFFSET UNITYSDK_OFFSET(0x95B78E0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSTRACKSURVEYCSREQ_OFFSET UNITYSDK_OFFSET(0x95B7D10)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSUPVOTEINTERVIEW_OFFSET UNITYSDK_OFFSET(0x95B7ED0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSUPVOTEPOST_OFFSET UNITYSDK_OFFSET(0x95B8010)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__CTOR_OFFSET UNITYSDK_OFFSET(0x95AF880)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__ONLIMAONEWSDATACHANGESCNOTIFY_OFFSET UNITYSDK_OFFSET(0x95B8290)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__ONLIMAONEWSDATAITEMCHANGE_OFFSET UNITYSDK_OFFSET(0x95B8530)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSFINISHCLIENTEVENTCSREQ_B__11_0_OFFSET UNITYSDK_OFFSET(0x95B9BD0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSFINISHCLIENTMESSAGECSREQ_B__12_0_OFFSET UNITYSDK_OFFSET(0x95B9C20)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSGETDATA_B__1_0_OFFSET UNITYSDK_OFFSET(0x95B9270)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSETMAINPAGEFLAGCSREQ_B__7_0_OFFSET UNITYSDK_OFFSET(0x95B99D0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSUBMITISSUECSREQ_B__4_0_OFFSET UNITYSDK_OFFSET(0x95B9810)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSUBMITPOSTCSREQ_B__5_0_OFFSET UNITYSDK_OFFSET(0x95B98C0)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSUPVOTEINTERVIEW_B__9_0_OFFSET UNITYSDK_OFFSET(0x95B9A30)
#define RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSUPVOTEPOST_B__10_0_OFFSET UNITYSDK_OFFSET(0x95B9AB0)

namespace RPG::Client::MVVM::Service
{
	inline static constexpr unsigned int LimaoNewsNetworkService_TypeDefinitionIndex = 59282;

	class LimaoNewsNetworkService : public ::Class_1_737E9F3E232B5664
	{
	public:
		::RPG::Client::MVVM::Model::LimaoNewsModule* _LimaoNewsModule; // 0x18

		::System::Void _ctor(::RPG::Client::MVVM::Model::LimaoNewsModule* module)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::MVVM::Model::LimaoNewsModule*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__CTOR_OFFSET))(this, module);
		}

		::System::Void SendLimaoNewsGetData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSGETDATA_OFFSET))(this);
		}

		::System::Void RefreshLimaoNewsOfficeSurveyWithFilter(::System::Collections::Generic::List_1<::System::UInt32>* surveyTypes, ::System::Collections::Generic::List_1<::System::UInt32>* locationIDs, ::System::Collections::Generic::List_1<::Enum_3_4608E37A1B3D374A_20>* states)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::UInt32>*, ::System::Collections::Generic::List_1<::System::UInt32>*, ::System::Collections::Generic::List_1<::Enum_3_4608E37A1B3D374A_20>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_REFRESHLIMAONEWSOFFICESURVEYWITHFILTER_OFFSET))(this, surveyTypes, locationIDs, states);
		}

		::System::Void SendLimaoNewsCompleteOfficeSurveyListCsReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSCOMPLETEOFFICESURVEYLISTCSREQ_OFFSET))(this);
		}

		::System::Void SendLimaoNewsSubmitIssueCsReq(::System::UInt32 issueID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSUBMITISSUECSREQ_OFFSET))(this, issueID);
		}

		::System::Void SendLimaoNewsSubmitPostCsReq(::System::UInt32 postID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSUBMITPOSTCSREQ_OFFSET))(this, postID);
		}

		::System::Void SendLimaoNewsFinishClientReplyCsReq(::System::UInt32 postID, ::System::UInt32 commentID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTREPLYCSREQ_OFFSET))(this, postID, commentID);
		}

		::System::Void SendLimaoNewsSetMainPageFlagCsReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSSETMAINPAGEFLAGCSREQ_OFFSET))(this);
		}

		::System::Void SendLimaoNewsTrackSurveyCsReq(::System::UInt32 surveyID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSTRACKSURVEYCSREQ_OFFSET))(this, surveyID);
		}

		::System::Void SendLimaoNewsUpvoteInterview(::System::UInt32 interviewID, ::System::Boolean isUpvote)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSUPVOTEINTERVIEW_OFFSET))(this, interviewID, isUpvote);
		}

		::System::Void SendLimaoNewsUpvotePost(::System::UInt32 postID, ::System::Boolean isUpvote)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSUPVOTEPOST_OFFSET))(this, postID, isUpvote);
		}

		::System::Void SendLimaoNewsFinishClientEventCsReq(::System::UInt32 eventID, ::System::UInt32 chooseParam)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTEVENTCSREQ_OFFSET))(this, eventID, chooseParam);
		}

		::System::Void SendLimaoNewsFinishClientMessageCsReq(::System::UInt32 messsageID)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE_SENDLIMAONEWSFINISHCLIENTMESSAGECSREQ_OFFSET))(this, messsageID);
		}

		::System::Void _OnLimaoNewsDataChangeScNotify(::System::UInt16 cmd, ::Class_1_E85FDBE62E39A5EA_11* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::Class_1_E85FDBE62E39A5EA_11*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__ONLIMAONEWSDATACHANGESCNOTIFY_OFFSET))(this, cmd, rsp);
		}

		::System::Void _OnLimaoNewsDataItemChange(::Class_1_481283E0067B5773* detail)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_481283E0067B5773*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__ONLIMAONEWSDATAITEMCHANGE_OFFSET))(this, detail);
		}

		::System::Void _SendLimaoNewsGetData_b__1_0(::Class_1_732AF221927F3BE0_1* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_732AF221927F3BE0_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSGETDATA_B__1_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsSubmitIssueCsReq_b__4_0(::Class_1_FA4F4A67B1C04320_459* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FA4F4A67B1C04320_459*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSUBMITISSUECSREQ_B__4_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsSubmitPostCsReq_b__5_0(::Class_1_9D5608F598A30CAC_21* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_9D5608F598A30CAC_21*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSUBMITPOSTCSREQ_B__5_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsSetMainPageFlagCsReq_b__7_0(::Class_1_FA4F4A67B1C04320_468* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FA4F4A67B1C04320_468*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSSETMAINPAGEFLAGCSREQ_B__7_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsUpvoteInterview_b__9_0(::Class_1_E9FAC3539FD8861A_14* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_E9FAC3539FD8861A_14*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSUPVOTEINTERVIEW_B__9_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsUpvotePost_b__10_0(::Class_1_4CF8088A158DCE25_48* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_4CF8088A158DCE25_48*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSUPVOTEPOST_B__10_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsFinishClientEventCsReq_b__11_0(::Class_1_120319518E6F6581_50* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_120319518E6F6581_50*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSFINISHCLIENTEVENTCSREQ_B__11_0_OFFSET))(this, rsp);
		}

		::System::Void _SendLimaoNewsFinishClientMessageCsReq_b__12_0(::Class_1_FA4F4A67B1C04320_466* rsp)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FA4F4A67B1C04320_466*))((::PBYTE)hIl2Cpp + RPG_CLIENT_MVVM_SERVICE_LIMAONEWSNETWORKSERVICE__SENDLIMAONEWSFINISHCLIENTMESSAGECSREQ_B__12_0_OFFSET))(this, rsp);
		}
	};
}
