#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

#define AKSPATIALAUDIOINITSETTINGS_DISPOSE_1_OFFSET UNITYSDK_OFFSET(0x196C5E90)
#define AKSPATIALAUDIOINITSETTINGS_DISPOSE_OFFSET UNITYSDK_OFFSET(0x196C5D70)
#define AKSPATIALAUDIOINITSETTINGS_FINALIZE_OFFSET UNITYSDK_OFFSET(0x196C5E20)
#define AKSPATIALAUDIOINITSETTINGS_GETCPTR_OFFSET UNITYSDK_OFFSET(0x196C5C30)
#define AKSPATIALAUDIOINITSETTINGS_GET_BENABLEDIFFRACTIONONREFLECTION_OFFSET UNITYSDK_OFFSET(0x196C6FE0)
#define AKSPATIALAUDIOINITSETTINGS_GET_BENABLEDIRECTPATHDIFFRACTION_OFFSET UNITYSDK_OFFSET(0x196C72A0)
#define AKSPATIALAUDIOINITSETTINGS_GET_BENABLETRANSMISSION_OFFSET UNITYSDK_OFFSET(0x196C7410)
#define AKSPATIALAUDIOINITSETTINGS_GET_FDIFFRACTIONSHADOWATTENFACTOR_OFFSET UNITYSDK_OFFSET(0x196C65F0)
#define AKSPATIALAUDIOINITSETTINGS_GET_FDIFFRACTIONSHADOWDEGREES_OFFSET UNITYSDK_OFFSET(0x196C68B0)
#define AKSPATIALAUDIOINITSETTINGS_GET_FMAXPATHLENGTH_OFFSET UNITYSDK_OFFSET(0x196C6E70)
#define AKSPATIALAUDIOINITSETTINGS_GET_FMOVEMENTTHRESHOLD_OFFSET UNITYSDK_OFFSET(0x196C6A20)
#define AKSPATIALAUDIOINITSETTINGS_GET_UDIFFRACTIONFLAGS_OFFSET UNITYSDK_OFFSET(0x196C6320)
#define AKSPATIALAUDIOINITSETTINGS_GET_UMAXREFLECTIONORDER_OFFSET UNITYSDK_OFFSET(0x196C6D00)
#define AKSPATIALAUDIOINITSETTINGS_GET_UMAXSOUNDPROPAGATIONDEPTH_OFFSET UNITYSDK_OFFSET(0x196C61B0)
#define AKSPATIALAUDIOINITSETTINGS_GET_UNUMBEROFPRIMARYRAYS_OFFSET UNITYSDK_OFFSET(0x196C6B90)
#define AKSPATIALAUDIOINITSETTINGS_SETCPTR_OFFSET UNITYSDK_OFFSET(0x196C5C80)
#define AKSPATIALAUDIOINITSETTINGS_SET_BENABLEDIFFRACTIONONREFLECTION_OFFSET UNITYSDK_OFFSET(0x196C6F20)
#define AKSPATIALAUDIOINITSETTINGS_SET_BENABLEDIRECTPATHDIFFRACTION_OFFSET UNITYSDK_OFFSET(0x196C71E0)
#define AKSPATIALAUDIOINITSETTINGS_SET_BENABLETRANSMISSION_OFFSET UNITYSDK_OFFSET(0x196C7350)
#define AKSPATIALAUDIOINITSETTINGS_SET_FDIFFRACTIONSHADOWATTENFACTOR_OFFSET UNITYSDK_OFFSET(0x196C63D0)
#define AKSPATIALAUDIOINITSETTINGS_SET_FDIFFRACTIONSHADOWDEGREES_OFFSET UNITYSDK_OFFSET(0x196C67F0)
#define AKSPATIALAUDIOINITSETTINGS_SET_FMAXPATHLENGTH_OFFSET UNITYSDK_OFFSET(0x196C6DB0)
#define AKSPATIALAUDIOINITSETTINGS_SET_FMOVEMENTTHRESHOLD_OFFSET UNITYSDK_OFFSET(0x196C6960)
#define AKSPATIALAUDIOINITSETTINGS_SET_UDIFFRACTIONFLAGS_OFFSET UNITYSDK_OFFSET(0x196C6260)
#define AKSPATIALAUDIOINITSETTINGS_SET_UMAXREFLECTIONORDER_OFFSET UNITYSDK_OFFSET(0x196C6C40)
#define AKSPATIALAUDIOINITSETTINGS_SET_UMAXSOUNDPROPAGATIONDEPTH_OFFSET UNITYSDK_OFFSET(0x196C60F0)
#define AKSPATIALAUDIOINITSETTINGS_SET_UNUMBEROFPRIMARYRAYS_OFFSET UNITYSDK_OFFSET(0x196C6AD0)
#define AKSPATIALAUDIOINITSETTINGS__CTOR_1_OFFSET UNITYSDK_OFFSET(0x196C6070)
#define AKSPATIALAUDIOINITSETTINGS__CTOR_OFFSET UNITYSDK_OFFSET(0x196C5C20)

inline static constexpr unsigned int AkSpatialAudioInitSettings_TypeDefinitionIndex = 41171;

class AkSpatialAudioInitSettings : public ::System::Object
{
public:
	::System::IntPtr swigCPtr; // 0x10
	::System::Boolean swigCMemOwn; // 0x18

	::System::Void _ctor(::System::IntPtr a1, ::System::Boolean a2)
	{
		return ((::System::Void(*)(::PVOID, ::System::IntPtr, ::System::Boolean))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS__CTOR_OFFSET))(this, a1, a2);
	}

	::System::Void _ctor_1()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS__CTOR_1_OFFSET))(this);
	}

	static ::System::IntPtr getCPtr(::AkSpatialAudioInitSettings* a1)
	{
		return ((::System::IntPtr(*)(::AkSpatialAudioInitSettings*))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GETCPTR_OFFSET))(a1);
	}

	::System::Void setCPtr(::System::IntPtr a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::IntPtr))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SETCPTR_OFFSET))(this, a1);
	}

	::System::Void Finalize()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_FINALIZE_OFFSET))(this);
	}

	::System::Void Dispose()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_DISPOSE_OFFSET))(this);
	}

	::System::Void Dispose_1(::System::Boolean a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_DISPOSE_1_OFFSET))(this, a1);
	}

	::System::Void set_uMaxSoundPropagationDepth(::System::UInt32 a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_UMAXSOUNDPROPAGATIONDEPTH_OFFSET))(this, a1);
	}

	::System::UInt32 get_uMaxSoundPropagationDepth()
	{
		return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_UMAXSOUNDPROPAGATIONDEPTH_OFFSET))(this);
	}

	::System::Void set_uDiffractionFlags(::System::UInt32 a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_UDIFFRACTIONFLAGS_OFFSET))(this, a1);
	}

	::System::UInt32 get_uDiffractionFlags()
	{
		return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_UDIFFRACTIONFLAGS_OFFSET))(this);
	}

	::System::Void set_fDiffractionShadowAttenFactor(::System::Single a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_FDIFFRACTIONSHADOWATTENFACTOR_OFFSET))(this, a1);
	}

	::System::Single get_fDiffractionShadowAttenFactor()
	{
		return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_FDIFFRACTIONSHADOWATTENFACTOR_OFFSET))(this);
	}

	::System::Void set_fDiffractionShadowDegrees(::System::Single a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_FDIFFRACTIONSHADOWDEGREES_OFFSET))(this, a1);
	}

	::System::Single get_fDiffractionShadowDegrees()
	{
		return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_FDIFFRACTIONSHADOWDEGREES_OFFSET))(this);
	}

	::System::Void set_fMovementThreshold(::System::Single a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_FMOVEMENTTHRESHOLD_OFFSET))(this, a1);
	}

	::System::Single get_fMovementThreshold()
	{
		return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_FMOVEMENTTHRESHOLD_OFFSET))(this);
	}

	::System::Void set_uNumberOfPrimaryRays(::System::UInt32 a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_UNUMBEROFPRIMARYRAYS_OFFSET))(this, a1);
	}

	::System::UInt32 get_uNumberOfPrimaryRays()
	{
		return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_UNUMBEROFPRIMARYRAYS_OFFSET))(this);
	}

	::System::Void set_uMaxReflectionOrder(::System::UInt32 a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_UMAXREFLECTIONORDER_OFFSET))(this, a1);
	}

	::System::UInt32 get_uMaxReflectionOrder()
	{
		return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_UMAXREFLECTIONORDER_OFFSET))(this);
	}

	::System::Void set_fMaxPathLength(::System::Single a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_FMAXPATHLENGTH_OFFSET))(this, a1);
	}

	::System::Single get_fMaxPathLength()
	{
		return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_FMAXPATHLENGTH_OFFSET))(this);
	}

	::System::Void set_bEnableDiffractionOnReflection(::System::Boolean a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_BENABLEDIFFRACTIONONREFLECTION_OFFSET))(this, a1);
	}

	::System::Boolean get_bEnableDiffractionOnReflection()
	{
		return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_BENABLEDIFFRACTIONONREFLECTION_OFFSET))(this);
	}

	::System::Void set_bEnableDirectPathDiffraction(::System::Boolean a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_BENABLEDIRECTPATHDIFFRACTION_OFFSET))(this, a1);
	}

	::System::Boolean get_bEnableDirectPathDiffraction()
	{
		return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_BENABLEDIRECTPATHDIFFRACTION_OFFSET))(this);
	}

	::System::Void set_bEnableTransmission(::System::Boolean a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_SET_BENABLETRANSMISSION_OFFSET))(this, a1);
	}

	::System::Boolean get_bEnableTransmission()
	{
		return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + AKSPATIALAUDIOINITSETTINGS_GET_BENABLETRANSMISSION_OFFSET))(this);
	}
};
