#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Collections/Generic/List_1_Enumerator.h"
#include "unitysdk/System/Object.h"

class Class_1_1F09213678A820A2;
class Class_1_D91AD7AC78B58FEA;
namespace System::Collections { class IEnumerator; }
namespace System::Collections::Generic { template <typename T> class IEnumerator_1; }

#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x10B500A0)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_RPG_CLIENT_BATTLECHARACTERHUDSPECIALBUFFDATA__GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0x10B50260)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_RPG_CLIENT_BATTLECHARACTERHUDSPECIALBUFFDATA__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x10B501F0)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0x10B502E0)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x10B50250)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x10B50200)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x10B50080)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0__CTOR_OFFSET UNITYSDK_OFFSET(0x10B4F0C0)
#define CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0___M__FINALLY1_OFFSET UNITYSDK_OFFSET(0x10B50090)

inline static constexpr unsigned int Class_1_D91AD7AC78B58FEA__GetSpecialBuffList_d__0_TypeDefinitionIndex = 56956;

class Class_1_D91AD7AC78B58FEA__GetSpecialBuffList_d__0 : public ::System::Object
{
public:
	::System::Collections::Generic::List_1_Enumerator<::Class_1_1F09213678A820A2*> __7__wrap1; // 0x10
	::Class_1_1F09213678A820A2* __2__current; // 0x28
	::Class_1_D91AD7AC78B58FEA* __4__this; // 0x30
	::System::Int32 __1__state; // 0x38
	::System::Int32 __l__initialThreadId; // 0x3C

	::System::Void _ctor(::System::Int32 __1__state)
	{
		return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0__CTOR_OFFSET))(this, __1__state);
	}

	::System::Void System_IDisposable_Dispose()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
	}

	::System::Boolean MoveNext()
	{
		return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_MOVENEXT_OFFSET))(this);
	}

	::System::Void __m__Finally1()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0___M__FINALLY1_OFFSET))(this);
	}

	::Class_1_1F09213678A820A2* System_Collections_Generic_IEnumerator_RPG_Client_BattleCharacterHUDSpecialBuffData__get_Current()
	{
		return ((::Class_1_1F09213678A820A2*(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_RPG_CLIENT_BATTLECHARACTERHUDSPECIALBUFFDATA__GET_CURRENT_OFFSET))(this);
	}

	::System::Void System_Collections_IEnumerator_Reset()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
	}

	::System::Object* System_Collections_IEnumerator_get_Current()
	{
		return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
	}

	::System::Collections::Generic::IEnumerator_1<::Class_1_1F09213678A820A2*>* System_Collections_Generic_IEnumerable_RPG_Client_BattleCharacterHUDSpecialBuffData__GetEnumerator()
	{
		return ((::System::Collections::Generic::IEnumerator_1<::Class_1_1F09213678A820A2*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_RPG_CLIENT_BATTLECHARACTERHUDSPECIALBUFFDATA__GETENUMERATOR_OFFSET))(this);
	}

	::System::Collections::IEnumerator* System_Collections_IEnumerable_GetEnumerator()
	{
		return ((::System::Collections::IEnumerator*(*)(::PVOID))((::PBYTE)hIl2Cpp + CLASS_1_D91AD7AC78B58FEA__GETSPECIALBUFFLIST_D__0_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET))(this);
	}
};
