#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/FiveDimRenderingPanel.h"

#define FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_5587AE4B03E68C58_OFFSET UNITYSDK_OFFSET(0x153ADDF0)
#define FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_70C856AE64234BE0_OFFSET UNITYSDK_OFFSET(0x153ADCE0)
#define FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_CA373AA1C7054598_OFFSET UNITYSDK_OFFSET(0x153ADD30)
#define FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_E6FA84ECDEF620CE_OFFSET UNITYSDK_OFFSET(0x153ADE00)
#define FIVEDIMRENDERINGPANELRUNTIME_ONDESTROY_OFFSET UNITYSDK_OFFSET(0x153ADD70)
#define FIVEDIMRENDERINGPANELRUNTIME__CTOR_OFFSET UNITYSDK_OFFSET(0x153ADDC0)

inline static constexpr unsigned int FiveDimRenderingPanelRuntime_TypeDefinitionIndex = 44472;

class FiveDimRenderingPanelRuntime : public ::FiveDimRenderingPanel
{
public:
	::System::Void _ctor()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME__CTOR_OFFSET))(this);
	}

	::System::Void Method_6_70C856AE64234BE0()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_70C856AE64234BE0_OFFSET))(this);
	}

	::System::Void Method_6_CA373AA1C7054598()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_CA373AA1C7054598_OFFSET))(this);
	}

	::System::Void OnDestroy()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME_ONDESTROY_OFFSET))(this);
	}

	::System::Void Method_6_5587AE4B03E68C58()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_5587AE4B03E68C58_OFFSET))(this);
	}

	::System::Void Method_6_E6FA84ECDEF620CE()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + FIVEDIMRENDERINGPANELRUNTIME_METHOD_6_E6FA84ECDEF620CE_OFFSET))(this);
	}
};
